TechnologyEnhancedLearning/DLSV2

DigitalLearningSolutions.Data.Tests/Services/SelfAssessmentServiceTests.cs, DigitalLearningSolutions.Data/Services/SelfAssessmentService.cs, DigitalLearningSolutions.Web.Tests/Controllers/CurrentTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningPortalControllerTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/SelfAssessmentTests.cs, DigitalLearningSolutions.Web.Tests/Helpers/SearchHelperTests.cs, DigitalLearningSolutions.Web.Tests/TestHelpers/SelfAssessmentHelper.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/Current.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/ViewModels/LearningPortal/Current/AllCurrentItemsPageViewModel.cs, DigitalLearningSolutions.Web/ViewModels/LearningPortal/Current/CurrentPageViewModel.cs, DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/SelfAssessmentDescriptionViewModel.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentCompetency.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentDescription.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_SelfAssessmentCard.cshtml
DLSV2-12 Initial commit. Adds GetSelfAssessmentsForCandidate to controller and changes GetSelfAssessmentForCandidate to GetSelfAssessmentForCandidateById adding Self Assessment Id parameter. Retrieves these as IEnumerable in CurrentPageViewModel.cs and adds them to the AllItems list. Updates tests to include additional param.
=> Handles multiple CandidateAssessments in Current view

DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/ContentViewerViewModelTests.cs, DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs, DigitalLearningSolutions.Web/Helpers/ConfigHelper.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/ContentViewerViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/ContentViewer.cshtml, README.md
Checking that we can show html content in an iframe + SCORM content in an iframe using the SCORM player in the old system.
=> HEEDLS-201 Add proof of concept content viewer

DigitalLearningSolutions.Data.Tests/Services/CourseContentServiceTests.cs, DigitalLearningSolutions.Data/Models/CourseContent/CourseContent.cs, DigitalLearningSolutions.Data/Services/CourseContentService.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs, DigitalLearningSolutions.Web.Tests/TestHelpers/CourseContentHelper.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/IntitialMenuViewModelTests.cs, DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/Available.cs, DigitalLearningSolutions.Web/Startup.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/InitialMenuViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/Index.cshtml
Add service class for fetching details about a course, including sections, tutorials, assessments. Currently just fetching course name as a placeholder.
=> HEEDLS-NONE Add course content service

DigitalLearningSolutions.Data.Tests/Services/CourseContentServiceTests.cs
Added transaction scopes around tests that change the database so that the changes are not made.
=> Put tests with changes in transaction scope

DigitalLearningSolutions.Data.Tests/Services/CourseContentServiceTests.cs, DigitalLearningSolutions.Data/Models/CourseContent/CourseContent.cs, DigitalLearningSolutions.Data/Models/CourseContent/CourseSection.cs, DigitalLearningSolutions.Data/Services/CourseContentService.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs, DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs
Add Section class, containing basic data about a candidate's progress
through a specific section.
Amend GetCourseContent class to contain a list of sections, and the get
method in the CourseContentService to collect all of this.
Modify LearningMenuController to use the candidate ID to find a course
overview, so details about progress through each section can be given.
Amend tests to reflect new structure of models, and add some to cover
the edge cases of getting a course.
Ran all tests after updating them, all tests passed.
=> HEEDLS-209 Back end for initial course page

DigitalLearningSolutions.Web/Startup.cs
Did a quick proof of concept to check using cookies to store session id would work. Most of it has just been added as details to HEEDLS-212 but this seemed worth just adding now 🙂
=> HEEDLS-213 Add session state to app

DigitalLearningSolutions.Web/Views/LearningMenu/Index.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Shared/_NavMenuItems.cshtml
Add a shared _NavMenuItems for learning menu pages with a "Learning portal" item that links to current activities.
=> HEEDLS-214 Learning portal header link

DigitalLearningSolutions.Web/Styles/learningMenu/index.scss, DigitalLearningSolutions.Web/Views/LearningMenu/Index.cshtml
Hard coded version of Link to completion summary. Pictures below show what the two different outputs can be depending on whether or not the course is completed or not.
Incomplete
Complete
How it looks against the rest of the page
Things left to do once @kwunkiuma has backend completed:
=> HEEDLS-211 Link To Completion Summary Front End

DigitalLearningSolutions.Web/Views/LearningPortal/Available/Available.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/Completed/Completed.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/Current/Current.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/Current/RemoveCurrentCourseConfirmation.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/Current/SetCompleteByDate.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/Current/UnlockCurrentCourse.cshtml
I was hoping the relative urls would be relative to the application, but they're not so small fix needed 🙂
=> HEEDLS-207 Fix header link on UAT

DigitalLearningSolutions.Data.Tests/Helpers/CourseContentTestHelper.cs, DigitalLearningSolutions.Data.Tests/Services/CourseContentServiceTests.cs, DigitalLearningSolutions.Data/Services/CourseContentService.cs
Modify the GetCourseContent query such that it returns a null progress entry for removed courses.
Ran and passed all unit tests and manually tested on Firefox.
=> HEEDLS-202 Create progress entry on reenrollment

DigitalLearningSolutions.Data.Migrations/202012021510_CandidateAssessmentSubmittedDate.cs, DigitalLearningSolutions.Data.Tests/Services/SelfAssessmentServiceTests.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/CurrentSelfAssessment.cs, DigitalLearningSolutions.Data/Services/SelfAssessmentService.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/FilteredResults.cs, DigitalLearningSolutions.Web/Helpers/MigrationHelperMethods.cs
Migration to add SubmittedDate field to CandidateAssessments. Service added to set submitted date when SA Submit button is first clicked. Added relevant data tests for service.
=> DLSV2-110 Candidate Assessment Submitted Date

DigitalLearningSolutions.Data.Tests/Services/CourseContentServiceTests.cs, DigitalLearningSolutions.Data/Models/CourseContent/CourseSection.cs, DigitalLearningSolutions.Data/Services/CourseContentService.cs, DigitalLearningSolutions.Web.Tests/TestHelpers/CourseSectionHelper.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/IntitialMenuViewModelTests.cs, DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/SectionCardViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/Section/Section.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/_SectionCard.cshtml
Add a blank section page for easier integration with backend later on.
Had to amend a lot of tests because section ID had to be added to the GetCourseContent query.
=> Add basic section page

DigitalLearningSolutions.Web/Styles/learningMenu/index.scss, DigitalLearningSolutions.Web/Views/LearningMenu/Index.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/_SectionCard.cshtml
=> Fix border for Initial Menu Page

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentCompetency.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentDescription.cshtml
=> DLSV2-113 Reads SA and Competency Descriptions in as HTML

DigitalLearningSolutions.Data.Tests/Services/TutorialContentServiceTests.cs, DigitalLearningSolutions.Data/Models/TutorialContent/TutorialContent.cs, DigitalLearningSolutions.Data/Services/TutorialContentService.cs
- Add service to get the contents of a given tutorial for that user.
- Add tests for this service.
Add unit tests for the service, all tests pass.
=> Add Tutorial Content Service

DigitalLearningSolutions.Web/Views/LearningMenu/Section/Section.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/_DiagnosticAssessmentCard.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/_PostLearningAssessmentCard.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/_TutorialCard.cshtml
Add hardcoded cards to section page, logic will need to be added later on to conditionally display the diagnostic and post learning assessment cards.
Screenshot of the page with hardcoded values:
=> HEEDLS-218 Tutorials and assessments list front end

DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs, DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs
- Fix session adding bug for invalid course
- Add tests to cover this
Add and modify the unit tests, and run them all.
=> HEEDLS-225 do not add session for invalid course

DigitalLearningSolutions.Data.Tests/Services/TutorialContentServiceTests.cs, DigitalLearningSolutions.Data/Models/TutorialContent/TutorialContent.cs, DigitalLearningSolutions.Data/Services/TutorialContentService.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs, DigitalLearningSolutions.Web.Tests/TestHelpers/TutorialContentHelper.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/TutorialViewModelTests.cs, DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs, DigitalLearningSolutions.Web/Startup.cs, DigitalLearningSolutions.Web/Styles/learningMenu/tutorial.scss, DigitalLearningSolutions.Web/ViewModels/LearningMenu/TutorialViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/Tutorial.cshtml
- Add course name to Tutorial Content
- Add a Tutorial view, and some CSS for that view
- Add a view model, and a controller action
- Add a controller and view model tests
Added and run unit tests for controller and view model. Tested on Chrome, Firefox, IE11, and Edge. Tested using a narrow viewport, high zoom and a screenreader.
=> HEEDLS-224 Tutorial page front end

DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs, DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs, DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/Tutorial.cshtml
- Add link to Play Tutorial button
- Add route to ContentViewer for this button to link to.
Unit tests still run. I can't think of any ways to test this outside of clicking the button and checking it works (which I have done). The ContentViewer action and view model will get more tests in the next ticket, all that's changed is a button's link and the route of the action.
=> HEEDLS-184 - Launch tutorial button

DigitalLearningSolutions.Data.Tests/Services/SectionContentServiceTests.cs, DigitalLearningSolutions.Data/Models/SectionContent/SectionContent.cs, DigitalLearningSolutions.Data/Services/SectionContentService.cs
I've stripped a lot of the stuff from the stored procedure and resulted in this query. I've tested that the query works but there are some weird things with it (such as the nested inner join). Do you have any suggestions on how to make this query better? And also whether it would be better to use Benji's query for courses and extend/change that. (Especially since in future I believe I will also need to do the multi mapping etc)
Once we've decided on the query I can begin writing the tests :D
=> HEEDLS-215 Section Page Basic Info Back End

DigitalLearningSolutions.Data.Tests/Services/TutorialContentServiceTests.cs, DigitalLearningSolutions.Data/Models/TutorialContent/TutorialContent.cs, DigitalLearningSolutions.Data/Models/TutorialContent/TutorialInformation.cs, DigitalLearningSolutions.Data/Services/TutorialContentService.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs, DigitalLearningSolutions.Web.Tests/TestHelpers/TutorialContentHelper.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/TutorialViewModelTests.cs, DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/TutorialViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/Tutorial.cshtml
- Rename `TutorialContent` to `TutorialInformation` - this is overall information for a tutorial
- Add a new `TutorialContent` class, to be used by the `ContentViewer` action and view
- Add a new `GetTutorialContent` method to the `TutorialContentService` to get one of these objects
- Add tests for this new `TutorialContentService` method
Add and run unit tests for this new method.
=> HEEDLS-227 SCORM Content viewer back end

DigitalLearningSolutions.Data.Tests/Services/CourseContentServiceTests.cs, DigitalLearningSolutions.Data/Models/CourseContent/CourseSection.cs, DigitalLearningSolutions.Data/Services/CourseContentService.cs, DigitalLearningSolutions.Web.Tests/TestHelpers/CourseSectionHelper.cs
Add extra fields to the query and class.
Amend the tests to use the new constructor.
=> HEEDLS-235 Show times on section cards back end

DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs, DigitalLearningSolutions.Web.Tests/TestHelpers/TutorialContentHelper.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/ContentViewerViewModelTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/TutorialViewModelTests.cs, DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs, DigitalLearningSolutions.Web/Styles/index.scss, DigitalLearningSolutions.Web/ViewModels/LearningMenu/ContentViewerViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/ContentViewer.cshtml
- Add parameters to ContentViewer view model to replace hard coded values.
- Get data from TutorialContentService in the Learning Menu Controller
to pass into the ContentViewer view.
- Add some CSS to control the page content based on whether JS is
enabled.
- Add tests to these methods.
Add some unit tests for controller and view model. Tested site using Chrome, 
Firefox, Edge and IE11, all with a screenreader, and with no-JS and high zoom in Chrome. 
- There are scrollbars on some of the HTML content as well as some of the 
SCORM content. See the last screenshot. Is this ok?
- The height for the `iframe` was fixed in the proof of concept code, but this can lead to scrollbars (eg. 2nd screenshot of SCORM player) that could be avoided by allowing it to be longer. Should we change this?
=> Add ContentViewer front end

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/SectionCardViewModelTest.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/SectionCardViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/_SectionCard.cshtml
Add time information to view, view model, and tests.
Ran and passed all unit tests and manually tested in Firefox.
=> HEEDLS-235 Show times on section cards front end

DigitalLearningSolutions.Data.Tests/Services/TutorialContentServiceTests.cs, DigitalLearningSolutions.Data/Exceptions/LogoNotFoundException.cs, DigitalLearningSolutions.Data/Exceptions/VideoNotFoundException.cs, DigitalLearningSolutions.Data/LogoNotFoundException.cs, DigitalLearningSolutions.Data/Models/Logo.cs, DigitalLearningSolutions.Data/Models/TutorialContent/TutorialVideo.cs, DigitalLearningSolutions.Data/Services/LogoService.cs, DigitalLearningSolutions.Data/Services/TutorialContentService.cs
- Add a `TutorialVideo` data model
- Add a `GetTutorialVideo` method to the `TutorialContentService`
- Add tests for this method
Add unit tests for the new method
=> HEEDLS-239 Add backend to get Tutorial videos

DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs, DigitalLearningSolutions.Web.Tests/Helpers/ContentUrlHelperTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/TutorialVideoViewModelTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/TutorialViewModelTests.cs, DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs, DigitalLearningSolutions.Web/Helpers/ContentUrlHelper.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/TutorialVideoViewModel.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/TutorialViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/Tutorial.cshtml
- Move Tutorial Video URL parser into helper class, ContentUrlHelper
- Add a nullable variant for the ContentUrl parser, and add tests.
- Modify the tutorial overview view model to parse and store the
supporting materials path.
- Update various classes to pass through the IConfiguration to the
tutorial view model.
Add more and update existing unit tests. Tested using Chrome, Firefox, Edge, and IE11, using a screen reader.
=> HEEDLS-185 Download supporting materials

DigitalLearningSolutions.Data.Tests/Services/SectionContentServiceTests.cs, DigitalLearningSolutions.Data/Models/SectionContent/SectionTutorial.cs, DigitalLearningSolutions.Data/Services/SectionContentService.cs, DigitalLearningSolutions.Web.Tests/TestHelpers/SectionTutorialHelper.cs
Needed to add the tutorial idea to a section tutorial so we can direct to the correct tutorial page
=> Add tutorial id to section tutorial

DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/SectionContentViewModelTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/TutorialCardViewModelTests.cs, DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/SectionContentViewModel.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/TutorialCardViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/Section/Section.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Section/_TutorialCard.cshtml
Integrated the tutorial information into the tutorial cards and also added the Time Information to solve HEEDLS-233.
The important changes are the ones to the cshtml and the two view models. Other changes were just to fix tests to have new information
=> Heedls 236 section page tutorials and assessments list integration

DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs, DigitalLearningSolutions.Web/Views/LearningMenu/Diagnostic/Diagnostic.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Section/_DiagnosticAssessmentCard.cshtml
Create the view using hardcoded values for the diagnostic assessment page.
Ran and passed all unit tests, screenshot taken in Firefox.
=> HEEDLS-241 Assessment page diagnostic front end

DigitalLearningSolutions.Web.Tests/TestHelpers/SectionContentHelper.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/SectionContentViewModelTests.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/SectionContentViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/Section/Section.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Section/_DiagnosticAssessmentCard.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Section/_PostLearningAssessmentCard.cshtml
Integration all complete and tests added, let me know if there are any tests missing. As the PR was getting a little big I decided not to do the bug fix HEEDLS-250 and will instead do that separately :D
=> HEEDLS-236-Section Page Assessments List Integration

DigitalLearningSolutions.Data.Tests/Services/SectionContentServiceTests.cs, DigitalLearningSolutions.Data/Services/SectionContentService.cs
Small bugfix to fix ordering of tutorials within the section page
=> HEEDLS-NONE- Add Tutorial ID to Order By

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/TutorialCardViewModelTests.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/TutorialCardViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/Section/_TutorialCard.cshtml
What do we think about the "(s)", would we prefer to just add some logic to the view model to display the s if val != 1?
=> HEEDLS-246 - Section Page Improve Time Information

DigitalLearningSolutions.Data.Tests/Helpers/DiagnosticAssessmentTestHelper.cs, DigitalLearningSolutions.Data.Tests/Services/DiagnosticAssessmentServiceTests.cs, DigitalLearningSolutions.Data/Models/DiagnosticAssessment/OldScores.cs, DigitalLearningSolutions.Data/Models/DiagnosticAssessment/OldTutorial.cs
Add some tests to compare results from the service class to results from stored procedures.
=> HEEDLS-NONE Assessment page diagnostic tests

DigitalLearningSolutions.Data.Tests/Services/CourseCompletionServiceTests.cs, DigitalLearningSolutions.Data/Models/CourseCompletion/CourseCompletion.cs, DigitalLearningSolutions.Data/Services/CourseCompletionService.cs
Make a CourseCompletionService and data model for the information required by the course completion page
Added unit tests for this service
=> HEEDLS-258 Back end for course completion summary

DigitalLearningSolutions.Data.Tests/Helpers/DiagnosticAssessmentTestHelper.cs, DigitalLearningSolutions.Data.Tests/Helpers/SectionContentTestHelper.cs, DigitalLearningSolutions.Data.Tests/Services/SectionContentServiceTests.cs, DigitalLearningSolutions.Data/Models/OldTutorial.cs, DigitalLearningSolutions.Data/Models/SectionContent/OldSectionTutorial.cs, DigitalLearningSolutions.Data/Models/SectionContent/SectionTutorial.cs, DigitalLearningSolutions.Data/Services/SectionContentService.cs, DigitalLearningSolutions.Web.Tests/TestHelpers/SectionTutorialHelper.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/SectionContentViewModelTests.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/SectionContentViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/Section/_DiagnosticAssessmentCard.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Section/_PostLearningAssessmentCard.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Section/_TutorialCard.cshtml
Fixing the bugs on ticket HEEDLS-178
Todo:
=> HEEDLS-178 Section Page Tutorials and Assessments List Bug Fixes

DigitalLearningSolutions.Data.Tests/Services/SectionContentServiceTests.cs, DigitalLearningSolutions.Data/Services/SectionContentService.cs
As both HEEDLS-178 and this are accessing the same things I have based this one off the changes from 178
=> HEEDLS-232 - Redirect To 404 if Customisation is not active

DigitalLearningSolutions.Data.Tests/Helpers/PostLearningAssessmentTestHelper.cs, DigitalLearningSolutions.Data.Tests/Services/PostLearningAssessmentTests.cs, DigitalLearningSolutions.Data/Models/PostLearningAssessment/OldPostLearningAssessmentScores.cs, DigitalLearningSolutions.Data/Models/PostLearningAssessment/PostLearningAssessment.cs, DigitalLearningSolutions.Data/Services/PostLearningAssessmentService.cs
Add query for retrieving post learning information.
Add unit tests and compare results to stored procedure.
=> HEEDLS-262 Assessment page post learning back end

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/SectionContentViewModelTests.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/SectionContentViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/Section/Section.cshtml
Horizontal rule added between Diagnostic assessment and tutorials. And another between tutorials and post learning assessments. Logic added to view model so separators are only displayed when necessary, tests have been written for these
=> HEEDLS-255 - Section Page Add Horizontal Rule

DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/SectionContentViewModelTests.cs, DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/SectionContentViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/Section/Section.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Section/_ConsolidationExerciseCard.cshtml
Added the front end for the consolidation button link as well as changes to view model to help with integration. Tests need to be changed/added once the backend is complete and these have been highlighted with comments.
=> HEEDLS-264 - Section Page Consolidation Exercise Frontend

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/ContentViewerViewModelTests.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/ContentViewerViewModel.cs
Add a tutorial ID query parameter to the tutorial iframe URLs.
Update the unit tests for this URL generation. I've not tested the changes in browser very thoroughly (it would be easier to do that on UAT I think) but it seems consistent
=> HEEDLS-266 Add tutorial ID to tutorial content iframe URL

DigitalLearningSolutions.Data/Models/PostLearningAssessment/PostLearningAssessment.cs, DigitalLearningSolutions.Data/Services/PostLearningAssessmentService.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs, DigitalLearningSolutions.Web.Tests/TestHelpers/DiagnosticAssessmentHelper.cs, DigitalLearningSolutions.Web.Tests/TestHelpers/PostLearningAssessmentHelper.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/PostLearningAssessmentViewModelTests.cs, DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs, DigitalLearningSolutions.Web/Startup.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/PostLearningAssessmentViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/Diagnostic/Diagnostic.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/PostLearning/PostLearning.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Section/_PostLearningAssessmentCard.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Shared/_AssessmentPageImportantInformation.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/_TutorialNextLink.cshtml
Create view for post learning page and add caption to diagnostic assessment page.
Integrate with back end by adding view model and controller logic.
Add tests for view model and controller.
Ran and passed all unit tests, screenshots taken in Firefox.
=> HEEDLS-263 Assessment page post learning front end

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/CourseCompletionViewModelTests.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/CourseCompletionViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/Completion/Completion.cshtml
* Add `null` checking to diagnostic score row
* Change finalise button naming logic to match completed course learning portal page
Amended unit tests, tested in Google Chrome
=> HEEDLS-192 Fix bugs in course completion front end

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/IntitialMenuViewModelTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/SectionCardViewModelTest.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/InitialMenuViewModel.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/SectionCardViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/Index.cshtml
Same as the last approved PR, I messed the branches up (it was going into the backend HEEDLS-273 branch, and I forgot to change the branch target to learning menu master before I merged). No changes have been made since the last branch was approved.
=> HEEDLS-274 initial menu page customisation front end

DigitalLearningSolutions.Data.Tests/Services/SectionContentServiceTests.cs, DigitalLearningSolutions.Data/Models/SectionContent/SectionContent.cs, DigitalLearningSolutions.Data/Services/SectionContentService.cs, DigitalLearningSolutions.Web.Tests/TestHelpers/SectionContentHelper.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/SectionContentViewModelTests.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/SectionContentViewModel.cs
This PR includes the integration so the entire system works
=> HEEDLS-265 - Section Page Consolidation Exercise Backend

DigitalLearningSolutions.Data.Tests/Helpers/DiagnosticAssessmentTestHelper.cs, DigitalLearningSolutions.Data.Tests/Services/DiagnosticAssessmentServiceTests.cs, DigitalLearningSolutions.Data/Models/DiagnosticAssessment/DiagnosticContent.cs, DigitalLearningSolutions.Data/Services/DiagnosticAssessmentService.cs
Create query for retrieving data for content viewer and add tests.
=> HEEDLS-276 Diagnostic assessment launch back end

DigitalLearningSolutions.Web/Views/LearningMenu/PostLearning/PostLearning.cshtml
Change the page header from the course title to the section name.
=> HEEDLS-189 Assessment page post learning bugfix

DigitalLearningSolutions.Data.Tests/Services/TutorialContentServiceTests.cs, DigitalLearningSolutions.Data/Models/TutorialContent/TutorialContent.cs, DigitalLearningSolutions.Data/Models/TutorialContent/TutorialInformation.cs, DigitalLearningSolutions.Data/Models/TutorialContent/TutorialVideo.cs, DigitalLearningSolutions.Data/Services/TutorialContentService.cs, DigitalLearningSolutions.Web.Tests/TestHelpers/TutorialContentHelper.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/ContentViewerViewModelTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/TutorialVideoViewModelTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/TutorialViewModelTests.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/ContentViewerViewModel.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/TutorialVideoViewModel.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/TutorialViewModel.cs
- Add section name to tutorial info, content and video classes.
- Add these section names to the view models of these pages.
Amend the tests to cover this new data.
=> HEEDLS-292 Use breadcrumbs backend

DigitalLearningSolutions.Web/Views/LearningMenu/Section/_DiagnosticAssessmentCard.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Section/_PostLearningAssessmentCard.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Section/_TutorialCard.cshtml
Minor change to the wording on the buttons to open the diagnostic pages and the tutorial page.
=> HEEDLS-285 Improve buttons wording on section page

README.md
The old query would just get the day in the date, e.g. 11 today. So it would return any date with day 11, for example 11th Nov last year. Which was not exactly what I wanted... 🤦
=> HEEDLS-NONE Improve useful queries in readme

DigitalLearningSolutions.Web/Styles/learningMenu/tutorial.scss, DigitalLearningSolutions.Web/Views/LearningMenu/Completion/Completion.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Diagnostic/Diagnostic.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Index.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/PostLearning/PostLearning.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Section/Section.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/ContentViewer.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/Tutorial.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/TutorialVideo.cshtml, DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml
* Add breadcrumbs to all of the views
* Remove all back links
* Tweak the next link in the tutorial page to play nice now a backlink is no longer present
Tested in Chrome, Firefox, IE11 and Edge, using no JS, narrow viewports and a screenreader.
=> HEEDLS-293 Add breadcrumbs to all learning menu views

DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml
Add `NavBreadcrumbs` section rendering to the learning menu layout.
Mirrors change made in HEEDLS-293 to learning-menu-master
=> HEEDLS-NONE Add breadcrumbs set by inner view to layout

DigitalLearningSolutions.Data.Tests/Helpers/SectionContentTestHelper.cs, DigitalLearningSolutions.Data.Tests/Services/SectionContentServiceTests.cs, DigitalLearningSolutions.Data/Models/SectionContent/SectionContent.cs, DigitalLearningSolutions.Data/Services/SectionContentService.cs, DigitalLearningSolutions.Web.Tests/TestHelpers/SectionContentHelper.cs
Backend complete and tests added. Only missing test case is when sectionNumber is shared by 2 sections as that case doesn't exist in the DB. The tests could potentially be parameterized but i'm not sure if it would have as good readability so let me know what you prefer :D
=> HEEDLS-220 - Section Page Next Button Backend

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/SectionContentViewModelTests.cs, DigitalLearningSolutions.Web/Styles/learningMenu/index.scss, DigitalLearningSolutions.Web/Styles/learningMenu/tutorial.scss, DigitalLearningSolutions.Web/ViewModels/LearningMenu/SectionContentViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/Section/Section.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Section/_SectionNextLink.cshtml
=> HEEDLS 221 Section Page Next Button Frontend

DigitalLearningSolutions.Web/DigitalLearningSolutions.Web.csproj, DigitalLearningSolutions.Web/Scripts/learningMenu/diagnosticContentViewer.ts, DigitalLearningSolutions.Web/Scripts/spec/diagnosticContentViewer.spec.ts, DigitalLearningSolutions.Web/Views/LearningMenu/Diagnostic/DiagnosticContent.cshtml
Implement page close and tests.
=> HEEDLS-278 Diagnostic assessment launch page close

DigitalLearningSolutions.Data.Tests/Services/SectionContentServiceTests.cs, DigitalLearningSolutions.Data/Services/SectionContentService.cs
Ensure that the next section page with all tutorials of Status and
DiagStatus of 0 has a post learning assessment path, as well as the
course being assessed.
Add a regression test.
=> HEEDLS-NONE Fix section page next link bug

DigitalLearningSolutions.Data.Tests/Models/CourseSettingsTests.cs, DigitalLearningSolutions.Data.Tests/Services/TutorialContentServiceTests.cs, DigitalLearningSolutions.Data/Models/CourseSettings.cs, DigitalLearningSolutions.Data/Models/TutorialContent/TutorialInformation.cs, DigitalLearningSolutions.Data/Services/TutorialContentService.cs, DigitalLearningSolutions.Web.Tests/TestHelpers/TutorialContentHelper.cs
* Add a "Supporting information" field to the course settings object
* Get course settings when getting tutorial information
Add some more unit tests to the course settings and tutorial service,
tweak some existing ones to make constructor signatures match.
=> HEEDLS-298 Add tutorial customisation back end

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/DiagnosticContentViewModelTests.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/DiagnosticContentViewModel.cs
Add a conditional assignment to view model tutorials.
Add new test.
=> HEEDLS-NONE Diagnostic assessment launch fix tutorials list

DigitalLearningSolutions.Data.Tests/Helpers/PostLearningAssessmentTestHelper.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/DiagnosticContentViewModelTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/PostLearningContentViewModelTests.cs, DigitalLearningSolutions.Web/Helpers/ContentViewerHelper.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/DiagnosticContentViewModel.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/PostLearningContentViewModel.cs
Implement view model and tests.
=> HEELDS-297 Post learning assessment launch view models

DigitalLearningSolutions.Data/Services/PostLearningAssessmentService.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs, DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs, DigitalLearningSolutions.Web/Views/LearningMenu/PostLearning/PostLearningContent.cshtml
Add view and controller logic.
Add controller tests.
Ran and passed all unit tests. Screenshot taken in Firefox.
=> HEEDLS-297 Post learning assessment launch front end

DigitalLearningSolutions.Data.Tests/Helpers/SectionContentTestHelper.cs, DigitalLearningSolutions.Data.Tests/Services/SectionContentServiceTests.cs, DigitalLearningSolutions.Data/Services/SectionContentService.cs
Some of these tests will also need to be done on the Diagnostic Assessment tests which I will do in a separate PR
=> HEEDLS-289 - Section Page Fix Diagnostic Assessment Scores

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/SectionContentViewModelTests.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/SectionContentViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/Section/Section.cshtml
=> HEEDLS-283 - Section Page Show Post Learning Status

DigitalLearningSolutions.Data.Tests/Helpers/PostLearningAssessmentTestHelper.cs, DigitalLearningSolutions.Data.Tests/Services/PostLearningAssessmentTests.cs, DigitalLearningSolutions.Data/Models/PostLearningAssessment/PostLearningAssessment.cs, DigitalLearningSolutions.Data/Services/PostLearningAssessmentService.cs, DigitalLearningSolutions.Web.Tests/TestHelpers/PostLearningAssessmentHelper.cs
=> HEEDLS-305 Post learning assessment next button back end

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/PostLearningAssessmentViewModelTests.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/PostLearningAssessmentViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/PostLearning/PostLearning.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/PostLearning/_PostLearningNextLink.cshtml
Implement front end and integrate.
Small change on section page for consistency.
Ran and passed all unit tests, screenshots taken in firefox
=> HEEDLS-306 Post learning assessment next button front end

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/DiagnosticAssessmentViewModelTests.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/DiagnosticAssessmentViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/Diagnostic/Diagnostic.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Diagnostic/_DiagnosticNextLink.cshtml
Add additional fields to view model.
Add view model tests.
Create new partial view for next button.
Add next button to view.
Ran and passed all unit tests, screenshot taken in Firefox and tested linking to tutorial, post learning, section, and finish.
=> HEEDLS-311 Diagnostic assessment next button front end

DigitalLearningSolutions.Web/Views/LearningMenu/_SectionCard.cshtml
Change "Launch section" to "View section" for the initial menu page
=> HEEDLS-303 - Initial Menu Improve Section Button

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/PostLearningAssessmentViewModelTests.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/PostLearningAssessmentViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/Diagnostic/Diagnostic.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/PostLearning/PostLearning.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Shared/_TutorialTimeSummary.cshtml
Split the post learning view model assessment status field.
Update view model tests.
Add hidden text to post learning assessment and diagnostic assessment pages.
Ran and passed all unit tests, tested screen reader in Firefox & Chrome.
=> HEEDLS-314 Assessment page improve voice over text

DigitalLearningSolutions.Web/Views/LearningMenu/Section/_TutorialCard.cshtml
Small typo causing formatting issue on front end
=> HEEDLS-307 - Section Page Show Diagnostic Recommendation Status Fix Typo

DigitalLearningSolutions.Data.Tests/Helpers/DiagnosticAssessmentTestHelper.cs, DigitalLearningSolutions.Data.Tests/Services/DiagnosticAssessmentDataServiceTests/DiagnosticAssessmentDataServiceNextTests.cs, DigitalLearningSolutions.Data.Tests/Services/DiagnosticAssessmentDataServiceTests/DiagnosticAssessmentDataServiceOtherItemAndSectionTests.cs, DigitalLearningSolutions.Data.Tests/Services/DiagnosticAssessmentDataServiceTests/DiagnosticAssessmentDataServiceTests.cs, DigitalLearningSolutions.Data/Models/DiagnosticAssessment/DiagnosticAssessment.cs, DigitalLearningSolutions.Data/Services/DiagnosticAssessmentDataService.cs
* Add single item in section field, and single section in course field to diagnostic assessment information.
* Add completion information to diagnostic assessment information.
* Move diagnostic assessment data tests to their own folder
* Add unit tests for these additional fields in separate partial class.
=> HEEDLS 319 One diagnostic assessment back end

DigitalLearningSolutions.Data/Services/CourseContentService.cs, DigitalLearningSolutions.Data/Services/DiagnosticAssessmentDataService.cs, DigitalLearningSolutions.Data/Services/PostLearningAssessmentService.cs, DigitalLearningSolutions.Data/Services/SectionContentService.cs, DigitalLearningSolutions.Data/Services/TutorialContentService.cs
Added some comments to the SQL queries. Do let me know if there is anything else I should be talking about 🙂
=> HEEDLS-NONE Add some comments to the data service SQL queries

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/TutorialViewModelTests.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/TutorialViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/Tutorial.cshtml
=> HEEDLS-326 - Tutorial Page - Change Button Text On Restart

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/DiagnosticAssessmentViewModelTests.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/DiagnosticAssessmentViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/Diagnostic/Diagnostic.cshtml
=> HEEDLS-327-Diagnostic Assessment Page Change Button Text On Restart

DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs, DigitalLearningSolutions.Web/appSettings.UAT.json, DigitalLearningSolutions.Web/appsettings.Development.json, DigitalLearningSolutions.Web/appsettings.Production.json, DigitalLearningSolutions.Web/appsettings.Test.json, DigitalLearningSolutions.Web/appsettings.json
`LegacyLearningMenu `bool setting added to app settings. If `true` then Learning Menu controller Index action redirects to old learning menu. If `false` then new menu is used.
=> DLSV2-151 config setting for learning menu

DigitalLearningSolutions.Data.Tests/Services/SelfAssessmentServiceTests.cs, DigitalLearningSolutions.Data/Services/SelfAssessmentService.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/SelfAssessmentTests.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs
And tweaks tests and calls accordingly
=> DLSV2-151 Reads min and max values from database in service method

DigitalLearningSolutions.Data/Services/SelfAssessmentService.cs
To service method. Tests should now run.
=> DLSV2-152 Adds handling of null assessment question

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/DiagnosticAssessmentViewModelTests.cs, DigitalLearningSolutions.Web/Styles/learningMenu/index.scss, DigitalLearningSolutions.Web/ViewModels/LearningMenu/DiagnosticAssessmentViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/Completion/Completion.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Diagnostic/Diagnostic.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Diagnostic/_DiagnosticNextLink.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/Tutorial.cshtml
Add ShowNextButton field to viewmodel.
Add tests for new field.
Replace next link with button aligned with start assessment button.
Hidden button
Link to first tutorial
Link to post learning assessment
Link to next section
Link to finish
Appearance with completion summary
=> HEEDLS-333-DiagnosticAssessmentChangeNextButton

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/PostLearningAssessmentViewModelTests.cs, DigitalLearningSolutions.Web/ViewModels/LearningMenu/PostLearningAssessmentViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/PostLearning/PostLearning.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/PostLearning/_PostLearningNextLink.cshtml
Add ShowNextButton field to viewmodel.
Add tests for new field.
Replace next link with button aligned with start assessment button.
Assessment not attempted
Assessment attempted and also with completion summary card.
=> HEEDLS-223 Post learning assessment change button

README.md
=> HEEDLS-NONE: Update readme reverting a migration section.

DigitalLearningSolutions.Data.Migrations/202103300939_FixSelfAssessmentUTCDates.cs, DigitalLearningSolutions.Data.Tests/Helpers/SelfAssessmentHelper.cs, DigitalLearningSolutions.Data.Tests/Helpers/TutorialContentTestHelper.cs, DigitalLearningSolutions.Data.Tests/Services/SelfAssessmentServiceTests.cs, DigitalLearningSolutions.Data/Services/SelfAssessmentService.cs, DigitalLearningSolutions.Web.Tests/TestHelpers/CompletedCourseHelper.cs, DigitalLearningSolutions.Web.Tests/TestHelpers/CurrentCourseHelper.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/CompletionSummaryCardViewModelTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/CourseCompletionViewModelTests.cs
I think this does everything that's needed. All tests pass locally.
=> DLSV2-166 Moves SelfAssessment and tests to use UTCDate

DigitalLearningSolutions.Web/Controllers/LoginController.cs, DigitalLearningSolutions.Web/DigitalLearningSolutions.Web.csproj, DigitalLearningSolutions.Web/Startup.cs, DigitalLearningSolutions.Web/appSettings.UAT.json, DigitalLearningSolutions.Web/appsettings.Development.json, DigitalLearningSolutions.Web/appsettings.Production.json, DigitalLearningSolutions.Web/appsettings.Test.json
Removing the login feature flag as it won't be required anymore, now that we are refactoring the user account functionality. The FeatureGate was not used elsewhere on the project.
=> HEEDLS-371: Remove login feature flag.

README.md
Rider works! 🎉 
Also left a note that migrations sometimes don't all run the first time.
=> docs: Update readme with Rider and migrations troubleshooting

DigitalLearningSolutions.Data/Services/PasswordResetService.cs, DigitalLearningSolutions.Web.Tests/Controllers/ForgotPassword/ForgotPasswordControllerTests.cs, DigitalLearningSolutions.Web/Controllers/ForgotPasswordController.cs, DigitalLearningSolutions.Web/ViewModels/ForgotPassword/ForgotPasswordViewModel.cs, DigitalLearningSolutions.Web/Views/ForgotPassword/Index.cshtml, DigitalLearningSolutions.Web/appsettings.Test.json
Added new content and fixed all bugs mentioned in the comments of https://softwiretech.atlassian.net/browse/HEEDLS-337 except for the "Skip to content" link skipping past the error summary - this will require further investigation, probably in another ticket. The ForgotPassword controller and Index page were refactored to use more generic components.
Tested manually in Chrome and ran all Unit tests.
=> HEEDLS-337 - Forgot Password bug fixes and refactoring

Jenkinsfile
Adding integration tests to Jenkins pipeline.
=> HEEDLS-362: Add integration tests to CI/CD pipeline.

DigitalLearningSolutions.Web/appsettings.Test.json
Should not have "/" in the end to match other envs.
=> HEEDLS-NONE: Fix app root path.

DigitalLearningSolutions.Web/Views/LearningMenu/Shared/_IFrameWithFullscreen.cshtml
=> DLSV2-169 Moves full screen button above content

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentReview.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_MeanScores.cshtml
Using question maxValue instead of fixing at /10
=> DLSV2-170 Reads SA Review out of score dynamically

DigitalLearningSolutions.Web/Views/FindYourCentre/Index.cshtml, DigitalLearningSolutions.Web/Views/LearningContent/Index.cshtml, DigitalLearningSolutions.Web/Views/Pricing/Index.cshtml
Added title attributes to the iframes for the automated tests
=> HEEDLS-NONE Add titles to iframes

DigitalLearningSolutions.Data.Tests/Services/NotificationPreferencesDataServiceTests.cs, DigitalLearningSolutions.Data/Models/NotificationPreference.cs, DigitalLearningSolutions.Data/Services/NotificationPreferenceService.cs, DigitalLearningSolutions.Data/Services/NotificationPreferencesDataService.cs, DigitalLearningSolutions.Web/Controllers/NotificationPreferencesController.cs, DigitalLearningSolutions.Web/Startup.cs, DigitalLearningSolutions.Web/ViewModels/MyAccount/NotificationPreferencesViewModel.cs, DigitalLearningSolutions.Web/Views/NotificationPreferences/Index.cshtml
Part 2, covering backend fetching of notification data
=> HEEDLS-346: get notification preferences in the backend

DigitalLearningSolutions.Web/Styles/myAccount/notificationPreferences.scss, DigitalLearningSolutions.Web/ViewModels/MyAccount/NotificationPreferencesViewModel.cs, DigitalLearningSolutions.Web/Views/NotificationPreferences/Index.cshtml, DigitalLearningSolutions.Web/Views/NotificationPreferences/_NotificationPreferenceList.cshtml
Final MR for HEEDLS-346, displaying the data in the front end.
=> HEEDLS-346: show notifications in front end

DigitalLearningSolutions.Data.Tests/Services/EmailServiceTests.cs, DigitalLearningSolutions.Data/Services/EmailService.cs
This is for UAT debugging (+ I ran the formatter)
=> HEEDLS-NONE: Add logging to email service.

DigitalLearningSolutions.Data/Mappers/MapperHelper.cs, DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests.cs, DigitalLearningSolutions.Web.AutomatedUiTests/DigitalLearningSolutions.Web.AutomatedUiTests.csproj, DigitalLearningSolutions.Web.AutomatedUiTests/SeleniumServerFactory.cs, DigitalLearningSolutions.sln, Jenkinsfile
Quick automated UI tests with Selenium + adding them to pipeline. Creating a MR now so people can start using these.
Left to do:
* Make error messages nicer and better readable. ==> Fixed.
Future work:
* Log in the user and test all the pages that user needs to be logged in for.
=> Automated UI tests 

DigitalLearningSolutions.Data/Services/EmailService.cs, DigitalLearningSolutions.Data/Services/FrameworkService.cs, DigitalLearningSolutions.Web/Helpers/ConfigHelper.cs
And fix to launchi9ng of certificates in legacy platform relating to DLSV2-173.
=> DLSV2-174 Fixes email service content encoding

DigitalLearningSolutions.Web/Styles/myAccount/myAccount.scss, DigitalLearningSolutions.Web/Views/MyAccount/Index.cshtml
Small css change to remove the left margin from the button for the mobile layout so they line up.
=> HEEDLS-393 Change left margin on button for mobile layout

Jenkinsfile
PR to send individual Slack notifications on pipeline failure.
=> HEEDLS-NONE: Individual Slack notifications.

DigitalLearningSolutions.Web.Tests/ControllerHelpers/ControllerContextHelper.cs, DigitalLearningSolutions.Web.Tests/Controllers/ForgotPassword/ForgotPasswordControllerTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/Login/LoginControllerTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/Logout/LogoutControllerTests.cs, DigitalLearningSolutions.Web.Tests/TestHelpers/LoginTestHelper.cs, DigitalLearningSolutions.Web/Controllers/LogoutController.cs, DigitalLearningSolutions.Web/Views/MyAccount/Index.cshtml, DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml
Does exactly what is says on the tin.
Tested manually in chrome, and ran all unit tests. Also tested the old site to make sure the shared cookie/session is affected properly to log the user out on the old site.
=> HEEDLS-348 - Implemented Log Out functionality

DigitalLearningSolutions.Web/Styles/home/learningContent.scss, DigitalLearningSolutions.Web/Views/Home/LearningContent.cshtml, DigitalLearningSolutions.Web/Views/Shared/MiniHub/_ContentsList.cshtml
Fixed `Current page` marking and link colours.
=> Heedls 338 landing page fixes

DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests.cs, DigitalLearningSolutions.Data.Tests/Services/UserServiceTests.cs, DigitalLearningSolutions.Data/DataServices/UserDataService.cs, DigitalLearningSolutions.Data/DigitalLearningSolutions.Data.csproj, DigitalLearningSolutions.Data/Services/ImageResizeService.cs, DigitalLearningSolutions.Data/Services/UserService.cs, DigitalLearningSolutions.Web/Attributes/AllowedExtensionsAttribute.cs, DigitalLearningSolutions.Web/Controllers/MyAccountController.cs, DigitalLearningSolutions.Web/Startup.cs, DigitalLearningSolutions.Web/Styles/index.scss, DigitalLearningSolutions.Web/Styles/myAccount/myAccount.scss, DigitalLearningSolutions.Web/ViewComponents/FileInputViewComponent.cs, DigitalLearningSolutions.Web/ViewModels/Common/FileInputViewModel.cs, DigitalLearningSolutions.Web/ViewModels/MyAccount/EditDetailsViewModel.cs, DigitalLearningSolutions.Web/Views/MyAccount/EditDetails.cshtml, DigitalLearningSolutions.Web/Views/Shared/Components/FileInput/Default.cshtml, DigitalLearningSolutions.Web/Views/Shared/Components/TextInput/Default.cshtml
Added the profile picture editor to the Edit Details screen. Added a FileInputViewComponent that is just a modified version of the TextInput so that I could have all the same error functionality. The rest of the image stuff is still in the main EditDetails view. I've added what I think are the allowed file types to the file input based on the old site, but I couldn't find anything for file size for the profile image. If we do need this we'll need to create another custom attribute to handle it.
Checked that the tab ordering makes sense, and that a screen reader reads it OK. Checked mobile layout in chrome devtools. Ran all unit tests
=> Heedls 405 edit details profile picture

DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests.cs, DigitalLearningSolutions.Web.AutomatedUiTests/SeleniumServerFactory.cs, DigitalLearningSolutions.Web/appsettings.SIT.json
Tested on Jenkins with a broken page to check we get expected errors on failed scans. 👍
=> HEEDLS-420 Accessibility scan for authenticated pages

DigitalLearningSolutions.Web/Controllers/FrameworksController/Frameworks.cs, DigitalLearningSolutions.Web/Styles/frameworks/frameworksShared.scss, DigitalLearningSolutions.Web/Views/Frameworks/Developer/AssessmentQuestion.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/AssessmentQuestionConfirm.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/AssessmentQuestionLevelDescriptor.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/AssessmentQuestionOptions.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/AssessmentQuestionScoring.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Branding.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Collaborators.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Competency.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/CompetencyGroup.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Description.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Name.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Review.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Similar.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Summary.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Type.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/_Structure.cshtml
Improvements include:
- Rewording of branding page to categorisation
- Restyling of cancel buttons to reduce chances of accidental clicking
- Fixing back button error message in create framework flow
- Send user to structure tab, improve tab styling and add explanation callout to empty framework
=> Fixes relating to interim Frameworks UX testing report

DigitalLearningSolutions.Web/Controllers/MyAccountController.cs, DigitalLearningSolutions.Web/Views/MyAccount/EditDetails.cshtml
Fixes the removal of profile pictures and changed the hint text to be less confusing.
=> HEEDLS-405 Fix remove profile picture and hint text

DigitalLearningSolutions.Data.Tests/DataServices/CentresDataServiceTests.cs, DigitalLearningSolutions.Data/DataServices/CentresDataService.cs, DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/TrackingSystem/CentreConfigurationViewModelTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/CentreConfigurationController.cs, DigitalLearningSolutions.Web/Styles/index.scss, DigitalLearningSolutions.Web/ViewComponents/TextAreaViewComponent.cs, DigitalLearningSolutions.Web/ViewModels/Common/TextAreaViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CentreConfigurationViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/EditCentreWebsiteDetailsViewModel.cs, DigitalLearningSolutions.Web/Views/Shared/Components/TextArea/Default.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/EditCentreWebsiteDetails.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/Index.cshtml
- Ran all unit tests
- Tested in Chrome, Firefox, Edge, IE11
- Checked with No JS, mobile view/zoom, screenreader
Screenshots of UI (with horrendous cropping):
=> HEEDLS-379 - Editing centre website details functionality implemented

DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests.cs
Added checks for the page heading (h1 element text) to the accessibility tests
=> HEEDLS-456 Check page title in accessibility tests

DigitalLearningSolutions.Web/Helpers/CustomClaimHelper.cs, DigitalLearningSolutions.Web/Helpers/CustomPolicies.cs, DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml, DigitalLearningSolutions.Web/Views/Shared/_NhsChevronRight.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/EditCentreManagerDetails.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/EditCentreWebsiteDetails.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/Index.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/RegistrationPrompts.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateApprovals/Index.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Shared/_NavMenuItems.cshtml
Modifed the navbar for the tracking system pages and changed the header home link for these pages
Again there are a load of line ending changes that should all now be CRLF
=> Heedls 449 tracking system navbar

DigitalLearningSolutions.Data.Migrations/202105210850_AddMapDisplayColumnToCentres.cs, DigitalLearningSolutions.Web/Helpers/MigrationHelperMethods.cs, README.md
Added ShowOnMap to Centres table.
Tested manually migrating up and then migration down to make sure both work. Also checked the default values are all good. Ran all unit tests.
=> HEEDLS-451 - New migration to add ShowOnMap cable to Centres table

DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests.cs, DigitalLearningSolutions.Data.Tests/Services/UserServiceTests.cs, DigitalLearningSolutions.Data/DataServices/UserDataService.cs, DigitalLearningSolutions.Data/Services/UserService.cs
Fixed an incorrect condition causing email validation to fail when unchanged. Added a couple of unit tests to check it.
=> HEEDLS-345 Fix incorrect boolean condition

SQLScripts/PopulateTestUsers.sql
Added the update statement to set up a candidate for the admin user at the same centre for accessibility tests
=> HEEDLS-455 Add extra change to test data to PopulateTestUsers

DigitalLearningSolutions.Web/Helpers/CustomClaimHelper.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/EditCentreManagerDetails.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/EditCentreWebsiteDetails.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/Index.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/RegistrationPrompts/AddRegistrationPromptSelectPrompt.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/RegistrationPrompts/EditRegistrationPrompt.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/RegistrationPrompts/Index.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateApprovals/Index.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Shared/_NavMenuItems.cshtml
Added navbar to the Edit Registration Prompt page and fixed the claims checking to actually check the value of the custom claims rather than just whether they have them.
=> HEEDLS-449 Add navbar to new page and fix claims checks

DigitalLearningSolutions.Web.Tests/ViewModels/TrackingSystem/CentreConfiguration/CentreConfigurationViewModelTests.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CentreConfiguration/CentreConfigurationViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/Index.cshtml
Ran all unit tests.
Manually tested on chrome.
=> HEEDLS-447 - Remove Preview On Website button when ShopOnMap is false.

DigitalLearningSolutions.Web/Styles/shared/cardWithButtons.scss
A small fix for issues with card text with long words on small screens.
=> HEEDLS-422 break words to avoid issues on mobile view

DigitalLearningSolutions.Data.Tests/DataServices/RegistrationDataServiceTests.cs
Disables the test that's breaking master while I try to find a way to fix it
=> (no ticket) Disabled broken RegistrationDataService test temporarily

Jenkinsfile
Add my email address and softwire username to the jenkinsfile for build notifications on Slack.
=> HEEDLS-NONE add user for individual slack notifications

DigitalLearningSolutions.Web.Tests/Controllers/Login/LoginControllerTests.cs, DigitalLearningSolutions.Web.Tests/Helpers/LoginClaimsHelperTests.cs, DigitalLearningSolutions.Web/Controllers/LoginController.cs, DigitalLearningSolutions.Web/Helpers/LoginClaimsHelper.cs
Refactor GetClaimsForSignIn into helper class; fix bug causing error when user has email=NULL; update which claims are set depending on user type; add some unit tests.
=> HEEDLS-476 Login Claims bug fix

DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Dashboard/CentreDashboardViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Dashboard/Index.cshtml
Added a check for if the first name is whitespace as well as null and linked the Edit centre details button to the centre configuration Index page
=> HEEDLS-466 Check for empty first name and link button

DigitalLearningSolutions.Web/Styles/viewComponents/textInput.scss, DigitalLearningSolutions.Web/ViewComponents/TextInputViewComponent.cs, DigitalLearningSolutions.Web/ViewModels/Common/TextInputViewModel.cs, DigitalLearningSolutions.Web/Views/Shared/Components/TextInput/Default.cshtml
@stellake The registration create-password page doesn't use the VC, so it still only shows one validation error per input. Do you want me to change that so it uses the VC as well?
=> HEEDLS-355: Show multiple validation errors in text input VC

DigitalLearningSolutions.Web/Controllers/ForgotPasswordController.cs, DigitalLearningSolutions.Web/Controllers/LoginController.cs, DigitalLearningSolutions.Web/Controllers/MyAccountController.cs, DigitalLearningSolutions.Web/Controllers/RegisterController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/CentreConfiguration/RegistrationPromptsController.cs, DigitalLearningSolutions.Web/ViewModels/Common/PasswordViewModel.cs, DigitalLearningSolutions.Web/ViewModels/ForgotPassword/ForgotPasswordViewModel.cs, DigitalLearningSolutions.Web/ViewModels/Login/LoginViewModel.cs, DigitalLearningSolutions.Web/ViewModels/MyAccount/EditDetailsViewModel.cs, DigitalLearningSolutions.Web/ViewModels/Register/RegisterViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CentreConfiguration/AddRegistrationPromptConfigureAnswersViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CentreConfiguration/EditCentreManagerDetailsViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CentreConfiguration/EditCentreWebsiteDetailsViewModel.cs, DigitalLearningSolutions.Web/Views/LearningPortal/Current/RemoveCurrentCourseConfirmation.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/Current/SetCompleteByDate.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/Current/UnlockCurrentCourse.cshtml, DigitalLearningSolutions.Web/Views/Login/Index.cshtml, DigitalLearningSolutions.Web/Views/MyAccount/EditDetails.cshtml, DigitalLearningSolutions.Web/Views/NotificationPreferences/UpdateNotificationPreferences.cshtml
Update error messages and validation for consistency and conformity with NHS/GOV guidelines and database.
Affected parts:
- Log in
- Forgot password
- Reset password
- Registration
- Edit details (my account)
- Centre configuration forms
- Edit centre manager details
- Edit centre details on DLS website
- Add registration prompts
- Edit registration prompts
=> HEEDLS-419 Consistent error messages and validation

DigitalLearningSolutions.Data/Services/RegistrationService.cs, DigitalLearningSolutions.Web/Controllers/RegisterController.cs, DigitalLearningSolutions.Web/Views/Register/Password.cshtml, DigitalLearningSolutions.Web/Views/Register/Summary.cshtml
Fixes various issues raised in testing:
* All error summaries should show errors in the order that the form fields appear
* Job group and centre are now entered on different pages so the error where you don't select a centre is not applicable any more
* Input VCs are being updated elsewhere to show all errors
* Error summary link on the summary page has been fixed
* Approval link in the confirmation email has been updated to the new approvals page
=> HEEDLS-347 Testing markups

DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/RegistrationPrompts/RemoveRegistrationPrompt.cshtml
Updated the wording and spacing on the remove confirmation page
=> HEEDLS-381 Change wording and spacing

DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/_CentreConfigurationCentreDetails.cshtml
Changed the text of the Preview button to Preview certificate
=> HEEDLS-486 Rename preview button

DigitalLearningSolutions.Web/Controllers/LearningContentController.cs, DigitalLearningSolutions.Web/Styles/index.scss, DigitalLearningSolutions.Web/ViewModels/LearningContent/LearningContentViewModel.cs, DigitalLearningSolutions.Web/Views/FindYourCentre/Index.cshtml, DigitalLearningSolutions.Web/Views/Home/LearningContent.cshtml, DigitalLearningSolutions.Web/Views/Home/Products.cshtml, DigitalLearningSolutions.Web/Views/Home/Welcome.cshtml, DigitalLearningSolutions.Web/Views/LearningContent/Index.cshtml
Updated Learning Content iframes to use new titles, with new breadcrumb. 
Changes iframes to have a min-height of 500px on desktops so they are a little more useable. Mobile has been left as it is to minimise confusion on the reliance of two scrollers.
Other minor changes also performed.
Ran all unit tests,
Tested in chrome,
Checked with screenreader
Example screen shot of learning content page:
=> HEEDLS-483 - Home and Iframe accessibility bug fixes.

DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/_CentreConfigurationCentreDetails.cshtml
Changed the preview button to open in new page
=> HEEDLS-486 Make preview certificate link open in new tab

DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/EditCentreManagerDetails.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/EditCentreWebsiteDetails.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateApprovals/DelegateRejectionPage.cshtml
More spacing fixes, this time for:
Edit centre manager details:
Edit centre website details:
Delegate approvals reject page:
=> HEEDLS-528 Refactor Tracking system views to fix inconsistent spacing

DigitalLearningSolutions.Web/Scripts/searchSortAndPaginate/sort.ts, DigitalLearningSolutions.Web/Scripts/spec/sort.spec.ts
Fixed the sort properties in the javascript after I changed them for the no javascript version
=> HEEDLS-415 Fix sort properties not being picked up correctly

DigitalLearningSolutions.Data/Enums/Enumeration.cs, DigitalLearningSolutions.Web/ModelBinders/EnumerationModelBinder.cs
- Add flag to ignore case in TryGetFromIdOrName method in Enumeration
- Ignore case when matching with enumerations in model binder
=> HEEDLS-429 Notification preferences endpoints case insensitivity

DigitalLearningSolutions.Web.Tests/Helpers/FilterableTagHelperTests.cs, DigitalLearningSolutions.Web.Tests/Helpers/FilteringHelperTests.cs, DigitalLearningSolutions.Web.Tests/ViewComponents/CurrentFiltersViewComponentTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/TrackingSystem/Centre/Administrator/CentreAdministratorsViewModelTests.cs, DigitalLearningSolutions.Web/Helpers/FilterOptions/AdminFilterOptions.cs, DigitalLearningSolutions.Web/Helpers/FilterableTagHelper.cs, DigitalLearningSolutions.Web/Helpers/FilteringHelper.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Administrator/CentreAdministratorsViewModel.cs
Changed filters so that filters in the same group work like an OR rather than an AND.
=> HEEDLS-532 Make filters in the same category OR not AND

DigitalLearningSolutions.Data.Tests/Services/RegistrationServiceTests.cs, DigitalLearningSolutions.Data/Services/RegistrationService.cs, DigitalLearningSolutions.Web.Tests/Controllers/Register/RegisterControllerTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/Support/SupportControllerTests.cs, DigitalLearningSolutions.Web/Controllers/Register/RegisterController.cs, DigitalLearningSolutions.Web/Controllers/Register/RegisterDelegateByCentreController.cs, DigitalLearningSolutions.Web/Controllers/Support/SupportController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Administrator/AdministratorController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Dashboard/ContractDetailsController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Dashboard/DashboardController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Dashboard/RankingController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Dashboard/TopCoursesController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Reports/ReportsController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/CentreConfiguration/CentreConfigurationController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/CentreConfiguration/RegistrationPromptsController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/CourseSetup/CourseSetupController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/AllDelegatesController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateApprovalsController.cs, DigitalLearningSolutions.Web/DigitalLearningSolutions.Web.csproj, DigitalLearningSolutions.Web/Helpers/FeatureFlags.cs, DigitalLearningSolutions.Web/Startup.cs, DigitalLearningSolutions.Web/Views/ApplicationSelector/Index.cshtml, DigitalLearningSolutions.Web/Views/_ViewImports.cshtml, DigitalLearningSolutions.Web/appSettings.UAT.json, DigitalLearningSolutions.Web/appsettings.Development.json, DigitalLearningSolutions.Web/appsettings.Production.json, DigitalLearningSolutions.Web/appsettings.SIT.json, DigitalLearningSolutions.Web/appsettings.Test.json, DigitalLearningSolutions.Web/appsettings.json
Documentation here for context.
https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/19639795799/Feature+flags
This is to be able to release the main website without any references to the refactored Tracking system (I think I found all the references - fingers crossed).
Tested manually by changing the development appsettings.
=> HEEDLS-549: Refactored Tracking system feature flag

DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Administrator/_SearchableAdminCard.cshtml
Fixed capitalisation of 'Manage roles'
=> HEEDLS-416 Fix capitalisation of link

DigitalLearningSolutions.Data.Tests/DataServices/CentresDataServiceTests.cs, DigitalLearningSolutions.Data/DataServices/CentresDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/CentreConfiguration/CentreConfigurationControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/CentreConfiguration/CentreConfigurationController.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CentreConfiguration/EditCentreWebsiteDetailsViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/EditCentreWebsiteDetails.cshtml
Removed the show on map checkbox from the Edit centre website details page
=> HEEDLS-543 Remove Show on map checkbox from edit centre details

DigitalLearningSolutions.Web/Scripts/trackingSystem/reports.ts, DigitalLearningSolutions.Web/Styles/trackingSystem/reports.scss, DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Reports/Index.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Reports/_ActivityGraph.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Reports/_ActivityTable.cshtml, DigitalLearningSolutions.Web/package-lock.json, DigitalLearningSolutions.Web/package.json
=> Heedls 458 add chartist package

DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Ranking/Index.cshtml
Increased the width of the region dropdown.
Note that this build failed unit tests because master is currently broken, will have to wait until that is resolved.
=> HEEDLS-469 Make region filter wider

Jenkinsfile
Adding myself to the Jenkinsfile for slackbot notifications
=> HEEDLS-NONE add olizor to jenkins

DigitalLearningSolutions.Web.AutomatedUiTests/DigitalLearningSolutions.Web.AutomatedUiTests.csproj
_HEEDLS-NONE_
Updated the chromedriver version to 92 so that automated UI tests run
N/A
-----
I have:
=> HEEDLS-NONE Update chromedriver version

DigitalLearningSolutions.Data.Tests/DataServices/TutorialContentDataServiceTests/TutorialContentDataServiceTests.cs, DigitalLearningSolutions.Data.Tests/DataServices/TutorialContentDataServiceTests/TutorialContentTests.cs, DigitalLearningSolutions.Data.Tests/DataServices/TutorialContentDataServiceTests/TutorialInformationNextTutorialAndSectionTests.cs, DigitalLearningSolutions.Data.Tests/DataServices/TutorialContentDataServiceTests/TutorialInformationOtherItemAndSectionTests.cs, DigitalLearningSolutions.Data.Tests/DataServices/TutorialContentDataServiceTests/TutorialInformationTests.cs, DigitalLearningSolutions.Data.Tests/DataServices/TutorialContentDataServiceTests/TutorialVideoTests.cs, DigitalLearningSolutions.Data.Tests/DigitalLearningSolutions.Data.Tests.csproj, DigitalLearningSolutions.Data/DataServices/TutorialContentDataService.cs, DigitalLearningSolutions.Data/Services/DiagnosticAssessmentDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/TutorialContentTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/TutorialTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/TutorialVideoTests.cs, DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs, DigitalLearningSolutions.Web/Startup.cs
https://softwiretech.atlassian.net/browse/HEEDLS-440
Refactored TutorialContentService into DataService.
N/A
-----
I have:
=> HEEDLS-440 - refactored TutorialContentService into DataService

DigitalLearningSolutions.Data.Tests/Services/SelfAssessmentServiceTests.cs, DigitalLearningSolutions.Data/Services/SelfAssessmentService.cs
DLSV2-269
Fixes bug introduced with previous branch pull request and related breaking test
=> DLSV2-269 Fixes bug with results RAG query

DigitalLearningSolutions.Web/Views/RegisterAdmin/PersonalInformation.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-562
Added a missing cancel back link in the register admin journey.
-----
I have:
=> HEEDLS-562 Add cancel back link to register admin first page

DigitalLearningSolutions.Data.Tests/DataServices/CustomPromptsDataServiceTests.cs, DigitalLearningSolutions.Data.Tests/Services/CustomPromptsServiceTests.cs, DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Data/DataServices/CustomPromptsDataService.cs, DigitalLearningSolutions.Data/Models/CustomPrompts/CourseCustomPromptsResult.cs, DigitalLearningSolutions.Data/Models/CustomPrompts/CustomPrompt.cs, DigitalLearningSolutions.Data/Services/CustomPromptsService.cs, DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests/EditCourseAdminFieldsAccessibilityTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/CourseSetup/AdminFieldsControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/CourseSetup/AdminFieldsController.cs, DigitalLearningSolutions.Web/Models/AddAdminFieldData.cs, DigitalLearningSolutions.Web/Models/EditAdminFieldData.cs, DigitalLearningSolutions.Web/Startup.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Configuration/RegistrationPrompts/BulkRegistrationPromptAnswersViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/AdminFieldAnswersViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/AdminFieldsViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/BulkAdminFieldAnswersViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/CourseCustomPromptManagementViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/EditAdminFieldViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/RemoveAdminFieldViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/BulkAdminFieldAnswers.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/EditAdminField.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/_AdminFieldAnswerTable.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/_AdminFieldCard.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/_NoConfiguredAnswers.cshtml, SQLScripts/AddAdminFieldToCustomisationForTest.sql
[_HEEDLS-437_](https://softwiretech.atlassian.net/browse/HEEDLS-437)
Adds a page to edit course admin field answers and a page to edit them in bulk. 
-----
I have:
=> Heedls 437 edit course admin fields

DigitalLearningSolutions.Web/Scripts/common.ts, DigitalLearningSolutions.Web/Scripts/searchSortFilterAndPaginate/filter.ts
https://softwiretech.atlassian.net/browse/HEEDLS-417
IE fix for the javascript filtering since IE does stuff a different way for some reason.
N/A
-----
I have:
=> HEEDLS-417 IE javascript event fix

Jenkinsfile
A quick change in the pipeline stages order.
=> HEEDLS-NONE: Move TS lint together with TS build stage.

DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/TopCourses/Index.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-470
Reorganised columns to match description in comment on ticket
-----
I have:
=> HEEDLS-470 - rename and reorganise top courses columns

DigitalLearningSolutions.Web.AutomatedUiTests/TestFixtures/AccessibilityTestsFixture.cs
[HEEDLS-572](https://softwiretech.atlassian.net/browse/HEEDLS-572)
Dispose of SeleniumServerFactory correctly
N/A.
-----
I have:
=> HEEDLS-572 Faster automated UI tests fix

DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests/AdminUserDataServiceTests.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/AdminUserDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Centre/Administrator/AdministratorControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Administrator/AdministratorController.cs, DigitalLearningSolutions.Web/Styles/trackingSystem/centreAdministrators.scss, DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Administrator/_SearchableAdminCard.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-425
Unlock account button on centre admins page now unlocks the account.
N/A
-----
I have:
=> HEEDLS-425 - Implemented unlocking of admin accounts

DigitalLearningSolutions.Data.Tests/DataServices/GroupsDataServiceTests.cs, DigitalLearningSolutions.Data.Tests/DigitalLearningSolutions.Data.Tests.csproj, DigitalLearningSolutions.Data/DataServices/GroupsDataService.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateGroupsController.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/DelegateGroups/GroupDelegatesRemoveViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateGroups/GroupDelegatesRemove.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-515
Make the progress checkbox conditional and fix a layout issue with long group names.
-----
I have:
=> Heedls 515 remove delegate from group

DigitalLearningSolutions.Data/Services/FrameworkNotificationService.cs, DigitalLearningSolutions.Data/Services/FrameworkService.cs, DigitalLearningSolutions.Data/Services/SupervisorService.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs
DLSV2-298
Sets Ordering value when inserting assessment questions.
=> DLSV2-298 Fixes assessment question ordering

DigitalLearningSolutions.Web.Tests/Helpers/FilteringHelperTests.cs, DigitalLearningSolutions.Web/Helpers/FilteringHelper.cs, DigitalLearningSolutions.Web/Scripts/searchSortFilterAndPaginate/filter.ts, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/AllDelegates/_SearchableDelegateCard.cshtml
[HEEDLS-492](https://softwiretech.atlassian.net/browse/HEEDLS-492)
- Fix new filter not being added if substring of existing filters
- Fix long names overflowing and not wrapping on delegate card
-----
I have:
=> HEEDLS-492 All delegates - Filter - fix

DigitalLearningSolutions.Data/Models/SessionData/SelfAssessments/SessionRequestVerification.cs, DigitalLearningSolutions.Data/Models/Supervisor/CandidateAssessmentSupervisor.cs, DigitalLearningSolutions.Data/Services/FrameworkNotificationService.cs, DigitalLearningSolutions.Data/Services/SelfAssessmentService.cs, DigitalLearningSolutions.Data/Services/SupervisorService.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/VerificationPickResultsViewModel.cs, DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/VerificationPickSupervisorViewModel.cs, DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/VerificationSummaryViewModel.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/AddSupervisorSummary.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/VerificationPickResults.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/VerificationPickSupervisor.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/VerificationSummary.cshtml
DLSV2-263
Implements three-step request verification flow (choose supervisor, choose results, summary/confirm) using standard temp data approach with email request to supervisor.
=> DLSV2-263 Implements request verification flow

DigitalLearningSolutions.Web.Tests/Helpers/DateHelperTests.cs, DigitalLearningSolutions.Web/Helpers/DateHelper.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/CourseDelegates/_SearchableCourseDelegateCard.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-563
Bug fixes for the time display, word wrapping and button displayed when it shouldn't be.
-----
I have:
=> HEEDLS-563 Fix button being display when it shouldn't and time wording

DigitalLearningSolutions.Web/ViewModels/MyAccount/MyAccountViewModel.cs, DigitalLearningSolutions.Web/Views/MyAccount/_AccountSummaryCard.cshtml, DigitalLearningSolutions.Web/Views/MyAccount/_MyDetailsCard.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-598
Add the delegate AliasID to the My Account basic details card if it is populated and fix capitalisation of "My details"
-----
I have:
=> HEEDLS-598 Add alias ID to My Account page

DigitalLearningSolutions.Web.AutomatedUiTests/DigitalLearningSolutions.Web.AutomatedUiTests.csproj
N/A
Update chrome driver
N/A
-----
I have:
=> HEEDLS-NONE Update chrome driver

DigitalLearningSolutions.Data.Migrations/202109230834_AddManageOptionalCompetenciesPromptToSelfAssessments.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/SelfAssessment.cs, DigitalLearningSolutions.Data/Services/SelfAssessmentService.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/ManageOptionalCompetenciesViewModel.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/ManageOptionalCompetencies.cshtml
DLSV2-343
Presents custom optional competencies prompt text in the self assessment Manage optional competencies view:
- Migration to add ManageOptionalCompetenciesPrompt string 500 field to SelfAssessments table
- Loads ManageOptionalCompetenciesPrompt into view model and present in Manage Optional Competencies view if exists
=> DLSV2-343 Present custom optional competencies prompt

DigitalLearningSolutions.Web/Views/NotificationPreferences/Index.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-601
Add breadcrumbs to the notification preferences page
-----
I have:
=> Heedls 601 notification preferences breadcrumbs

DigitalLearningSolutions.Web/Controllers/HomeController.cs, DigitalLearningSolutions.Web/Controllers/LearningContentController.cs, DigitalLearningSolutions.Web/Views/Home/Products.cshtml
Make sure the names of learning content are capitalised correctly.
_HEEDLS-616_
Tiny capitalisation change without changes to UI/styling or functionality.
=> HEEDLS-616: Change capitalisation of learning content and sub-sections.

DigitalLearningSolutions.Web/Views/Home/LearningContent.cshtml
_HEEDLS-616_
Made a capitalisation amendment based on David's comment on 616, and asked Kevin to make the same amendment to the old site, for consistency across the two sites (and the iframe on the refactored site).
=> HEEDLS-616: Modify capitalisation to match new iframe content.

.github/pull_request_template.md
It's so meta.
NA
Made it more explicit that you should leave the developer checks unticked if not appropriate for your ticket.
See this description.
-----
Do I include the new line here? Well, why not.
_(Leave tasks unticked if they haven't been appropriate for your ticket.)_
I have:
=> docs: Update pr checklist

DigitalLearningSolutions.Data.Tests/Services/TrackerServiceTests.cs, DigitalLearningSolutions.Data/Enums/TrackerEndpointAction.cs, DigitalLearningSolutions.Data/Enums/TrackerEndpointErrorResponse.cs, DigitalLearningSolutions.Data/Models/Tracker/TrackerEndpointQueryParams.cs, DigitalLearningSolutions.Data/Services/TrackerService.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/TrackerController.cs, DigitalLearningSolutions.Web/Startup.cs
https://softwiretech.atlassian.net/browse/HEEDLS-583
Add a basic tracker endpoint and basic scaffolding for future implementations on it.
N/A
-----
I have:
=> HEEDLS-583 Add basic tracker endpoint

DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/ManageOptionalCompetencies.cshtml
DLSV2-355 DLSV2-362
Fixes routing of get/post methods for optional capabilities which was mismatched after adding competency vocabulary to route.
Removes descriptions from manage optional competencies view.
=> DLSV2-355 DLSV2-362 Routing fix and remove descriptions

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentCompetency.cshtml
DLSV2-358
Adds conditional label to Submit button so that it continues to read "Save and continue" in linear self-assessments
=> DLSV2-358 Adds conditional label to Submit button

DigitalLearningSolutions.Data/Models/SelfAssessments/SupervisorSignOff.cs, DigitalLearningSolutions.Data/Services/FrameworkNotificationService.cs, DigitalLearningSolutions.Data/Services/SelfAssessmentService.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/SelfAssessmentTests.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/RequestSignOffViewModel.cs, DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/SelfAssessmentOverviewViewModel.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/RequestSignOff.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml
DLSV2-303
Implements request self-assessment sign-off interface:
- Displays existing sign-off requests and status in Overview
- Provides request sign-off button if all results submitted and verified
- Implements choose supervisor for sign-off request interface
- Notifies supervisor by email (with reminder link)
=> DLSV2-303 Implements self-assessment sign-off requests

DigitalLearningSolutions.Data/Services/SupervisorService.cs, DigitalLearningSolutions.Web/Views/Supervisor/Index.cshtml
DLSV2-365
Fixes sign-off request count query and dashboard labelling in Supervisor dashboard.
=> DLSV2-365 Fixes sign-off request count query and dashboard labelling

DigitalLearningSolutions.Data.Tests/Services/UserServiceTests.cs, DigitalLearningSolutions.Data/Services/UserService.cs
https://softwiretech.atlassian.net/browse/HEEDLS-613
Fixed a bug with email validation causing it to reject emails when the case didn't match a user's other account.
N/A
-----
I have:
=> HEEDLS-613 Change email change validation to ignore case

SQLScripts/UpdateUsersAndSelfAssessmentsForTests.sql
Added cases for new entities already existing.
=> Make new test data SQL script idempotent

SQLScripts/uspUpdateAdminUser_v2_SP_AddFrameworkDevRole.sql
DLSV2-407
Adds create or alter script for Update Admin User V2 SP missing from live after publish on 08/11/21
This should be run and is safe to run on all test / dev databases.
=> DLSV2-407 Adds create or alter script for SP missing from live 

SQLScripts/SetFrameworkPermissionsForAdmin.sql
DLSV2-408
Script to run on test db to set admin frameworks permissions
=> DLSV2-408 Script to set admin framework permissions for test db

SQLScripts/CreateOrAlterReorderFramerworkCompetenciesAndGroupsSPs.sql
DLSV2-410
Adds create or alter SP scripts to the SQLScripts folder to ensure they are added to any Test DBs affected by the issue with the original script which included a USING statement that prevented them from being applied to the test DB during migration.
=> DLSV2-410 Add reorder sp scripts to scripts folder

DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests/AdminUserDataServiceTests.cs, DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests/DelegateUserDataServiceTests.cs, DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests/UserDataServiceTests.cs, DigitalLearningSolutions.Data.Tests/Services/PasswordResetServiceTests.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/AdminUserDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/DelegateUserDataService.cs, DigitalLearningSolutions.Data/Services/PasswordResetService.cs, DigitalLearningSolutions.Web.Tests/Controllers/ForgotPassword/ForgotPasswordControllerTests.cs, DigitalLearningSolutions.Web/Controllers/ForgotPasswordController.cs, SQLScripts/20211103_UpdateResetPasswordIdForTests.sql
https://softwiretech.atlassian.net/browse/HEEDLS-448
-----
I have:
=> Heedls 448 remove old hash

DigitalLearningSolutions.Data.Migrations/202111181057_UpdateLearningLogItemsTable.cs, DigitalLearningSolutions.Data.Migrations/202111181218_UpdateAppointmentTypesTableToActivityTypes.cs, DigitalLearningSolutions.Data.Migrations/202111181337_AddCandidateAssessmentLearningLogItemsTable.cs, DigitalLearningSolutions.Data.Migrations/202111181348_AddLearningLogItemCompetenciesTable.cs
https://softwiretech.atlassian.net/browse/HEEDLS-663
https://softwiretech.atlassian.net/browse/HEEDLS-668
https://softwiretech.atlassian.net/browse/HEEDLS-669
Adds migrations to alter the LearningLogItems and AppoinmentTypes tables, and create new tables CandidateAssessmentLearningLogItems and LearningLogItemCompetencies
N/A
-----
I have:
=> Heedls 663 signposting migrations learning log

DigitalLearningSolutions.Web/DigitalLearningSolutions.Web.csproj, DigitalLearningSolutions.Web/Scripts/checkboxGroup.ts, DigitalLearningSolutions.Web/Scripts/learningPortal/selfAssessment.ts, DigitalLearningSolutions.Web/Scripts/supervisor/verifyMultipleResults.ts, DigitalLearningSolutions.Web/Styles/learningPortal/selfAssessment.scss, DigitalLearningSolutions.Web/Styles/shared/searchableElements/common.scss, DigitalLearningSolutions.Web/Styles/supervisor/verifyMultipleResults.scss, DigitalLearningSolutions.Web/ViewModels/Supervisor/ReviewSelfAssessmentViewModel.cs, DigitalLearningSolutions.Web/Views/Supervisor/VerifyMultipleResults.cshtml
https://hee-dls.atlassian.net/browse/DLSV2-335
Added "Select all" and "Deselect all" buttons for capabilities.
-----
After completing an assessment, go to "Digital Capability Self Assessment" and press "Verify multiple results" button. It should display capabilities with "Select/Deselect all" buttons for each group.
=> DLSV2-335 Add select all, deselect all competencies in group to verify multiple results

DigitalLearningSolutions.Data.Migrations/202111231427_IncreaseSelfassessmentSignOffRequestorStatementLength.cs, DigitalLearningSolutions.Data.Migrations/202111231708_IncreaseSelfassessmentSignOffSupervisorStatementLength.cs
None
Cherrypicked migration merged to master by HEE at 10:10 this morning
-----
I have:
=> Cherry pick migrations onto release

DigitalLearningSolutions.Data.Tests/DataServices/CompetencyLearningResourcesDataServiceTests.cs, DigitalLearningSolutions.Data.Tests/DataServices/LearningLogItemsDataServiceTests.cs, DigitalLearningSolutions.Data.Tests/DataServices/SelfAssessmentDataServiceTests.cs, DigitalLearningSolutions.Data.Tests/Services/ActionPlanServiceTests.cs, DigitalLearningSolutions.Data.Tests/TestHelpers/CompetencyLearningResourcesTestHelper.cs, DigitalLearningSolutions.Data.Tests/TestHelpers/LearningLogItemsTestHelper.cs, DigitalLearningSolutions.Data/DataServices/CompetencyLearningResourcesDataService.cs, DigitalLearningSolutions.Data/DataServices/LearningLogItemsDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService.cs, DigitalLearningSolutions.Data/Models/LearningResources/CompetencyLearningResource.cs, DigitalLearningSolutions.Data/Models/LearningResources/LearningLogItem.cs, DigitalLearningSolutions.Data/Services/ActionPlanService.cs, DigitalLearningSolutions.Data/Services/LearningHubApiService.cs, DigitalLearningSolutions.Web/Startup.cs
https://softwiretech.atlassian.net/browse/HEEDLS-652
Add back end code for the Add to action plan functionality
N/A
-----
I have:
=> HEEDLS-652 Add back end code to add resource to action plan

DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/ManageCourse/EditAutoRefreshOptions.cshtml
[_HEEDLS-442_](https://softwiretech.atlassian.net/browse/HEEDLS-444)
Just fixed a few typos in the view, and changed the cancel link to a back link to match the wireframe. 
-----
I have:
=> HEEDLS-442 Fix typos and change cancel to back link

DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/Shared/_DelegateProfileAssessmentGrid.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/Shared/_NavMenuItems.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/Shared/_StaffMemberCard.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/SignOffProfileAssessment.cshtml
[DLSV2-432](https://hee-dls.atlassian.net/browse/DLSV2-432)
Removes the word "profile" throughout the Supervisor interface views.
=> DLSV2-432 Removes "Profile" term throughout supervisor interface

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml
[DLSV2-435](https://hee-dls.atlassian.net/browse/DLSV2-435)
Tiny tweak to Self Assessment Overview razor view to remove the count of competencies from the "Manage optional competencies" link button.
=> DLSV2-435 Removes count from link

DigitalLearningSolutions.Data/Services/SupervisorService.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/DigitalLearningSolutions.Web.csproj, DigitalLearningSolutions.Web/Scripts/supervisor/assessmentVerify.ts, DigitalLearningSolutions.Web/ViewModels/Supervisor/ReviewCompetencySelfAsessmentViewModel.cs, DigitalLearningSolutions.Web/Views/Supervisor/ReviewCompetencySelfAsessment.cshtml, DigitalLearningSolutions.Web/appsettings.Development.json
https://hee-dls.atlassian.net/browse/DLSV2-429
Replaced checkbox “Verify self-assessment response" to Verify and Reject radio option
-----
I have:
- [Y ] Run the formatter and made sure there are no IDE errors.
- [ Y] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ Y] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [ Y] Scanned over my own MR to ensure everything is as expected.
=> DLSV2-429 Added verify updates

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_OverviewTable.cshtml
[DLSV2-436](https://hee-dls.atlassian.net/browse/DLSV2-436)
Adds missing view data to first assessment question cells partial view to fix broken View Notes link in first assessment question for competency.
=> DLSV2-436 Adds missing view data value from partial

DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Views/Supervisor/SignOffProfileAssessment.cshtml
[DLSV2-433](https://hee-dls.atlassian.net/browse/DLSV2-433)
Replaced verify checkbox with verify and reject radio button. check for the client and server side validation
-----
I have:
- [ Y] Run the formatter and made sure there are no IDE errors.
- [ Y] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ Y] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [ Y] Scanned over my own MR to ensure everything is as expected.
=> Added sign off updates

DigitalLearningSolutions.Data.Tests/TestHelpers/SelfAssessmentHelper.cs
DLSV2-438
Fixes create default assessment question helper to include new Required param
=> DLSV2-438 Update SelfAssessmentHelper.cs to fix tests

DigitalLearningSolutions.Web/appsettings.Production.json
_HEEDLS-693_
Just changed value of UseSignposting in the production config to false
-----
I have:
=> HEEDLS-693 Change production value to false

DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml
[DLSV2-427](https://hee-dls.atlassian.net/browse/DLSV2-427)
Fixes breadcrumb nav backlink dom position missed in previous PR.
=> DLSV2-427 Updates ReviewSelfAssessment.cshtml with correctly positioned backlink

DigitalLearningSolutions.Data.Tests/DataServices/TutorialContentDataServiceTests/ObjectiveTests.cs, DigitalLearningSolutions.Data.Tests/Services/TrackerActionServiceTests.cs, DigitalLearningSolutions.Data.Tests/Services/TrackerServiceTests.cs, DigitalLearningSolutions.Data/DataServices/TutorialContentDataService.cs, DigitalLearningSolutions.Data/Enums/TrackerEndpointAction.cs, DigitalLearningSolutions.Data/Models/Tracker/CcObjective.cs, DigitalLearningSolutions.Data/Models/Tracker/Objective.cs, DigitalLearningSolutions.Data/Models/Tracker/ObjectiveBase.cs, DigitalLearningSolutions.Data/Models/Tracker/TrackerEndpointQueryParams.cs, DigitalLearningSolutions.Data/Models/Tracker/TrackerObjectiveArrayCc.cs, DigitalLearningSolutions.Data/Services/TrackerActionService.cs, DigitalLearningSolutions.Data/Services/TrackerService.cs
HEEDLS-409
Added second tracker endpoint action with relevant tests.
N/A
-----
I have:
=> Heedls 409 tracker endpoint getobjectivearraycc

README.md
Updated Readme with docs on running migrations via CLI
-----
I have:
=> docs: Add to readme "How to run migrations by CLI "

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentCompetency.cshtml
[DLSV2-450](https://hee-dls.atlassian.net/browse/DLSV2-450)
Fixes typo in the routing (asp-route-competencyGroupId) of the form.
=> DLSV2-450 Update SelfAssessmentCompetency.cshtml to fix form routing typo

DigitalLearningSolutions.Web/Views/Supervisor/ReviewCompetencySelfAsessment.cshtml
[DLSV2-429](https://hee-dls.atlassian.net/browse/DLSV2-429)
Markup changes in .cshtml merged in PR #766 have been overwritten in subsequent commits to master. This PR reinstates them
=> DLSV2-429 Reinstates radio button markup and .js ref

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs
[DLSV2-453](https://hee-dls.atlassian.net/browse/DLSV2-453)
Prevents inserting of duplicate assessment enrolments from the Available activities list in Learning Portal.
=> DLSV2-453 Prevents inserting of duplicate assessment enrolments

DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/DelegateProgress/EditCompleteByDateFormData.cs
https://softwiretech.atlassian.net/browse/HEEDLS-569
Fixed the capitalisation in the validation message
-----
I have:
=> HEEDLS-569 Fix capitalisation in validation error message

DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/SetSupervisorRoleViewModel.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SetSupervisorRole.cshtml
[DLSV2-455](https://hee-dls.atlassian.net/browse/DLSV2-455)
Repurposes existing choose supervisor role interface and reworks controller to handle setting role outside of the full add supervisor flow when supervisor delegate id is passed in.
=> DLSV2-455 Implements choose role for quick add supervisor

DigitalLearningSolutions.Web/Views/MyAccount/_MyDetailsCard.cshtml
=> HEEDLS-685 change capitalisation of PRN row

DigitalLearningSolutions.Web/Views/LearningPortal/Current/MarkActionPlanResourceAsComplete.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateProgress/EditCompleteByDate.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateProgress/EditCompletionDate.cshtml
[_HEEDLS-664_](https://softwiretech.atlassian.net/browse/HEEDLS-664)
Increased the bottom margin on the date input on the Mark resource as complete page, so when there is a validation error the red line doesn't touch the save button.
I noticed the Edit complete by date and Edit completion date pages for Delegate progress also had this issue so I took the liberty of adding the same margin there for consistency.
-----
I have:
=> HEEDLS-664 Increase bottom margin on completed/complete by date inputs

DigitalLearningSolutions.Web.Tests/Controllers/Frameworks/FrameworkControllerTests.cs, DigitalLearningSolutions.Web/Controllers/FrameworksController/AssessmentQuestions.cs, DigitalLearningSolutions.Web/Controllers/FrameworksController/Comments.cs, DigitalLearningSolutions.Web/Controllers/FrameworksController/Competencies.cs, DigitalLearningSolutions.Web/Controllers/FrameworksController/Frameworks.cs, DigitalLearningSolutions.Web/Controllers/FrameworksController/FrameworksController.cs, DigitalLearningSolutions.Web/Controllers/FrameworksController/ImportCompetencies.cs, DigitalLearningSolutions.Web/Controllers/FrameworksController/Review.cs, DigitalLearningSolutions.Web/Controllers/FrameworksController/Signposting.cs
[DLSV2-463](https://hee-dls.atlassian.net/browse/DLSV2-463)
Improves handling of null variables and fixes other formatting problems to improve and standardise code in the Frameworks controller.
=> DLSV2-463 Fix warnings throughout Frameworks controller

DigitalLearningSolutions.Web/Views/LearningPortal/Current/MarkActionPlanResourceAsComplete.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateProgress/EditCompletionDate.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/EmailDelegates/Index.cshtml
[_HEEDLS-670_](https://softwiretech.atlassian.net/browse/HEEDLS-670)
The previous MR involved a change to the hint text on the date input component, I've fixed a few implementations of the component that I had forgot about.
-----
I have:
=> HEEDLS-670 Fix hint text on implementations of date input component

DigitalLearningSolutions.Web.AutomatedUiTests/DigitalLearningSolutions.Web.AutomatedUiTests.csproj
N/A
Update chrome driver to version 97.
N/A
-----
I have:
=> HEEDLS-NONE Update chrome driver to version 97

DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests/LearningPortalAccessibilityTests.cs, DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests/SelfAssessmentAccessibilityTests.cs, DigitalLearningSolutions.Web/Views/LearningPortal/Current/SetCompleteByDate.cshtml
[_HEEDLS-670_](https://softwiretech.atlassian.net/browse/HEEDLS-670)
Fixed the title on the page to say "complete by date" rather than "completion date"
-----
I have:
=> HEEDLS-670 Fix title wording for Set complete by date

DigitalLearningSolutions.Web/appSettings.UAT.json, DigitalLearningSolutions.Web/appsettings.Development.json, DigitalLearningSolutions.Web/appsettings.Production.json, DigitalLearningSolutions.Web/appsettings.SIT.json, DigitalLearningSolutions.Web/appsettings.Test.json, DigitalLearningSolutions.Web/appsettings.json
Update URL for open API in config for various environments to point to test api (and prod to prod api).
I have:
=> config: Point DLS to correct LH open API envs

DigitalLearningSolutions.Data/Services/SupervisorService.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/ManageSupervisors.cshtml
[DLSV2-473](https://hee-dls.atlassian.net/browse/DLSV2-473)
Fixes errors introduced when refactoring the SelfAssessment controller. Some post method URL routing templates were mistakenly removed. These have been returned so that data is posted and processed properly in this flow.
=> DLSV2-473 Fixes problems posting data in manage supervisor flows

README.md
Add some FluentMigrator docs
-----
I have:
=> docs: Document some FluentMigrator behaviour

DigitalLearningSolutions.Data/Services/TrackerActionService.cs
[_HEEDLS-413_](https://softwiretech.atlassian.net/browse/HEEDLS-413)
Changed LogWarning to LogError so the StoreDiagnosticException is logged in the Exception column
-----
I have:
=> HEEDLS-413 Log store diagnostic exception

DigitalLearningSolutions.Web/Controllers/FrameworksController/Signposting.cs
https://hee-dls.atlassian.net/browse/DLSV2-443
Set default values when no question selected and parameter is new.
- Go to Competency Resource Signposting
- Click "Add resource"
- Search for "test"
- Select first resource
- Click "Confirm"
- Click "Skip"
- Click "Next"
=> DLSV2-443 Bug fixing: setting default values after adding resource from api

DigitalLearningSolutions.Web/Helpers/GenericSearchHelper.cs, DigitalLearningSolutions.Web/ViewModels/Support/Faqs/FaqsPageViewModel.cs
[https://softwiretech.atlassian.net/browse/HEEDLS-520](https://softwiretech.atlassian.net/browse/HEEDLS-520)
Adjust fuzzy sharp config for FAQs to better align search with JS search.
-----
I have:
=> HEDLS-520 FAQ search fixes

DigitalLearningSolutions.Web/Styles/shared/searchableElements/pagination.scss, DigitalLearningSolutions.Web/Views/Shared/PaginatedPage/_PaginationNav.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-627
Added some css to fix the cursor being reset to default on the button
-----
I have:
=> HEEDLS-627 Add css to fix the pagination button cursor

DigitalLearningSolutions.Web/Styles/trackingSystem/delegates/courseDelegates.scss, DigitalLearningSolutions.Web/Styles/trackingSystem/selectCourse.scss
[_HEEDLS-551_](https://softwiretech.atlassian.net/browse/HEEDLS-551)
Added a missing scss file which is why some styles were breaking on test
-----
I have:
=> HEEDLS-551 Add selectCourse.scss file

DigitalLearningSolutions.Web.Tests/ViewModels/TrackingSystem/CourseSetup/CourseSetupViewModelTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/CourseSetup/CourseSetupController.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/CourseSetupViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/Index.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-626
Add custom items per page to the Centre Course Setup page
-----
I have:
=> HEEDLS-626 Add variable result count to Centre Course Setup

DigitalLearningSolutions.Data/Models/Supervisor/SupervisorDelegateDetail.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/ViewModels/Supervisor/SupervisorDelegateViewModel.cs, DigitalLearningSolutions.Web/Views/Supervisor/RemoveConfirm.cshtml
https://hee-dls.atlassian.net/browse/DLSV2-486
Added mandatory confirmation checkbox to the current supervisor confirmation removal page.
=> DLSV2-486 Added mandatory confirmation checkbox for removing supervisor

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentDescription.cshtml
[DLSV2-495](https://hee-dls.atlassian.net/browse/DLSV2-495)
Simplifies navigation buttons on the self assessment description page:
- The continue button has been relabelled "Continue from where I left off" and is only shown if the bookmark is not the overview page.
- The "Go to capability 1" button is only displayed if the bookmark is null.
- The styling of the buttons has also been tweaked so that there is always a primary navigation button.
=> DLSV2-495 Reworks self assessment description nav buttons

DigitalLearningSolutions.Web/Scripts/trackingSystem/addGroupDelegate.ts, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateGroupsSideNavMenu.cshtml
[https://softwiretech.atlassian.net/browse/HEEDLS-514](https://softwiretech.atlassian.net/browse/HEEDLS-514)
Fix the JS search capabilities.
Note: Unrelated fix to delegate group side nav bar link
-----
I have:
=> HEEDLS-514 Add delegate to group fixes

DigitalLearningSolutions.Web/Controllers/TrackingSystem/TrackerController.cs
[https://softwiretech.atlassian.net/browse/HEEDLS-777](https://softwiretech.atlassian.net/browse/HEEDLS-777)
Add the tracking system feature flag to the tracker endpoint
-----
I have:
=> HEEDLS-777 Add feature flag to tracker endpoint

DigitalLearningSolutions.Web.IntegrationTests/AuthenticatedTests/Signposting/LinkLearningHubSsoTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/Signposting/SignpostingSsoControllerTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/Signposting/LinkLearningHubViewModelTests.cs, DigitalLearningSolutions.Web/Controllers/Signposting/SignpostingSsoController.cs, DigitalLearningSolutions.Web/ViewModels/Signposting/LinkLearningHubViewModel.cs, DigitalLearningSolutions.Web/Views/Signposting/LinkLearningHubSso.cshtml
[https://softwiretech.atlassian.net/browse/HEEDLS-681](https://softwiretech.atlassian.net/browse/HEEDLS-681)
- Update header text
- Fix grammar in content
- Merge `Signposting` namespaces
Highlighted in yellow are the changes made.
-----
I have:
=> HEEDLS-681 LH SSO Account Link page test fixes

DigitalLearningSolutions.Data/Services/FrameworkNotificationService.cs
[DLSV2-485](https://hee-dls.atlassian.net/browse/DLSV2-485)
Adds the name of the competency group in brackets after the name of the competency in competency review emails.
=> DLSV2-485 Adds group name to competency reviewed email

DigitalLearningSolutions.Web/Views/Supervisor/Shared/_StaffMemberCard.cshtml
[DLSV2-501](https://hee-dls.atlassian.net/browse/DLSV2-501)
Fixes bug caused by passing incorrect model to staff member card partial.
=> DLSV2-501 Fixes issue by passing correct model to partial

DigitalLearningSolutions.Web.Tests/ViewComponents/CurrentFiltersViewComponentTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/TrackingSystem/Centre/Administrator/CentreAdministratorsViewModelTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Administrator/AdministratorController.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Administrator/CentreAdministratorsViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Administrator/Index.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-625
Add custom items per page to the Centre Admins page
-----
I have:
=> HEEDLS-625 Set up custom items per page for centre admins page

DigitalLearningSolutions.Web/appSettings.UAT.json, DigitalLearningSolutions.Web/appsettings.Production.json
Merge release into master after https://softwiretech.atlassian.net/browse/HEEDLS-761
Bug fix was applied to release branch for 761. This PR is to merge those changes from release to master.
N/A
-----
I have:
=> Release 22.2.1

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentExportDataService.cs
[DLSV2-504](https://hee-dls.atlassian.net/browse/DLSV2-504)
Fixes query to return information about self assessment sign-off for excel export. The data was previously being pulled based on  an incorrect join.
=> DLSV2-504 Fixes query to retrieve sign-off info for excel export

DigitalLearningSolutions.Web/appSettings.UAT.json
DLSV2-505
Tweaks UAT app settings to switch on Excel export during Critical Care Steps testing.
=> DLSV2-505 switches on Excel Export in UAT app settings

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_OverviewTable.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/Shared/_AssessmentQuestionOverviewCells.cshtml
DLSV2-506
Adds "status" to "Self-assessment" column header on the self assessment overview screen.
=> DLSV2-506 Tweaks column header for self assessment overview

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentDescription.cshtml
DLSV2-508
Urgent fix for null handling in self assessment description.
=> DLSV2-508 check for null before assigning val

DigitalLearningSolutions.Web/Views/MyAccount/_AccountSummaryCard.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateApprovals/_unapprovedDelegateExpandable.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-708
Searched through the ViewModels and Views for incorrectly cased ID display strings. Found them in the Delegate Approvals and My Account pages.
-----
I have:
=> HEEDLS-708 Fix ID casing in my account and unapproved delegates

DigitalLearningSolutions.Data.Tests/DataServices/CourseDataServiceTests.cs
Increased time tolerance for test that was failing on master. In the failing test runs there was a discrepancy of just over 700ms.
Also did a bit of refactoring.
For ease of review:
* First commit is actual change
* Second commit is refactor
-----
I have:
=> Fix increase test time tolerance

DigitalLearningSolutions.Data/Models/CustomPrompts/CentreCustomPrompts.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/ViewModels/Supervisor/AddMemberOfStaffViewModel.cs, DigitalLearningSolutions.Web/ViewModels/Supervisor/MyStaffListViewModel.cs, DigitalLearningSolutions.Web/Views/Supervisor/MyStaffList.cshtml
When adding a member of staff, check that email address was entered and the text seems to be an email address. 
https://hee-dls.atlassian.net/browse/DLSV2-509
Implemented standard email validation used in DLS. Before my changes, email address was being posted back to server but validation requires a model, so I have added new field to the model. Since the model inherits from `BaseSearchablePageViewModel`, I'e fixed related issues with .Net binder not being able to map properties. Binder requires parameterless constructor and this cannot be created without initialising readonly properties in the base class.
=> DLSV2-509 Add required validation and email validation to the Add Staff text box

DigitalLearningSolutions.Web.Tests/Helpers/ProfessionalRegistrationNumberHelperTests.cs, DigitalLearningSolutions.Web/Helpers/ProfessionalRegistrationNumberHelper.cs, DigitalLearningSolutions.Web/Views/MyAccount/EditDetails.cshtml, DigitalLearningSolutions.Web/Views/Register/LearnerInformation.cshtml, DigitalLearningSolutions.Web/Views/Shared/_EditRegistrationNumber.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/EditDelegate/Index.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-794
Fixed issues with error summaries for PRN for Edit Delegate, My Account Edit Details and Register Journey. Fields will now show errors in the order of the inputs, with better text.
-----
I have:
=> HEEDLS-794 Fix error message issues with PRN fields

DigitalLearningSolutions.Web/Views/Supervisor/SignOffProfileAssessment.cshtml
[DLSV2-515](https://hee-dls.atlassian.net/browse/DLSV2-515)
The Supervisor sign-off hint displayed as plain text, this change allows it to display HTML markup.
=> DLSV2-515 Adds html raw to supervisor sign-off hint

DigitalLearningSolutions.Data.Tests/Helpers/LinkedFieldHelperTests.cs, DigitalLearningSolutions.Data.Tests/Services/GroupServiceTests/GroupsServiceSynchroniseGroupsTests.cs, DigitalLearningSolutions.Data/Helpers/LinkedFieldHelper.cs, DigitalLearningSolutions.Data/Services/GroupsService.cs
_HEEDLS-805_
This is just a second pull request for 805 because I forgot to change the base branch on the last one to master, and merged it into the branch I originally based it on. All these changes were approved.
-----
I have:
=> Heedls 805 synchronise groups bugfix

DigitalLearningSolutions.Data/Services/FrameworkNotificationService.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Views/LearningPortal/ConfirmSupervisor.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentCompetency.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SupervisorComments.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/VerificationPickResults.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/VerificationPickSupervisor.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/VerificationSummary.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_CompetencySummary.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_OverviewActionButtons.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_OverviewTable.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/Shared/_AssessmentQuestionStatusTag.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/Index.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/ReviewCompetencySelfAsessment.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/Shared/_AssessmentQuestionResponse.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/Shared/_AssessmentQuestionReviewCells.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/Shared/_AssessmentQuestionStatusTag.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/Shared/_ProfileAssessmentStatusTag.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/SignOffProfileAssessment.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/VerifyMultipleResults.cshtml
Change verify for confirm throughout the Supervisor and Self Assessment interface and email notifications.
https://hee-dls.atlassian.net/browse/DLSV2-514
Updated user interface 
Url ending with **_Supervisor/Staff/1002/ProfileAssessment/1/ConfirmMultiple_**
-----
Checked that:
- "Confirm multiple results" button still works after renaming the url as "/ConfirmMultiple"
=> DLSV2-514 Change verify for confirm for Supervisor, SelfAssessment and email notifications.

DigitalLearningSolutions.Data.Tests/DataServices/CourseDataServiceTests.cs, DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Data/Models/Courses/DelegateCourseInfo.cs, DigitalLearningSolutions.Data/Models/DetailedProgress.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/CourseDelegates/DelegateProgressViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/DelegateProgress/DetailedCourseProgressViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateProgress/DetailedProgress.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateProgress/Index.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateProgress/_DelegateDetails.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateProgress/_DelegateProgressSummary.cshtml
[_HEEDLS-795_](https://softwiretech.atlassian.net/browse/HEEDLS-795)
Added PRN fields to the tables on Delegate Progress and Detailed Delegate Progress pages
Delegate progress:
Detailed delegate progress:
-----
I have:
=> HEEDLS-795 Add PRN to delegate progress pages

DigitalLearningSolutions.Web/Scripts/trackingSystem/reports.ts
https://softwiretech.atlassian.net/browse/HEEDLS-599
Adjusted the calculations being used to set the positions of the labels in IE
Loads of screenshots at various label numbers/window sizes:
-----
I have:
=> HEEDLS-599 Adjust the label translation function for IE

DigitalLearningSolutions.Web/Scripts/trackingSystem/courseDelegates.ts, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/CourseDelegates/Index.cshtml
_[HEEDLS-778](https://softwiretech.atlassian.net/browse/HEEDLS-778)_
_Updated the export button and hint on the course delegates page._
-----
I have:
=> HEEDLS-778 : Update export button and hint

DigitalLearningSolutions.Web/appsettings.Test.json
N/A
Follow up to https://github.com/TechnologyEnhancedLearning/DLSV2/pull/1027
I had missed a change that needed to be fixed. It is being fixed here.
N/A
-----
I have:
=> HEEDLS-NONE - a further correction that was previously missed.

DigitalLearningSolutions.Web/Properties/PublishProfiles/PublishToUARTest.pubxml, Jenkinsfile
_[HEEDLS-812](https://softwiretech.atlassian.net/browse/HEEDLS-812)_
Changed the jenkinsfile to point to a new publish profile with different values for `DeployIisAppPath` and `SiteUrlToLaunchAfterPublish`.
N/A
-----
I have:
=> HEEDLS-812 set up jenkinsfile and publish profile to publish to hee_dls_uar_test_zoo_lan folder and hee-dls-sql.zoo.lan/uar-test

DigitalLearningSolutions.Web/Scripts/searchSortFilterAndPaginate/search.ts
https://softwiretech.atlassian.net/browse/HEEDLS-647
Changed the uid we're inputting into js-search so it doesn't remove duplicate items.
-----
I have:
=> HEEDLS-647 Fix search on duplicate items

DigitalLearningSolutions.Data.Tests/Services/UserServiceTests.cs, DigitalLearningSolutions.Data/Services/UserService.cs
https://softwiretech.atlassian.net/browse/HEEDLS-841
Fall back to deactivating the admin account when an exception occurs when attempting to delete the account.
N/A
-----
I have:
=> HEEDLS-841 Deactivate admin when deletion fails

DigitalLearningSolutions.Web.AutomatedUiTests/DigitalLearningSolutions.Web.AutomatedUiTests.csproj
Chrome driver update
-----
I have:
=> HEEDLS-NONE Chrome driver 100 update

Jenkinsfile
_HEEDLS-831_
Commenting out the Data tests stage in the Jenkins file because the new migration causes many tests to fail.
-----
I have:
=> UAR-831 Comment out data tests in Jenkinsfile

Jenkinsfile
_HEEDLS-831_
Comment out Automated UI TEsts from Jenkins file because the new migrations break them
-----
I have:
=> HEEDLS-831 Comment out Automated UI Tests in Jenkinsfile

DigitalLearningSolutions.Data.Migrations/202203161448_RestructureAdminAndDelegateTables.cs, DigitalLearningSolutions.Data.Migrations/Scripts/UAR-831-CreateViewsForAdminUsersAndCandidatesTables-UP.sql
[_HEEDLS-831_](https://softwiretech.atlassian.net/browse/HEEDLS-831)
Rename AdminID and CandidateID each to ID
-----
I have:
=> UAR-831 restructure admin and delegate tables

DigitalLearningSolutions.Data.Migrations/202204071100_SnapshotData.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.Designer.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.resx, DigitalLearningSolutions.Data.Migrations/Scripts/UAR-858-SnapshotData-UP.sql
https://softwiretech.atlassian.net/browse/HEEDLS-858
Adds a migration to snapshot the current database, saving in the default location with a timestamp name.
N/A
-----
I have:
=> HEEDLS-858 Add migration to snapshot database before data migration

DigitalLearningSolutions.Data/Services/ImportCompetenciesFromFileService.cs, DigitalLearningSolutions.Web/Views/Frameworks/Developer/ImportCompetencies.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/ImportFailed.cshtml
When user tries to import a spreadsheet that is not formatted as a table
[DLSV2-542](https://hee-dls.atlassian.net/browse/DLSV2-542)
Improves import instructions to correct cell references and include instructions about formatting data as a table. Uses the import error view to alert the user when they try to upload data that is not formatted as a table.
=> DLSV2-542 Improves instructions and error messages for import from Excel

DigitalLearningSolutions.Data.Tests/DataServices/BrandsDataServiceTests.cs, DigitalLearningSolutions.Data.Tests/Services/BrandsServiceTests.cs, DigitalLearningSolutions.Data/DataServices/BrandsDataService.cs, DigitalLearningSolutions.Data/Services/BrandsService.cs, DigitalLearningSolutions.Web.Tests/ServiceFilter/RedirectEmptySessionDataTests.cs, DigitalLearningSolutions.Web.Tests/ServiceFilter/VerifyAdminUserCanAccessAdminUserTests.cs, DigitalLearningSolutions.Web.Tests/ServiceFilter/VerifyAdminUserCanAccessDelegateUserTests.cs, DigitalLearningSolutions.Web.Tests/ServiceFilter/VerifyAdminUserCanAccessProgressTests.cs, DigitalLearningSolutions.Web.Tests/ServiceFilter/VerifyAdminUserCanManageCourseTests.cs, DigitalLearningSolutions.Web.Tests/ServiceFilter/VerifyAdminUserCanViewCourseTests.cs, DigitalLearningSolutions.Web.Tests/ServiceFilter/VerifyDelegateCanAccessActionPlanResourceTests.cs, DigitalLearningSolutions.Web.Tests/ServiceFilter/VerifyDelegateProgressAccessedViaValidRouteTests.cs, DigitalLearningSolutions.Web/Controllers/HomeController.cs, DigitalLearningSolutions.Web/Startup.cs, DigitalLearningSolutions.Web/ViewModels/Home/LearningContentLandingPageViewModel.cs, DigitalLearningSolutions.Web/ViewModels/Home/LearningContentSummary.cs, DigitalLearningSolutions.Web/Views/Home/LearningContent.cshtml, DigitalLearningSolutions.Web/Views/Home/_LearningContentCard.cshtml
(_HEEDLS-864_)[https://softwiretech.atlassian.net/browse/HEEDLS-864]
_Changed Home/Learning Content to generate dynamic webpage from database instead of hard coded example._
-----
I have:
=> HEEDLS-864 Dynamic Learning Content

DigitalLearningSolutions.Data.Tests/DataServices/TutorialContentDataServiceTests/TutorialSummaryTests.cs, DigitalLearningSolutions.Data.Tests/Services/TutorialServiceTests.cs, DigitalLearningSolutions.Data/DataServices/TutorialContentDataService.cs, DigitalLearningSolutions.Data/Models/TutorialContent/TutorialSummary.cs, DigitalLearningSolutions.Data/Services/TutorialService.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningContentControllerTests.cs, DigitalLearningSolutions.Web/Controllers/LearningContentController.cs, DigitalLearningSolutions.Web/Styles/home/brands.scss, DigitalLearningSolutions.Web/ViewModels/LearningContent/LearningContentViewModel.cs, DigitalLearningSolutions.Web/Views/LearningContent/Index.cshtml, DigitalLearningSolutions.Web/Views/LearningContent/_TutorialCard.cshtml
[HEEDLS-870](https://softwiretech.atlassian.net/browse/HEEDLS-870)
_Edited LearningContent/Index.cshtml to include a list of tutorials for that brand, displayed using a tutorial card._
-----
I have:
=> Heedls 870 brand tutorials

DigitalLearningSolutions.Data.Migrations/202204071000_AddDetailsLastCheckedToUsersTableAndRenameOnDelegateAccounts.cs, DigitalLearningSolutions.Data.Migrations/202204071530_PopulateUsersTableFromAccountsTables.cs, DigitalLearningSolutions.Data.Migrations/DigitalLearningSolutions.Data.Migrations.csproj, DigitalLearningSolutions.Data.Migrations/Properties/Resources.Designer.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.resx, DigitalLearningSolutions.Data.Migrations/Scripts/UAR-859-PopulateUsersTableFromAccountsTables-DOWN.sql
https://softwiretech.atlassian.net/browse/HEEDLS-859
Migration to transfer data from the DelegateAccounts and AdminAccounts tables into the new Users tables
N/A
-----
I have:
=> Uar 859 populate user tables

DigitalLearningSolutions.Data.Migrations/202204071530_PopulateUsersTableFromAccountsTables.cs
https://softwiretech.atlassian.net/browse/HEEDLS-859
Revert change to Email column in admins transfer
N/A
-----
I have:
=> HEEDLS-859 Revert updating email for admin user, so they all get linked

DigitalLearningSolutions.Data.Migrations/202204071530_PopulateUsersTableFromAccountsTables.cs
https://softwiretech.atlassian.net/browse/HEEDLS-859
Update delegate account linking logic to deal with errrors
N/A
-----
I have:
=> HEEDLS-859 Update delegate account linking logic

DigitalLearningSolutions.Data.Tests/DataServices/CentresDataServiceTests.cs, DigitalLearningSolutions.Data.Tests/Services/CentresServiceTests.cs, DigitalLearningSolutions.Data/DataServices/CentresDataService.cs, DigitalLearningSolutions.Data/Models/Centres/CentreSummaryForMap.cs, DigitalLearningSolutions.Data/Services/CentresService.cs, DigitalLearningSolutions.Web.Tests/Controllers/FindYourCentreControllerTests.cs, DigitalLearningSolutions.Web/Controllers/FindYourCentreController.cs
https://softwiretech.atlassian.net/browse/HEEDLS-865
Added an endpoint that returns JSON data for centres to display on the Find Your Centre map
N/A
-----
I have:
=> HEEDLS-865 Add endpoint with json centres data for find your centre map

DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests/AdminUserDataServiceTests.cs, DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests/DelegatePromptsDataServiceTests.cs, DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests/DelegateUserCardDataServiceTests.cs, DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests/DelegateUserDataServiceTests.cs, DigitalLearningSolutions.Data.Tests/Services/DelegateApprovalsServiceTests.cs, DigitalLearningSolutions.Data.Tests/Services/DelegateUploadFileServiceTests.cs, DigitalLearningSolutions.Data.Tests/Services/UserServiceTests.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/AdminUserDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/DelegatePromptsDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/DelegateUserCardDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/DelegateUserDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Data/Services/DelegateApprovalsService.cs, DigitalLearningSolutions.Data/Services/DelegateUploadFileService.cs, DigitalLearningSolutions.Data/Services/UserService.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/EditDelegateControllerTests.cs, DigitalLearningSolutions.Web/Controllers/Register/RegisterDelegateByCentreController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/EditDelegateController.cs
https://softwiretech.atlassian.net/browse/HEEDLS-853
Provisionally fixed all the queries in UserDataService, some of the unit tests may not work on other environments due to differing IDs, so we'll need to sort those out when we have a plan to deal with that.
N/A
-----
I have:
=> HEEDLS-853 Fix UserDataService queries

SQLScripts/OtherScripts/ObfuscateUserData-DESTRUCTIVE-NOT-FOR-LIVE.sql
N/A
A basic obfuscation script to mash user data in DLS dbs for use in development.
=> Create obfuscate user data SQL script

DigitalLearningSolutions.Data/Services/NotificationService.cs, DigitalLearningSolutions.Data/Services/TrackerActionService.cs
[_HEEDLS-410_](https://softwiretech.atlassian.net/browse/HEEDLS-410)
Fixed the email to have more descriptive hyperlinks and the correct base url, and moved the second part of the StoreAspProgressV2 TrackerActionService method into the try expression as well so nothing will be updated if an error occurs.
-----
I have:
=> HEEDLS-410 Fix links and try-catch

DigitalLearningSolutions.Data.Migrations/202205061441_SeparateCentreEmailsTable.cs
_[HEEDLS-895](https://softwiretech.atlassian.net/browse/HEEDLS-895)_
_Missed a couple of things after incorrectly running the migration locally. This should hopefully fix it._
-----
I have:
=> HEEDLS-895 : UAR - Fix for broken migration

DigitalLearningSolutions.Data.Migrations/202205163500_AddDescriptionToCompetencyGroupsTable.cs, DigitalLearningSolutions.Data.Tests/Services/FrameworkServiceTests.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs, DigitalLearningSolutions.Data/Models/Frameworks/CompetencyGroupBase.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/Competency.cs, DigitalLearningSolutions.Data/Services/FrameworkService.cs, DigitalLearningSolutions.Data/Services/ImportCompetenciesFromFileService.cs, DigitalLearningSolutions.Web/Controllers/FrameworksController/Competencies.cs, DigitalLearningSolutions.Web/Views/Frameworks/Developer/CompetencyGroup.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml
Add description field to competency groups, allow editing and displaying in self assessment and supervisor interfaces.
https://hee-dls.atlassian.net/browse/DLSV2-544
- Added migration for creating new Description column on table CompetencyGroups.
- Added HTML editor to **CompetencyGroup.cshtml** and made changes on views **SelfAssessmentOverview.cshtml** and **ReviewSelfAssessment.cshtml** for displaying description as Html.
- Enabled user input validation for Description on **CompetencyGroup.cshtml**: although logics where there for competency group Name validation, error summary was missing on the view. 
- Updated Test project.
[LearningPortal/SelfAssessment/Capabilities](https://localhost:44363/LearningPortal/SelfAssessment/1/Capabilities)
Note the bold and italic styles on the word …
=> DLSV2-544 Add description to competency groups

DigitalLearningSolutions.Data.Migrations/202205051500_AddManageSupervisorsDescriptionToSelfAssessments.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/CurrentSelfAssessment.cs, DigitalLearningSolutions.Data/Services/FrameworkNotificationService.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/ManageSupervisors.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml
[DLSV2-545](https://hee-dls.atlassian.net/browse/DLSV2-545)
-----
I have:
=> DLSV2-545 Self assessment intro wording

DigitalLearningSolutions.Web/Styles/shared/searchableElements/common.scss, DigitalLearningSolutions.Web/Styles/shared/searchableElements/filter.scss, DigitalLearningSolutions.Web/Styles/shared/searchableElements/itemsPerPage.scss, DigitalLearningSolutions.Web/Styles/shared/searchableElements/search.scss, DigitalLearningSolutions.Web/Styles/shared/searchableElements/sort.scss, DigitalLearningSolutions.Web/Styles/trackingSystem/centreRanking.scss, DigitalLearningSolutions.Web/Styles/trackingSystem/courseContent.scss, DigitalLearningSolutions.Web/Styles/trackingSystem/delegates/courseDelegates.scss, DigitalLearningSolutions.Web/Styles/trackingSystem/delegates/emailDelegates.scss, DigitalLearningSolutions.Web/Styles/trackingSystem/selectCourse.scss, DigitalLearningSolutions.Web/Views/Frameworks/Developer/AddCompetencyLearningResources.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Shared/_FrameworkPageSearch.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Shared/_FrameworkPageSort.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/ManageOptionalCompetencies.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/VerificationPickResults.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_SearchSelfAssessmentOverview.cshtml, DigitalLearningSolutions.Web/Views/RoleProfiles/Shared/_PageSearch.cshtml, DigitalLearningSolutions.Web/Views/RoleProfiles/Shared/_PageSort.cshtml, DigitalLearningSolutions.Web/Views/Shared/Components/CurrentFilters/Default.cshtml, DigitalLearningSolutions.Web/Views/Shared/SearchablePage/_Filters.cshtml, DigitalLearningSolutions.Web/Views/Shared/SearchablePage/_ItemsPerPageSelect.cshtml, DigitalLearningSolutions.Web/Views/Shared/SearchablePage/_Search.cshtml, DigitalLearningSolutions.Web/Views/Shared/SearchablePage/_Sort.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/VerifyMultipleResults.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Ranking/Index.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AddNewCentreCourse/_CategoryTopicFilter.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/CourseContent/_EditSectionDiagnostic.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/CourseContent/_EditSectionLearning.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/CourseDelegates/Index.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/EmailDelegates/Index.cshtml
[HEEDLS-885](https://softwiretech.atlassian.net/browse/HEEDLS-885)
* Fixed missing right border of filter dropdowns on the Add new course - Select course page
* Renamed `.input-with-no-js-submit-button` to `.pagination-input-with-no-js-submit-button`, as suggested by Stephen
* Fixed a number of inconsistencies with the display and behaviour of input, select, and button elements (see the ticket for details)
-----
I have:
=> Heedls 885 select course dropdown styling issue

DigitalLearningSolutions.Web/Styles/shared/searchableElements/common.scss, DigitalLearningSolutions.Web/Styles/shared/searchableElements/filter.scss, DigitalLearningSolutions.Web/Styles/trackingSystem/selectCourse.scss
https://softwiretech.atlassian.net/browse/HEEDLS-885
Fixed button heights and input widths on small screens in response to bugs @AlexJacksonDS found during testing
-----
I have:
=> HEEDLS-885 Fixed styling on small screens

DigitalLearningSolutions.Web/Scripts/searchSortFilterAndPaginate/searchSortFilterAndPaginate.ts
https://softwiretech.atlassian.net/browse/HEEDLS-861
Added a null check for the element that may not access on pages that don't have a result count and pages.
N/A
-----
I have:
=> HEEDLS-861 Fix attempt to access element that may not exist

README.md
Updated README:
* Fixed command for getting the code
* Added instructions for running the app in Rider
-----
I have:
=> docs: Improved README

DigitalLearningSolutions.Data/Services/FrameworkNotificationService.cs
[DLSV2-507](https://hee-dls.atlassian.net/browse/DLSV2-507)
URL change for delegate self assessment enrolment
-----
I have:
=> DLSV2-507 fix link supervisor enrolment email

DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateProgress/EditCompleteByDate.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateProgress/EditCompletionDate.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateProgress/EditSupervisor.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateProgress/Index.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-862
Fixed missing form data causing 404s and made the strange custom inset text consistent with other inset text.
-----
I have:
=> HEEDLS-862 Fix missing form data and make inset text consistent

DigitalLearningSolutions.Web/Scripts/searchSortFilterAndPaginate/sort.ts, DigitalLearningSolutions.Web/Scripts/spec/sort.spec.ts, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateProgress/LearningLog.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-904
* Fixed sorting by "When" column on Delegate learning log page
* Hide sort button on Delegate learning log when javascript is enabled
-----
I have:
=> Heedls 904 fix sorting

DigitalLearningSolutions.Web.AutomatedUiTests/DigitalLearningSolutions.Web.AutomatedUiTests.csproj
_HEEDLS-XXXX_
Update chrome driver to 102
-----
I have:
=> HEEDLS-NONE Update chrome driver to 102

DigitalLearningSolutions.Web.AutomatedUiTests/TestHelpers/LoginHelper.cs, DigitalLearningSolutions.Web/Controllers/LogoutController.cs, DigitalLearningSolutions.Web/Views/MyAccount/Index.cshtml, DigitalLearningSolutions.Web/Views/Shared/_LogoutForm.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-913
Changed the logout endpoint to a POST. Made a partial view containing a form to replace the current place we had a link to logout. Fixed the UI tests logout method.
-----
I have:
=> HEEDLS-913 Make logout a POST action and add partial form for it

DigitalLearningSolutions.Web/Views/FindYourCentre/RefactoredFindYourCentre.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-846
Add results count to find your centre page.
-----
I have:
=> HEEDLS-846 Add results count partial to find your centre

DigitalLearningSolutions.Web/Controllers/Register/RegisterController.cs, DigitalLearningSolutions.Web/ViewModels/Register/PersonalInformationViewModel.cs, DigitalLearningSolutions.Web/Views/Register/Summary.cshtml
_[HEEDLS-886](https://softwiretech.atlassian.net/browse/HEEDLS-886)_
- Removed obsolete validation-execution conditions from email validation.
- Corrected validation messages.
- Added filling of centre email on return to Personal Information page.
- Corrected screen reader text.
N/A (no change)
-----
I have:
=> HEEDLS-886 fix screen reader text, email storage, email validation

DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/EditDelegate/EditDelegateFormData.cs, DigitalLearningSolutions.Web/Views/ApplicationSelector/Index.cshtml, DigitalLearningSolutions.Web/Views/ChangePassword/Index.cshtml, DigitalLearningSolutions.Web/Views/ChangePassword/Success.cshtml, DigitalLearningSolutions.Web/Views/MyAccount/EditDetails.cshtml, DigitalLearningSolutions.Web/Views/MyAccount/Index.cshtml, DigitalLearningSolutions.Web/Views/NotificationPreferences/Index.cshtml, DigitalLearningSolutions.Web/Views/NotificationPreferences/UpdateNotificationPreferences.cshtml, DigitalLearningSolutions.Web/Views/RegisterDelegateByCentre/Confirmation.cshtml, DigitalLearningSolutions.Web/Views/RegisterDelegateByCentre/LearnerInformation.cshtml, DigitalLearningSolutions.Web/Views/RegisterDelegateByCentre/Password.cshtml, DigitalLearningSolutions.Web/Views/RegisterDelegateByCentre/PersonalInformation.cshtml, DigitalLearningSolutions.Web/Views/RegisterDelegateByCentre/Summary.cshtml, DigitalLearningSolutions.Web/Views/RegisterDelegateByCentre/WelcomeEmail.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/ManageCourse/EditAutoRefreshOptions.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateApprovals/DelegateRejectionPage.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-785
Fixed missed changes and a validation message bug that was previously unnoticed
-----
I have:
=> Heedls 785 tidy tracking system wording

DigitalLearningSolutions.Web/Controllers/Register/RegisterAdminController.cs
[HEEDLS-903](https://softwiretech.atlassian.net/jira/software/c/projects/HEEDLS/boards/753?modal=detail&selectedIssue=HEEDLS-903)
For the admin registration journey, make the check that the email provided matches the AutoRegisterManagerEmail case insensitive
-----
I have:
=> HEEDLS-903 Make the email in the register admin journey case insensitive

DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests/UserCentreDetailsDataServiceTests.cs, DigitalLearningSolutions.Data.Tests/Services/CentreRegistrationPromptsServiceTests.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserCentreDetailsDataService.cs, DigitalLearningSolutions.Data/Services/CentreRegistrationPromptsService.cs, DigitalLearningSolutions.Web.Tests/Controllers/MyAccount/MyAccountControllerTests.cs, DigitalLearningSolutions.Web.Tests/Helpers/ProfessionalRegistrationNumberHelperTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/MyAccount/MyAccountViewModelTests.cs, DigitalLearningSolutions.Web/Controllers/LoginController.cs, DigitalLearningSolutions.Web/Controllers/MyAccountController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/EditDelegateController.cs, DigitalLearningSolutions.Web/Helpers/CustomClaimHelper.cs, DigitalLearningSolutions.Web/Helpers/ProfessionalRegistrationNumberHelper.cs, DigitalLearningSolutions.Web/Helpers/PromptsService.cs, DigitalLearningSolutions.Web/ViewModels/MyAccount/MyAccountEditDetailsFormData.cs, DigitalLearningSolutions.Web/ViewModels/MyAccount/MyAccountEditDetailsViewModel.cs, DigitalLearningSolutions.Web/ViewModels/MyAccount/MyAccountViewModel.cs, DigitalLearningSolutions.Web/Views/MyAccount/EditDetails.cshtml, DigitalLearningSolutions.Web/Views/MyAccount/Index.cshtml, DigitalLearningSolutions.Web/Views/MyAccount/_CentreSpecificDetailsCard.cshtml, DigitalLearningSolutions.Web/Views/MyAccount/_MyDetailsCard.cshtml
[HEEDLS-884](https://softwiretech.atlassian.net/browse/HEEDLS-884)
Fixes after testing:
- Display job group, PRN and centre email on the MyAccount and EditDetails pages for admin only users
- When submitting an empty centre email, delete the record in the UserCentreDetails table instead of having an entry with a null email
- Validate both primary email and centre email at the same time
- Added a hidden text to the Primary email tag on the MyAccount page
- Changed spacing on the MyAccount page to make it look better on mobile
-----
I have:
=> Uar 884 extend my account journey fixes

README.md
=> new readme section

DigitalLearningSolutions.Data.Tests/Services/RegistrationServiceTests.cs, DigitalLearningSolutions.Data/Services/RegistrationService.cs
_HEEDLS-XXXX_
Fix build error introduced by merging master to uar-test
-----
I have:
=> HEEDLS-NONE Remove unnecessary logic from promote to admin

DigitalLearningSolutions.Data.Tests/DataServices/RegistrationDataServiceTests.cs, DigitalLearningSolutions.Data.Tests/Services/RegistrationServiceTests.cs, DigitalLearningSolutions.Data.Tests/TestHelpers/UserTestHelper.cs, DigitalLearningSolutions.Data/DataServices/RegistrationDataService.cs, DigitalLearningSolutions.Data/Services/RegistrationService.cs, DigitalLearningSolutions.Web.Tests/Controllers/Register/RegisterAdminControllerTests.cs, DigitalLearningSolutions.Web/Controllers/Register/RegisterAdminController.cs
https://softwiretech.atlassian.net/browse/HEEDLS-964
Set TCAgreed in the Register centre manager journey in the same way it has been done on UAR.
No visual changes.
-----
I have:
=> HEEDLS-964 Add setting of TCAgreed to register admin

DigitalLearningSolutions.Web/Controllers/TrackingSystem/CourseSetup/AdminFieldsController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/CourseSetup/CourseSetupController.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Configuration/RegistrationPrompts/EditRegistrationPrompt.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/EditAdminField.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-925
Added a couple of missing hidden form fields, and moved a transaction commit to fix testing failures.
N/A
-----
I have:
=> HEEDLS-925 Add missing hidden inputs and move TransactionScope

DigitalLearningSolutions.Data/Services/RegistrationService.cs, DigitalLearningSolutions.Web.Tests/Controllers/Register/RegisterAtNewCentreControllerTests.cs, DigitalLearningSolutions.Web/Controllers/Register/RegisterAtNewCentreController.cs, DigitalLearningSolutions.Web/Views/RegisterAtNewCentre/LearnerInformation.cshtml, DigitalLearningSolutions.Web/Views/RegisterAtNewCentre/PersonalInformation.cshtml, DigitalLearningSolutions.Web/Views/RegisterAtNewCentre/Summary.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-877
Fixed the centre email validation so that a user's own emails are allowed values, fixed the final post action and fixed the cancel links not taking you to the expected page.
N/A
-----
I have:
=> HEEDLS-877 Fix validation errors and cancel links

DigitalLearningSolutions.Web/Helpers/FeatureFlags.cs, DigitalLearningSolutions.Web/Views/ApplicationSelector/Index.cshtml, DigitalLearningSolutions.Web/appSettings.UAT.json, DigitalLearningSolutions.Web/appsettings.Development.json, DigitalLearningSolutions.Web/appsettings.Production.json, DigitalLearningSolutions.Web/appsettings.SIT.json, DigitalLearningSolutions.Web/appsettings.Test.json, DigitalLearningSolutions.Web/appsettings.json
https://softwiretech.atlassian.net/browse/HEEDLS-969
Added new ShowAppCardForLegacyTrackingSystem feature flag, and a new card in the application selector.
-----
I have:
=> Heedls 969 app selector legacy tracking system

DigitalLearningSolutions.Web.Tests/Controllers/Register/RegisterAtNewCentreControllerTests.cs, DigitalLearningSolutions.Web/Controllers/Register/RegisterAtNewCentreController.cs
https://softwiretech.atlassian.net/browse/HEEDLS-877
Flipped the boolean value from the email verification check since the old method checked if email was invalid for use, vs the new one which check if it is valid.
N/A
-----
I have:
=> HEEDLS-877 Flip boolean value to correct logic

DigitalLearningSolutions.Data.Migrations/202206221541_AddEmailVerificationHashesTable.cs
[_HEEDLS-922_](https://softwiretech.atlassian.net/browse/HEEDLS-922)
Wrote a migration to add an EmailVerificationHashes table, with foreign keys to the Users and UserCentreDetails tables.
-----
I have:
=> HEEDLS-922 Write migration to create EmailVerificationHashes table

DigitalLearningSolutions.Data.Tests/Services/ActionPlanServiceTests.cs, DigitalLearningSolutions.Data.Tests/Services/LoginServiceTests.cs, DigitalLearningSolutions.Data/Extensions/ConfigurationExtensions.cs, DigitalLearningSolutions.Data/Services/LoginService.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/CompletedTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/CurrentTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/RecommendedLearningControllerTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/MyAccount/MyAccountControllerTests.cs, DigitalLearningSolutions.Web.Tests/Helpers/StringHelperTests.cs, DigitalLearningSolutions.Web.Tests/ServiceFilter/ValidateAllowedDlsSubApplicationTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/MyAccount/MyAccountViewModelTests.cs, DigitalLearningSolutions.Web/Controllers/MyAccountController.cs, DigitalLearningSolutions.Web/Helpers/StringHelper.cs, DigitalLearningSolutions.Web/Startup.cs, DigitalLearningSolutions.Web/Styles/login/chooseACentre.scss, DigitalLearningSolutions.Web/ViewModels/MyAccount/MyAccountViewModel.cs, DigitalLearningSolutions.Web/Views/Login/ChooseACentre.cshtml, DigitalLearningSolutions.Web/Views/MyAccount/Index.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-879 and https://softwiretech.atlassian.net/browse/HEEDLS-912
A number of changes to fix the Choose a Centre / Switch Centre page failures on 912 and 879
NOTE: the failed point on 879 was partially corrected in a ticket scope update, but the uar-test environment loss would still need fixing (and is tackled in this PR)
Desktop: 
Tablet (for button spacing):
Mobile (for button spacing): 
Desktop (with reworded inset text):
-----
I have:
=> HEEDLS-912 - implement fixes for Choose A Centre and Switch Centre page

DigitalLearningSolutions.Data.Migrations/RecurringSqlJobs/DeleteMultipageFormDataOlderThan30Days.sql, DigitalLearningSolutions.Data.Migrations/RecurringSqlJobs/DeleteResetPasswordRecordsOlderThan4Days.sql
[_HEEDLS-959_](https://softwiretech.atlassian.net/browse/HEEDLS-959)
Added two recurring SQL scripts:
- a script to delete MultipageFormData older than 30 days, to be run nightly at 2AM
- a script to delete ResetPassword records older than 4 days, to be run nightly at 3AM
-----
I have:
=> HEEDLS-959 Add recurring SQL jobs

DigitalLearningSolutions.Web/appSettings.UAT.json, DigitalLearningSolutions.Web/appsettings.Production.json
Update feature flags for release.
RefactoredTrackingSystem > true
CandidateAssessmentExcelExport > true
PricingPage > false
I've also added any flags that were missing on production or UAT config and put them in the same order as FeatureFlags.cs.
=> Config: Update feature flag config for release

DigitalLearningSolutions.Web/appSettings.UAT.json, DigitalLearningSolutions.Web/appsettings.Production.json
Update prod feature flags for release 22.7.1 on master
=> Heedls set config for release

DigitalLearningSolutions.Web/Views/Login/ChooseACentre.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-912
Update unapproved account inset text.
-----
I have:
=> HEEDLS-912 Update wording on unapproved account inset text

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_Layout.cshtml
DLSV2-575
Adds contact us link to self assessments layout footer (and implements SR only text).
=> DLSV2-575 Add missing contact us link to self assessment layout

DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests/DelegateUserDataServiceTests.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/DelegateUserDataService.cs, DigitalLearningSolutions.Data/Models/User/DelegateEntity.cs, DigitalLearningSolutions.Data/Models/User/DelegateUserCard.cs
_[HEEDLS-988](https://softwiretech.atlassian.net/browse/HEEDLS-988)_
Added an AdminID fetch to the data service method to get delegate entities and passed it through to the card. Changed the password set check for cards.
N/A
-----
I have:
=> Heedls 988 fix delegate tags

DigitalLearningSolutions.Data.Tests/Services/RegistrationServiceTests.cs, DigitalLearningSolutions.Data/DataServices/NotificationDataService.cs, DigitalLearningSolutions.Data/Models/Notifications/Recipient.cs, DigitalLearningSolutions.Data/Services/RegistrationService.cs
[DLSV2-598](https://hee-dls.atlassian.net/browse/DLSV2-558)
Loads recipients for approval notifications at centre and emails all of them after registration of delegate requiring approval.
-----
I have:
=> DLSV2-598 Emails all admin approval recipients for centre

DigitalLearningSolutions.Web/Services/PasswordResetService.cs
[HEEDLS-974](https://softwiretech.atlassian.net/browse/HEEDLS-974)
In the previous merge I forgot to update the path sent to the user via email
-----
I have:
=> HEEDLS-974 Fix path in email sent to user

DigitalLearningSolutions.Web/Views/ClaimAccount/CompleteRegistration.cshtml, DigitalLearningSolutions.Web/Views/ClaimAccount/Confirmation.cshtml, DigitalLearningSolutions.Web/Views/ClaimAccount/Index.cshtml
[HEEDLS-974](https://softwiretech.atlassian.net/browse/HEEDLS-974)
Fixed some UI bugs
-----
I have:
=> Uar 974 complete delegate registration page

DigitalLearningSolutions.Web/Views/ClaimAccount/AccountsLinked.cshtml, DigitalLearningSolutions.Web/Views/ClaimAccount/CompleteRegistration.cshtml, DigitalLearningSolutions.Web/Views/ClaimAccount/Confirmation.cshtml, DigitalLearningSolutions.Web/Views/ClaimAccount/Index.cshtml, DigitalLearningSolutions.Web/Views/Login/ChooseACentre.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-976
* Made page headers a consistent size
* Fixed “Link this record” action link on the Complete registration page so that it contains email and code in the query string, making it possible to complete the journey
* Added word wrapping to centre name display on claim account -> confirmation page, and on Choose a Centre page
-----
I have:
=> Heedls 976 fixes

DigitalLearningSolutions.Data/Models/User/AdminEntity.cs, DigitalLearningSolutions.Web/Helpers/FilterOptions/AdminFilterOptions.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Administrator/AdministratorsViewModelFilterOptions.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Administrator/SearchableAdminViewModel.cs
https://softwiretech.atlassian.net/browse/HEEDLS-1007
Changed `AdminEntity` so that it can work with `SearchFilterSortAndPaginate`
-----
I have:
=> HEEDLS-1007 Make SearchFilterSortAndPaginate work with AdminEntity

DigitalLearningSolutions.Web.Tests/Controllers/Register/ClaimAccountControllerTests.cs, DigitalLearningSolutions.Web.Tests/Services/ClaimAccountServiceTests.cs, DigitalLearningSolutions.Web/Controllers/Register/ClaimAccountController.cs, DigitalLearningSolutions.Web/Services/ClaimAccountService.cs, DigitalLearningSolutions.Web/ViewModels/Common/ViewComponents/SetPasswordViewModel.cs, DigitalLearningSolutions.Web/ViewModels/Register/ClaimAccount/ClaimAccountCompleteRegistrationViewModel.cs, DigitalLearningSolutions.Web/ViewModels/Register/ClaimAccount/ClaimAccountViewModel.cs, DigitalLearningSolutions.Web/ViewModels/Register/ClaimAccount/IHasDataForDelegateRecordSummary.cs, DigitalLearningSolutions.Web/Views/ChangePassword/Index.cshtml, DigitalLearningSolutions.Web/Views/ClaimAccount/AccountAlreadyExists.cshtml, DigitalLearningSolutions.Web/Views/ClaimAccount/AccountsLinked.cshtml, DigitalLearningSolutions.Web/Views/ClaimAccount/CompleteRegistration.cshtml, DigitalLearningSolutions.Web/Views/ClaimAccount/CompleteRegistrationWithoutPassword.cshtml, DigitalLearningSolutions.Web/Views/ClaimAccount/Confirmation.cshtml, DigitalLearningSolutions.Web/Views/ClaimAccount/Index.cshtml, DigitalLearningSolutions.Web/Views/ClaimAccount/LinkDlsAccount.cshtml, DigitalLearningSolutions.Web/Views/ClaimAccount/WrongUser.cshtml, DigitalLearningSolutions.Web/Views/ClaimAccount/_DelegateRecordSummary.cshtml, DigitalLearningSolutions.Web/Views/Register/Password.cshtml, DigitalLearningSolutions.Web/Views/RegisterAdmin/Password.cshtml, DigitalLearningSolutions.Web/Views/ResetPassword/Index.cshtml, DigitalLearningSolutions.Web/Views/SetPassword/Index.cshtml, DigitalLearningSolutions.Web/Views/Shared/_SetPasswordFields.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-975
* Added a new view for claiming an account when the user needs to set a password, making the wireframe in Jira
* Added a new POST route and modified the ClaimAccountService to handle the case where the user needs to set a password
* The old POST route has been changed to `CompleteRegistrationWithoutPassword`, the new one is `CompleteRegistration`. This is because there is a requirement to show a view with errors when there are password fields, and we want to keep the URL the same (i.e. /ClaimAccount/CompleteRegistration) when this happens.
* The `CompleteRegistration` POST route has password/confirm password in the HTTP body, but `email` and `code` as part of the query string. This is also so that the URL will be unchanged if the POST …
=> Heedls 975 claim account set password

DigitalLearningSolutions.Web/Views/FindYourCentre/_CentreSummaryCard.cshtml, DigitalLearningSolutions.Web/Views/ForgotPassword/Index.cshtml, DigitalLearningSolutions.Web/Views/Home/Welcome.cshtml, DigitalLearningSolutions.Web/Views/Login/Index.cshtml, DigitalLearningSolutions.Web/Views/Shared/_NavMenuItems.cshtml
_[HEEDLS-1020](https://softwiretech.atlassian.net/browse/HEEDLS-1020)_
Changed the five Register/Index endpoint calls mentioned in the ticket to Start endpoint calls. I was unable to find any others besides those mentioned, checking redirects, other register controller calls and direct usages of the Index method.
N/A
-----
I have:
=> HEEDLS-1020 switch register index links to start links

DigitalLearningSolutions.Data.Migrations/202208031701_AddSupportEmailConfigValue.cs
=> support email migration

DigitalLearningSolutions.Web.AutomatedUiTests/DigitalLearningSolutions.Web.AutomatedUiTests.csproj
Update chrome driver to version 104.
=> Chore: Update chromedriver to version 104

DigitalLearningSolutions.Web.AutomatedUiTests/DigitalLearningSolutions.Web.AutomatedUiTests.csproj, DigitalLearningSolutions.Web/Views/Supervisor/RemoveConfirm.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/Shared/_StaffMemberCard.cshtml
Merge changes on master into uar:
* Update chromedriver to version 104
* DLSV2-560-RemoveStaffMemberFromMyStaffList
=> Merge master into uar

DigitalLearningSolutions.Data.Migrations/202208030945_AddEmailVerificationHashesIndexes.cs, DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests/UserCentreDetailsDataServiceTests.cs, DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests/UserDataServiceTests.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserCentreDetailsDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Data/Models/EmailVerificationDetails.cs, DigitalLearningSolutions.Web.Tests/Controllers/VerifyEmailControllerTests.cs, DigitalLearningSolutions.Web.Tests/Services/UserServiceTests.cs, DigitalLearningSolutions.Web/Controllers/VerifyEmailController.cs, DigitalLearningSolutions.Web/Services/UserService.cs, DigitalLearningSolutions.Web/Views/VerifyEmail/Index.cshtml, DigitalLearningSolutions.Web/Views/VerifyEmail/VerificationLinkExpired.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-1024
* Added a VerifyEmailController with a single endpoint: `/VerifyEmail`
* Added service and data service methods to get user/user centre details records matching the given email and code
* Added service and data service methods to update `EmailVerified` and `EmailVerificationHashID` for all user/user centre details records matching the given email if any email/code match is found in either `Users` or `UserCentreDetails` tables
* I have done one thing that isn't specified by the issue: I have used `[Authorize(Policy = CustomPolicies.BasicUser)]` in the controller. It isn't strictly necessary, but I don't think there's a downside to doing it - anyone who wants to verify an email will already have a login.
* I have added a …
=> Heedls 1024 verify email

DigitalLearningSolutions.Web/Views/Login/AccountInactive.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-1032
Added mailto link for support email address on Account Inactive page
-----
I have:
=> HEEDLS-1032 Added mailto link for support email address

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/GroupDelegatesControllerTests.cs, DigitalLearningSolutions.Web.Tests/Services/DelegateUploadFileServiceTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/GroupDelegatesController.cs, DigitalLearningSolutions.Web/Services/DelegateUploadFileService.cs
https://softwiretech.atlassian.net/browse/HEEDLS-874
* Update delegate groups when a bulk upload updates a delegate
* Return NotFound from `/TrackingSystem/Delegates/Groups/:GroupId/Delegates/:DelegateId/Remove` if `DelegateId` isn't in the group, instead of an internal server error
-----
I have:
=> Heedls 874 bug fixes

DigitalLearningSolutions.Web/Views/ClaimAccount/Index.cshtml
https://softwiretech.atlassian.net/browse/HEEDLS-1045
Changed the wording on the page at the start of the Claim Account journey to match the new wireframe agreed by HEE
---
-----
I have:
=> HEEDLS-1045 Modify wording at start of Claim Account journey

DigitalLearningSolutions.Web/Services/EmailVerificationService.cs
[HEEDLS-915](https://softwiretech.atlassian.net/browse/HEEDLS-915)
Fixed the link sent in the verification email
-----
I have:
=> HEEDLS-915 Fix link in the verification email

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/GroupDelegatesControllerTests.cs, DigitalLearningSolutions.Web.Tests/Services/GroupServiceTests/GroupsServiceSynchroniseGroupsTests.cs, DigitalLearningSolutions.Web.Tests/Services/GroupServiceTests/GroupsServiceTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/GroupDelegatesController.cs, DigitalLearningSolutions.Web/Helpers/LinkedFieldHelper.cs, DigitalLearningSolutions.Web/Services/GroupsService.cs
_[HEEDLS-1018](https://softwiretech.atlassian.net/browse/HEEDLS-1018)_
Added a method to get delegate accounts associated with a user besides the one being updated, and then update their job group group memberships depending on 
N/A
-----
I have:
=> Heedls 1018 update user centre job groups

DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests/UserCentreDetailsDataServiceTests.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserCentreDetailsDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Web.Tests/Services/UserServiceTests.cs, DigitalLearningSolutions.Web/Controllers/MyAccountController.cs, DigitalLearningSolutions.Web/Services/UserService.cs
_HEEDLS-1044_
Added the active account exclusion to retrieving DelegateAccount emails as well as AdminAccount emails.
N/A
-----
I have:
=> Heedls 1044b inactive delegate account handling

DigitalLearningSolutions.Web/Controllers/FrameworksController/Competencies.cs
Flag checkboxes are missing when user enters invalid competency name e.g. less than three characters.
https://hee-dls.atlassian.net/browse/DLSV2-523
When errors are detected and the model is not valid, still need to retrieve competency flags from the database. In addition, if the user has selected any flag by clicking on the checkboxes, we need to keep selected flags so the user doesn't have to select flags again after amending other errors.
-----
- Navigate to Frameworks
- Click on View/Edit
- Click on Framework tab
- Expand a competency group and Edit a competency
Check that flags no longer missing when competency name is too short and they preserve selected flags when posted back
=> DLSV2-523 Fixes bug: flag checkboxes missing when user enters invalid competency name

DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests/BasicAuthenticatedAccessibilityTests.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Reports/Index.cshtml
[DLSV2-597](https://hee-dls.atlassian.net/browse/DLSV2-597)
Fixes H1 title of reports page to make it consistent with navigation link.
-----
I have:
=> DLSV2-597 Fixes course reports title and associated UI Test

DigitalLearningSolutions.Web/Views/Shared/Components/Logo/Default.cshtml
[DLSV2-548](https://hee-dls.atlassian.net/browse/DLSV2-548)
Appends "logo" to centre logo alt text to provide better alt description.
-----
I have:
=> DLSV2-548 Adds logo to centre logo alt text

DigitalLearningSolutions.Web/Views/Supervisor/NominateSupervisor.cshtml
DLSV2-619
Uncommitted tweak to DLSV2-619. Title said "Confirm Nominate supervisor" instead of "Confirm Nominated supervisor"
=> DLSV2-619 missed tweak

DigitalLearningSolutions.Web/package.json, DigitalLearningSolutions.Web/yarn.lock
[DLSV2-637](https://hee-dls.atlassian.net/browse/DLSV2-637)
Adds dom purify to yarn packages in web project in readiness for use in client-side sanitisation of HTML inputs.
=> DLSV2-637 Add dom purify to yarn packages

DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Views/Supervisor/Shared/_AssessmentQuestionReviewCells.cshtml
[DLSV2-535](https://hee-dls.atlassian.net/browse/DLSV2-535)
Adds "/Confirm" to the controller route so that review/confirmation page loads correctly.
-----
I have:
=> DLSV2-535 Fixes supervisor review action routing

DigitalLearningSolutions.Web/Views/Supervisor/NominateSupervisor.cshtml
[_HEEDLS-XXXX_](https://hee-dls.atlassian.net/browse/DLSV2-619)
Made hint text capitalisation of "Nominated supervisor" consistent with other parts of the view.
-----
I have:
=> DLSV2-619 Update NominateSupervisor.cshtml capitalisation fix

DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/SelfAssessmentReports/Index.cshtml
[DLSV2-597](https://hee-dls.atlassian.net/browse/DLSV2-597)
Tweaks to text following feedback.
-----
I have:
=> DLSV2-597 Text tweaks

DigitalLearningSolutions.Web/Views/Shared/Components/SelectList/Default.cshtml
DLSV2-651
Further fixes to select list view component to ensure current value is selected on load.
-----
I have:
=> DLSV2-651 Fixes select view component

DigitalLearningSolutions.Data/Services/FrameworkService.cs
_HEEDLS-XXXX_
Deleting a competency with a flag was throwing an exception because of a foreign key violation. The issue is fixed.
No Screenshots. The steps are defined in the jira item; https://hee-dls.atlassian.net/browse/DLSV2-577
-----
I have:
- [X ] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ X] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
=> DLSV2-577  Framework - Delete Competency results in error

DigitalLearningSolutions.Web/Views/Shared/Components/TextArea/Default.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/ReviewCompetencySelfAsessment.cshtml
[DLSV2-653](https://hee-dls.atlassian.net/browse/DLSV2-653)
The white spaces issue and the problem of the correct selection not displayed is resolved.
https://hee-dls.atlassian.net/browse/DLSV2-653
-----
I have:
=> DLSV2-653 Spacing added to text area inputs when loading page

DigitalLearningSolutions.Data/Services/CandidateAssessmentDownloadFileService.cs
https://hee-dls.atlassian.net/browse/DLSV2-621
Rework because the whole workbook was not protected.
https://hee-dls.atlassian.net/browse/DLSV2-621
-----
I have:
- [ X] Run the formatter and made sure there are no IDE errors.
- [X ] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [X ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [X ] Scanned over my own MR to ensure everything is as expected.
=> DLSV2-621 Rework

DigitalLearningSolutions.Web/Views/FindYourCentre/RefactoredFindYourCentre.cshtml
https://hee-dls.atlassian.net/jira/software/projects/DLSV2/boards/1?assignee=6321797ece3e476e42ac8a00&selectedIssue=DLSV2-660
Updated screen text to remove reference to map view as per suggestion (see attached screenshot).
New text screenshot attached.
-----
I have:
=> Updated screen text as per bug suggestion.

DigitalLearningSolutions.Data.Migrations/202210030601_AddAvailableCustomisationsForCentreFiltered_V6.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.Designer.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.resx, DigitalLearningSolutions.Data.Migrations/Scripts/DLSV2-581-GetActiveAvailableCustomisationsForCentreFiltered_V6.sql, DigitalLearningSolutions.Data.Migrations/Scripts/DropActiveAvailableV6.sql, DigitalLearningSolutions.Data.Tests/DataServices/CourseDataServiceTests.cs, DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Data/Enums/MultiPageFormDataFeature.cs, DigitalLearningSolutions.Data/Models/BaseLearningItem.cs, DigitalLearningSolutions.Data/Models/SessionData/Tracking/Deligate/Enrol/SessionEnrolDelegate.cs, DigitalLearningSolutions.Data/Models/Supervisor/SupervisorForEnrolDelegate.cs, DigitalLearningSolutions.Data/Services/SupervisorService.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/EnrolControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/EnrolController.cs, DigitalLearningSolutions.Web/DigitalLearningSolutions.Web.csproj, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/Enrol/CompletedByDateViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/Enrol/EnrolCurrentLearningViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/Enrol/EnrolDelegateSummaryViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/Enrol/EnrolSupervisorViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/AllDelegates/_SearchableDelegateCard.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Enrol/EnrolCompleteBy.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Enrol/EnrolDelegateSummary.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Enrol/EnrolDelegateSupervisor.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Enrol/Index.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ViewDelegate/Index.cshtml
https://hee-dls.atlassian.net/browse/DLSV2-581
There is a button in the expanded view of a delegate on the All Delegates page labelled “Enrol on course”. This button launches a modal popup allowing the user to select the course, then choose supervisor, complete by date and review the learning pathway defaults for the course.
The screenshots can be found at https://hee-dls.atlassian.net/browse/DLSV2-581
-----
I have:
=> DLSV2-581 Enrol delegate on activity from All Delegates view

DigitalLearningSolutions.Web/yarn.lock
[DLSV2-705](https://hee-dls.atlassian.net/browse/DLSV2-705)
Updates Terser version in yarn.lock to fix vulnerability.
-----
I have:
=> DLSV2-705 Update yarn.lock

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs
[DLSV2-682](https://hee-dls.atlassian.net/browse/DLSV2-682)
Supervisor Name not displaying on self assessment review page.
-----
I have:
=> DLSV2-682 sql query updated

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/EnrolController.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ViewDelegate/Index.cshtml
https://hee-dls.atlassian.net/browse/DLSV2-581
fixed issues during submission for date and supervisor id
no screenshots
-----
I have:
=> DLSV2-581-error-in-sumiting-without-supervisor-and-date-issue

DigitalLearningSolutions.Web/Scripts/trackingSystem/reports.ts
[DLSV2-711](https://hee-dls.atlassian.net/browse/DLSV2-711)
Corrects the reference to the data endpoint to ensure the reports.js file can retrieve the data to chart
-----
I have:
=> DLSV2-711 Corrects data url in reports.ts

DigitalLearningSolutions.Data/Services/FrameworkService.cs, DigitalLearningSolutions.Web/Controllers/FrameworksController/Frameworks.cs
https://hee-tis.atlassian.net/browse/TD-525
make changes in validation of adding contributor if owner email is same as provided email id the validation message will be shown
screenshots can be found on https://hee-tis.atlassian.net/browse/TD-525
-----
I have:
=> TD-525 Framework Owner Email Address Validation while add contributor

DigitalLearningSolutions.Data/Services/RegistrationService.cs, DigitalLearningSolutions.Web/Helpers/FilterOptions/AdminFilterOptions.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Administrator/AdminRoleInputs.cs
[TD-583](https://hee-dls.atlassian.net/browse/TD-583)
Role update Email notification isn't consistent with roles on delegate  _promote to admin_  page
-----
I have:
=> Role Name Email Update

DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Extensions/FormExtension.cs
[TD-546](https://hee-dls.atlassian.net/browse/TD-546)
Same Supervisor gets added multiple times when submit button continuously clicked
Kindly refer to the jira link for a video
-----
I have:
=> TD-546 manage supervisor same supervisor gets added multiple times

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Data/Models/Courses/DelegateCourseInfo.cs, DigitalLearningSolutions.Web.Tests/ViewModels/TrackingSystem/Delegates/AllDelegates/DelegateCourseInfoViewModelTests.cs, DigitalLearningSolutions.Web/Styles/trackingSystem/viewDelegate.scss, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/Shared/DelegateCourseInfoViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateCourseProgressDetails.cshtml
https://hee-tis.atlassian.net/browse/TD-671
Added archived and inactive border flash and tags to Manage Delegate Course List page.
-----
I have:
=> TD-671 Implemented border and tag styles for delegate course current status.

DigitalLearningSolutions.Web/Controllers/FrameworksController/Frameworks.cs
https://hee-tis.atlassian.net/browse/TD-525
changes in validation message of the add reviewer or contributor of the framework
the screenshots can be found on : https://hee-tis.atlassian.net/browse/TD-525
-----
I have:
=> TD-525: Change In The Error Message

DigitalLearningSolutions.Data/Services/RegistrationService.cs
https://hee-tis.atlassian.net/browse/TD-672
Email notification for registration of delegate which requires approval to centre notification email if available 
N/A
-----
I have:
=> TD-672: Approval Notifications For The Centre

DigitalLearningSolutions.Data.Migrations/202211081400_AddIsdeletedFrameworkCollaborators.cs, DigitalLearningSolutions.Data/Services/FrameworkService.cs
https://hee-tis.atlassian.net/browse/TD-680
added new column in frameworkcontributor table named IsDeleted and set it as false by default and on select add and update manage it
N/A
-----
I have:
=> TD-680-Framework Remove Contributor

DigitalLearningSolutions.Data/Models/SearchSortFilterPaginate/SearchOptions.cs, DigitalLearningSolutions.Data/Services/SearchSortFilterPaginateService.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/AllDelegatesController.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-669
The scorer option was added to SearchOptions and passed from the delegate search.
-----
I have:
[x] Run the formatter and made sure there are no IDE errors
[ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
[x] Manually tested my work with and without JavaScript
[x] Tested any Views or partials created or changed with [Wave Chrome plugin]
[ ] Updated/added documentation in [Confluence]
[x] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to …
=> DLSV2-669-problems-with-Delegate-Search

DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/ConfirmOverwrite.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/ConfirmOverwriteSelfAssessment.cshtml
https://hee-tis.atlassian.net/browse/TD-160
Changes for text typos and on click of error text focus and scroll to the checkbox
Screenshots can be found on : https://hee-tis.atlassian.net/browse/TD-160
-----
I have:
=> TD-160 confirmation screen changes

DigitalLearningSolutions.Web/Views/Frameworks/Developer/SimilarCompetency.cshtml
https://hee-tis.atlassian.net/browse/TD-499
changed header for mobile view table. and added size change of text in name column/row
screenshots can be found on : https://hee-tis.atlassian.net/browse/TD-499
-----
I have:
=> TD-499: Similar Competency Table View Issue

DigitalLearningSolutions.Web/Views/Supervisor/Shared/_StaffDetails.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-720
Removed extra curly bracket from HTML.
Screenshots
-----
I have:
=> TD-720 curly brackets appearing in UAR My Staff list

DigitalLearningSolutions.Web/Views/Frameworks/Developer/SimilarCompetency.cshtml
https://hee-tis.atlassian.net/browse/TD-499
The inconsistent font for Name and Description fields and its data on desktop and mobile is fixed
-----
I have:
=> CSS Issues fixed.

DigitalLearningSolutions.Web/Views/Shared/_TextInputItem.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/EnrolDelegateSetCompleteBy.cshtml
Hidden BOM character U+FEFF was causing unwanted whitespace on the login page.
https://hee-tis.atlassian.net/jira/software/c/projects/TD/boards/165?modal=detail&selectedIssue=TD-719&assignee=6321797ece3e476e42ac8a00
The issue was caused by hidden Byte Order Marks being encoded into the view cshtml text file.
This was being rendered in the browser as spurious U-FEFF whitespace characters.
This affected the vertical formatting on the login page. 
It was also present on EnrolDelegateSetCompleteBy.cshtml
I could not find any other instances of hidden BOM encoding elsewhere in the solution.
Screenshots attached.
-----
I have:
=> Removed spurious Byte Order Mark characters from solution

DigitalLearningSolutions.Web/Views/RegisterAtNewCentre/PersonalInformation.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-717
'Required' attribute added to controls.
Screenshots
-----
I have:
=> TD-717 Show form controls after choosing centre from Find Your Centre

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/EditDelegateController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ViewDelegateController.cs, DigitalLearningSolutions.Web/Helpers/DisplayStringHelper.cs, DigitalLearningSolutions.Web/ViewModels/Common/EditAccountDetailsFormDataBase.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/AllDelegates/AllDelegateItems.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/AllDelegates/Index.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/AllDelegates/_SearchableDelegateCard.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-718
Validator added to  CenterSpecificEmail property.
-----
I have:
=> TD-718-blank-email-not-validated-UAR

DigitalLearningSolutions.Web/Views/RegisterAtNewCentre/LearnerInformation.cshtml
JIRA link
https://hee-tis.atlassian.net/browse/TD-717
Required property of control set to true.
-----
I have:
=> TD-717 Required property of dropdown for the Centre control set to true

DigitalLearningSolutions.Web/Styles/nhsuk.scss, DigitalLearningSolutions.Web/Views/Register/PersonalInformation.cshtml
https://hee-tis.atlassian.net/browse/TD-746
changes for UI related issue due to full length nhsuk-hint and primary email control was unable to find due to issue.
screenshots can be found on : https://hee-tis.atlassian.net/browse/TD-746
-----
I have:
=> TD-746: UI Issues And Primary Email Option

DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests/AdminUserDataServiceTests.cs, DigitalLearningSolutions.Data.Tests/TestHelpers/RegistrationModelTestHelper.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/AdminUserDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Data/Models/Register/AdminRegistrationModel.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Centre/Administrator/AdministratorControllerTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/PromoteToAdminControllerTests.cs, DigitalLearningSolutions.Web.Tests/Services/EmailGenerationServiceTests.cs, DigitalLearningSolutions.Web.Tests/Services/RegistrationServiceTests.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/SupervisorController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Administrator/AdministratorController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/PromoteToAdminController.cs, DigitalLearningSolutions.Web/Helpers/RegistrationMappingHelper.cs, DigitalLearningSolutions.Web/Services/EmailGenerationService.cs, DigitalLearningSolutions.Web/Services/RegistrationService.cs, DigitalLearningSolutions.Web/Services/UserService.cs, DigitalLearningSolutions.Web/Startup.cs, DigitalLearningSolutions.Web/Views/Supervisor/Shared/_StaffMemberCard.cshtml
https://hee-tis.atlassian.net/jira/software/c/projects/TD/boards/165?modal=detail&selectedIssue=TD-679&assignee=6321797ece3e476e42ac8a00
Refactored email generation code post-uar. 
Also fixed issue with 'promote delegate to nominated supervisor' where incorrect id was used to derive delegate details.
n/a
-----
I have:
=> TD-679 Delegate Promoted To Admin Email UAR

DigitalLearningSolutions.Web/Controllers/LoginController.cs, DigitalLearningSolutions.Web/Styles/myAccount/myAccount.scss, DigitalLearningSolutions.Web/Views/MyAccount/Index.cshtml
https://hee-tis.atlassian.net/browse/TD-759
Add a callout to the My Account page when user is not logged into a centre. The user is redirected to My Account page after login if the user is not associated with a center.
A video is attached to the jira item.
-----
I have:
=> TD-759 Add a callout to the My Account page when user is not logged into a centre

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/EditDelegateControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/EditDelegateController.cs
JIRA link
https://hee-tis.atlassian.net/browse/TD-718
server-side email validation implemented.
Screenshots
-----
I have:
=> TD-718 - Delegate edit-email-not-validated-UAR

DigitalLearningSolutions.Web/Controllers/MyAccountController.cs, DigitalLearningSolutions.Web/ViewModels/MyAccount/MyAccountViewModel.cs, DigitalLearningSolutions.Web/Views/MyAccount/_CentreSpecificDetailsCard.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-255
properties added to ViewModel to show roles.
-----
I have:
=> TD-255-Display user roles at the current centre on the My Account page

DigitalLearningSolutions.Web/Startup.cs, DigitalLearningSolutions.Web/appsettings.json
https://hee-tis.atlassian.net/browse/TD-754
Please see the jira for description
No Screenshot required.
-----
I have:
=> TD-754 UAR - fix transaction consistency

DigitalLearningSolutions.Web.Tests/Services/EmailGenerationServiceTests.cs, DigitalLearningSolutions.Web/Services/EmailGenerationService.cs
_[TD-583](https://hee-tis.atlassian.net/browse/TD-583)_
Tweaks the role names to match those seen elsewhere in the system.
-----
I have:
=> TD-583 tweak promote to admin email role labels

DigitalLearningSolutions.Web/Controllers/MyAccountController.cs
_[TD-583](https://hee-tis.atlassian.net/browse/TD-583)_
Tweaks roles on My Account to standardise capitalisation
-----
I have:
=> TD-583 Tweaks roles on My Account to standardise capitalisation

DigitalLearningSolutions.Web/Views/VerifyEmail/VerificationLinkError.cshtml
https://hee-tis.atlassian.net/browse/TD-745
Html Content Change for Verification link Expired Page as per comment added in ticket
https://hee-tis.atlassian.net/browse/TD-745
-----
I have:
=> Html Content Change for Verification link Expired Page

DigitalLearningSolutions.Web/Views/ClaimAccount/Index.cshtml, DigitalLearningSolutions.Web/Views/RegisterAtNewCentre/Confirmation.cshtml, DigitalLearningSolutions.Web/Views/Shared/_TextInputItem.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-756
Text message updated, switch center link added, style for textinput control removed.
-----
I have:
=> TD-756 - UAR - Tidy up UI for journeys added or changed

DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs
_[TD-848](https://hee-tis.atlassian.net/browse/TD-848)_
Fixes the confirmed by supervisor name in the supervisor review competency self assessment interface.
-----
I have:
=> TD-848 Fix to confirmed by supervisor name

DigitalLearningSolutions.Data/DataServices/CentresDataService.cs
_[TD-862](https://hee-tis.atlassian.net/browse/TD-862)_
Removes requirement for centre record to have geocoding information for centre to be displayed on "Find your centre" page
-----
I have:
=> TD-862 Fix "Find your centre" show centres without location data

DigitalLearningSolutions.Web/Views/MyAccount/Index.cshtml
https://hee-tis.atlassian.net/browse/TD-759
Html change as per comment added in ticket
https://hee-tis.atlassian.net/browse/TD-759
-----
I have:
=> html change as per comment added in ticket

DigitalLearningSolutions.Web/Controllers/LearningPortalController/Current.cs
https://hee-tis.atlassian.net/browse/TD-263
Parameter correction for self assessment result in current activities
-----
I have:
=> Parameter correction for self assessment result

DigitalLearningSolutions.Web/Views/RegisterAdmin/PersonalInformation.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-898
Required parameter added to control.
-----
I have:
=> TD-898-UAR: Primary email field is missing on External Admin Registration

DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests/UserCentreDetailsDataServiceTests.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserCentreDetailsDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Web.Tests/Services/GroupServiceTests/GroupsServiceSynchroniseGroupsTests.cs, DigitalLearningSolutions.Web/Services/GroupsService.cs, DigitalLearningSolutions.Web/Services/UserService.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-755
Execution of UpdateUser() method moved after SynchroniseJobGroupsOnOtherCentres() method.
N/A
-----
I have:
=> TD-755-UAR-Update all a user's centres' groups after a job group update

DigitalLearningSolutions.Data/DataServices/UserDataService/DelegateUserCardDataService.cs, DigitalLearningSolutions.Data/Models/User/DelegateUser.cs, DigitalLearningSolutions.Data/Models/User/DelegateUserCard.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ViewDelegateController.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ViewDelegate/DelegateAccountAlreadyClaimed.cshtml
https://hee-tis.atlassian.net/browse/TD-811
Fixed Delegate previously claimed account login doesn’t work
https://hee-tis.atlassian.net/browse/TD-811
-----
I have:
=> Fixed Delegate previously claimed account login doesn’t work

DigitalLearningSolutions.Data/DataServices/UserDataService/UserCentreDetailsDataService.cs
https://hee-tis.atlassian.net/browse/TD-826
Fixed showing status is Active when Delegate email is unverified
-----
I have:
=> Fixed showing status is Active when Delegate email is unverified

DigitalLearningSolutions.Web/Views/Shared/Components/DictionaryTextInput/Default.cshtml, DigitalLearningSolutions.Web/Views/Shared/_TextInputItem.cshtml
https://hee-tis.atlassian.net/browse/TD-907
Fixed edit details page not saving the new centre emails
https://hee-tis.atlassian.net/browse/TD-907
-----
I have:
=> Fixed edit details page not saving the new centre emails

DigitalLearningSolutions.Data/DataServices/UserDataService/UserCentreDetailsDataService.cs
Reverts TechnologyEnhancedLearning/DLSV2#1559 so that testing team can continue
=> Revert "Fixed showing status is Active when Delegate email is unverified"

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs
(https://hee-tis.atlassian.net/browse/TD-268)
Allow delegates to add supervisors from different centres for self-assessments
Backend change so no screenshots available
-----
I have:
=> TD-268 Allow delegates to add supervisors from different centres for self-assessments

DigitalLearningSolutions.Data/DataServices/SupervisorDelegateDataService.cs, DigitalLearningSolutions.Data/DataServices/SupervisorService.cs
https://hee-tis.atlassian.net/jira/software/c/projects/TD/boards/165?modal=detail&selectedIssue=TD-905
Corrected spurious 'Not registered' tag on MyStaff page - updated AddSuperviseDelegate to lookup via UserCentreDetails.Email instead of User.PrimaryEmail (which may still be a guid at this point).
-----
I have:
=> TD-905 My Staff List Issues

DigitalLearningSolutions.Data.Tests/DataServices/SelfAssessmentDataServiceTests/CompetencyDataServiceTests.cs, DigitalLearningSolutions.Data.Tests/DataServices/SelfAssessmentDataServiceTests/SelfAssessmentDataServiceTests.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/SupervisorComment.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs
[TD-1031](https://hee-tis.atlassian.net/browse/TD-1031)
Fixes duplicated self assessment result rows by changing latest assessment results queries to take delegateID parameter (instead of delegateUserID).
Also fixes broken reference to deprecated candidate ID field in supervisor comments service and model.
-----
I have:
[TD-1031]: https://hee-tis.atlassian.net/browse/TD-1031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1031 Fix duplicated self assessment result rows

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/PromoteToAdminController.cs, DigitalLearningSolutions.Web/ViewComponents/CheckboxesViewComponent.cs, DigitalLearningSolutions.Web/ViewModels/Common/ViewComponents/CheckboxesViewModel.cs, DigitalLearningSolutions.Web/Views/Shared/Components/Checkboxes/Default.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Administrator/EditAdminRoles.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AddNewCentreCourse/SetCourseOptions.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/ManageCourse/EditCourseOptions.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/Shared/_EditCourseOptionsFormInputs.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateGroups/GenerateGroups.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/PromoteToAdmin/Index.cshtml
https://hee-tis.atlassian.net/browse/TD-849
Fixed validation error not showing on the top of the input
https://hee-tis.atlassian.net/browse/TD-849
-----
I have:
=> Fixed validation error not showing on the top of the input

DigitalLearningSolutions.Data.Migrations/202301241533_CreateGetActivitiesForDelegateEnrolmentSP.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.Designer.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.resx, DigitalLearningSolutions.Data.Migrations/Scripts/td-1043-getactivitiesforenrolment.sql, DigitalLearningSolutions.Data.Migrations/Scripts/td-1043-getactivitiesforenrolment_down.sql, DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/DelegateUserDataService.cs, DigitalLearningSolutions.Data/Models/SessionData/Tracking/Deligate/Enrol/SessionEnrolDelegate.cs, DigitalLearningSolutions.Data/Models/User/DelegateUser.cs, DigitalLearningSolutions.Data/Models/User/DelegateUserCard.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/EnrolControllerTests.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/EnrolController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ViewDelegateController.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/Enrol/CompletedByDateViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/Enrol/EnrolCurrentLearningViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/Enrol/EnrolDelegateSummaryViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/Enrol/EnrolSupervisorViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/Shared/DelegateInfoViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ViewDelegate/Index.cshtml
[TD-1043](https://hee-tis.atlassian.net/browse/TD-1043)
Fixes problems with delegate enrolment on activities from the Tracking System -> Delegates interface.
Changes include:
- Adds delegate user ID (distinct from delegate ID) to the Delegate info model so that the enrol service has access to both ids.
- Better uses the multi-page form session data to store and retrieve values relating to enrolment (rather than relying on URL params)
- Introduces a common, refactored stored procedure for retrieving activities available for delegate enrolment (used across Tracking System -> Delegate enrolment and Learning Portal -> Available activities)
- Fixes to data services for enrolment on self assessments and adding supervisor delegate records
-----
(Leave tasks unticked if they haven't been …
=> TD-1043 enrol on self assessment error

DigitalLearningSolutions.Web.Tests/Controllers/Register/RegisterAtNewCentreControllerTests.cs, DigitalLearningSolutions.Web/Controllers/Register/RegisterAtNewCentreController.cs, DigitalLearningSolutions.Web/ViewModels/Register/InternalConfirmationViewModel.cs, DigitalLearningSolutions.Web/Views/RegisterAtNewCentre/Confirmation.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-756
Check added if the user has an admin account without a delegate account at the same centre.
Screenshots
-----
I have:
=> TD-756 uar tidy up UI for journeys added or changed bug fix

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentExportDataService.cs
https://hee-tis.atlassian.net/browse/TD-1050
Fixed Self-Assessment Export to Excel results in error
-----
I have:
=> Fixed Self-Assessment Export to Excel results in error

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/EmailDelegatesController.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/EmailDelegates/Index.cshtml
https://hee-tis.atlassian.net/browse/TD-1083
Fixed Validation error msg is missing on the 'select delegates' checkboxes on the 'Send welcome messages' screen
https://hee-tis.atlassian.net/browse/TD-1083
-----
I have:
=> Fixed validation error msg is missing on send welcome message screen

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/ReviewConfirmationRequests.cshtml
https://hee-tis.atlassian.net/browse/TD-584
Fixed optional proficiency in confirmation request
https://hee-tis.atlassian.net/browse/TD-584
-----
I have:
=> Fixed optional proficiency in confirmation request

DigitalLearningSolutions.Data/DataServices/SupervisorService.cs, DigitalLearningSolutions.Web/Controllers/Register/RegisterAtNewCentreController.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs
[TD-1045](https://hee-tis.atlassian.net/jira/software/c/projects/TD/boards/165?modal=detail&selectedIssue=TD-1045)
Fixed delegate registration paths (new ad-hoc delegate via MyStaff email, create new delegate account via email invite, add existing delegate to MyStaff) 
-----
I have:
[TD-1045]: https://hee-tis.atlassian.net/browse/TD-1045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1045 Fixed delegate registration paths 

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Administrator/AdministratorController.cs
[TD-253](https://hee-tis.atlassian.net/jira/software/c/projects/TD/boards/165?modal=detail&selectedIssue=TD-253)
Fixed issue when adding admin roles via /TrackingSystem/Centre/Administrators/ path.
-----
I have:
[TD-253]: https://hee-tis.atlassian.net/browse/TD-253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-253 Promote admin role uar rework

DigitalLearningSolutions.Web/Controllers/SuperAdmin/Users/UsersController.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Shared/_NavMenuItems.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Shared/_UserAccountsSideNavMenu.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Users/Index.cshtml
TD-1109
Formatter changes not pushed to remote for work on this ticket.
-----
I have:
=> TD-1109 VS formatter changes 

DigitalLearningSolutions.Web/Controllers/Register/RegisterDelegateByCentreController.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1097
Clearing tempdata avoided.
N/A
-----
I have:
=> TD-1097-UAR: Issue when refreshed the registration confirmation page after admin registers delegate internally

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1120
SQL queries updated to add delegate account active state
-----
I have:
=> TD-1120-Handle inactivated delegate accounts in the Learner Self Assessment interface

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_SelfAssessmentCard.cshtml
https://hee-tis.atlassian.net/browse/TD-265
Fixed show 'Enrolled at' in summary list
https://hee-tis.atlassian.net/browse/TD-265
-----
I have:
=> TD-265 Fixed show 'Enrolled at' in summary list

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Administrator/AdministratorController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/PromoteToAdminController.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Administrator/EditAdminRoles.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1133
Validation added for an admin role in edit mode.
-----
I have:
=> TD-1133-Error msg missing on 'Edit administrator roles' screen

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAsssessmentReportDataService.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/Export/SelfAssessmentReportData.cs, DigitalLearningSolutions.Data/Services/SelfAssessmentReportService.cs
TD-1142
Changes column names in Excel report for self assessments.
-----
I have:
=> TD-1142 Changes column names in Excel report

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_RadioQuestion.cshtml
https://hee-tis.atlassian.net/browse/TD-749
Fixed Spacing between Review questions heading and hint text
https://hee-tis.atlassian.net/browse/TD-749
-----
I have:
=> Fixed Spacing between Review questions heading and hint text

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/PromoteToAdminController.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1132
ContentManager role validation added.
N/A
-----
I have:
=> TD-1132-UAR: Error message showing when 'Promoting delegate to admin' eventhough CMS roles have been selected

DigitalLearningSolutions.Data/DataServices/SupervisorService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/DelegateUserDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/PromoteToAdminControllerTests.cs, DigitalLearningSolutions.Web.Tests/Services/UserServiceTests.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Administrator/AdministratorController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/PromoteToAdminController.cs, DigitalLearningSolutions.Web/Services/UserService.cs
[TD-253](https://hee-tis.atlassian.net/jira/software/c/projects/TD/boards/165?modal=detail&selectedIssue=TD-253)
Fixed issue where the system was erroring when returning multiple delegate records when the delegate was already a nominated supervisor at a different centre.
Screenshot below
-----
I have:
[TD-253]: https://hee-tis.atlassian.net/browse/TD-253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-253 Nominated supervisor UAR rework 2

DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs
[TD-747](https://hee-tis.atlassian.net/browse/TD-747)
Removes redundant code that redirects the learner to the old site when various criteria are met, forcing all code paths to result in enrolment.
-----
I have:
[TD-747]: https://hee-tis.atlassian.net/browse/TD-747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-747 Fix delegate enrol on course from Available Activities

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs
[TD-1143](https://hee-tis.atlassian.net/jira/software/c/projects/TD/boards/165?modal=detail&selectedIssue=TD-1143)
Corrected sql join to filter on CentreSelfAssessments with the current centre.
-----
I have:
[TD-1143]: https://hee-tis.atlassian.net/browse/TD-1143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1143 Hide unpublished for centre self assessments rework

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs, DigitalLearningSolutions.Data/Models/SessionData/SelfAssessments/SessionAddSupervisor.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/SetSupervisorRoleViewModel.cs, DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/SupervisorCentreViewModel.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/AddSupervisor.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/AddSupervisorSummary.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelectSupervisorCentre.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SetSupervisorRole.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1123
Code modified to check supervisor from multiple centres. A view added to choose centre that we wish to add a supervisor from.
Screenshots
-----
I have:
=> TD-1123 Show supervisors from all user centres in Add Supervisor interface

DigitalLearningSolutions.Data/DataServices/UserDataService/AdminUserDataService.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Administrator/AdministratorController.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-844
Attribute NoCaching added, retrieved active admin user.
N/A
-----
I have:
=> TD-844 - UAR: Console '404' error when deactivating an admin account and clicking browser back

DigitalLearningSolutions.Data/DataServices/CertificateDataService.cs, DigitalLearningSolutions.Web/Controllers/Certificate/CertificateController.cs, DigitalLearningSolutions.Web/Services/LoginService.cs, DigitalLearningSolutions.Web/Views/LearningPortal/Completed/CompletedCourseCard/_CompletedCourseCard.cshtml
https://hee-tis.atlassian.net/browse/TD-858
Implement DLS course certificates in DLSV2 : 
Issue1 : Logged in as Admin Delegate, Name is not displayed in the Certificate
Issue 2: When logged in only as Delegate, Not able to download the certificate via Evaluate. It is showing access denied.
-----
I have:
=> TD-858 implement dls course certificates in dlsv2

DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs
[TD-1151](https://hee-tis.atlassian.net/jira/software/c/projects/TD/boards/165?modal=detail&selectedIssue=TD-1151)
Fixed issue where system was 404ing under certain conditions.
-----
I have:
[TD-1151]: https://hee-tis.atlassian.net/browse/TD-1151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1151 Overwrite confirmed self assessment result routing issue.

DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs
[TD-1151](https://hee-tis.atlassian.net/jira/software/c/projects/TD/boards/165?modal=detail&selectedIssue=TD-1151)
Corrected routing call on overwrite confirmed self-assessment result so that it now displays the next proficiency in the sequence.
-----
I have:
[TD-1151]: https://hee-tis.atlassian.net/browse/TD-1151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1151 Overwrite confirmed self assessment result fixed ongoing routing

DigitalLearningSolutions.Web/Helpers/CommonValidationErrorMessages.cs, DigitalLearningSolutions.Web/ViewModels/Supervisor/AddMultipleSupervisorDelegatesViewModel.cs
https://hee-tis.atlassian.net/browse/TD-1158
Improve validation error msg
https://hee-tis.atlassian.net/browse/TD-1158
-----
I have:
=> TD-1158 Improve validation error msg

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/AddSupervisor.cshtml
https://hee-tis.atlassian.net/browse/TD-1156
Fixed validation error msg is missing
https://hee-tis.atlassian.net/browse/TD-1156
-----
I have:
=> TD-1156 Fixed validation error msg is missing

DigitalLearningSolutions.Web/Scripts/cookiesbanner.ts, DigitalLearningSolutions.Web/Views/Shared/_CookieConsentPartial.cshtml
#1703 
Updated the process for obtaining the cookie consent URL. It will be consistent across all deployment techniques to create the fully qualified URL using URL.Action.
-----
I have:
=> TD-1703 Updated the way we get the post URL, through URL.Action

DigitalLearningSolutions.Web.Tests/Controllers/Register/ClaimAccountControllerTests.cs, DigitalLearningSolutions.Web/Controllers/Register/ClaimAccountController.cs, DigitalLearningSolutions.Web/Controllers/VerifyYourEmailController.cs, DigitalLearningSolutions.Web/Helpers/VerifyYourEmailTextHelper.cs
https://hee-tis.atlassian.net/browse/TD-1194
Fixed email is received twice
https://hee-tis.atlassian.net/browse/TD-1194
-----
I have:
=> TD-1194 Fixed email is received twice

DigitalLearningSolutions.Web/Controllers/Register/RegisterAtNewCentreController.cs
https://hee-tis.atlassian.net/browse/TD-261
Fixed error msg changed and field point
https://hee-tis.atlassian.net/browse/TD-261
-----
I have:
=> TD-261 error msg changed and field point

DigitalLearningSolutions.Web/Views/SuperAdmin/Users/UserCentreAccounts.cshtml
https://hee-tis.atlassian.net/browse/TD-1173
Wired up the "Admin" link on Super Admin - User Accounts - User centre accounts page
Please note: waiting for TD-943 to be completed to test this functionality
-----
I have:
=> TD-1173 wire up the admin link on super admin user accounts user centre accounts page

DigitalLearningSolutions.Web/Views/SuperAdmin/Users/_SearchableUserCard.cshtml
https://hee-tis.atlassian.net/browse/TD-1134
Super Admin - User Accounts - Unlock account action
Unlock is enabled now and is clickable.
-----
I have:
=> TD-1134:Super Admin - User Accounts - Unlock account action-Bug fix

DigitalLearningSolutions.Web/Controllers/SuperAdmin/Users/UsersController.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Users/Index.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Users/_SearchableUserCard.cshtml
https://hee-tis.atlassian.net/browse/TD-992
Fixed UI changes and paginated issue after edit
https://hee-tis.atlassian.net/browse/TD-992
-----
I have:
=> TD-992 Fixed UI changes and paginated issue after edit

DigitalLearningSolutions.Data/Models/User/AdminEntity.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1149
Properties added to AdminEntity
N/A
-----
I have:
=> TD-1149 -Search, sort, filter paginate service cached filters issue

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/ReviewConfirmationRequests.cshtml
https://hee-tis.atlassian.net/browse/TD-1186
Fixed Mobile View issue on Proficiency Confirmation requests
https://hee-tis.atlassian.net/browse/TD-1186
-----
I have:
=> TD-1186 Fixed Mobile View issue on Proficiency Confirmation requests

DigitalLearningSolutions.Data/Enums/ChooseACentreStatus.cs, DigitalLearningSolutions.Data/ViewModels/UserCentreAccount/UserCentreAccountsRoleViewModel.cs, DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/UsersControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Users/UsersController.cs, DigitalLearningSolutions.Web/Services/UserCentreAccountsService.cs
https://hee-tis.atlassian.net/browse/TD-994
Super Admin - User Accounts - User centre accounts page
**Before issue fix**
**After issue fix**
-----
I have:
=> TD-994:Super Admin - User Accounts - User centre accounts page_issue fix

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAsssessmentReportDataService.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/Export/SelfAssessmentReportData.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/Export/SelfAssessmentSelect.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/SelfAssessmentReports/SelfAssessmentReportsController.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentReportService.cs, DigitalLearningSolutions.Web/Startup.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Reports/SelfAssessmentReportsViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/SelfAssessmentReports/Index.cshtml
TD-1284
Reimplements Excel export centre reports for supervised self assessments against the UAR code branch.
-----
I have:
=> TD-1284 Re-implement self assessment excel reports for UAR

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/DelegateGroupsControllerTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/GroupDelegatesControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/GroupDelegatesController.cs, DigitalLearningSolutions.Web/Services/GroupsService.cs
https://hee-tis.atlassian.net/browse/TD-1234
Fixed delegate group doesnt display unclaimed delegates
-----
I have:
=> TD-1234 Fixed delegate group doesnt display unclaimed delegates

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAsssessmentReportDataService.cs
TD-1284
Removes declare variables accidentally left in query
-----
I have:
=> TD-1284 Self assessment reports tidy up

DigitalLearningSolutions.Web.Tests/Services/EmailGenerationServiceTests.cs, DigitalLearningSolutions.Web/Services/EmailGenerationService.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Administrator/AdminRoleInputs.cs
https://hee-tis.atlassian.net/browse/TD-583
Fixed mismatch of the wording of the roles
-----
I have:
=> TD-583 Fixed mismatch of the wording of the roles

DigitalLearningSolutions.Data/DataServices/UserDataService/UserCentreDetailsDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Web/Helpers/CommonValidationErrorMessages.cs, DigitalLearningSolutions.Web/Helpers/RegistrationEmailValidator.cs
https://hee-tis.atlassian.net/browse/TD-1276
Fixed not showing error msg on centre email
https://hee-tis.atlassian.net/browse/TD-1276
-----
I have:
=> TD-1276 Fixed not showing error msg on centre email

DigitalLearningSolutions.Web/Services/DelegateDownloadFileService.cs
https://hee-tis.atlassian.net/browse/TD-1280
Fixed Download Delegates Excel contains GUID in Email Address
-----
I have:
=> TD-1280 Fixed Download Delegates Excel contains GUID in Email Address

DigitalLearningSolutions.Data/DataServices/UserDataService/AdminUserDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/AdminAccountsControllerTests.cs, DigitalLearningSolutions.Web.Tests/Helpers/FilterableTagHelperTests.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Administrators/AdminAccountsController.cs, DigitalLearningSolutions.Web/Helpers/FilterableTagHelper.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Administrators/SearchableAdminAccountsViewModel.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/AdminAccounts/Index.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-943
Title display name order changed to First name, Last name.
A check is added if logged in admin active.
Role tags SuperAdmin, ReportsViewer added.
View - search text/ button alignment done.
-----
I have:
=> TD-943 Super Admin - Administrators - Issue fix

DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/UsersControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Users/UsersController.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Users/_SearchableUserCard.cshtml
https://hee-tis.atlassian.net/browse/TD-1308
Super Admin - User Accounts - Verify email action
-----
I have:
=> Super Admin - User Accounts - Verify email action

DigitalLearningSolutions.Data/DataServices/GroupsDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/DelegateGroupsControllerTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/GroupDelegatesControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/GroupDelegatesController.cs, DigitalLearningSolutions.Web/Services/GroupsService.cs
https://hee-tis.atlassian.net/browse/TD-1234
Fixed delegate count not correct
-----
I have:
=> TD-1234 delegate count not correct

DigitalLearningSolutions.Web/Controllers/SuperAdmin/Administrators/AdminAccountsController.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/AdminAccounts/_SearchableAdminAccountsCard.cshtml
https://hee-tis.atlassian.net/browse/TD-990
Super Admin - Administrators - Delete unused admin account action
-----
I have:
=> TD-990 Super Admin - Administrators - Delete unused admin account action

DigitalLearningSolutions.Data/DataServices/UserDataService/AdminUserDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Administrators/AdminAccountsController.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/AdminAccounts/_SearchableAdminAccountsCard.cshtml
https://hee-tis.atlassian.net/browse/TD-1135
Super Admin - Administrators - Inactivate/Activate action
https://hee-tis.atlassian.net/browse/TD-1135
-----
I have:
=> TD-1135 Super Admin - Administrators - Inactivate/Activate action

DigitalLearningSolutions.Data.Migrations/Scripts/TD-1283-UpdateHtmlContactDetails.sql, DigitalLearningSolutions.Web.Tests/Controllers/LearningSolutions/LearningSolutionsControllerTests.cs, DigitalLearningSolutions.Web/Controllers/LearningSolutions/LearningSolutionsController.cs, DigitalLearningSolutions.Web/ViewModels/LearningSolutions/ContactViewModel.cs, DigitalLearningSolutions.Web/Views/LearningSolutions/Contact.cshtml, DigitalLearningSolutions.Web/Views/LearningSolutions/_CentreDetails.cshtml
[TD-1283](https://hee-tis.atlassian.net/browse/TD-1283)
Update the contact details of the contact us page
**Unauthenticated User**
**Authenticated User**
-----
I have:
[TD-1283]: https://hee-tis.atlassian.net/browse/TD-1283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD 1283 Add centre contact details into the contact us screen

DigitalLearningSolutions.Web/Controllers/LearningSolutions/LearningSolutionsController.cs, DigitalLearningSolutions.Web/Controllers/Register/RegisterDelegateByCentreController.cs
https://hee-tis.atlassian.net/browse/TD-1181
Fixed error showing sometimes ‘404’/'302'
-----
I have:
=> TD-1181 Fixed error showing sometimes 404 302

DigitalLearningSolutions.Web/Services/AdminDownloadFileService.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-951
Additional columns added to the report.
N/A
-----
I have:
=> TD-951-Super Admin - Administrators-Export to excel-columns added.

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/ReviewConfirmationRequests.cshtml
https://hee-tis.atlassian.net/browse/TD-1186
Fixed Desktop View issue on Proficiency Confirmation requests
https://hee-tis.atlassian.net/browse/TD-1186
-----
I have:
=> TD-1186 Fixed Desktop View issue on Proficiency Confirmation requests

.gitignore, DigitalLearningSolutions.Web/DigitalLearningSolutions.Web.csproj, DigitalLearningSolutions.Web/Models/Enums/ContentManagementRole.cs, DigitalLearningSolutions.Web/ViewComponents/RadiosViewComponent.cs, DigitalLearningSolutions.Web/ViewModels/Common/AdminRolesViewModel.cs, DigitalLearningSolutions.Web/ViewModels/Common/ViewComponents/RadiosItemViewModel.cs, DigitalLearningSolutions.Web/ViewModels/Common/ViewComponents/RadiosListItemViewModel.cs, DigitalLearningSolutions.Web/ViewModels/Common/ViewComponents/RadiosViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Administrator/AdminRoleInputs.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/DelegateProgress/EditDelegateCourseAdminFieldViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/Enrol/EnrolSupervisorViewModel.cs, DigitalLearningSolutions.Web/Views/Shared/Components/Radios/Default.cshtml
[TD-1383](https://hee-tis.atlassian.net/browse/TD-1383)
Replace the nuget package in DLS Solution and re implement radios view component
-----
I have:
[TD-1383]: https://hee-tis.atlassian.net/browse/TD-1383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1383 implement checkboxes and radios view components in dls solution

DigitalLearningSolutions.Data/DataServices/SupervisorService.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1307
Check added if the supervisor exists and is active.
N/A
-----
I have:
=> TD-1307-Remove Staff member and Adding the same staff again results in error.

DigitalLearningSolutions.Web/Startup.cs
https://hee-tis.atlassian.net/browse/TD-1111
TD-1111
-----
I have:
=> Fixing java script error

DigitalLearningSolutions.Web/Views/SuperAdmin/Users/EditUserDetails.cshtml
https://hee-tis.atlassian.net/browse/TD-996
Changed submit button to Save button
https://hee-tis.atlassian.net/browse/TD-996
-----
I have:
=> TD-996 Changed submit button to Save button

DigitalLearningSolutions.Data/DataServices/SupervisorService.cs
https://hee-tis.atlassian.net/browse/TD-1241
Fixed Confirm assessments link missing on Supervisor Dashboard
https://hee-tis.atlassian.net/browse/TD-1241
-----
I have:
=> TD-1241 Fixed Confirm assessments link missing on Supervisor Dashboard

DigitalLearningSolutions.Data/DataServices/UserDataService/AdminUserDataService.cs
https://hee-tis.atlassian.net/browse/TD-990
Fixed delete unused account 500 error
-----
I have:
=> TD-990 Fixed delete unused account 500 error

DigitalLearningSolutions.Web/Controllers/LearningSolutions/CookieConsentController.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_Layout.cshtml, DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml
https://hee-tis.atlassian.net/browse/TD-1395
Respect users cookie choices when deciding whether to load Google analytics
-----
I have:
=> TD-1395 Respect user's cookie choice

DigitalLearningSolutions.Web/Views/Supervisor/VerifyMultipleResults.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1389
css link removed.
-----
I have:
=> TD-1389-Mobile view issue when navigated to 'Confirm Multiple results' screen

DigitalLearningSolutions.Web/Controllers/LearningSolutions/CookieConsentController.cs
https://hee-tis.atlassian.net/browse/TD-1395
Fix - Only delete the cookies for the given domain.
-----
I have:
=> TD-1395 Delete HJ and GA cookies only for the given domain

DigitalLearningSolutions.Data/DataServices/NotificationDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/AdminUserDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Data/Models/User/AdminUser.cs, DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/AdminAccountsControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Administrators/AdminAccountsController.cs, DigitalLearningSolutions.Web/ViewModels/Common/AdminRolesFormData.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Administrators/ManageRoleViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Administrator/AdminRoleInputs.cs, DigitalLearningSolutions.Web/Views/Shared/Components/Radios/Default.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/AdminAccounts/ManageRoles.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/AdminAccounts/_SearchableAdminAccountsCard.cshtml
https://hee-tis.atlassian.net/browse/TD-954
Super Admin - Administrators - Manage Roles view
https://hee-tis.atlassian.net/browse/TD-954
-----
I have:
=> TD-954 Super Admin - Administrators - Manage Roles view

DigitalLearningSolutions.Data/DataServices/SupervisorService.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1307
Removed CandidateID from Sql query.
N/A
-----
I have:
=> TD-1307-Remove Staff member and Adding the same staff again results in error

DigitalLearningSolutions.Data.Migrations/202304191130_AddSystemVersioning_SelfAssessmentResultSupervisorVerifications.cs, DigitalLearningSolutions.Data.Migrations/202304191130_Delete_SelfAssessmentResult_SupervisorVerifications.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.Designer.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.resx, DigitalLearningSolutions.Data.Migrations/Scripts/TD-1220-AddSystemVersioning_SelfAssessmentResultSupervisorVerifications.sql, DigitalLearningSolutions.Data.Migrations/Scripts/TD-1220-RemoveSystemVersioning_SelfAssessmentResultSupervisorVerifications.sql, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentExportDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAsssessmentReportDataService.cs, DigitalLearningSolutions.Data/DataServices/SupervisorService.cs
https://hee-tis.atlassian.net/browse/TD-1220
1. Created history table SelfAssessmentResultSupervisorVerificationsHistory for SelfAssessmentResultSupervisorVerifications
2. Deleted multiple records from tables SelfAssessmentResults & SelfAssessmentResultSupervisorVerifications
3. Created a Unique constraint to the SelfAssessmentResults table on DelegateUserID, CompetencyID, AssessmentQuestionID
4. Altered queries used logic to get latest record from SelfAssessmentResults table.
After code changes:
SelfAssessmentResultSupervisorVerifications table changes:
SelfAssessmentResults table changes
Deleted duplicate records
1. CandidateAssessmentExportDataService.cs
GetCandidateAssessmentExportSummary 
Old query result:
After change result:
2. CompetencyDataService.cs
Before code change:
After …
=> TD-1220:Fixes to SelfAssessmentResults table usage

DigitalLearningSolutions.Data/DataServices/FrameworkService.cs, DigitalLearningSolutions.Data/Models/Frameworks/FrameworkCompetency.cs, DigitalLearningSolutions.Web/Controllers/FrameworksController/Competencies.cs, DigitalLearningSolutions.Web/ViewModels/Frameworks/SimilarCompetencyViewModel.cs, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Competency.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/SimilarCompetency.cshtml
[TD-710](https://hee-tis.atlassian.net/browse/TD-710)
re-implemented TD-710
-----
I have:
[TD-710]: https://hee-tis.atlassian.net/browse/TD-710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-710 reimplementation

DigitalLearningSolutions.Data/DataServices/CentresDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/AdminUserDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/AdminAccountsControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Administrators/AdminAccountsController.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Administrators/EditCentreViewModel.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Administrators/ManageRoleViewModel.cs, DigitalLearningSolutions.Web/Views/ApplicationSelector/Index.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/AdminAccounts/EditCentre.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/AdminAccounts/_SearchableAdminAccountsCard.cshtml
[TD-1400](https://hee-tis.atlassian.net/browse/TD-1400)
Implements a new Super Admin change centre view for updating Administrator centre. Also tweaks the "Super admin" tile on the app selector to read "Super Admin".
-----
I have:
[TD-1400]: https://hee-tis.atlassian.net/browse/TD-1400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1400 Super admin - Administrator - change centre view

DigitalLearningSolutions.Data.Migrations/Scripts/TD-1283-UpdateHtmlContactDetails.sql
[TD-1283](https://hee-tis.atlassian.net/browse/TD-1283)
The script to overwrite contactHtml db content updated.
-----
I have:
[TD-1283]: https://hee-tis.atlassian.net/browse/TD-1283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1283: Database content update

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs
Removes use of ELSE IF / ELSE to concrete standalone IF statements for better reliability when choosing whether to insert or update a result record.
-----
I have:
=> TD-1220 Improvements to insert result logic

DigitalLearningSolutions.Data/Models/Common/Users/Administrator.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/DigitalLearningSolutions.Web.csproj, DigitalLearningSolutions.Web/Scripts/learningPortal/supervisorList.ts, DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/AddSupervisorViewModel.cs, DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/AllSupervisorsViewModel.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/AddSupervisor.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/AllSupervisors.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SetSupervisorRole.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-161
Search (Javascript and Non-JavaScript) added.
-----
I have:
=> TD-161 -Provide searchable list of supervisors when adding a supervisor from the self assessment manage supervisors view

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs
Fixes the issue with overwriting stored NULL results by tweaking the data service query.
-----
I have:
=> TD-1220 Fixes the issue with overwriting stored NULL results

DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SetSupervisorRole.cshtml
https://hee-tis.atlassian.net/browse/TD-1464
1) Fixed 410 error while clicking back button after navigating to set supervisor role page.
2) Changed the back link in set supervisor role while we navigated there from "Add new supervisor" page.
3) Changed the back link label to "Back to Manage Supervisors" from "Back to Choose a supervisor" while adding supervisor from quick add.
[Self-Assessment---Digital-Learning-Solutions.webm](https://github.com/TechnologyEnhancedLearning/DLSV2/assets/111436026/2c4766ec-b93a-4c44-90af-1091d6fa95ec)
-----
I have:
=> TD-1464 Fixed 410 error and back link in set supervisor role

DigitalLearningSolutions.Web/Views/SuperAdmin/Users/EditUserDetails.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1398
Check box moved to next line.
-----
I have:
=> TD-1398-Issue overlapping the error msg with checkbox on Super Admin section of 'Edit Details' screen

DigitalLearningSolutions.Data/Enums/TrackerEndpointAction.cs, DigitalLearningSolutions.Web/Services/TrackerService.cs
[TD-1555](https://hee-tis.atlassian.net/browse/TD-1555)
Converts tracker action names to lower case for comparison to overcome case sensitivity issues.
-----
I have:
[TD-1555]: https://hee-tis.atlassian.net/browse/TD-1555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1555 Converts tracker action names to lower case for comparison

DigitalLearningSolutions.Web/Controllers/TrackingSystem/TrackerController.cs
[TD-1555](https://hee-tis.atlassian.net/browse/TD-1555)
Handles post and get request on tracker endpoints because posted requests are still returning an error.
-----
I have:
[TD-1555]: https://hee-tis.atlassian.net/browse/TD-1555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1555 Handles post and get request on tracker endpoints

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SetSupervisorRole.cshtml
https://hee-tis.atlassian.net/browse/TD-1464
1) Fixed navigation issue for Back to Choose a supervisor link.
[My-Current-Activities---Digital-Learning-Solutions.webm](https://github.com/TechnologyEnhancedLearning/DLSV2/assets/111436026/20dbf5b5-0997-409b-80c0-4e09392ba46b)
-----
I have:
=> TD-1464 Fixed navigation issue for Back to Choose a supervisor link

DigitalLearningSolutions.Data/DataServices/UserDataService/DelegateUserDataService.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1554
Used FirstOrDefault() for SQL query to return single record.
N/A
-----
I have:
=> TD-1554-Showing Console '500' error on the screen when clicked 'Manage Delegate'

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/AddSupervisorSummary.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1448
Page title changed to 'Supervisor summary'.
-----
I have:
=> TD-1448-Manage Supervisors > summary: change 'Add Supervisor Summary' title to 'Supervisor Summary' 

DigitalLearningSolutions.Web/Controllers/MyAccountController.cs, DigitalLearningSolutions.Web/Views/MyAccount/_CentreSpecificDetailsCard.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1450
Description
'Delegate' role removed.
-----
I have:
=> TD-1450-Remove 'delegate' as role under 'My account' (as this applies to everyone), and rename section description to 'Admin roles'.

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/ReviewConfirmationRequests.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1449
A static header added to the page.
-----
I have:
=> TD-1449-Change wording of 'Proficiencies confirmation' button to 'Manage confirmation requests'

DigitalLearningSolutions.Data/DataServices/UserDataService/AdminUserDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Administrators/AdminAccountsController.cs
https://hee-tis.atlassian.net/browse/TD-1435
1) Fixed error in changing centre for admin.
[Administrators---Digital-Learning-Solutions.webm](https://github.com/TechnologyEnhancedLearning/DLSV2/assets/111436026/f359c856-6bbc-4ef6-888d-bcf698f395d8)
-----
I have:
=> TD-1435 Fixed error in changing centre for admin

DigitalLearningSolutions.Data/DataServices/SupervisorService.cs
https://hee-tis.atlassian.net/browse/TD-1553
TD-1553
-----
I have:
=> Resolving issue with signoff self assessment page

DigitalLearningSolutions.Web/Controllers/SuperAdmin/Administrators/AdminAccountsController.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1630
validation added for content manager role selection.
-----
I have:
=> TD-1630-Super Admin: Error message showing on 'Edit Administrator Roles'

DigitalLearningSolutions.Web/package.json, DigitalLearningSolutions.Web/yarn.lock
https://hee-tis.atlassian.net/browse/TD-1642
updated babel packages
<html>
<body>
Package | Current | Wanted | Upgraded to | Latest
-- | -- | -- | -- | --
@babel/core | 7.18.0 | 7.21.8 | 7.21.8 | 7.21.8
@babel/preset-env | 7.18.0 | 7.21.5 | 7.21.5 | 7.21.5
@babel/preset-typescript | 7.17.12 | 7.21.5 | 7.21.5 | 7.21.5
babel-jest | 28.1.0 | 28.1.3 | 28.1.3 | 29.5.0
babel-loader | 8.2.5 | 8.3.0 | 8.3.0 | 9.1.2
</body>
</html>
-----
I have:
=> TD-1642, updated babel packages

DigitalLearningSolutions.Web/Startup.cs
https://hee-tis.atlassian.net/browse/TD-1632
1) Fixed console errors related to hot jar/google analytics.
-----
I have:
=> TD-1632 Fixed console errors related to hot jar/google analytics

DigitalLearningSolutions.Web/Views/CookieConsent/CookiePolicy.cshtml
https://hee-tis.atlassian.net/browse/TD-1392
1) Fixed mobile view issue on cookie policy page.
-----
I have:
=> TD-1392 Fixed mobile view issue on cookie policy page

DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml
https://hee-tis.atlassian.net/browse/TD-1446
Correcting of GTM core 
Not required
-----
I have:
=> TD-1446 use of correct GTM code

DigitalLearningSolutions.Data/DataServices/SupervisorService.cs, DigitalLearningSolutions.Data/Models/Supervisor/SelfAssessmentSupervisorRole.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/ViewModels/Supervisor/EnrolDelegateSummaryViewModel.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/AddSupervisorSummary.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/EnrolDelegateSummary.cshtml
https://hee-tis.atlassian.net/browse/TD-1577
hide change link based on AllowSupervisorRoleSelection and change centre click navigate to wrong page issue resolved
Wrong page loads when click Change centre:
Change link for Roles will be displayed based on number of rules>1 and AllowSupervisorRoleSelection value.
-----
I have:
=> TD-1577: hide change link for Roles based on AllowSupervisorRoleSelection and change centre click navigate to wrong page issue resolved

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/DCSAReportDataService.cs
https://hee-tis.atlassian.net/browse/TD-1911
The existing query gave the same results throughout the page in the second tab of the DCSA report. The updated query fixes the issue.
Screenshots will be attached once testers test it with sufficient data to show that data is as what's expected.
-----
I have:
=> TD-1911 Corrected the query used for DCSA report to include missing joins as per the query given.

DigitalLearningSolutions.Web/Controllers/FrameworksController/Signposting.cs
https://hee-tis.atlassian.net/browse/TD-1601
Framework → Add Competency Group → Add Competency → Manage resource Signposting → Search for a resource → select → Results in 500 error.
Before code change:
After code change:
-----
I have:
=> TD-1601:  Add competency learning resource results in 500 error during Signpost

DigitalLearningSolutions.Web.Tests/Controllers/VerifyEmailControllerTests.cs, DigitalLearningSolutions.Web.Tests/Services/PasswordResetServiceTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ViewDelegateController.cs, DigitalLearningSolutions.Web/Controllers/VerifyEmailController.cs, DigitalLearningSolutions.Web/Services/PasswordResetService.cs
https://hee-tis.atlassian.net/browse/TD-1863
Points addressed - 
1. Removed generation of new hashes while sending registration emails
2. Removed functionality to check the validity of verification emails.
Points already in place that were required in this - 
1. Email content body had mention of expiry of such mails. This is already taken care in Jira Issue TD-1470
2. New hashes for verification won't be generated since when registration link is followed, the email is already verified now  according to Jira Issue TD-1865
Since it is a backend change, no screenshots are required.
-----
I have:
=> TD-1863 Removed functionality to create new hashes for sending welcome email and removed expiry of verification email.

DigitalLearningSolutions.Web/Controllers/UserFeedbackController.cs, DigitalLearningSolutions.Web/Styles/layout.scss, DigitalLearningSolutions.Web/Styles/userFeedback/userFeedback.scss, DigitalLearningSolutions.Web/Views/Shared/_UserFeedbackBarPartial.cshtml, DigitalLearningSolutions.Web/Views/UserFeedback/UserFeedbackComplete.cshtml
[TD-1116](https://hee-tis.atlassian.net/browse/TD-1116)
Changes to feedback bar following design review (updated feedback button to GDS tag, implemented GDS 'phase banner' html and css).
Fixed issue with back button/404 due to tempdata being purged plus caching issue.
-----
I have:
[TD-1116]: https://hee-tis.atlassian.net/browse/TD-1116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1116 User Feedback Bar rework

DigitalLearningSolutions.Data/DataServices/UserDataService/UserCentreDetailsDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/VerifyYourEmailControllerTests.cs, DigitalLearningSolutions.Web/Controllers/VerifyYourEmailController.cs, DigitalLearningSolutions.Web/Services/EmailVerificationService.cs, DigitalLearningSolutions.Web/Services/UserService.cs
https://hee-tis.atlassian.net/browse/TD-1863
Point addressed- 
1. Removed logic to generate new hashes every time 'resend verification emails' was clicked. This included hashes for primary email as well as associated centre emails.
Since it is a backend change, no screenshot is required.
-----
I have:
=> TD-1863 Updated code to remove generation of new hashes during external registration journey

DigitalLearningSolutions.Web/Styles/layout.scss, DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml, DigitalLearningSolutions.Web/Views/Shared/_UserFeedbackBarPartial.cshtml
[TD-1116](https://hee-tis.atlassian.net/browse/TD-1116)
Improved layout and cosmetic tweaks to feedback bar.
Implemented alternative feedback bar mechanism and text for guest v logged-in user.
-----
I have:
[TD-1116]: https://hee-tis.atlassian.net/browse/TD-1116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1116 Feedback bar design review rework

DigitalLearningSolutions.Data/DataServices/UserDataService/AdminUserDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Data/Extensions/ConfigurationExtensions.cs, DigitalLearningSolutions.Web/Services/AdminDownloadFileService.cs, DigitalLearningSolutions.Web/appSettings.UAT.json, DigitalLearningSolutions.Web/appsettings.Development.json, DigitalLearningSolutions.Web/appsettings.Production.json, DigitalLearningSolutions.Web/appsettings.SIT.json, DigitalLearningSolutions.Web/appsettings.Test.json, DigitalLearningSolutions.Web/appsettings.UarTest.json
https://hee-tis.atlassian.net/browse/TD-1914
Optimised export excel functionality in SuperAdmin>Administrator by using 1. Sql pagination with row limit 2. used with (nolock)
Exported excel sheet attached in ticket(https://hee-tis.atlassian.net/browse/TD-1914). The data populated before and after code change look same.
-----
I have:
=> TD:1914- Optimised export excel functionality in SuperAdmin>Administrator by using 1. Sql pagination with row limit 2. used with (nolock)

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/EnrolController.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-2061
TempData cleared on summary submit.
-----
I have:
=> TD-2061-fixed issue by clearing tempdata.

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/CourseSetup/CourseSetupControllerTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/DelegateCoursesControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/CourseSetup/CourseSetupController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateCoursesController.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/CourseSetupViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/DelegateCourses/DelegateCoursesViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Reports/Index.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/Index.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateCourses/Index.cshtml
https://hee-tis.atlassian.net/browse/TD-1874
For admins assigned to a specific category, Course Reports → Message should be modified to include the name of the category they are assigned to.
-----
I have:
=> TD-1874 updating course reports message

DigitalLearningSolutions.Data.Tests/DataServices/RegistrationDataServiceTests.cs, DigitalLearningSolutions.Data.Tests/Services/SupervisorServiceTest.cs, DigitalLearningSolutions.Data/DataServices/CommonService.cs, DigitalLearningSolutions.Data/DataServices/RegistrationDataService.cs, DigitalLearningSolutions.Data/DataServices/SupervisorService.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1920
Check added to find if user is exist and creating delegate account if account does not exist in the other centre where we are adding supervisor.
N/A
-----
I have:
=> TD-1920-Created delegate account for existing user while adding supervisor to another centre.

DigitalLearningSolutions.Data/DataServices/PlatformReportsDataService.cs, DigitalLearningSolutions.Data/Models/PlatformReports/PlatformUsageSummary.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/PlatformReports/PlatformReportsController.cs, DigitalLearningSolutions.Web/Models/Enums/SuperAdminReportsPage.cs, DigitalLearningSolutions.Web/Services/PlatformReportService.cs, DigitalLearningSolutions.Web/Startup.cs, DigitalLearningSolutions.Web/Styles/superAdmin/platformreports.scss, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/PlatformReports/PlatformReportsViewModel.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/PlatformReports/Index.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Shared/_NavMenuItems.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Shared/_PlatformReportsSideNavMenu.cshtml
[TD-935](https://hee-tis.atlassian.net/browse/TD-935)
Implements the reports landing page with basic platform usage stats and side nav to access other super admin report pages (not yet implemented).
Desktop:
Mobile:
-----
I have:
[TD-935]: https://hee-tis.atlassian.net/browse/TD-935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-935 Implements super admin reports navigation and platform usage page

DigitalLearningSolutions.Web/Views/SuperAdmin/AdminAccounts/Index.cshtml
https://hee-tis.atlassian.net/browse/TD-1914
Spinning wheel class removed . Now the page **_Super Admin> Administrators_**  retains after excel export.
Before code change:
After code change:
-----
I have:
=> TD-1914: Removed spinning wheel class since this is not using anywhere in DLS export area.

DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Data/Models/User/DelegateEntity.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Delegates/DelegatesController.cs, DigitalLearningSolutions.Web/Startup.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Delegates/DelegatesViewModel.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Delegates/SearchableDelegatesViewModel.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Delegates/Index.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Delegates/_SearchableDelegatesCard.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Shared/_UserAccountsSideNavMenu.cshtml
Super admin > Delegate account -basic page created with below functionalities
1. Basic page creation
2. Search filters
3. pagination
4. Link buttons(functionality expected to be in other tickets)
5. View link to User account
Filters:
Delegate card:
View link to User account page:
-----
I have:
=> TD-2000: Super admin Delegate account -basic page created

DigitalLearningSolutions.Data.Migrations/202307101239_AddAcceptableUsePolicyRecord.cs, DigitalLearningSolutions.Data/DataServices/ConfigDataService.cs, DigitalLearningSolutions.Web/Controllers/LearningSolutions/LearningSolutionsController.cs, DigitalLearningSolutions.Web/Models/PageReviewModel.cs, DigitalLearningSolutions.Web/Styles/home/Policies.scss, DigitalLearningSolutions.Web/ViewModels/LearningSolutions/AcceptableUsePolicyViewModel.cs, DigitalLearningSolutions.Web/Views/LearningSolutions/AcceptableUsePolicy.cshtml, DigitalLearningSolutions.Web/Views/Shared/_DlsFooter.cshtml, DigitalLearningSolutions.Web/Views/Shared/_PageReviewPartial.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1751
Feature 'Acceptable use policy' added.
-----
I have:
=> TD-1751-Acceptable use policy, link added.

DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Web/Models/Enums/DelegateAccountCard.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Delegates/SearchableDelegatesViewModel.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Delegates/_DelegateStatusTag.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Delegates/_SearchableDelegatesCard.cshtml
1. Included missed Remove link for Centre email
2. Query change made for account status & LH link status
-----
I have:
=> TD-2000: Super Admin - Delegates - Set up basic page- included missed links

DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Delegates/_SearchableDelegatesCard.cshtml
https://hee-tis.atlassian.net/browse/TD-2157
1. Status tag implemented. 
2. Included ONLY the required columns in select query for delegates.
-----
I have:
=> TD-2157: Status tag implemented. And included the required columns in select query for delegates.

DigitalLearningSolutions.Web/Controllers/SuperAdmin/Delegates/DelegatesController.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Delegates/_SearchableDelegatesCard.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-2006
Action method added to approve delegate.
N/A
-----
I have:
=> TD-2006- Action added to approve delegate

DigitalLearningSolutions.Data.Tests/DataServices/CentresDataServiceTests.cs, DigitalLearningSolutions.Data/DataServices/CentresDataService.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs, DigitalLearningSolutions.Web/Services/CentresService.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/_CentreCard.cshtml
https://hee-tis.atlassian.net/browse/TD-953
1) Added feature for deactivate and reactivate centre by modifying the controller,service,dataservice,views and dataservice test.
-----
I have:
=> TD-953 Added feature for deactivate and reactivate centre

DigitalLearningSolutions.Data/DataServices/CentresDataService.cs, DigitalLearningSolutions.Data/Models/Centres/Centre.cs, DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/CentresControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Centres/EditCentreDetailsSuperAdminViewModel.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/EditCentreDetails.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/ManageCentre.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-986
Feature 'edit centre details' added.
-----
I have:
=> TD-986- feature 'edit centre details' added to Super Admin -> Centres.

DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Data/Exceptions/DeleteUserException.cs, DigitalLearningSolutions.Web/Controllers/Register/RegisterController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ViewDelegateController.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ViewDelegate/Index.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-2177
Validation added to restrict registration if email present in UserCentreDetails at that centre.
Replaced 'Deactivate' button with 'Delete account' to delete user and associate accounts.
-----
I have:
=> TD-2177- validation added to restrict registration if email present in UserCentreDetails at that centre

DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/ManageCentre.cshtml
https://hee-tis.atlassian.net/browse/TD-948
Addressed wording issue on the manage centre page as per comment on the ticket.
-----
I have:
=> TD-948 Addresses wording issues

DigitalLearningSolutions.Web/Views/SuperAdmin/Delegates/_SearchableDelegatesCard.cshtml
Super admin > Delegates -"Account claimed" row has been removed from details.
**_After code change:_**
-----
I have:
=> TD-2000: Super admin > Delegates -"Account claimed" row has been removed from details.

DigitalLearningSolutions.Web/Views/Supervisor/MyStaffList.cshtml
https://hee-tis.atlassian.net/browse/TD-1760
Issue when loading staff list page after adding my self to self assessment resolved.
After refresh
**_After code change:_**
-----
I have:
=> TD-1760: Issue in loading staff list page resolved

DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/EditCentreDetails.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-986
Check box label issue ‘Show on find your centre’ has been fixed.
Mobile view (long error text) issue  is going be covered in https://hee-tis.atlassian.net/browse/TD-2282
-----
I have:
=> TD-986-Super Admin - Edit Centre Details-check box label case changed.

DigitalLearningSolutions.Web/Controllers/SuperAdmin/Users/UsersController.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Users/UserCentreAccounts.cshtml
https://hee-tis.atlassian.net/browse/TD-2284
Linked User centre delegate link to Super Admin - delegate account
After clicking above, we are redirected to the below page - 
-----
I have:
=> TD-2284 Linked User centre delegate link to Super Admin - delegate account

DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/ManageCentreManager.cshtml
https://hee-tis.atlassian.net/browse/TD-987
Included "details to page title. Now it is "**_Edit centre manager details_**"
Removed **_optional_** from first name, last name and email fields.
**_After code change_**
-----
I have:
=> TD-987: Included "details to page title. Removed optional from first name, last name and email fields.

DigitalLearningSolutions.Data/DataServices/SupervisorService.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-2100
Supervisor search modified to check existing supervisor.
-----
I have:
=> TD-2100- Duplicated 'Not Registered' users on 'My Staff' - supervisor search modified.

DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs
[TD-987](https://hee-tis.atlassian.net/jira/software/c/projects/TD/boards/165?modal=detail&selectedIssue=TD-987)
Fixed merge issue (CentresController.ManageCentreManager routes were mistakenly merged out).
-----
I have:
[TD-987]: https://hee-tis.atlassian.net/browse/TD-987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-987_Fixed Manage Centre Manager merge issue.

DigitalLearningSolutions.Data.Tests/DataServices/CentresDataServiceTests.cs, DigitalLearningSolutions.Data/DataServices/CentresDataService.cs, DigitalLearningSolutions.Data/Models/Centres/Centre.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Centres/AddCentreSuperAdminViewModel.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/AddCentre.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/Index.cshtml
https://hee-tis.atlassian.net/browse/TD-985
Added a new form to add a new centre
-----
I have:
=> TD-985 Added functionality of adding a new centre in Super Admin

DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs
https://hee-tis.atlassian.net/browse/TD-985
Corrected the issue with dropdown losing the values on validation error.
-----
I have:
=> TD-985 Corrected the issue with dropdown losing the values on validation error.

DigitalLearningSolutions.Data.Tests/TestHelpers/CentreContractAdminUsageTestHelper.cs, DigitalLearningSolutions.Data/DataServices/CentresDataService.cs, DigitalLearningSolutions.Data/DataServices/ContractTypesDataService.cs, DigitalLearningSolutions.Data/Models/Centres/ContractInfo.cs, DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/CentresControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs, DigitalLearningSolutions.Web/Helpers/SelectListHelper.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Centres/ContractTypeViewModel.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/EditContractInfo.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/ManageCentre.cshtml
Edit centre contract info page and removing default files from the branches
-----
I have:
=> TD-988 Edit contract review date removing default file

DigitalLearningSolutions.Web/Controllers/SuperAdmin/PlatformReports/PlatformReportsController.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/PlatformReports/SelfAssessmentsEditFiltersViewModel.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/PlatformReports/Index.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/PlatformReports/SelfAssessmentsEditFilters.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/PlatformReports/SelfAssessmentsReport.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Reports/EditFilters.cshtml
[TD-2115](https://hee-tis.atlassian.net/browse/TD-2115)
Makes the following fixes:
- Implements mobile navigation (equivalent to side nav in desktop)
- Removes reference to moved CSS file from edit filters pages (because it is unnecessary)
- Fixes validation of start and end date in edit filters screen
- Tweaks wording of self assessment filter dropdown label
Mobile nav:
Console errors gone:
Fixed capitalisation of label:
Fixed validation:
-----
I have:
[TD-2115]: https://hee-tis.atlassian.net/browse/TD-2115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-2115 Address test fails for super admin self assessment reports

DigitalLearningSolutions.Data.Migrations/2023080911401334_updateTermsAndConditions.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.Designer.cs, DigitalLearningSolutions.Data.Migrations/Resources/TermsAndConditions.txt
https://hee-tis.atlassian.net/browse/TD-1334
fixing issue regarding to tester comment
-----
I have:
=> TD-1334 fixing issue regarding to tester comment

DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Configuration/EditCentreManagerDetailsViewModel.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/ManageCentreManager.cshtml
https://hee-tis.atlassian.net/browse/TD-2366
1) Removed required field validation from first three fields on 'Edit centre manager details' page and marked them as optional by modifying the viewmodel and view.
-----
I have:
=> TD-2366 Removed required field validation from first three fields on 'Edit centre manager details' page and marked them as optional

DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/CentresControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs
1. Issue when Date field is filled 0 has been resolved
2. Dropdown value issue resolved
3. Not accepting current date issue resolved
Issue: Dropdown not retaining value after date filed validation
new values selection retained after validation
**_Issue when Date field is filled 0 has been resolved_**
**_Not accepting current date issue resolved_**
-----
I have:
=> TD-988: Issue when Date field is filled 0 has been resolved

DigitalLearningSolutions.Web.Tests/Controllers/ForgotPassword/ForgotPasswordControllerTests.cs, DigitalLearningSolutions.Web/Controllers/ForgotPasswordController.cs, DigitalLearningSolutions.Web/Views/ForgotPassword/Confirm.cshtml
https://hee-tis.atlassian.net/browse/TD-2247
Mitigating against information disclosure
-----
I have:
=> TD-2247 Resolving Information disclosure

DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs, DigitalLearningSolutions.Web/Helpers/CommonValidationErrorMessages.cs
[_TD-2408_](https://hee-tis.atlassian.net/browse/TD-2408)
Added a condition to check existing centre name
-----
I have:
=> TD-2408 Added a condition to check existing centre name

DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs
Date field issues when entering 0's has been addressed
Scenarios covered:
1. Current date
2.  Only Month & year field
3. Only year field
4. Day,Month,Year fields NULL
5. 0 in Day field
6. 0 in Day & Month fields
7. 0 in Day, Month and Year filed
8. Invalid day,moth and year
-----
I have:
=> TD-988: Date field errors handled

DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/CentresControllerTests.cs
Unit test failure has been fixed. Also missing code has been re-introduced.
-----
I have:
=> TD-988: Unit test failure fix

DigitalLearningSolutions.Web/Views/Supervisor/Shared/_SupervisorSignOffSummary.cshtml
[TD-2027](https://hee-tis.atlassian.net/browse/TD-2027)
Updated resend supervisor signoff email link.
-----
I have:
[TD-2027]: https://hee-tis.atlassian.net/browse/TD-2027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TD-2027]: https://hee-tis.atlassian.net/browse/TD-2027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-2027 Supervisor sign off email resend caption

DigitalLearningSolutions.Data.Tests/DataServices/CentresDataServiceTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/CentresControllerTests.cs
[TD-2409](https://hee-tis.atlassian.net/browse/TD-2409)
Added a web test for add centre in super admin. Also, removed the associated data test.
-----
I have:
[TD-2409]: https://hee-tis.atlassian.net/browse/TD-2409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-2409 Added a web test and removed the data test

DigitalLearningSolutions.Web/Services/AdminDownloadFileService.cs
https://hee-tis.atlassian.net/browse/TD-2505
Removed use of async void since it is creating memory issue
Attached export report in Jira
-----
I have:
=> TD-2505: Removed use of async avoid in AdminDownloadFileService.cs

DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/CourseContent/Index.cshtml
https://hee-tis.atlassian.net/browse/TD-2004
Alters the Razor conditional code to ensure all content is displayed when editing content in Course Setup
-----
I have:
=> TD-2004 section not Showing in  the courseSetup

.github/workflows/continuous-integration-workflow.yml, DigitalLearningSolutions.Web/package.json
https://hee-tis.atlassian.net/browse/TD-2500
-----
I have:
=> TD-2500 update ci to use windows latest

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/CourseDelegatesControllerTests.cs, DigitalLearningSolutions.Web.Tests/Services/CourseDelegatesDownloadFileServiceTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/CourseDelegatesController.cs, DigitalLearningSolutions.Web/Services/CourseDelegatesDownloadFileService.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/CourseDelegates/Index.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-2186
Feature 'Refactor the Tracking System - Course delegates list export functionality to use paginated record retrieval' added.
-----
I have:
=> TD-2186 - feature 'Refactor the Tracking System - Course delegates list export functionality...' added

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/CourseSetup/CourseSetupControllerTests.cs, DigitalLearningSolutions.Web.Tests/Services/CourseServiceTests.cs, DigitalLearningSolutions.Web/Services/CourseService.cs
https://hee-tis.atlassian.net/browse/TD-2185
1) Added paginated record retrieval in export functionality of Delegates courses list by modifying the dataservice, service and test cases.
-----
I have:
=> TD-2185 Added paginated record retrieval in export functionality of Delegates courses list

DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Data/Models/SuperAdmin/SuperAdminDelegateAccount.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Delegates/DelegatesViewModel.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Delegates/SearchableDelegatesViewModel.cs
https://hee-tis.atlassian.net/browse/TD-2523
Super admin > Delegate page took long time to load and getting timed out after some time.
After code changes Delegate account main page and detail page returns same result.
-----
I have:
=> TD- 2523 super admin delegate page doesn't load and results in time out error

DigitalLearningSolutions.Web.Tests/Controllers/SupervisorController/SupervisorControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs
https://hee-tis.atlassian.net/browse/TD-1877
1) Fixed error in exporting a summary of a learner's progress to Excel by modifying the controller.
-----
I have:
=> TD-1877 Fixed error in exporting a summary of a learner's progress to Excel

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/BulkUploadController.cs
https://hee-tis.atlassian.net/browse/TD-2492
After validation message, (max 200rows) changed to (max 0 rows) as below.
**_After code change_**
-----
I have:
=> TD-2492: Model value set for MaxBulkUploadRows.

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Web.Tests/ViewModels/TrackingSystem/CourseSetup/CourseStatisticsViewModelFilterOptionsTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/CourseSetup/CourseSetupController.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/CourseStatisticsViewModelFilterOptions.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-2182
Search string trimmed, filter name modified, search SQL 'order by' modified.
-----
I have:
=> TD-2182-Course Setup list to use SQL filtering-Issue fix

DigitalLearningSolutions.Data.Migrations/202310021046_DeleteGroupDelegatesDuplicateRecord.cs, DigitalLearningSolutions.Data/DataServices/GroupsDataService.cs
https://hee-tis.atlassian.net/browse/TD-755
1. Insert duplicate record to "GroupDelegates" table has been fixed. 
2.  Issue when clicking "Remove from group" has been fixed
3. Created migration script to delete  already existing duplicate record from "GroupDelegates" table
**Before code change:**
Steps: 
Changed the job group of a Delegate to another job group (Admin/Clerical to Care Worker)
resulted duplicate entry in Delegate groups page.
**After code change:**
-----
I have:
=> TD-755: 1. Insert duplicate record to GroupDelegates table has been fixed. 2.  Issue when clicking "Remove from group" has been fixed

DigitalLearningSolutions.Data/Helpers/GenericSortingHelper.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/DelegateCourses/DelegateCoursesViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateCourses/Index.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegatesSideNavMenu.cshtml, DigitalLearningSolutions.Web/appsettings.Development.json, DigitalLearningSolutions.Web/appsettings.json
https://hee-tis.atlassian.net/browse/TD-1567
1. Changed the text in side nav link,h1 title and sort by option by modifying the helper, viewmodel and view.
-----
I have:
=> TD-1567 Relabel the delegate courses page and nav links to delegate activities

DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Configuration/EditCentreManagerDetailsViewModel.cs
https://hee-tis.atlassian.net/browse/TD-2879
Removing the required field validation as this is an optional field.
-----
I have:
=> TD-2879 Removed Required Field From First And Last Name

DigitalLearningSolutions.Data/ApiClients/LearningHubReportApiClient.cs, DigitalLearningSolutions.Data/DataServices/ProgressDataService.cs, DigitalLearningSolutions.Data/Models/Courses/DelegateCourseProgressInfo.cs, DigitalLearningSolutions.Data/Models/Progress/SectionProgress.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/DelegateProgressControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateProgressController.cs, DigitalLearningSolutions.Web/Services/CertificateService.cs, DigitalLearningSolutions.Web/Services/PdfService.cs, DigitalLearningSolutions.Web/Services/ProgressService.cs, DigitalLearningSolutions.Web/Startup.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/DelegateProgress/PreviewProgressViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateProgress/DownloadProgress.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateProgress/Index.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateProgress/ViewDelegateProgress.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-2481
Feature course progress view in refactored tracking system implemented.
-----
I have:
=> TD-2481 - Implement course progress view in refactored tracking system

DigitalLearningSolutions.Data/DataServices/CentresDataService.cs, DigitalLearningSolutions.Data/Models/Centres/CentresExport.cs, DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/CentresControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs, DigitalLearningSolutions.Web/Services/CentresDownloadFileService.cs, DigitalLearningSolutions.Web/Startup.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/Index.cshtml
https://hee-tis.atlassian.net/browse/TD-2892
1) Created Export list to Excel feature for centres in Super Admin by modifying the dataservice,model,controller,view and test.
-----
I have:
=> TD-2892 Created Export list to Excel feature for centres in Super Admin

DigitalLearningSolutions.Web.Tests/Controllers/SupervisorController/SupervisorControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml
https://hee-tis.atlassian.net/browse/TD-1877
1) Fixed file name,mobile view and show hide criteria for sign off button by modifying view and controller.
-----
I have:
=> TD-1877 Fixed file name,mobile view and show hide criteria for sign off button

DigitalLearningSolutions.Web.Tests/ViewModels/TrackingSystem/CourseSetup/CourseStatisticsViewModelFilterOptionsTests.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/CourseStatisticsViewModelFilterOptions.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-2182
Filter header text updated
-----
I have:
=> TD-2182 - Course Setup list -filter header text issue fixed.

DigitalLearningSolutions.Web/yarn.lock
Reverts TechnologyEnhancedLearning/DLSV2#2271
=> Revert "Bump @babel/traverse from 7.17.12 to 7.23.2 in /DigitalLearningSolutions.Web"

DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/CentresControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Centres/EditCentreDetailsSuperAdminViewModel.cs
https://hee-tis.atlassian.net/browse/TD-2408
Addressed the following issues - 
1. Saving successfully if centre name is not changed by comparing against the centre name fetched from centre ID
2. Issue is spaces solved by trimming before comparing and before entering into database
3. Upper/lower case issue resolved since now comparing as case insensitive so no two centres will have same name just because their casing is different.
4. Added a 250 character limit for centre name.
-----
I have:
=> TD-2408 Adressing testing issues

DigitalLearningSolutions.Data/DataServices/GroupsDataService.cs, DigitalLearningSolutions.Data/Models/DelegateGroups/GroupDelegateAdmin.cs, DigitalLearningSolutions.Web.Tests/ViewModels/TrackingSystem/Delegates/DelegateGroups/DelegateGroupsViewModelFilterOptionsTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateGroupsController.cs, DigitalLearningSolutions.Web/Services/GroupsService.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/DelegateGroups/AllDelegateGroupsViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/DelegateGroups/DelegateGroupsViewModelFilterOptions.cs
[TD-2181](https://hee-tis.atlassian.net/browse/TD-2181)
Fixed issue where 'AddedByAdmin' filter was not showing the complete set of Admins after the Group data had a filter applied.
Also fixed related issues where zero results were causing 404 errors.
-----
I have:
[TD-2181]: https://hee-tis.atlassian.net/browse/TD-2181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-2181 Delegate groups list sql filtering pagination fixes updated

DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs
https://hee-tis.atlassian.net/browse/TD-3003
1) Show console '410' error when clicking back link from assigning the role view by modifying controller.
[My-Staff-List---Digital-Learning-Solutions.webm](https://github.com/TechnologyEnhancedLearning/DLSV2/assets/111436026/9ff16cf9-ea59-4e48-8a2c-dcda587b6b1f)
-----
I have:
=> TD-3003 Show console '410' error when clicking back link from assigning the role view

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/DelegateCoursesControllerTests.cs, DigitalLearningSolutions.Web.Tests/Services/CourseDelegatesDownloadFileServiceTests.cs, DigitalLearningSolutions.Web.Tests/Services/CourseServiceTests.cs, DigitalLearningSolutions.Web/Services/CourseDelegatesDownloadFileService.cs, DigitalLearningSolutions.Web/Services/CourseService.cs
https://hee-tis.atlassian.net/browse/TD-2185
1) Fixed sorting order of records in export to excel by modifying dataservice,service and tests.
This is backend change so no screenshot available
-----
I have:
=> TD-2185 Fixed sorting order of records in export to excel

DigitalLearningSolutions.Web/Views/Supervisor/DelegateProfileAssessments.cshtml
https://hee-tis.atlassian.net/browse/TD-2999
1) Changed button name from "enrol on assessment" to "enrol on self assessment" by modifying view.
-----
I have:
=> TD-2999 Changed button name from "enrol on assessment" to "enrol on self assessment"

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs
https://hee-tis.atlassian.net/browse/TD-2185
1) Fixed no records coming on excel in export to excel when search field is blank by modifying dataservice.
-----
I have:
=> TD-2185 Fixed no records coming on excel in export to excel when search field is blank

DigitalLearningSolutions.Data/DataServices/SupervisorService.cs
https://hee-tis.atlassian.net/browse/TD-2310
1) Fixed registered user added to my staff list not showing as the user added to the staff list on supervisor dashboard by modifying dataservice.
-----
I have:
=> TD-2310 Fixed registered user added to my staff list not showing as the user added to the staff list on supervisor dashboard

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs
https://hee-tis.atlassian.net/browse/TD-2968
I added a query to remove the signoff request made when the is change in the confirm self-assessment
-----
I have:
=> TD-2968 Remove signoff requests

DigitalLearningSolutions.Data.Migrations/202311060819_AspProgressAddLessonLocationColumn.cs, DigitalLearningSolutions.Data/DataServices/ProgressDataService.cs, DigitalLearningSolutions.Data/Enums/TrackerEndpointAction.cs, DigitalLearningSolutions.Data/Models/Tracker/TrackerEndpointQueryParams.cs, DigitalLearningSolutions.Web/Services/ProgressService.cs, DigitalLearningSolutions.Web/Services/StoreAspService.cs, DigitalLearningSolutions.Web/Services/TrackerActionService.cs, DigitalLearningSolutions.Web/Services/TrackerService.cs
Adds a new LessonLocation field to the aspProgress table and implements Tracker API endpoints to store data to it and retrieve data from it.
-----
I have:
=> TD-3009 Adds lesson location tracking endpoints to the tracker api

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateGroupsController.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateGroups/AddDelegateGroup.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateGroups/EditGroupName.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateGroups/Index.cshtml
https://hee-tis.atlassian.net/browse/TD-2958
Resolved test failures regarding whitespaces in Add and edit group
-----
I have:
=> TD-2958 Resolved test failures regarding whitespaces in Add and edit group

DigitalLearningSolutions.Web.Tests/ViewModels/TrackingSystem/Delegates/DelegateCourses/DelegateCoursesStatisticsViewModelFilterOptionsTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateCoursesController.cs, DigitalLearningSolutions.Web/Helpers/FilterOptions/DelegateActivityFilterOptions.cs, DigitalLearningSolutions.Web/Helpers/FilterableTagHelper.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/DelegateCourses/DelegateCourseStatisticsViewModelFilterOptions.cs
https://hee-tis.atlassian.net/browse/TD-1571
New filter activity type created and applied in the Delegate activities view.
-----
I have:
=> TD-1571- Delegate activity type filter added

DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegatesSideNavMenu.cshtml
[TD-1567](https://hee-tis.atlassian.net/browse/TD-1567)
Corrected spelling of activities heading
-----
I have:
[TD-1567]: https://hee-tis.atlassian.net/browse/TD-1567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1567 Correcting spelling of activities heading

DigitalLearningSolutions.Web/Services/StoreAspService.cs
Fixes mapping of the tutorialId and progressId from the endpoint parameters to the update method signature.
-----
I have:
=> TD-3009 Fix broken parameter-method signature mapping

DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Centres/AddCentreSuperAdminViewModel.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Centres/EditCentreDetailsSuperAdminViewModel.cs
[TD-3108](https://hee-tis.atlassian.net/browse/TD-3108)
Validations corrected for Add centre and edit centre in Super Admin Area
Add centre - 
Edit Centre - Allowing to put multiple comma-separated IP Addresses
-----
I have:
[TD-3108]: https://hee-tis.atlassian.net/browse/TD-3108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3108 correcting validation on IP Prefix

DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateCourseProgressDetails.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateSelfAssessmentDetails.cshtml
https://hee-tis.atlassian.net/browse/TD-1572
View label text modified.
-----
I have:
=> TD-1572 - Load delegate progress against self assessments - view label text modified.

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/CurrentSelfAssessment.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/ViewDelegateControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ViewDelegateController.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/ViewDelegate/ViewDelegateViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateCourseProgressButtons.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateCourseProgressDetailsWithStatusTags.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateSelfAssessmentProgressButtons.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateSelfAssessmentProgressDetails.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ViewDelegate/Index.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ViewDelegate/_DelegateSelfAssessmentInfoCard.cshtml
[TD-1565](https://hee-tis.atlassian.net/browse/TD-1565)
Introduced Self Assessments in Manage Delegate View by getting the current self assessments from the selfAssessmentService service and adding them to the existing model. In the view, running a loop to take out courses and self assessments separately and showing them.
List showing all current self assessments along with courses- 
Expanded course and self assessment cards - 
-----
I have:
[TD-1565]: https://hee-tis.atlassian.net/browse/TD-1565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1565 Introduced Self Assessments in Manage Delegate View

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs
[TD-1565](https://hee-tis.atlassian.net/browse/TD-1565)
Corrected table name in query.
-----
I have:
[TD-1565]: https://hee-tis.atlassian.net/browse/TD-1565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1565 corrected table name

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/CourseDelegatesControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ActivityDelegatesController.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/CourseDelegates/EditCompleteByDateFormData.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/CourseDelegates/EditCompleteByDateViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/Shared/DelegateSelfAssessmentInfoViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ActivityDelegates/EditCompleteByDate.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateSelfAssessmentDetails.cshtml
https://hee-tis.atlassian.net/browse/TD-3167
Complete by edit link activity implemented as shown below in screenshots.
-----
I have:
=> TD-3167- Edit link on activity delegates cards

DigitalLearningSolutions.Web/Controllers/Support/RequestSupportTicketController.cs, DigitalLearningSolutions.Web/Views/Support/RequestSupportTicket/Request.cshtml, DigitalLearningSolutions.Web/Views/Support/RequestSupportTicket/RequestAttachment.cshtml, DigitalLearningSolutions.Web/Views/Support/RequestSupportTicket/RequestSummary.cshtml, DigitalLearningSolutions.Web/Views/Support/RequestSupportTicket/SuccessPage.cshtml, DigitalLearningSolutions.Web/Views/Support/RequestSupportTicket/SupportTicketSummaryPage.cshtml, DigitalLearningSolutions.Web/Views/Support/RequestSupportTicket/TypeOfRequest.cshtml
- Fixes accessibility and styling issues identified during testing. 
- Implements a Jodit HTML editor for the problem description field. 
- Improves URLs and back navigation by returning a redirect to action instead of a view at the end of POST methods in the controller. 
- Improves use of standard NHS design system controls and patterns.
Tested and working in mobile too.
-----
I have:
=> TD-2286 Fix Freshdesk request support initial fails

DigitalLearningSolutions.Data.Migrations/202311291230_CreateSelfAssessmentRemindersSPs.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.Designer.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.resx, DigitalLearningSolutions.Data.Migrations/Scripts/TD-3190-SendOneMonthSelfAssessmentOverdueRemindersSP.sql, DigitalLearningSolutions.Data.Migrations/Scripts/TD-3190-SendOneMonthSelfAssessmentTBCRemindersSP.sql
[TD-3190](https://hee-tis.atlassian.net/browse/TD-3190)
Migration to add stored procedures for sending self assessment completion reminders for self assessments that have a complete by date set. There are two reminders, each handled in separate stored procedures. One for due dates that are approaching and a second for due dates that have passed. These will be called weekly from SQL Server Agent jobs.
-----
I have:
[TD-3190]: https://hee-tis.atlassian.net/browse/TD-3190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3190 Implement self assessment reminders

DigitalLearningSolutions.Web/Controllers/LearningSolutions/LearningSolutionsController.cs, DigitalLearningSolutions.Web/DigitalLearningSolutions.Web.csproj, DigitalLearningSolutions.Web/Middleware/DLSIPRateLimitMiddleware.cs, DigitalLearningSolutions.Web/Startup.cs, DigitalLearningSolutions.Web/Views/LearningSolutions/Error/TooManyRequests.cshtml, DigitalLearningSolutions.Web/appsettings.Development.json, DigitalLearningSolutions.Web/appsettings.json, DigitalLearningSolutions.Web/yarn.lock
[TD-2246](https://hee-tis.atlassian.net/browse/TD-2246)
[TD-2249](https://hee-tis.atlassian.net/browse/TD-2249)
Rate limiting middleware has been added to the DLS solution. The rate limiting has been configured to apply to ForgotPassword POSTs and Login POSTs only.
-----
I have:
[TD-2246]: https://hee-tis.atlassian.net/browse/TD-2246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TD-2249]: https://hee-tis.atlassian.net/browse/TD-2249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-2246, TD-2249 Added rate limiting for forgotten password and login POST requests

DigitalLearningSolutions.Data/DataServices/CourseContentService.cs, DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/IndexTests.cs, DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs, DigitalLearningSolutions.Web/yarn.lock
[TD-2243](https://hee-tis.atlassian.net/browse/TD-2243)
When a request is made to the LearningMenu a check is performed to attempt to determine if the request is a genuine navigation or an attempt to manipulate a unique id.
-----
I have:
[TD-2243]: https://hee-tis.atlassian.net/browse/TD-2243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-2243 unique id manipulation

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs, DigitalLearningSolutions.Data/DataServices/SupervisorService.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/SelfAssessmentSupervisor.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/ManageSupervisors.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/Shared/_DelegateProfileAssessmentGrid.cshtml
https://hee-tis.atlassian.net/browse/TD-3128
I added the SelfAssessmentSupervisorRoles.AllowDelegateNomination to the query so that the Remove button can show if the delegate have access role
I added the Stop supervisor link so that the supervisor can remove themselves  
-----
I have:
=> TD-3128 fix problems with user permissions for removing supervisors from self assessments

DigitalLearningSolutions.Web/Controllers/Support/RequestSupportTicketController.cs, DigitalLearningSolutions.Web/ViewModels/Support/RequestSupportTicket/RequestAttachmentViewModel.cs, DigitalLearningSolutions.Web/ViewModels/Support/RequestSupportTicket/RequestSummaryViewModel.cs, DigitalLearningSolutions.Web/ViewModels/Support/RequestSupportTicket/RequestTypeViewModel.cs, DigitalLearningSolutions.Web/Views/Support/RequestSupportTicket/RequestAttachment.cshtml, DigitalLearningSolutions.Web/Views/Support/RequestSupportTicket/RequestError.cshtml, DigitalLearningSolutions.Web/Views/Support/RequestSupportTicket/RequestSummary.cshtml, DigitalLearningSolutions.Web/Views/Support/RequestSupportTicket/SuccessPage.cshtml, DigitalLearningSolutions.Web/Views/Support/RequestSupportTicket/SupportTicketSummaryPage.cshtml, DigitalLearningSolutions.Web/Views/Support/RequestSupportTicket/TypeOfRequest.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/AddAdminField.cshtml
Addresses testing fails by:
- Removing character limit validation on the description field,
- Fixing validation handling on the attach screenshot screen
- Fixing routing to include DLS sub application throughout flow
-----
I have:
=> TD-2286 Addresses testing fails including routing and validation problems

DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs
[TD-2892](https://hee-tis.atlassian.net/browse/TD-2892)
Trimmed the search string.
-----
I have:
[TD-2892]: https://hee-tis.atlassian.net/browse/TD-2892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-2892 Resolved space issue while export

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs, DigitalLearningSolutions.Web/appsettings.Development.json
https://hee-tis.atlassian.net/browse/TD-2968
Fixed bug when candidate is changing self assessment status 
-----
I have:
=> TD-2968 Resolving bug observe during testing

DigitalLearningSolutions.Web/Services/PlatformUsageSummaryDownloadFileService.cs
https://hee-tis.atlassian.net/browse/TD-936
Fixing test failure 
-----
I have:
=> TD- 936 super admin reports overallusagedownload

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ActivityDelegates/RemoveDelegateSelfAssessment.cshtml
https://hee-tis.atlassian.net/browse/TD-1570
I increase the width of the column to accommodate long name as it was observed in the UAT
-----
I have:
=> TD-1570 correcting alignment issues

DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ActivityDelegates/Index.cshtml
https://hee-tis.atlassian.net/browse/TD-3268
Export button click - controller name updated.
-----
I have:
=> TD-3268-View course Delegates - Activity Delegates Export is resulting in 404 error

DigitalLearningSolutions.Web/Views/Support/RequestSupportTicket/RequestAttachment.cshtml, DigitalLearningSolutions.Web/Views/Support/RequestSupportTicket/SuccessPage.cshtml
Implements two changes requested after review with the support team:
- Indicates that there is a 20MB total file size limit on the attachments view (fix typo in hint too).
- Indicates that the user will receive an automated email response acknowledging receipt of the request.
-----
I have:
=> TD-2286 Fix issues identified during support review

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs
https://hee-tis.atlassian.net/browse/TD-2968
need to add verify is null to only get only pending signoff request
-----
I have:
=> TD-2968 fixing removing rejected sign off request

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Data/DataServices/ProgressDataService.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateProgress/_SectionProgress.cshtml
https://hee-tis.atlassian.net/browse/TD-2481
Total learning time calculated from tutorials. 
-----
I have:
=> TD-2481-Course progress UI issue fixed.

DigitalLearningSolutions.Data/DataServices/SupervisorService.cs
https://hee-tis.atlassian.net/browse/TD-2932
A self-assessment ID check is added when the learner removes the supervisor.
**Current situation:**
IV Therapy Passport
Adult Critical Care IV Therapy Passport
**When learner removes supervisor for  IV Therapy Passport**
IV Therapy Passport
Adult Critical Care IV Therapy Passport
**When supervisor removes staff**
IV Therapy Passport
Adult Critical Care IV Therapy Passport
-----
I have:
=> TD-2932-Removing supervisor from list does not withdraws the open confirmation request

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/CurrentSelfAssessment.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_OverviewActionButtons.cshtml
https://hee-tis.atlassian.net/browse/TD-3032
I added the name of the delegate from DelegateAccount table and following the standard format in renaming the export file
-----
I have:
=> TD-3032 Following right format in naming the export file

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/DCSAReportDataService.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/SelfAssessmentReports/SelfAssessmentReportsController.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentReportService.cs
https://hee-tis.atlassian.net/browse/TD-1988
In query, condition added for DCSA and removed centre Id condition.
-----
I have:
=> TD-1988- Show all centre learners progress on DCSA reports, regardless of which centre enrolled

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/CurrentSelfAssessment.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ActivityDelegatesController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ViewDelegateController.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateSelfAssessmentProgressDetails.cshtml
[TD-1565](https://hee-tis.atlassian.net/browse/TD-1565)
1. Shows hyphen when complete by date is not present
2. Implements the edit complete by date feature
Hyphen when complete by date is not present
Edit page - 
Changed date - 
-----
I have:
[TD-1565]: https://hee-tis.atlassian.net/browse/TD-1565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1565 Implemented Complete By Date Edit link

DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Centres/EditCentreDetailsSuperAdminViewModel.cs
[TD-3321](https://hee-tis.atlassian.net/browse/TD-3321)
Trimmed the IP Prefix For Add And Edit Centre
-----
I have:
[TD-3321]: https://hee-tis.atlassian.net/browse/TD-3321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3321 Trimmed the IP Prefix For Add And Edit Centre

DigitalLearningSolutions.Web/DigitalLearningSolutions.Web.csproj, DigitalLearningSolutions.Web/Scripts/trackingSystem/courseSetup.ts, DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/Index.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/_CentreCourseCard.cshtml
https://hee-tis.atlassian.net/browse/TD-3207
Typescript code added to copy course URL to clipboard.
When user clicks on 'Copy course link', course URL gets copied to clipboard and link text updates as 'Copy course link - Link copied!'.
-----
I have:
=> TD-3207- Typescript code added to copy course URL to clipboard.

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ActivityDelegatesController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/AllDelegatesController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateGroupsController.cs, DigitalLearningSolutions.Web/Helpers/FilterHelper.cs
https://hee-tis.atlassian.net/browse/TD-3611
Course delegates SQL query modified for prompts answers.
-----
I have:
=> TD-3611-Course delegates SQL query modified for prompts answers

DigitalLearningSolutions.Web/Helpers/FeatureFlags.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ViewDelegate/_DelegateSelfAssessmentInfoCard.cshtml, DigitalLearningSolutions.Web/appsettings.json
[TD-3622](https://hee-tis.atlassian.net/browse/TD-3622)
Feature flagging self assessment card buttons
When feature flag is OFF -
When feature flag is ON -
-----
I have:
[TD-3622]: https://hee-tis.atlassian.net/browse/TD-3622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3622 Feature flagging self assessment card buttons

DigitalLearningSolutions.Web/ViewModels/LearningPortal/RecommendedLearning/RecommendedLearningViewModel.cs, DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/AddSupervisorViewModel.cs, DigitalLearningSolutions.Web/ViewModels/Supervisor/MyStaffListViewModel.cs, DigitalLearningSolutions.Web/ViewModels/Support/Faqs/FaqsPageViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/AllDelegates/AllDelegatesViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/DelegateCourses/DelegateCoursesViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/DelegateGroups/DelegateGroupsViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/GroupCourses/AddCourseToGroupCoursesViewModel.cs, DigitalLearningSolutions.Web/Views/Shared/SearchablePage/_Search.cshtml
[TD-3621](https://hee-tis.atlassian.net/browse/TD-3621)
1. Using Model.SearchLabel as placeholder text in the _Search partial.
2. Changing the search text to 'Search' everywhere the partial is being used.
-----
I have:
[TD-3621]: https://hee-tis.atlassian.net/browse/TD-3621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3621 Changing text of placeholder text based on condition

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/Accessor.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/CompetencySelfAssessmentCertificate.cs, DigitalLearningSolutions.Web/Views/LearningPortal/Current/CompetencySelfAssessmentCertificate.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/Current/DownloadCompetencySelfAssessmentCertificate.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_OverviewActionButtons.cshtml
Changing of background colour to white and rewrite the self assessment query to remove duplication
I remove the comma from the accessor that did not have professional number
-----
I have:
=> TD-149 Background Color change and Resolving Duplication Selfassessment 

DigitalLearningSolutions.Web/ViewModels/FindYourCentre/RefactoredFindYourCentreViewModel.cs, DigitalLearningSolutions.Web/ViewModels/LearningPortal/Available/AvailablePageViewModel.cs, DigitalLearningSolutions.Web/ViewModels/LearningPortal/Completed/CompletedPageViewModel.cs, DigitalLearningSolutions.Web/ViewModels/LearningPortal/Current/CurrentPageViewModel.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Administrators/AdminAccountsViewModel.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Centres/CentresViewModel.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Delegates/DelegatesViewModel.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Users/UserAccountsViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Administrator/CentreAdministratorsViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/CourseSetupViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/CourseDelegates/SelectedCourseDetailsViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/CourseDelegates/SelectedDelegateDetailsViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/DelegateCourses/DelegateCoursesViewModel.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/AdminAccounts/Index.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/Index.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Delegates/Index.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Users/Index.cshtml
[TD-3621](https://hee-tis.atlassian.net/browse/TD-3621)
Correcting placeholder text for locations mentioned in test failures.
-----
I have:
[TD-3621]: https://hee-tis.atlassian.net/browse/TD-3621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3621 Addressing test fails for different locations mentioned

DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs
[TD-3637](https://hee-tis.atlassian.net/browse/TD-3637)
Call to GetAdminUserById was using the wrong parameters. Now sending the correct parameter i.e. AdminID.-
var loggedInAdminUser = userDataService.GetAdminUserById(adminId);
This variable is being used to populate the IsNominatedSupervisor property
When nominated supervisor role is present- 
When nominated supervisor role is NOT present- 
-----
I have:
[TD-3637]: https://hee-tis.atlassian.net/browse/TD-3637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3637 Using Correct AdminID For Getting Nominated Supervisor

DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/DelegateCourses/DelegateCoursesViewModel.cs
[TD-3621](https://hee-tis.atlassian.net/browse/TD-3621)
Correcting placeholder text
-----
I have:
[TD-3621]: https://hee-tis.atlassian.net/browse/TD-3621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3621 Correcting placeholder text

DigitalLearningSolutions.Data/DataServices/SupervisorService.cs
[TD-3644](https://hee-tis.atlassian.net/browse/TD-3644)
Correcting the where condition for IsSupervisorDelegateExistAndReturnId. The work done here is reverting the changes done in TD-2310.
-----
I have:
[TD-3644]: https://hee-tis.atlassian.net/browse/TD-3644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3644 Correcting the where condition for IsSupervisorDelegateExistAndReturnId

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CentreSelfAssessmentsDataService.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/SelfAssessmentForPublish.cs, DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests/SuperAdminAccessibilityTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/CentresControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs, DigitalLearningSolutions.Web/DigitalLearningSolutions.Web.csproj, DigitalLearningSolutions.Web/Services/CentreSelfAssessmentsService.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Centres/CentreCoursesViewModel.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Centres/SelfAssessmentAddViewModel.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/Courses.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/SelfAssessmentAdd.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/SelfAssessments.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/_CourseCard.cshtml, SQLScripts/UnitTestDBOnlyScripts/SetPublishStateOfSelfAssessments.sql
[TD-3220](https://hee-tis.atlassian.net/browse/TD-3220)
Implements a super admin interface for adding self assessments to a centre. Any self assessment that is Published is available for adding if it hasn't already been added to the centre.
-----
I have:
[TD-3220]: https://hee-tis.atlassian.net/browse/TD-3220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3220 Implements super admin interface to add centre self assessments

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs, DigitalLearningSolutions.Web/Styles/learningPortal/selfassessmentcertificate.scss, DigitalLearningSolutions.Web/Views/LearningPortal/Current/CompetencySelfAssessmentCertificate.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/Current/DownloadCompetencySelfAssessmentCertificate.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_OverviewActionButtons.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_SelfAssessmentCard.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml
Resolve duplication of self assessment 
alignment of the certificate 
-----
I have:
=> TD-149  Resolving duplication self assessment and other certificate issue

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/CompetencySelfAssessmentCertificate.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/Current.cs, DigitalLearningSolutions.Web/Styles/learningPortal/selfassessmentcertificate.scss, DigitalLearningSolutions.Web/Views/LearningPortal/Current/CompetencySelfAssessmentCertificate.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/Current/DownloadCompetencySelfAssessmentCertificate.cshtml
I needed to change the join of the Centre table from adminuser to candidateassessment table to fixed wrong centre name
I added delegateaccount table to fixed the wrong delegate response count 
-----
I have:
=> TD-149 Resolving wrong PRN, Educator name and Centre name issue

DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml
[TD-3677](https://hee-tis.atlassian.net/browse/TD-3677)
Changing Condition For Sign Off And Confirm Results
-----
I have:
[TD-3677]: https://hee-tis.atlassian.net/browse/TD-3677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3677 Changing Condition For Sign Off And Confirm Results

DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Centres/AddCentreSuperAdminViewModel.cs
[TD-3321](https://hee-tis.atlassian.net/browse/TD-3321)
1. Edit centre details - Trimming IP Prefix
2. Add Centre - Trimming added to ContactFirstName, ContactLastName, ContactEmail, ContactPhone
3. Add Centre - Validations added for Phone number and email.
-----
I have:
[TD-3321]: https://hee-tis.atlassian.net/browse/TD-3321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3321 Correcting test fails for trimming and validation

DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Styles/learningPortal/selfassessmentcertificate.scss, DigitalLearningSolutions.Web/ViewModels/Supervisor/ReviewSelfAssessmentViewModel.cs, DigitalLearningSolutions.Web/Views/LearningPortal/Current/CompetencySelfAssessmentCertificate.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/Current/DownloadCompetencySelfAssessmentCertificate.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml
I corrected the activity summary header 
I hide the certificate button when there is a confirm request
-----
I have:
=> TD-149 resolving duplication self assessment issuefix

DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/CentresControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/SelfAssessmentAdd.cshtml
[TD-3220](https://hee-tis.atlassian.net/browse/TD-3220)
Fixes routing of the form's post method to ensure that validation errors are displayed when adding a self assessment.
-----
I have:
[TD-3220]: https://hee-tis.atlassian.net/browse/TD-3220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3220 Fixes add self assessment validation

DigitalLearningSolutions.Data/DataServices/CentreApplicationsDataService.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs
[TD-3216](https://hee-tis.atlassian.net/browse/TD-3216)
- Fixes caching issues with forms
- Tweaks query to exclude inactive customisations
- Adds step to remove course code to inactivate associated customisations
-----
I have:
[TD-3216]: https://hee-tis.atlassian.net/browse/TD-3216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3216 Fixes to centre courses to address test fails

DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/CourseAddChooseFlow.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/_CourseCard.cshtml
[TD-3217](https://hee-tis.atlassian.net/browse/TD-3217)
Fixes:
- Typo in no customisations text
- Removes centre name from bullet list of add flow choices
-----
I have:
[TD-3217]: https://hee-tis.atlassian.net/browse/TD-3217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3217 Fix test fails for add course to centre

DigitalLearningSolutions.Web.Tests/ServiceFilter/VerifyDelegateCanAccessActionPlanResourceTests.cs, DigitalLearningSolutions.Web.Tests/Services/ActionPlanServiceTests.cs, DigitalLearningSolutions.Web/ServiceFilter/VerifyDelegateCanAccessActionPlanResource.cs, DigitalLearningSolutions.Web/Services/ActionPlanService.cs
https://hee-tis.atlassian.net/browse/TD-3738
Action plan access verification done by user Id instead of delegate Id.
-----
I have:
=> TD-3738 -Action plan access verification done by user Id instead of delegate Id.

DigitalLearningSolutions.Data/DataServices/CentreApplicationsDataService.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/CourseAdd.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/CourseAddChooseFlow.cshtml
[TD-3217](https://hee-tis.atlassian.net/browse/TD-3217)
Fixes the query returning other centre courses to prevent courses already published to centre from being returned. Fixes small typos noticed during testing.
-----
I have:
[TD-3217]: https://hee-tis.atlassian.net/browse/TD-3217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3217 Fix other courses query and typos for super admin add course flow

.github/workflows/build-and-deploy-dev.yml, .github/workflows/continuous-integration-workflow.yml
[TD-1279](https://hee-tis.atlassian.net/browse/TD-1279)
Adds a self hosted workflow action to build and deploy to a new dev environment (hosted at https://www.dls.nhs.uk/dls-dev/) when changes are pushed to the DEV branch. Also excludes pushes to the DEV branch from CI workflow.
-----
I have:
[TD-1279]: https://hee-tis.atlassian.net/browse/TD-1279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1279 Adds self-hosted action build and deploy workflow 

.github/workflows/build-and-deploy-uat.yml
[TD-1279](https://hee-tis.atlassian.net/browse/TD-1279)
Adds self-hosted Github action workflow for continuous deployment to UAT environment
-----
I have:
[TD-1279]: https://hee-tis.atlassian.net/browse/TD-1279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1279 CD workflow for UAT environment

.github/workflows/build-and-deploy-production.yml
[TD-1279](https://hee-tis.atlassian.net/browse/TD-1279)
Adds a deploy to production action self-hosted workflow runner. This is triggered manually from GitHub Actions and will deploy the Master code branch to DLS production.
-----
I have:
[TD-1279]: https://hee-tis.atlassian.net/browse/TD-1279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1279 Deploy to production action workflow (Manual trigger)

DigitalLearningSolutions.Web/Controllers/LearningPortalController/Current.cs
skipped supervisor details when learner checks for certificate.
NA
-----
I have:
=> TD-149- skipped supervisor details when learner checks for certificate.

DigitalLearningSolutions.Web/Views/LearningPortal/Current/CompetencySelfAssessmentCertificate.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/Current/DownloadCompetencySelfAssessmentCertificate.cshtml
centre name replaced with supervisor centre name.
NA
-----
I have:
=> TD-149-centre name replaced with supervisor centre name.

DigitalLearningSolutions.Web/Views/LearningPortal/Current/CompetencySelfAssessmentCertificate.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/Current/DownloadCompetencySelfAssessmentCertificate.cshtml
[TD-3877](https://hee-tis.atlassian.net/browse/TD-3877)
Hiding Optional Proficiencies Heading If No optional proficiencies Are Present
Certificate on DLS - 
Downloaded Certificate - 
-----
I have:
[TD-3877]: https://hee-tis.atlassian.net/browse/TD-3877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3877 Hiding Optional Proficiencies Heading If No optional proficiencies Are Present

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/CompetencySelfAssessmentCertificate.cs, DigitalLearningSolutions.Web/Views/LearningPortal/Current/CompetencySelfAssessmentCertificate.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/Current/DownloadCompetencySelfAssessmentCertificate.cshtml
[TD-3878](https://hee-tis.atlassian.net/browse/TD-3878)
Added a check to find whether a certificate is real or example certificate by including NonReportable column from CandidateAssessments table and using that condition to show the text.
Certificate on DLS-
Downloaded Certificate - 
-----
I have:
[TD-3878]: https://hee-tis.atlassian.net/browse/TD-3878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3878 Differentiating Real And Test Certificate

DigitalLearningSolutions.Web/Styles/layout.scss
[TD-1649](https://hee-tis.atlassian.net/browse/TD-1649)
Adding styles in the layout style sheet as suggested by @OluwatobiAwe 
Login screen-
Account - Edit details
-----
I have:
[TD-1649]: https://hee-tis.atlassian.net/browse/TD-1649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1649 Corrects spacing issue

DigitalLearningSolutions.Data.Migrations/202403221110_UpdateCandidateAssessmentsNonReportable.cs, DigitalLearningSolutions.Data/DataServices/SupervisorService.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs
https://hee-tis.atlassian.net/browse/TD-3932
NonReportable column updated on 'Supervise' link click in supervisor interface.
Migration script added to update existing data.
N/A
-----
I have:
=> TD-3932 - NonReportable column updated on 'Supervise' link click in supervisor interface

DigitalLearningSolutions.Web/Startup.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_Layout.cshtml, DigitalLearningSolutions.Web/Views/Shared/_GoogleTagManager.cshtml, DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml
https://hee-tis.atlassian.net/browse/TD-3880
GTM script code moved to partial view.
sha256 code added to avoid CSP error.
-----
I have:
=> TD-3880 - GTM script code moved to partial view.

DigitalLearningSolutions.Web/Models/Enums/UserCard.cs
N/A
Small tweak to fix the broken dev code on the Release .29 branch
-----
I have:
=> Makes the UserCard enum public to make it accessible to the partial view

DigitalLearningSolutions.Data/DataServices/GroupsDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/Register/RegisterDelegateByCentreControllerTests.cs, DigitalLearningSolutions.Web.Tests/Services/RegistrationServiceTests.cs, DigitalLearningSolutions.Web/Controllers/Register/RegisterDelegateByCentreController.cs, DigitalLearningSolutions.Web/Models/DelegateRegistrationByCentreData.cs, DigitalLearningSolutions.Web/Services/GroupsService.cs, DigitalLearningSolutions.Web/Services/JobGroupsService.cs, DigitalLearningSolutions.Web/Services/RegistrationService.cs, DigitalLearningSolutions.Web/ViewModels/Register/RegisterDelegateByCentre/ConfirmationViewModel.cs, DigitalLearningSolutions.Web/ViewModels/Register/RegisterDelegateByCentre/SummaryViewModel.cs, DigitalLearningSolutions.Web/Views/RegisterDelegateByCentre/AddToGroup.cshtml, DigitalLearningSolutions.Web/Views/RegisterDelegateByCentre/Confirmation.cshtml, DigitalLearningSolutions.Web/Views/RegisterDelegateByCentre/Summary.cshtml, DigitalLearningSolutions.Web/Views/RegisterDelegateByCentre/WelcomeEmail.cshtml
[TD-3834](https://hee-tis.atlassian.net/browse/TD-3834)
- Implements facility to add delegates to a group during centre delegate registration.
- Improves the registration summary page to split the information up and include details of the groups to which the delegate will be added.
- Adds suggested next steps list to the confirmation screen.
- Converts the centre delegate registration process to use the multipage form service (rather than temp data)
-----
I have:
[TD-3834]: https://hee-tis.atlassian.net/browse/TD-3834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3834 Delegate registration by centre admin grouping

DigitalLearningSolutions.Web/Startup.cs
[TD-2454](https://hee-tis.atlassian.net/browse/TD-2454)
Changed from using CurrentSystemBaseUrl to AppRootPath
-----
I have:
[TD-2454]: https://hee-tis.atlassian.net/browse/TD-2454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Changed from using CurrentSystemBaseUrl to AppRootPath

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/EnrolController.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/Enrol/EnrolDelegateSummaryViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Enrol/EnrolDelegateSummary.cshtml
[TD-3173](https://hee-tis.atlassian.net/browse/TD-3173)
Please see changes requested/comments from previous PR https://github.com/TechnologyEnhancedLearning/DLSV2/pull/2611
1. Getting only the roles where AllowSupervisorRoleSelection = 1
2. Using the role count to decide whether to give the option of role selection or not.
3. An option is also available to change the role on the summary page if the role count is more than one.
1. Choosing a supervisor when 1 role is available - 
2. Choosing supervisor if more than 1 role is available-
3. Summary page - 
4. Summary page if more than 1 role available-
-----
I have:
[TD-3173]: https://hee-tis.atlassian.net/browse/TD-3173?atlOrigin=eyJpIjoiNWRk …
=> TD-3173 Removed role selection from enrol on activity

DigitalLearningSolutions.Web/Services/LoginService.cs
[TD-2454](https://hee-tis.atlassian.net/browse/TD-2454)
Included the claims setup code in the LogIntoSingleCentre case
-----
I have:
[TD-2454]: https://hee-tis.atlassian.net/browse/TD-2454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Included the claims setup code in the LogIntoSingleCentre case

DigitalLearningSolutions.Web/Views/Shared/_GoogleTagManager.cshtml
https://hee-tis.atlassian.net/browse/TD-3880
gtag() script added.
-----
I have:
=> TD-3880- Google tag manager

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_Layout.cshtml, DigitalLearningSolutions.Web/Views/Shared/_GoogleTagManagerBodyTagJs.cshtml, DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml
[_DLSV2-3880_](https://hee-tis.atlassian.net/browse/TD-3880)
GTM head tag script placed just after head tag.
GTM body tag script added.
-----
I have:
=> TD-3880-GTM body JS added.

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/CourseSetup/CourseSetupControllerTests.cs, DigitalLearningSolutions.Web.Tests/Services/CourseTopicsServiceTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/CourseSetup/CourseSetupController.cs, DigitalLearningSolutions.Web/Services/CourseCategoriesService.cs, DigitalLearningSolutions.Web/Services/CourseTopicsService.cs, DigitalLearningSolutions.Web/Startup.cs
[_DLSV2-3928_](https://hee-tis.atlassian.net/browse/TD-3928)
Removed DataService ref from controller and added corresponding service class
-----
I have:
=> TD-3928-CourseSetupController - refactor

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/CourseSetup/CourseContentControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/CourseSetup/CourseContentController.cs
[_DLSV2-3927_](https://hee-tis.atlassian.net/browse/TD-3927)
DataService reference removed from the controller class.
-----
I have:
=> TD-3927 - CourseContentController - refactor

DigitalLearningSolutions.Web.Tests/Controllers/UserFeedbackControllerTest.cs, DigitalLearningSolutions.Web/Controllers/UserFeedbackController.cs, DigitalLearningSolutions.Web/Services/UserFeedbackService.cs, DigitalLearningSolutions.Web/Startup.cs
https://hee-tis.atlassian.net/browse/TD-3943
I added the UserFeedbackService to implement the service pattern in the UserFeedbackController
-----
I have:
=> TD-3943 user feedback controller refactor(controller service repository pattern)

DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/LearningPortalControllerTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningSolutions/LearningSolutionsControllerTests.cs, DigitalLearningSolutions.Web/Controllers/LearningSolutions/LearningSolutionsController.cs
[_DLSV2-3899_](https://hee-tis.atlassian.net/browse/TD-3899)
DataService reference removed from controller. 
Removed commented code from LearningPortlalControllerTests class.
**Banner text example which displays on error**
-----
I have:
=> TD-3899-LearningSolutionsController - refactor

DigitalLearningSolutions.Web.Tests/Controllers/Register/ClaimAccountControllerTests.cs, DigitalLearningSolutions.Web/Controllers/Register/ClaimAccountController.cs, DigitalLearningSolutions.Web/Services/UserService.cs
[_DLSV2-3902_](https://hee-tis.atlassian.net/browse/TD-3902)
DataService reference removed from controller and made changes accordingly to use service methods.
-----
I have:
=> TD-3902- ClaimAccountController - refactor

DigitalLearningSolutions.Data.Migrations/202405031044_AlterGetCurrentCoursesForCandidate_V2.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.Designer.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.resx, DigitalLearningSolutions.Data.Migrations/Resources/TD-3671-Alter_GetCurrentCoursesForCandidate_V2_proc_up.sql, DigitalLearningSolutions.Data.Migrations/Resources/TD_3671_Alter_CheckDelegateStatusForCustomisation_func_up.sql, DigitalLearningSolutions.Data/DataServices/ProgressDataService.cs, DigitalLearningSolutions.Web.Tests/Services/GroupServiceTests/GroupsServiceEnrolDelegateTests.cs, DigitalLearningSolutions.Web.Tests/Services/GroupServiceTests/GroupsServiceTests.cs, DigitalLearningSolutions.Web.Tests/Services/ProgressServiceTests.cs, DigitalLearningSolutions.Web/Services/EnrolService.cs, DigitalLearningSolutions.Web/Services/GroupsService.cs, DigitalLearningSolutions.Web/Services/ProgressService.cs
https://hee-tis.atlassian.net/browse/TD-3671
Make a tweak to the new business rule, to resolve the issue tester pointed out
-----
I have:
=> TD-3671 few courses which does not allow self enrolment

DigitalLearningSolutions.Web.Tests/Controllers/Login/LoginControllerTests.cs, DigitalLearningSolutions.Web/Controllers/LoginController.cs
[TD-3900](https://hee-tis.atlassian.net/browse/TD-3900)
-----
I have:
[TD-3900]: https://hee-tis.atlassian.net/browse/TD-3900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD 3900 Login controller refactor

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/PromoteToAdminControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/PromoteToAdminController.cs
[_TD-3940_](https://hee-tis.atlassian.net/browse/TD-3940)
DataService reference removed from the controller. Code modified to use service class methods.
-----
I have:
=> TD-3940 - PromoteToAdminController - refactor

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/DelegateCoursesControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateCoursesController.cs
[_TD-3936_](https://hee-tis.atlassian.net/browse/TD-3936)
-----
I have:
=> TD-3936-DelegateCoursesController - refactor

DigitalLearningSolutions.Web.Tests/Controllers/Register/RegisterControllerTests.cs, DigitalLearningSolutions.Web/Controllers/Register/RegisterController.cs, DigitalLearningSolutions.Web/Services/UserService.cs
[_TD-3905_](https://hee-tis.atlassian.net/browse/TD-3905)
GetUserIdFromUsername(+) added to service class.
-----
I have:
=> TD-3905-RegisterController - refactor

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/DelegateApprovalsControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateApprovalsController.cs
[_TD-3931_](https://hee-tis.atlassian.net/browse/TD-3931)
-----
I have:
=> TD-3931-DelegateApprovalsController - refactor

DigitalLearningSolutions.Web.Tests/Controllers/Register/RegisterDelegateByCentreControllerTests.cs, DigitalLearningSolutions.Web/Controllers/Register/RegisterDelegateByCentreController.cs
https://hee-tis.atlassian.net/browse/TD-3906
Removed the DataService reference from the controller and replace with web service.
-----
I have:
=> TD-3906 RegisterDelegateByCentreController - refactor (Controller-Service-Repository pattern)

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/CourseSetup/AdminFieldsControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/CourseSetup/AdminFieldsController.cs, DigitalLearningSolutions.Web/Services/CourseAdminFieldsService.cs
[_TD-3926_](https://hee-tis.atlassian.net/browse/TD-3926)
-----
I have:
=> TD-3926-AdminFieldsController - refactor 

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Dashboard/RankingController.cs
[_TD-3924_](https://hee-tis.atlassian.net/browse/TD-3924)
-----
I have:
=> TD-3924-RankingController - refactor

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Dashboard/ContractDetailsController.cs, DigitalLearningSolutions.Web/Services/CentresService.cs, DigitalLearningSolutions.Web/Services/CourseService.cs, DigitalLearningSolutions.Web/Services/UserService.cs
[_TD-3922_](https://hee-tis.atlassian.net/browse/TD-3922)
DataService reference removed from the controller. new method added to UserService, CentreService and CourseService
-----
I have:
=> TD-3922-ContractDetailsController - refactor

DigitalLearningSolutions.Data/DataServices/SupervisorService.cs, DigitalLearningSolutions.Web/Views/Frameworks/Developer/_Structure.cshtml
https://hee-tis.atlassian.net/browse/TD-4221
I added  join by Id to select the right confirm request 
-----
I have:
=> TD-4221 'Confirm results' link is not showing for few accounts on 'Supervisor Dashboard'

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Centre/Dashboard/DashboardControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Dashboard/DashboardController.cs
[TD-3923](https://hee-tis.atlassian.net/browse/TD-3923)
Removed data service reference from DashboardController and DashboardControllerTests
Dashboard-
Wave plugin screenshot -
-----
I have:
[TD-3923]: https://hee-tis.atlassian.net/browse/TD-3923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD 3923 DashboardController Refactor

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Centre/Configuration/CentreConfigurationControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Configuration/ConfigurationController.cs, DigitalLearningSolutions.Web/Services/CentresService.cs
[_TD-3920_](https://hee-tis.atlassian.net/browse/TD-3920)
DataService reference removed from the controller. Service methods UpdateCentreWebsiteDetails(+), UpdateCentreDetails(+) added to CentresService.
-----
I have:
=> TD-3920-ConfigurationController - refactor

DigitalLearningSolutions.Web/Views/Frameworks/Developer/_AllFrameworks.cshtml
[_TD-4224_](https://hee-tis.atlassian.net/browse/TD-4224)
The asp-action is updated with the correct controller name
-----
I have:
=> TD-4224-Sort button click on 'All Frameworks' page-404 error

DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/CentresControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs, DigitalLearningSolutions.Web/Services/CentresService.cs, DigitalLearningSolutions.Web/Services/ContractTypesService.cs, DigitalLearningSolutions.Web/Services/CourseService.cs, DigitalLearningSolutions.Web/Startup.cs
[_TD-3914_](https://hee-tis.atlassian.net/browse/TD-3914)
DataService reference removed from the controller. Following service classes added to CentreService
GetCentreTypes()
GetFullCentreDetailsById(+)
GetAllCentres(+)
UpdateCentreDetailsForSuperAdmin(+)
GetRoleLimitsForCentre(+)
UpdateCentreRoleLimits(+)
AddCentreForSuperAdmin(+)
GetContractInfo(+)
UpdateContractTypeandCenter(+)
-----
I have:
=> TD-3914-CentresController - refactor

DigitalLearningSolutions.Data/DataServices/SupervisorService.cs, DigitalLearningSolutions.Data/Models/SessionData/Tracking/Delegate/Enrol/SessionEnrolDelegate.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/EnrolController.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/Enrol/EnrolDelegateSummaryViewModel.cs
[_TD-4222_](https://hee-tis.atlassian.net/browse/TD-4222)
SupervisorEmail property added to hold supervisor email address.
Supervisor email address appended to drop down list, enrolment details view as shown in the screen shot below.
-----
I have:
=> TD-4222-Enrolled Supervisor has different email address

DigitalLearningSolutions.Web.Tests/Controllers/Register/RegisterInternalAdminControllerTests.cs, DigitalLearningSolutions.Web/Controllers/Register/RegisterInternalAdminController.cs, DigitalLearningSolutions.Web/Services/UserService.cs
[TD-3907](https://hee-tis.atlassian.net/browse/TD-3907)
1. Removed reference of data services from **RegisterInternalAdminController.cs** and **RegisterInternalAdminControllerTests.cs**
2. Added methods **GetDelegateAccountsByUserId** and **SetCentreEmail** in **UserService.cs**
If access is denied - 
If access is granted - 
-----
I have:
[TD-3907]: https://hee-tis.atlassian.net/browse/TD-3907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3907 RegisterInternalAdminController Refactor

DigitalLearningSolutions.Web.Tests/ServiceFilter/VerifyAdminUserCanAccessAdminUserTests.cs, DigitalLearningSolutions.Web.Tests/ServiceFilter/VerifyAdminUserCanAccessDelegateUserTests.cs, DigitalLearningSolutions.Web.Tests/Services/GroupServiceTests/GroupsServiceSynchroniseGroupsTests.cs, DigitalLearningSolutions.Web.Tests/Services/GroupServiceTests/GroupsServiceTests.cs, DigitalLearningSolutions.Web/Helpers/LinkedFieldHelper.cs, DigitalLearningSolutions.Web/ServiceFilter/VerifyAdminAndDelegateUserCentre.cs, DigitalLearningSolutions.Web/ServiceFilter/VerifyAdminUserCanAccessAdminUser.cs, DigitalLearningSolutions.Web/ServiceFilter/VerifyAdminUserCanAccessDelegateUser.cs, DigitalLearningSolutions.Web/Services/GroupsService.cs, DigitalLearningSolutions.Web/Services/UserService.cs, DigitalLearningSolutions.Web/ViewComponents/CentreContactInfoViewComponent.cs
https://hee-tis.atlassian.net/browse/TD-3946
I remove the DataService reference from the help service filter VerifyAdminAndDelegateUserCentre and replace with web service.
I remove the DataService reference from LinkedFieldHelper class and replace with web service.
I remove the DataService reference from the help service filter VerifyAdminUserCanAccessAdminUser and replace with web service.
I remove the DataService reference from the help service filter VerifyAdminUserCanAccessDelegateUser and replace with web service.
-----
I have:
=> TD-3946 helper/servicefilter/viewcomponent/viewmodel refactor (service repositorypattern)

DigitalLearningSolutions.Web/Controllers/Support/RequestSupportTicketController.cs, DigitalLearningSolutions.Web/Services/RequestSupportTicketService.cs, DigitalLearningSolutions.Web/Services/UserService.cs, DigitalLearningSolutions.Web/Startup.cs
https://hee-tis.atlassian.net/browse/TD-3918
I removed Dataservice reference from the RequestSupportTicketController and replace it with web service, I also added RequestSupportTicket service class and register it in the register service
-----
I have:
=> TD-3918 request support ticket controller refactor(controller service repository pattern)

DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/AdminAccountsControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Administrators/AdminAccountsController.cs, DigitalLearningSolutions.Web/Services/NotificationPreferencesService.cs, DigitalLearningSolutions.Web/Services/NotificationService.cs, DigitalLearningSolutions.Web/Services/UserService.cs
[_TD-3913_](https://hee-tis.atlassian.net/browse/TD-3913)
Service method added to
**_UserService:_**
GetAllAdmins(+)
UpdateAdminUserAndSpecialPermissions(+)
GetUserIdFromAdminId(+)
DeleteAdminAccount(+)
UpdateAdminStatus(+)
UpdateAdminCentre(+)
IsUserAlreadyAdminAtCentre(+)
**_NotificationPreferencesService_**
SetNotificationPreferencesForAdmin(+)
_**NotificationService**_
GetRoleBasedNotifications(+)
-----
I have:
=> TD-3913-AdminAccountsController - refactor

DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/UsersControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Users/UsersController.cs, DigitalLearningSolutions.Web/Services/UserService.cs
https://hee-tis.atlassian.net/browse/TD-3916
I remove dataservice reference in userscontroller and replace it with web service
-----
I have:
=> TD-3916 users controller refactor(controller service repository pattern)

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Data/Enums/EnrolmentMethod.cs
[_TD-4279_](https://hee-tis.atlassian.net/browse/TD-4279)
1. Enumeration created for enrolment method
2. Enrolment method id add to update statement.
Enrolled by admin
Self enrolled
-----
I have:
=> TD-4279- Re-enrolling a self assessment for the existing delegates not showing the 'remove' button

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Web.Tests/Services/CourseServiceTests.cs, DigitalLearningSolutions.Web/Services/CourseService.cs
[_TD-4277_](https://hee-tis.atlassian.net/browse/TD-4277)
TD-4277- Added restriction to add archived courses
Before resolution : Courses to add (along with archived courses)
After resolution : Courses to add (without archived courses)
-----
I have:
=> TD-4277- Added restriction to add archived courses

DigitalLearningSolutions.Web/Controllers/Register/ClaimAccountController.cs, DigitalLearningSolutions.Web/Views/ClaimAccount/Index.cshtml
[_TD-2364_](https://hee-tis.atlassian.net/browse/TD-2364)
Added VerifyLinkDlsAccount(+) action method without custom policy to verify DLS account before linking.
-----
I have:
=> TD-2364- Added action method without custom policy to verify dls account before linking.

DigitalLearningSolutions.Web/Views/UserFeedback/UserFeedbackComplete.cshtml
[TD-4136](https://hee-tis.atlassian.net/browse/TD-4136)
Removed Extra Text From Feedback Submit Page
-----
I have:
[TD-4136]: https://hee-tis.atlassian.net/browse/TD-4136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4136 Removed Extra Text From Feedback Submit Page

DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateSelfAssessmentProgressDetails.cshtml
[TD-4269](https://hee-tis.atlassian.net/browse/TD-4269)
Changing text to enrolled by supervisor
-----
I have:
[TD-4269]: https://hee-tis.atlassian.net/browse/TD-4269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4269 Changing text to enrolled by supervisor

DigitalLearningSolutions.Web/Views/UserFeedback/GuestFeedbackComplete.cshtml
[TD-4136](https://hee-tis.atlassian.net/browse/TD-4136)
Removing label for the guest users.
-----
I have:
[TD-4136]: https://hee-tis.atlassian.net/browse/TD-4136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD 4136 Removing label for guest user

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs
[_TD-4370_](https://hee-tis.atlassian.net/browse/TD-4370)
Email format validation added in SQL query.
This change will impact on 'In progress' and 'Completed' count as well as delegate list for courses in the export to excel file.
N/A
-----
I have:
=> TD-4370-Email format validation added in SQL query.

DigitalLearningSolutions.Data/Utilities/ClockUtility.cs
[TD-4467](https://hee-tis.atlassian.net/browse/TD-4467)
Reverting the changes made in ClockUtility
-----
I have:
[TD-4467]: https://hee-tis.atlassian.net/browse/TD-4467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4467 Reverting the changes made in ClockUtility

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/SelfAssessment.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/SelfAssessmentOverviewViewModel.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml
https://hee-tis.atlassian.net/browse/TD-4427
I resolve possible null reference return warning on GetCompetencySelfAssessmentCertificate and GetCompetencySelfAssessmentCertificate method
I added MinimumOptionalCompetencies field to GetSelfAssessmentForCandidateById query
I added MinimumOptionalCompetencies  property to SelfAssessment.cs
I added optionalCompetencies count to the SelfAssessmentOverviewViewModel.cs
I alter the logic for the visibility of the Request sign-off button to check that the self assessment includes at least the minimum number of optional 
I added a paragraph to the sign-off area text if the minimum number of optional competencies
-----
I have: …
=> TD-4427 Check the minimum optional competencies have been added before enabling Request Sign-off

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/CandidateAssessment.cs, DigitalLearningSolutions.Web.Tests/ServiceFilter/VerifyDelegateUserCanAccessSelfAssessmentTests.cs, DigitalLearningSolutions.Web.Tests/Services/SelfAssessmentServiceTests.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ActivityDelegatesController.cs, DigitalLearningSolutions.Web/ServiceFilter/IsCentreAuthorizedSelfAssessment.cs, DigitalLearningSolutions.Web/ServiceFilter/VerifyDelegateUserCanAccessSelfAssessment.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs, DigitalLearningSolutions.Web/Startup.cs
[_TD-4460_](https://hee-tis.atlassian.net/browse/TD-4460)
Created new action filter to check centre specific self assessment and applied to required methods in the SelfAssessment.cs 
Updated in the ticket.
-----
I have:
=> TD-4460- Action filter applied to verify centre specific self assessment

DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/FaqControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/SuperAdminFaqsController.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Shared/_SystemSideNavMenu.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/SuperAdminFaqs/SuperAdminFaqs.cshtml
[TD-4599](https://hee-tis.atlassian.net/browse/TD-4599)
Tweaks the navigation in Super Admin -> System to provide links to the remaining functionality delivered by the legacy app. This is part of the preparation for the removal of the legacy tracking system.
-----
I have:
[TD-4599]: https://hee-tis.atlassian.net/browse/TD-4599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4599 Provide links to legacy super admin

DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs
https://hee-tis.atlassian.net/browse/TD-4238
I change settempdata method from the method that takes candidateId, customisationId as a parameter to the one that takes candidateId, customisationId, progressId so that it can take the right record from the progress table
-----
I have:
=> TD-4238 Launching few courses from 'Current activities' or from 'Course set up' seeing back link as 'Completed activities'

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/BulkUploadController.cs
https://hee-tis.atlassian.net/browse/TD-4539
I am validating the tempdata in WelcomeEmail, UploadSummary, and StartProcessing action method to ensure the tempdata is empty. if empty I return 401 error
-----
I have:
=> TD-4539 Issue showing console '500' error on the screen when clicked browser back button after processing the Bulk Upload registration

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Dashboard/DashboardController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/SystemNotificationsController.cs
[_TD-4592_](https://hee-tis.atlassian.net/browse/TD-4592)
No caching attribute added to methods.
N/A
-----
I have:
=> TD-4592-NoCaching attribute added to methods

DigitalLearningSolutions.Data.Migrations/202408221440_UpdatePrivacyPolicyRecord.cs
[TD-4240](https://hee-tis.atlassian.net/browse/TD-4240)
Changed privacy data link with the help of migration, updating the Config table 'PrivacyPolicy' row's ConfigText
-----
I have:
[TD-4240]: https://hee-tis.atlassian.net/browse/TD-4240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4240 Changing privacy data link

DigitalLearningSolutions.Web/appSettings.UAT.json, DigitalLearningSolutions.Web/appsettings.Development.json, DigitalLearningSolutions.Web/appsettings.Production.json, DigitalLearningSolutions.Web/appsettings.SIT.json, DigitalLearningSolutions.Web/appsettings.Test.json, DigitalLearningSolutions.Web/appsettings.UarTest.json, DigitalLearningSolutions.Web/appsettings.json
[TD-4601](https://hee-tis.atlassian.net/browse/TD-4601)
AppSettings Changes For -
1. SSO - switched ON for all the environments
2. Freshdesk - changed 'GroupId' for UAT
-----
I have:
[TD-4601]: https://hee-tis.atlassian.net/browse/TD-4601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4601 AppSettings Changes For SSO and Freshdesk

DigitalLearningSolutions.Data.Migrations/202408271645_AlterAvailableandCompletedCoursesForDelegate.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.Designer.cs, DigitalLearningSolutions.Data.Migrations/Resources/TD-4243_Alter_GetActivitiesForDelegateEnrolment_proc_up.sql, DigitalLearningSolutions.Data.Migrations/Resources/TD-4243_Alter_GetCurrentCoursesForCandidate_V2_proc_up.sql
https://hee-tis.atlassian.net/browse/TD-4243
I modify GetActivitiesForDelegateEnrolment and GetCurrentCoursesForCandidate_V2 store procedure to remove course duplication in enrol activity, available and current activities
-----
I have:
=> Develop/fixes/td 4243 resolving duplicate of courses in enrol activity, available activities and current activities

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateProgressController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/EnrolController.cs
=> Rohit test branch2

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateProgressController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/EnrolController.cs
Reverts TechnologyEnhancedLearning/DLSV2#2816
=> Revert "Rohit test branch2"

DigitalLearningSolutions.Data/DataServices/SupervisorDataService.cs, DigitalLearningSolutions.Data/Models/Supervisor/DelegateSelfAssessment.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/ViewModels/Supervisor/SignOffProfileAssessmentViewModel.cs, DigitalLearningSolutions.Web/Views/Supervisor/SignOffProfileAssessment.cshtml
https://hee-tis.atlassian.net/browse/TD-4429
I resolved unboxing a possible null value warning in the AddSuperviseDelegate and InsertCandidateAssessmentSupervisor method
I added NumberOfSelfAssessedOptionalCompetencies count to the get and post SignOffProfileAssessment  action method in the Supervisor.cs
added MinimumOptionalCompetencies and DelegateUserID field to GetCandidateAssessmentSupervisor query
I added NumberOfSelfAssessedOptionalCompetencies  and OptionalCompetenciesChecked  property in the RequestSignOffViewModel.cs
I introduce a new checkbox, label, and validation in SignOffProfileAssessment.cshtml
-----
I have:
=> TD-4429 Additional optional competencies checkbox on the supervisor sign off screen

DigitalLearningSolutions.Web/Controllers/UserFeedbackController.cs, DigitalLearningSolutions.Web/Views/UserFeedback/UserFeedbackComplete.cshtml, DigitalLearningSolutions.Web/Views/UserFeedback/UserFeedbackTaskAchieved.cshtml, DigitalLearningSolutions.Web/Views/UserFeedback/UserFeedbackTaskAttempted.cshtml, DigitalLearningSolutions.Web/Views/UserFeedback/UserFeedbackTaskDifficulty.cshtml
[TD-4384](https://hee-tis.atlassian.net/browse/TD-4384)
Fixed the GoBack logic for the feedback questionnaire.
**WAVE Tool Screenshots**
-----
I have:
[TD-4384]: https://hee-tis.atlassian.net/browse/TD-4384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4384, changes to fix the issue with the Back Links on the User Feedback Component

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ActivityDelegatesController.cs
[_TD-4672_](https://hee-tis.atlassian.net/browse/TD-4672)
Dates converted to local date time
Variable name changed
-----
I have:
=> TD-4672-Acitivity Delegates - Dates converted to local date time

DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Administrator/AdminRoleInputs.cs
[TD-4709](https://hee-tis.atlassian.net/browse/TD-4709)
Changed The Text On Promote To Admin Screen
Tracking system
Super admin
-----
I have:
[TD-4709]: https://hee-tis.atlassian.net/browse/TD-4709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4709 Changed The Text On Promote To Admin Screen

DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml
https://hee-tis.atlassian.net/browse/TD-4322
I corrected the tag that is showing before the header and align the mobile view
-----
I have:
=> TD-4322 Fixing mobile view issue

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/CompetencySelfAssessmentCertificate.cshtml
https://hee-tis.atlassian.net/browse/TD-4702
I checked where the certificate is printing from to display the right download certificate button 
-----
I have:
=> TD-4702 Resolving download certificate error 403.

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_OverviewTable.cshtml
https://hee-tis.atlassian.net/browse/TD-4323
I added the optional tag to the _OverviewTable partial view 
Mobile view
-----
I have:
=> TD-4323 Introduce "Optional" tag in the learner Self Assessment view

DigitalLearningSolutions.Web/Views/UserFeedback/UserFeedbackTaskAttempted.cshtml, DigitalLearningSolutions.Web/Views/UserFeedback/UserFeedbackTaskDifficulty.cshtml
[TD-4364](https://hee-tis.atlassian.net/browse/TD-4364)
Adding back links in mobile view in feedback screens
-----
I have:
[TD-4364]: https://hee-tis.atlassian.net/browse/TD-4364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4364 Adding back links in mobile view in feedback screens

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DeactivateDelegateController.cs
https://hee-tis.atlassian.net/browse/TD-4383
I exclude the Active from the admin role
-----
I have:
=> TD-4383 Removing of Active from the Admin Role 

DigitalLearningSolutions.Data.Migrations/202409300912_AlterConstraintForCandidateAssessmentsAddUtcDate.cs
[_TD-4672_](https://hee-tis.atlassian.net/browse/TD-4672)
Migration script added to alter table constraint to add UTC date.
N/A
-----
I have:
=> TD-4672-Table constraint altered to add UTC date

DigitalLearningSolutions.Web/Extensions/EnumExtensions.cs, DigitalLearningSolutions.Web/Helpers/CompetencyFilterHelper.cs
[TD-4325](https://hee-tis.atlassian.net/browse/TD-4325)
Added filter for optional
-----
I have:
[TD-4325]: https://hee-tis.atlassian.net/browse/TD-4325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD 4325 Added filter for optional

DigitalLearningSolutions.Data/DataServices/SupervisorDataService.cs
[_TD4821-_](https://hee-tis.atlassian.net/browse/TD-4821)
Code which updates supervisor role, has been removed as updating supervisor role is not required.
N/A
-----
I have:
=> TD-4821-code which updates supervisor role, has been removed.

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs
[_TD-4785_](https://hee-tis.atlassian.net/browse/TD-4785)
Removed date updated to CandidateAssessmentSupervisors table.
N/A
-----
I have:
=> TD-4785- Removed date updated to CandidateAssessmentSupervisors table.

DigitalLearningSolutions.Web/Startup.cs
=> Xframe settings test

DigitalLearningSolutions.Web/Startup.cs
=> Reverting the X-Frame-Options change 

DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/SelfAssessmentTests.cs
[_TD-4791_](https://hee-tis.atlassian.net/browse/TD-4791)
Unit tests added for filter on optional competencies in the learner view. 
-----
I have:
=> TD-4791-Unit tests added for filter on optional competencies in the learner view.

.github/pull_request_template.md
[TD-4991](https://hee-tis.atlassian.net/browse/TD-4991)
Updates the pull request template in line with the changes agreed in the dev team review.
-----
I have:
[TD-4991]: https://hee-tis.atlassian.net/browse/TD-4991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4991 Updates the pull request template

DigitalLearningSolutions.Data.Migrations/DigitalLearningSolutions.Data.Migrations.csproj, DigitalLearningSolutions.Data/DigitalLearningSolutions.Data.csproj, DigitalLearningSolutions.Web.AutomatedUiTests/DigitalLearningSolutions.Web.AutomatedUiTests.csproj, DigitalLearningSolutions.Web.IntegrationTests/DigitalLearningSolutions.Web.IntegrationTests.csproj, DigitalLearningSolutions.Web.Tests/DigitalLearningSolutions.Web.Tests.csproj, DigitalLearningSolutions.Web/DigitalLearningSolutions.Web.csproj
[4771](https://hee-tis.atlassian.net/browse/TD-4771)
-----
I have:
=> TD-4771 Upgrading framework

DigitalLearningSolutions.Web.Tests/Controllers/SupervisorController/SupervisorControllerTests.cs
[TD-5020](https://hee-tis.atlassian.net/browse/TD-5020)
-----
I have:
[TD-5020]: https://hee-tis.atlassian.net/browse/TD-5020?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5020 Resolving build failure

.github/workflows/build-and-deploy-dev.yml
[TD-4773](https://hee-tis.atlassian.net/browse/TD-4773)
-----
I have:
[TD-4773]: https://hee-tis.atlassian.net/browse/TD-4773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4773 GitHub Actions Target To Dot Net 8

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentExportDataService.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/Export/CandidateAssessmentExportSummary.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Services/CandidateAssessmentDownloadFileService.cs
=> Release v1.0.0 to UAT

DigitalLearningSolutions.Data/DataServices/FrameworkDataService.cs
[_TD-4169_](https://hee-tis.atlassian.net/browse/TD-4169)
SQL query where condition modified to get current/non-deleted framework collaborator.
-----
I have:
=> TD-4169 - SQL query modified to get current/non-deleted framework collaborator.

DigitalLearningSolutions.Web/Controllers/TrackingSystem/CourseSetup/CourseSetupController.cs
https://hee-tis.atlassian.net/browse/TD-4340
I check if SectionContentData is not null and check the count is more or greater than 3 to ensure it is not a new request,
I return SectionContentData  for the multiPageFormService to prevent the user selecting the tutorials again
when I click the change from the summary page 
-----
I have:
=> TD-4340 Issue with the 'Course content' change link when creating a course from 'Course set up' screen

DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/ManageCentre.cshtml
[_TD-5019_](https://hee-tis.atlassian.net/browse/TD-5019)
Removed the hyperlink from the breadcrumb text 'Manage Centre'
-----
I have:
=> TD-5019- Removed the hyperlink from the breadcrumb text 'Manage Centre'

.github/workflows/build-and-deploy-production.yml, .github/workflows/build-and-deploy-uat.yml, .github/workflows/continuous-integration-workflow.yml
Merging release 1.0.0 to master with .Net 8 workflows
=> Merging release 1.0.0 to master with .Net 8 workflows

DigitalLearningSolutions.Data/DataServices/RegistrationDataService.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs
https://hee-tis.atlassian.net/browse/TD-4889
To resolve the internal server error bug, I check the value of the categoryid, when it is zero I change the categoryid  to NULL instead of inserting zero that is causing the error
-----
I have:
=> TD-4889 Resolving internal server error when nominating delegate to supervisor 

DigitalLearningSolutions.Web/Controllers/Register/ClaimAccountController.cs
[_TD-4372_](https://hee-tis.atlassian.net/browse/TD-4372)
Changed order of checking existing accounts.
Admin account checked for specific centre.
Code optimized to avoid unnecessary DB call.
N/A
-----
I have:
=> TD-4372- Issue with the msg showing on Link delegate record screen when claiming the account

DigitalLearningSolutions.Data/DataServices/UserDataService/AdminUserDataService.cs
https://hee-tis.atlassian.net/browse/TD-4889
I modified the query that is updating Adminaccount Table when nominating to supervisor, 
I check the categoryId when it is zero, I replace it with NULL 
-----
I have:
=> TD-4889 When a supervisor promotes a learner to the Nominated supervisor role, assign them to the same category as the supervisor

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs
https://hee-tis.atlassian.net/browse/TD-5131
I added to the where clause of the GetSignOffSupervisorsForSelfAssessmentId method so the query will remove delegate that did not have supervisor or nominated supervisor role
-----
I have:
Either:
Or:
=> TD-5131 self assessment manage supervisorstilldisplaysthe supervisoreventhoughsupervisorroleisremovedfromthe administrator

DigitalLearningSolutions.Web/Controllers/FrameworksController/Frameworks.cs, DigitalLearningSolutions.Web/Styles/frameworks/frameworksShared.scss, DigitalLearningSolutions.Web/Styles/layout.scss, DigitalLearningSolutions.Web/Views/Frameworks/Developer/FrameworkPrintLayout.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/_Structure.cshtml, DigitalLearningSolutions.Web/Views/Shared/_CookieConsentPartial.cshtml, DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml, DigitalLearningSolutions.Web/Views/Shared/_UserFeedbackBarPartial.cshtml
_Describe what has changed and how that will affect the app. If relevant, add links to any sources/documentation you used. Highlight anything unusual and give people context around particular decisions._
-----
I have:
Either:
Or:
=> TD-5263 Frameworks View for print feature

DigitalLearningSolutions.Web/Views/SuperAdmin/Users/UserCentreAccounts.cshtml
[TD-5242](https://hee-tis.atlassian.net/browse/TD-5242)
Added 'Inactive' label when admin is inactive.
-----
I have:
Either:
Or:
[TD-5242]: https://hee-tis.atlassian.net/browse/TD-5242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5242-Issue showing 'Admin' link as active on 'Super admin' section when re-registered the delegate account

DigitalLearningSolutions.Data/DataServices/FrameworkDataService.cs, DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml
[TD-5334](https://hee-tis.atlassian.net/browse/TD-5334)
Releases breadcrumb fix to dev.
[TD-5334]: https://hee-tis.atlassian.net/browse/TD-5334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Dls release v1.2.0 to DEV

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/SelfAssessmentReports/SelfAssessmentReportsController.cs
[TD-5306](https://hee-tis.atlassian.net/browse/TD-5306)
self-assessments report file name format changed.
Downloaded files screen shot
-----
I have:
Either:
Or:
[TD-5306]: https://hee-tis.atlassian.net/browse/TD-5306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5306-self-assessments excel report file name format changed.

DigitalLearningSolutions.Data/DataServices/CompetencyAssessmentDataService.cs, DigitalLearningSolutions.Web/Controllers/CompetencyAssessmentsController/CompetencyAssessments.cs, DigitalLearningSolutions.Web/Services/CompetencyAssessmentService.cs, DigitalLearningSolutions.Web/ViewModels/CompetencyAssessments/EditDescriptionViewModel.cs, DigitalLearningSolutions.Web/Views/CompetencyAssessments/EditDescription.cshtml
[TD-482](https://hee-tis.atlassian.net/browse/TD-482)
Implements edit description MVC form with "Mark task as complete" checkbox next to Save button
-----
I have:
Either:
Or:
[TD-482]: https://hee-tis.atlassian.net/browse/TD-482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-482 edit assessment description

DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AddNewCentreCourse/SetSectionContent.cshtml
https://hee-tis.atlassian.net/browse/TD-5292
I changed the Go Back button to  anchor tag and added the sectionIndex as parameter so when click it will return the previous page
I also check the index to get the previous page 
-----
I have:
Either:
Or:
=> TD-5292 Issue with 'Go back' link when creating a course and adding 'Course content' on 'Course set up' screen

DigitalLearningSolutions.Data/DataServices/CourseCategoriesDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/PromoteToAdminControllerTests.cs, DigitalLearningSolutions.Web.Tests/Services/EmailGenerationServiceTests.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Administrator/AdministratorController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/PromoteToAdminController.cs, DigitalLearningSolutions.Web/Services/CourseCategoriesService.cs, DigitalLearningSolutions.Web/Services/EmailGenerationService.cs
[TD-5368](https://hee-tis.atlassian.net/browse/TD-5368)
The work done in this PR is Adding a 'Category Name' To Emails triggered when - 
1. **Promote to Nominated supervisor :** Supervisor - View My staff list - Select any - Promote to Nominated supervisor
2. **EditAdminRoles :** Tracking System - Centre Details - Edit Centre Details - Administrators - Expand Any - Manage Roles
3. **Promote To Admin Controller :** Tracking System - Delegates - Manage Delegate - Promote to Admin
Promoting a delegate and setting learning category as Digital workspace-
The email received -
-----
I have:
Either:
Or:
[TD-5368]: https://hee-tis.atlassian.net/browse/TD-5368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …
=> TD-5368 Adding Category To Email Content

DigitalLearningSolutions.Web/Controllers/Support/RequestSupportTicketController.cs, DigitalLearningSolutions.Web/ViewModels/Support/RequestSupportTicket/RequestSummaryViewModel.cs, DigitalLearningSolutions.Web/Views/Support/RequestSupportTicket/RequestSummary.cshtml
[TD-5390](https://hee-tis.atlassian.net/browse/TD-5390)
Solved validation issue on create FreshDesk ticket.
RequestSubject property was not being set from multipage form data on page load after validation, and hence it was not loading on the screen.
**Wave-**
The two errors showing are those of the Jodit rich text editor. We are going to find a solution for this in the coming sprints; hence, we are ignoring this for now.
-----
I have:
Either:
Or:
[TD-5390]: https://hee-tis.atlassian.net/browse/TD-5390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5390- Solved Validation Issues

DigitalLearningSolutions.Web/Views/Frameworks/Developer/_Structure.cshtml
[TD-5322](https://hee-tis.atlassian.net/browse/TD-5322)
Moved the framework buttons from the bottom of the page to the top of the page
Wave tool Screenshot 
-----
I have:
Either:
Or:
[TD-5322]: https://hee-tis.atlassian.net/browse/TD-5322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5322 Moving the framework buttons from the bottom of the screen to the top for visibility

DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Data/Models/User/UserAccount.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Users/SearchableUserAccountViewModel.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Users/_SearchableUserCard.cshtml
[TD-3717](https://hee-tis.atlassian.net/browse/TD-3717)
Adding LastAccessed Date In SuperAdmin UserAccounts Card
-----
I have:
Either:
Or:
[TD-3717]: https://hee-tis.atlassian.net/browse/TD-3717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3717 Adding LastAccessed Date In SuperAdmin UserAccounts Card

DigitalLearningSolutions.Data/DataServices/FrameworkDataService.cs, DigitalLearningSolutions.Web/Controllers/FrameworksController/Frameworks.cs, DigitalLearningSolutions.Web/Controllers/FrameworksController/ImportCompetencies.cs, DigitalLearningSolutions.Web/Services/FrameworkService.cs, DigitalLearningSolutions.Web/Services/ImportCompetenciesFromFileService.cs, DigitalLearningSolutions.Web/ViewModels/Frameworks/Import/ImportCompetenciesFormData.cs, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/ImportFailed.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/Index.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/_Structure.cshtml, DigitalLearningSolutions.Web/Views/Shared/Components/DateInput/Default.cshtml, DigitalLearningSolutions.Web/Views/Shared/Components/ErrorSummary/Default.cshtml, DigitalLearningSolutions.Web/Views/Shared/Components/RadioList/Default.cshtml
[TD-5153](https://hee-tis.atlassian.net/browse/TD-5153)
Fixes fails found during testing of TD-5153.
-----
I have:
Either:
Or:
[TD-5153]: https://hee-tis.atlassian.net/browse/TD-5153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5153 fix testing fails for competency upload

DigitalLearningSolutions.Data/DataServices/FrameworkDataService.cs
[TD-5219](https://hee-tis.atlassian.net/browse/TD-5219)
Fixes downloading and uploading of ungrouped competencies by changing inner to left join.
-----
I have:
Either:
Or:
[TD-5219]: https://hee-tis.atlassian.net/browse/TD-5219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5219 Fixes downloading and uploading of ungrouped competencies

DigitalLearningSolutions.Web/Views/SuperAdmin/AdminAccounts/Index.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Delegates/Index.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Users/Index.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/EmailDelegates/Index.cshtml, DigitalLearningSolutions.Web/Views/UserFeedback/GuestFeedbackStart.cshtml, DigitalLearningSolutions.Web/Views/UserFeedback/UserFeedbackComplete.cshtml, DigitalLearningSolutions.Web/Views/UserFeedback/UserFeedbackTaskAchieved.cshtml, DigitalLearningSolutions.Web/Views/UserFeedback/UserFeedbackTaskAttempted.cshtml, DigitalLearningSolutions.Web/Views/UserFeedback/UserFeedbackTaskDifficulty.cshtml
[TD-5327](https://hee-tis.atlassian.net/browse/TD-5327)
Fixes styling issues noticed by testers after upgrade to NHS design system version 9 / TEL design system.
-----
I have:
Either:
Or:
[TD-5327]: https://hee-tis.atlassian.net/browse/TD-5327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5327 fix styling issues after upgrade to TEL design system

DigitalLearningSolutions.Data/DataServices/FrameworkDataService.cs
[TD-5409](https://hee-tis.atlassian.net/browse/TD-5409)
There was a typo within the inline SQL query responsible to submit the framework review, that typo has now been fixed and tested.
No Screenshots.
-----
I have:
Either:
Or:
[TD-5409]: https://hee-tis.atlassian.net/browse/TD-5409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5409 Fix for the Console Error During Freamwork Review Submission

DigitalLearningSolutions.Web/Views/SuperAdmin/AdminAccounts/Index.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Delegates/Index.cshtml, DigitalLearningSolutions.Web/Views/Support/RequestSupportTicket/RequestAttachment.cshtml, DigitalLearningSolutions.Web/Views/Support/RequestSupportTicket/RequestSummary.cshtml, DigitalLearningSolutions.Web/Views/Support/RequestSupportTicket/SupportTicketSummaryPage.cshtml, DigitalLearningSolutions.Web/Views/Support/RequestSupportTicket/TypeOfRequest.cshtml
[TD-5327](https://hee-tis.atlassian.net/browse/TD-5327)
Fixes styling issues for super admin and request support identified by testers after upgrade to NHS frontend.
-----
I have:
Either:
Or:
[TD-5327]: https://hee-tis.atlassian.net/browse/TD-5327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5327 fix styling issues in request support and super admin

DigitalLearningSolutions.Web/Controllers/Support/RequestSupportTicketController.cs
[TD-5390](https://hee-tis.atlassian.net/browse/TD-5390)
Route URL updated in post action method
N/A
-----
I have:
Either:
Or:
[TD-5390]: https://hee-tis.atlassian.net/browse/TD-5390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5390-Route URL updated in post action method

DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/SelfAssessmentReports/TableauCompetencyDashboard.cshtml
[TD-5486](https://hee-tis.atlassian.net/browse/TD-5486)
Adds inset text above the embedded dashboards to instruct users to go full screen. This was the only one of the suggested improvements in the ticket that proved feasible, mainly due to limitations of Tableau embed.
-----
I have:
Either:
Or:
[TD-5486]: https://hee-tis.atlassian.net/browse/TD-5486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5486 improve embedded dashboard

DigitalLearningSolutions.Web/Controllers/FrameworksController/Competencies.cs
[TD-5512](https://hee-tis.atlassian.net/browse/TD-5512)
I added a null check for the 'selectedFlagIds' array which basically stores the flag ids that have been selected on the UI, since we were performing array functions on a null array, we were getting the 500 error as it was breaking the code.
No screenshots
-----
I have:
Either:
Or:
[TD-5512]: https://hee-tis.atlassian.net/browse/TD-5512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD_5512 code checkin for competency 500 error while adding competency with flags

DigitalLearningSolutions.Data.Migrations/202504290900_UpdateNotifications.cs
[TD-5545](https://hee-tis.atlassian.net/browse/TD-5545)
Updated Notifications Table to fix the typo.
-----
I have:
Either:
Or:
[TD-5545]: https://hee-tis.atlassian.net/browse/TD-5545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5545 Update Notifications Table

DigitalLearningSolutions.Data/DataServices/FrameworkDataService.cs, DigitalLearningSolutions.Web/Views/Frameworks/Developer/_MyFrameworks.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Shared/_BrandedFrameworkTable.cshtml
[TD-5511](https://hee-tis.atlassian.net/browse/TD-5511)
Removed hardcoded value from the select statement.
Displaying View/Review link based on framework review.
N/A
-----
I have:
Either:
Or:
[TD-5511]: https://hee-tis.atlassian.net/browse/TD-5511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5511-Displaying View/Review link based on framework review

DigitalLearningSolutions.Web/Views/SuperAdmin/Delegates/_SearchableDelegatesCard.cshtml
[TD-3719](https://hee-tis.atlassian.net/browse/TD-3719)
Changed the text 'Last Accessed' to 'Last accessed date' on the delegates card within superadmin module.
-----
I have:
Either:
Or:
[TD-3719]: https://hee-tis.atlassian.net/browse/TD-3719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD_3719 Added 'Last accessed date' to the delegates card within the superadmin module

DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ViewDelegate/Index.cshtml
[TD-5583](https://hee-tis.atlassian.net/browse/TD-5583)
Added a 'Last accessed date' section to the View Delegates information page within the Managed Delegates functionality of the tracking system module 
-----
I have:
Either:
Or:
[TD-5583]: https://hee-tis.atlassian.net/browse/TD-5583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD_5583_ Added Last accessed date field to the view delegates section within Tracking System

.github/workflows/build-and-deploy-production.yml, .github/workflows/build-and-deploy-uat.yml, .github/workflows/continuous-integration-workflow.yml
https://hee-tis.atlassian.net/browse/TD-5618
Hotfix for dot net version update
-----
I have:
Either:
Or:
=> TD-5618 DLS-Release-v1.2.0-Hotfix for dot net version update

DigitalLearningSolutions.Data/DataServices/PlatformReportsDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/DCSAReportDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAsssessmentReportDataService.cs, DigitalLearningSolutions.Data/DigitalLearningSolutions.Data.csproj, DigitalLearningSolutions.Data/Factories/ReadOnlyConnectionFactory.cs, DigitalLearningSolutions.Web/Helpers/ConfigHelper.cs, DigitalLearningSolutions.Web/Startup.cs, DigitalLearningSolutions.Web/appsettings.json
[DLS Inverness Release 1.2.1 Hotfix-2.0](https://hee-tis.atlassian.net/projects/TD/versions/13115/tab/release-report-all-issues)
Moving self assessment reports to Azure SQL replica.
=> Dls release v1.2.1 hotfix

DigitalLearningSolutions.Data.Migrations/202507221424_AddNewColumnsInSelfAssessments.cs
[TD-5837](https://hee-tis.atlassian.net/browse/TD-5837)
Added a script to add
RetirementDate,
EnrolmentCutoffDate and RetirementReason
columns to the SelfAssessments table.
N/A
-----
I have:
Either:
Or:
[TD-5837]: https://hee-tis.atlassian.net/browse/TD-5837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added a script to add columns to the SelfAssessments table.

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs, DigitalLearningSolutions.Web/ViewModels/Supervisor/RetiringSelfAssessmentViewModel.cs, DigitalLearningSolutions.Web/Views/Supervisor/ConfirmRetiringSelfAssessment.cshtml
[TD-5616](https://hee-tis.atlassian.net/browse/TD-5616)
Added confirmation screen, view model and related changes in controller.
-----
I have:
Either:
Or:
[TD-5616]: https://hee-tis.atlassian.net/browse/TD-5616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5616-Supervisor enrolling learners onto a retiring self assessment
