TechnologyEnhancedLearning/DLSV2

.github/workflows/continuous-integration-workflow.yml
DigitalLearningSolutions.Data.Migrations/202010161445_ApplyLPDefaultSPs.cs
DigitalLearningSolutions.Data.Migrations/Properties/Resources.resx
DigitalLearningSolutions.Data.Tests/Helpers/SelfAssessmentHelper.cs
DigitalLearningSolutions.Data.Tests/Helpers/ServiceTestHelper.cs
DigitalLearningSolutions.Data.Tests/Services/CentresServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/SelfAssessmentServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/UnlockDataServiceTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/SelfAssessmentTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningPortal/AvailableCourseViewModelTests.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs
DigitalLearningSolutions.Web/Controllers/LoginController.cs
DigitalLearningSolutions.Web/Helpers/ConfigHelper.cs
DigitalLearningSolutions.Web/Scripts/learningPortal/dlscommon.ts
DigitalLearningSolutions.Web/Scripts/learningPortal/selfAssessment.ts
DigitalLearningSolutions.Web/appsettings.json
Jenkinsfile
README.md

* Add a GitHub Actions workflow which will build and test the code. It won't run the data tests since they need to use a database.
* Fix issue with latest migration. Looks like there was a field missed when creating the new FilteredLearningActivity. And the ApplyLPDefaultsToSelfEnrol field was already present in the Customisations table so couldn't be added again.
* Fix web and data unit tests. There were a few different errors, some to do with the difference between using an obfuscated database and a non-obfuscated one. I think it would be best to stick with the obfuscated version if possible.
* Fix linting issues.

HEEDLS-130 Fix build

---

DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/AvailableTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/CompletedTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/CurrentTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/LearningPortalControllerTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/SelfAssessmentTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningSolutions/LearningSolutionsControllerTests.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/Available.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/Completed.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/Current.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/FilteredResults.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/LearningPortalController.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs
DigitalLearningSolutions.Web/Controllers/LearningSolutionsController.cs
DigitalLearningSolutions.Web/Helpers/CustomClaimHelper.cs
DigitalLearningSolutions.Web/Startup.cs
DigitalLearningSolutions.Web/ViewModels/LearningSolutions/AccessibilityHelpViewModel.cs
DigitalLearningSolutions.Web/ViewModels/LearningSolutions/ErrorViewModel.cs
DigitalLearningSolutions.Web/ViewModels/LearningSolutions/TermsViewModel.cs
DigitalLearningSolutions.Web/Views/LearningSolutions/AccessibilityHelp.cshtml
DigitalLearningSolutions.Web/Views/LearningSolutions/Error/Forbidden.cshtml
DigitalLearningSolutions.Web/Views/LearningSolutions/Error/PageNotFound.cshtml
DigitalLearningSolutions.Web/Views/LearningSolutions/Error/UnknownError.cshtml
DigitalLearningSolutions.Web/Views/LearningSolutions/Terms.cshtml
DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml

Summary of changes:
* Moved error pages, terms and accessibility actions to their own controller
* Moved view models and views for the corresponding pages to a new learning solutions folder
* Moved some helper methods to get candidate id and centre id to the claims helper so that they can be used from anywhere in the application, not just the learning portal controller
* Updated all redirects to the error pages to redirect to the new controller
Testing:
* Checked navigating to an unknown url gave 404
* Checked navigating to an existing page but with invalid parameter gave 404
* Checked causing exception gave 500
* Checked footer links working on both learning portal pages and error pages

HEEDLS-165 Move shared pages to own controller

---

README.md
SQLScripts/MakeLocalDatabaseConsistentWithLive.sql

There were some changes made to the database after the obfuscated database backup was created and before the project was setup to use migrations for database changes. Therefore there are some inconsistencies between the database backup and the live
& UAT databases. I've added a script to fix this which should be run on any locally created databases and on test.

HEEDLS-NONE Add script to fix inconsistencies in obfuscated database

---

DeployToFtpServer.bat
DeployToFtpServer.txt
DeployToProduction.bat
DeployToUAT.bat
Jenkinsfile

Made some minor improvements to the deployment script.
I noticed that you'd changed the ftp ip. To avoid having to change this back and forth I've now made it a parameter to be passed in to the script. So you can call the script by e.g.:
```
DeployToUAT.bat "USERNAME:PASSWORD" 10.0.1.82
```
I also made some minor changes to how the WinSCP logs are printed, to prevent them from printing the ftp password. The complete logs will still be available in the log file 🙂

HEEDLS-NONE Improve the ftp deployment script

---

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/ContentViewerViewModelTests.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/ContentViewerViewModel.cs

As the SCORM urls in the db refer to content hosted in the live application, running them with customisation values from the test db won't work.
The UAT values won't work when running locally or on test, but should work when deployed to UAT, so that should be enough for a proof of concept.

HEEDLS-201 Use UAT values for hardcoded SCORM content

---

DigitalLearningSolutions.Web/appsettings.Test.json

Plan for SCORM player testing documented here: https://swiki.softwire.com/display/HEE/Testing.
The only code change necessary was to change the test application to point to the UAT version of the old system. This isn't strictly necessary, as we shouldn't be doing SCORM testing on test (we should be testing locally and on UAT). But just in case some content works and is launched during testing it would be better for the tracking for that content to be updated in the UAT database. As we're just using a test account it shouldn't matter much either way but might as well be safe 🙂

HEEDLS-201 Change test old system url

---

DigitalLearningSolutions.Data.Tests/Services/CourseContentServiceTests.cs
DigitalLearningSolutions.Data/Models/CourseContent/CourseContent.cs
DigitalLearningSolutions.Data/Services/CourseContentService.cs
DigitalLearningSolutions.Web.Tests/TestHelpers/CourseContentHelper.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/IntitialMenuViewModelTests.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/InitialMenuViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/Index.cshtml

Subtask of HEEDLS-173
1. Add the following pieces of information to the `CourseContent` model:
- Course title (`"{Application Name} - {Customisation Name}"`)
- Average course duration
- Centre name
- Centre banner text (nullable)
2. Rewrite the `GetCourseContent` method in `CourseService`, to run a query similar to the one on the HEEDLS-173 ticket to get this information, trimmed to only get the required information
3. Modify the `InitialMenuViewModel` to collect these new fields and assign them to its own fields, including renaming one of the fields for consistency (`Name` to `Title`) 
4. Amend tests to use the new fields of the `CourseContent` and `InitialMenuViewModel`
Refactored and amended the tests that use this code to cover the new fields. After this, ran all unit tests and they …

HEEDLS-203 Menu Header Course information back end

---

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_Layout.cshtml

We noticed in testing that I'd forgotten to update the footer links on the self assessment pages 🙂

HEEDLS-165 Fix footer links for self assessment pages

---

DigitalLearningSolutions.Web/Views/LearningMenu/Index.cshtml
DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml

Few things I wasn't sure about. In the old website the test centre was the title for the box that contained all of the different tasks etc, I just put it on a new line as I wasn't sure where exactly it should go (since I'm not sure where the task etc will be viewed). 
I used secondary text colour for the banner and use a `<br/>` so that the banner text would be grouped with the centre name as using a new `<p>` would leave a large gap between them. I wasn't actually able to find an example of the banner text in the old website when I was looking through it so I wasn't exactly sure how it used to look.

HEEDLS-204 menu header course information front end

---

DigitalLearningSolutions.Web/Views/LearningMenu/Index.cshtml

Button will redirect you to the current courses page. The code is a copy of what is used in the _layout.cshtml for the SelfAssessment page. May want to consider using it in a partial in future if it is used enough.
Wondering if it would be better to use a Chevron rather than the close icon as it is a "return" to rather than a "close"

Heedls 174 menu header close button

---

DigitalLearningSolutions.Data.Tests/Helpers/CourseContentTestHelper.cs
DigitalLearningSolutions.Data.Tests/Services/CourseContentServiceTests.cs
DigitalLearningSolutions.Data/Services/CourseContentService.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs
DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs

Added an method for updating LoginCount and Duration in Progress; this required a new method for obtaining ProgressID from Progress using CandidateID and CustomisationID which was also added. This update will be ran whenever a learning menu is opened.
Ran and passed all unit tests then manually tested by changing the stored value then opening the page on Firefox.

HEEDLS-198 Update login count and duration

---

DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml

Make only the NHS logo on the shared header clickable. As the rest of the header text won't necessarily match the link destination (the dls homepage switch application).

HEEDLS-207 Make part of shared header not clickable

---

DigitalLearningSolutions.Data.Tests/Helpers/CourseContentTestHelper.cs
DigitalLearningSolutions.Data.Tests/Services/CourseContentServiceTests.cs
DigitalLearningSolutions.Data/Services/CourseContentService.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs
DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs

Update the SubmittedTime in the Progress table when launching a course.
Also small changes to the tests because they were previously testing dates after SubmittedTime.
Ran and passed all unit tests then manually tested by launching a course on Firefox.

HEEDLS-198 Update submitted time and change tests

---

DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml

Normally service names are links in a header, where the link covers the
NHS logo and the text. It doesn't make sense for the text to be a link
here, but keep the same layout by using the CSS classes in a `<div>`
instead of on the `<a>` tag.
Tested using Chrome, Firefox, Edge and IE11, all using narrow viewports and large zooms. Tested on Chrome and IE11 using a screenreader. The only cases when the header layout breaks down (menu button overlapping text mainly) are for extremely narrow viewports combined with large zooms. In these cases it occurs in exactly the same way for other NHS pages (tested with [this one](https://service-manual.nhs.uk/design-system/components) mainly), so none of the changes we have made have changed this behaviour.

HEEDLS-207 Fix layout for long titles on narrow screens

---

DigitalLearningSolutions.Data.Tests/Helpers/CourseContentTestHelper.cs
DigitalLearningSolutions.Data.Tests/Services/CourseContentServiceTests.cs
DigitalLearningSolutions.Data/Services/CourseContentService.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs
DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs

Add a new method to check if a given entry exists in the progress table and executes the uspCreateProgressRecord_V3 stored procedure if the entry doesn't exist.
The stored procedure has a few checks and doesn't insert the entry if any fail. This will be logged but the program will still try to run GetProgress method so this has been kept as QueryFirstOrDefault to prevent crashing if the entry wasn't added.
Ran and passed all unit tests and manually tested on Firefox, "Current Activities" will show newly enrolled courses.

Create progress entry on first launch

---

DigitalLearningSolutions.Web.Tests/TestHelpers/CourseSectionHelper.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/IntitialMenuViewModelTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/SectionCardViewModelTest.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/InitialMenuViewModel.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/SectionCardViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/Index.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/_SectionCard.cshtml

I tried to reuse code from the course cards (but this time utilising the nhsuk course card css class). I had to hard code in the padding as it by default it was far too large.
With this method, the return to activity button is stuck all the way at the bottom. Would we prefer to put it just above the section cards?
What still needs to be added is:
- A `SectionCardViewModel` which I can give to the section card partial
- A list of `Sections` (custom class) added to the `courseContent` @benjimarshall is doing this on his end
- Change the current `for` loop to a `foreach section in courseContent.Sections`
- Change the hard coded values to use values from the View Models

HEEDLS-208 Initial Menu Page Front End

---

DigitalLearningSolutions.Web/Views/LearningPortal/Available/Available.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/Completed/Completed.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/Current/Current.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/Current/RemoveCurrentCourseConfirmation.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/Current/SetCompleteByDate.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/Current/UnlockCurrentCourse.cshtml
DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml
DigitalLearningSolutions.Web/appsettings.Development.json

- Make base URL port consistent across AppSettings JSON (I think this is just a bugfix but will this break something I don't know about?)
- Add Application name and nav menu to all LearningPortal pages
- Add header links to LearningPortal pages to link back to Current Courses (with alt text), with the default link for other pages (eg. error pages) linking to switch application
Tested using Chrome, Firefox, Edge and IE11 using high zoom, narrow viewports and a screenreader.

HEEDLS-207 add header link

---

DigitalLearningSolutions.Data.Tests/Helpers/SessionTestHelper.cs
DigitalLearningSolutions.Data.Tests/Services/SessionServiceTests.cs
DigitalLearningSolutions.Data/Models/Session.cs
DigitalLearningSolutions.Data/Services/SessionService.cs

- Add `SessionService` to manage interactions with sessions, with methods to:
- Start or restart a session
- Update the duration of a session
- Make a session as inactive
This is the DB side of HEEDLS-212. This will need to be connected up to the Controllers in a future PR.
Added unit tests to check the three methods of the service to ensure they behave as expected.

HEEDLS-212 Add SessionService (and tests) to track sessions

---

DigitalLearningSolutions.Web/Views/LearningMenu/Index.cshtml

Add header link and alt text for the Learning Menu initial course page
Tested on Chrome, Firefox, Edge and IE11 using a screenreader and large zoom.

HEEDLS-207 Add link to LearningMenu course initial menu

---

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/SectionCardViewModelTest.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/SectionCardViewModel.cs

Add a rounding to the percentage completion using string formatting.
Tested on Google Chrome only because this is just changing a string before it gets passed to the View.

Round percentage completion to nearest integer

---

DigitalLearningSolutions.Data.Tests/Helpers/CourseContentTestHelper.cs
DigitalLearningSolutions.Data.Tests/Services/CourseContentServiceTests.cs
DigitalLearningSolutions.Data/Models/CourseContent/CourseContent.cs
DigitalLearningSolutions.Data/Services/CourseContentService.cs
DigitalLearningSolutions.Web.Tests/TestHelpers/CourseContentHelper.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/IntitialMenuViewModelTests.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/InitialMenuViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/Index.cshtml

Add extra fields to `GetCourseContent` query and `CourseContent` class for extra information used in summary page. Had to amend some existing tests that use the CourseContent class.
Add extra properties to `InitialViewModel` and helper methods to get styling and completed status.
Integrate backend into frontend by replacing hardcoded values.
Ran and passed all unit tests, manually tested on Firefox by setting `IncludeCertificate` to 1 for a complete and incomplete course then opening the pages. The summary card was displayed when expected and the information was also correct, appearing as shown in #53.

HEEDLS-210 Link to completion summary back end

---

DigitalLearningSolutions.Data.Tests/Helpers/MockHttpContextSession.cs
DigitalLearningSolutions.Data.Tests/Services/SessionDataServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/SessionServiceTests.cs
DigitalLearningSolutions.Data/DigitalLearningSolutions.Data.csproj
DigitalLearningSolutions.Data/Services/SessionDataService.cs
DigitalLearningSolutions.Data/Services/SessionService.cs
DigitalLearningSolutions.Web.Tests/ControllerHelpers/MockHttpContextSession.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs
DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs
DigitalLearningSolutions.Web/Startup.cs
DigitalLearningSolutions.Web/Views/LearningMenu/Index.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Shared/_NavMenuItems.cshtml

- Inject SessionService into Web project.
- Maintain Session state in the LearningMenu using the SessionService.
- Add a mock HttpContext.Session class and use this to test the new
LearningMenu controller session tracking.
Add new unit tests and check they run. Tested links in Chrome, Firefox, Edge and IE11

HEEDLS-212 Add session tracking to LearningMenu controller

---

DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/IntitialMenuViewModelTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/SectionCardViewModelTest.cs
DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/InitialMenuViewModel.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/SectionCardViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/_SectionCard.cshtml

Add customisation ID to the section page URL and section card view model. The customisation ID is needed for the backend methods and session tracking.

HEEDLS-216 Add customisation ID to section page

---

DigitalLearningSolutions.Web/Views/LearningMenu/Index.cshtml

Set the ViewData title to be the course title for learning menu pages. This means the tab name for learning menu pages will be the course name - Digital Learning Solutions.
@kwunkiuma @benjimarshall this should be set for the section page and tutorial page as well. I think it makes sense to set it to the course name for both of those, no need to include section or tutorial name 🙂

HEEDLS-222 Fix learning menu tab name

---

DigitalLearningSolutions.Web/Views/LearningMenu/Section/Section.cshtml

Adds basic info to section page.
Displays the section title, %complete, minutes spent, average minutes spent, and back button.

HEEDLS-216 Section page basic info front end

---

DigitalLearningSolutions.Data.Tests/Services/CourseContentServiceTests.cs
DigitalLearningSolutions.Data/Services/CourseContentService.cs

- Inner join against the CustomisationsTutorials to make sure we only
consider tutorials selected for this course customisation.
- Fix a percentage complete counting bug, which when counting the number
of tutorials that need to be completed it considered all potential
tutorials instead of just the ones selected for this course.
I spotted the percentage counting bug when discussing this ticket with Frank 
and fixing this bug solved the main issue of the ticket (pretty much by accident)
so I said I would push it up.
Added a test for the bug in this ticket.

Fix too many sections on initial menu

---

DigitalLearningSolutions.Data.Tests/Services/TutorialContentServiceTests.cs
DigitalLearningSolutions.Data/Services/TutorialContentService.cs

- When a candidate is not enrolled on a course but queries a tutorial in
it, return the tutorial with progress values set to a default (eg.
TimeSpent = 0).
- Adjust the TutorialContentService tests to reflect this.
- Automatically enrol a user after returning a tutorial if they are
not already enrolled is part of the LearningMenuController already.
Add unit tests for this default behaviour.

HEEDLS-180 Add default values to TutorialContent query

---

DigitalLearningSolutions.Data.Tests/Helpers/CourseContentTestHelper.cs
DigitalLearningSolutions.Data.Tests/Services/CourseContentServiceTests.cs
DigitalLearningSolutions.Data/Models/CourseContent/OldCourseSection.cs

Since we've had issues with our queries not matching the old stored procedures I thought tests like this might be useful. If you come across a course worth adding to the test list (e.g. because it wasn't working at any point, or it has some interesting properties) then feel free to add it. I'll try to find time to hunt for some more useful courses to add to the test list. I'll also try to add something similar for the section and tutorial pages 🙂

HEEDLS-NONE Add more tests for initial menu SQL query

---

DigitalLearningSolutions.Web/Views/LearningMenu/_TutorialCard.cshtml

Add a link to the existing "Launch tutorial" button on the section page (in the tutorial card partial) to go to the tutorial page. This is a hardcoded link to one tutorial, and will need to be updated when the backend in HEEDLS-217 is finished and connected up.
Tested on Chrome and IE11, using a screen reader

HEEDLS-218 Add link to open Tutorial page

---

DigitalLearningSolutions.Data.Tests/Services/SectionContentServiceTests.cs
DigitalLearningSolutions.Data/Services/SectionContentService.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs
DigitalLearningSolutions.Web.Tests/TestHelpers/SectionContentHelper.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/SectionContentViewModelTests.cs
DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs
DigitalLearningSolutions.Web/Startup.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/SectionContentViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/Section/Section.cshtml

Integrate the front and back ends for basic info on the section page.
Replace hardcoded values in view with view model values.
Add tests for view model and controller.
Ran and passed all unit tests. Manually tested on Firefox and pages are displaying the correct information, including when opening a unenrolled section via URL.

HEEDLS-177 Section page basic info integration

---

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/TutorialViewModelTests.cs
DigitalLearningSolutions.Web/DigitalLearningSolutions.Web.csproj
DigitalLearningSolutions.Web/ViewModels/LearningMenu/TutorialViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/Tutorial.cshtml

- Install the Html Agility Pack NuGet package.
- Add tutorial objective parsing, to the view model, and display it in
the Tutorial view.
- Add tests for this view model parsing method.
Add view model unit tests, test in Chrome, Firefox, Edge and IE11, using a screen reader and large zoom.

Add objectives to tutorial page

---

DigitalLearningSolutions.Data.Tests/Services/CourseContentServiceTests.cs
DigitalLearningSolutions.Data/Services/CourseContentService.cs

Change the query to filter out inactive customisations.
Some tests were using inactive customisations so new test cases had to be used.
Ran and passed all unit tests, manually tested on Firefox and checked logs to see the page was redirecting for the correct reason.

HEEDLS-237 Redirect learning menu to 404 if customisation not active

---

DigitalLearningSolutions.Data.Tests/Services/CourseContentServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/TutorialContentServiceTests.cs
DigitalLearningSolutions.Data/Models/TutorialContent/TutorialInformation.cs
DigitalLearningSolutions.Data/Services/TutorialContentService.cs
DigitalLearningSolutions.Web.Tests/TestHelpers/TutorialContentHelper.cs

Amend `GetTutorialInformation` query and data model to get the next
tutorial ID, the next section ID, and the post-learning assessment
path.
- Add test for course contents section test: test a course which has some sections where none of the section's
tutorials are in the CustomisationTutorial table (based on some checks I did this morning)
- Amend `GetTutorialInformation` tests, and add tests for edge cases like being the last tutorial
in a section, and check tutorials not in CustomisationTutorials are skipped.

HEEDLS-244 Tutorial next button back end

---

DigitalLearningSolutions.Web.Tests/TestHelpers/TutorialContentHelper.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/TutorialNextLinkViewModelTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/TutorialViewModelTests.cs
DigitalLearningSolutions.Web/Styles/learningMenu/tutorial.scss
DigitalLearningSolutions.Web/ViewModels/LearningMenu/TutorialNextLinkViewModel.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/TutorialViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/Tutorial.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/_TutorialNextLink.cshtml

- Add a partial for the next link, and a view model for the partial.
- Add some CSS to style the next link.
Add view model tests for the new data. Tested in Chrome, Firefox, Edge and IE11 using high zoom, narrow viewports, a screen reader an no-JS.

Add front end for tutorial overview next link

---

DigitalLearningSolutions.Data.Tests/Services/CourseContentServiceTests.cs
DigitalLearningSolutions.Data/Models/CourseContent/CourseSection.cs
DigitalLearningSolutions.Data/Services/CourseContentService.cs
DigitalLearningSolutions.Web.Tests/TestHelpers/CourseSectionHelper.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/SectionCardViewModelTest.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/SectionCardViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/_SectionCard.cshtml

- Remove times from section cards in initial menu
- Tidy up the view model and tests.
Tested in Chrome and IE11 using a high zoom, screen reader, and narrow viewport.

HEEDLS-249 Remove times from section cards in initial menu

---

DigitalLearningSolutions.Data/Services/CourseContentService.cs
DigitalLearningSolutions.Web.Tests/Helpers/CompletionSummaryHelperTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/IntitialMenuViewModelTests.cs
DigitalLearningSolutions.Web/Helpers/CompletionSummaryHelper.cs
DigitalLearningSolutions.Web/Styles/learningMenu/index.scss
DigitalLearningSolutions.Web/ViewModels/LearningMenu/InitialMenuViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/Index.cshtml

- Add section tie break to ordering of initial menu
- Add completion summary text
- Add breakline to InitialMenu page between Section cards and course
completion status card
- Add completion requirements dummy text to CompletionCard
- Add status tag on the right of the card
- Convert summary card to a clickable card
Added unit tests for summary text maker, and for changes to the view model. There is no easy way to test the sorting of sections because no two sections in a section course share a section number, but the change for that is so small I am quite confident it is right.
Tested UI in Chrome, Firefox, Edge and IE11, using no JS, high zoom, narrow viewports and a screenreader.

HEEDLS-251 Improve completion summary link front end

---

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/ContentViewerViewModelTests.cs
DigitalLearningSolutions.Web/Helpers/ConfigHelper.cs

Change the tracking URL.
Change a test using the tracking URL.
Ran and passed all unit tests, manually tested on Firefox and inspected the correct URL used in the iframe.

HEEDLS-253 Content viewer fix tracking url

---

DigitalLearningSolutions.Web/Views/LearningMenu/_SectionCard.cshtml

Add section id to heading text of section card, and use that for an `aria-describedby` on the Launch section button.
Tested with a screen reader in Chrome, Firefox, Edge and IE11. No visual changes occured.

HEEDLS-256 Add name to aria text of launch section link

---

DigitalLearningSolutions.Data.Tests/Services/TutorialContentServiceTests.cs
DigitalLearningSolutions.Data/Services/TutorialContentService.cs

*Bug description*:
If a course as a post learning assessment, but it has been disabled by
`IsAssessed`, then the next link should not link to that post learning
assessment.
Amend query to discard post learning assessment path if `IsAssessed` is `false`
Add a regression test for the example @FridaTveit found whilst testing.

Fix tutorial next link back end bug

---

DigitalLearningSolutions.Web/DigitalLearningSolutions.Web.csproj
DigitalLearningSolutions.Web/Scripts/learningMenu/contentViewer.ts
DigitalLearningSolutions.Web/Scripts/spec/contentViewer.spec.ts
DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/ContentViewer.cshtml

I don't think this is ready to go yet, and I've got a questions section below. I thought the easiest way for me to explain what I had done so far was a PR, and I can add any changes needed to it
- Add `closeMpe` function for Content Viewer in a new TypeScript file
- Add this script to the `ContentViewer` view
- I've added no tests. How should I test this, in particular is there a good way of mocking up a `window` object? Also, where should I put these tests?
- I've exposed this as a global function using `window.closeMpe = closeMpe` to make sure it's still accessible after webpack runs. Is there a better way of doing this?
- The `closeMpe` function needs the `customisationId` and `sectionId` for it to redirect. Currently I'm extracting this from the URL using `window.location.href`, is …

HEEDLS-254 Content Closing page

---

DigitalLearningSolutions.Web/Scripts/learningMenu/contentViewer.ts
DigitalLearningSolutions.Web/Scripts/spec/contentViewer.spec.ts

Change the URLs to be absolute and not relative, to fix the issue with redirects found in testing.
Amend the TypeScript unit tests to reflect this change. Checked running the function works from Chrome developer console, integration testing has not been done yet because it is easiest to do this on UAT when there are no cross-site scripting concerns.

HEEDLS-254 Bugfix: use absolute, not relative URLs in content close script

---

DigitalLearningSolutions.Data.Tests/Services/CourseContentServiceTests.cs

Rename a test procedure added for HEEDLS-247. This procedure had a temporary name and ended up getting push up, sorry about that. I've renamed it to something more helpful here.

HEEDLS-NONE Rename a test procedure

---

DigitalLearningSolutions.Data.Tests/Helpers/DiagnosticAssessmentTestHelper.cs
DigitalLearningSolutions.Data.Tests/Services/DiagnosticAssessmentServiceTests.cs
DigitalLearningSolutions.Data/Models/DiagnosticAssessment/DiagnosticAssessment.cs
DigitalLearningSolutions.Data/Models/DiagnosticAssessment/DiagnosticTutorial.cs
DigitalLearningSolutions.Data/Models/DiagnosticAssessment/OldScores.cs
DigitalLearningSolutions.Data/Models/DiagnosticAssessment/OldTutorial.cs
DigitalLearningSolutions.Data/Services/DiagnosticAssessmentService.cs
DigitalLearningSolutions.Data/Services/SectionContentService.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs
DigitalLearningSolutions.Web.Tests/TestHelpers/DiagnosticAssessmentHelper.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/DiagnosticAssessmentViewModelTest.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/DiagnosticAssessmentViewModelTests.cs
DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs
DigitalLearningSolutions.Web/Startup.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/DiagnosticAssessmentViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/Diagnostic/Diagnostic.cshtml

Create query for diagnostic assessment information.
Create view model.
Replace hardcoded values in view.
Add logic to controller.
Add service, view model and controller tests.
Ran and passed all unit tests, manually tested on Firefox to check webpage was displaying correct information from backend.
Screenshot shows a page where the user does not have the option to select assessment areas.

HEEDLS-242 Assessment page diagnostic back end

---

DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/CourseCompletionViewModelTests.cs
DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs
DigitalLearningSolutions.Web/Helpers/ConfigHelper.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/CourseCompletionViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/Completion/Completion.cshtml

Add progress ID and app configuration to the view model parameters to
generate the URL for the summary link.
Update the unit tests to reflect these changes. Tested in Google Chrome, but not with the old code running (I often have issues getting the old system running with SQL requests timing out). It should be easier to test on the test site, and I doubt there will be any issues with it considering how small the change is.

HEEDLS-194 Add download summary link to button

---

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/IntitialMenuViewModelTests.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/InitialMenuViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/Index.cshtml

Hide average duration on initial menu if n/a. On Jira I've added my thoughts on why this is the only line that needs changing.
Amend unit tests, and tested on course 6940 (one with an n/a duration).

HEEDLS-267 Hide average duration on initial menu if n/a

---

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/DiagnosticAssessmentViewModelTests.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/DiagnosticAssessmentViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/Diagnostic/Diagnostic.cshtml

Add some logic to not display the selection prompt if there are no tutorials even if `diagObjSelect` is true.
Ran and passed all unit tests. Screenshot taken in Firefox.

HEELDS-188 Assessment page diagnostic bugfix

---

DigitalLearningSolutions.Data.Tests/Models/CourseSettingsTests.cs
DigitalLearningSolutions.Data.Tests/Services/SectionContentServiceTests.cs
DigitalLearningSolutions.Data/Models/CourseSettings.cs
DigitalLearningSolutions.Data/Models/SectionContent/SectionContent.cs
DigitalLearningSolutions.Data/Services/SectionContentService.cs
DigitalLearningSolutions.Web.Tests/TestHelpers/SectionContentHelper.cs

* Add some more fields to the course settings object
* Get course settings when getting section content
* Cover some more edge cases for course settings JSON
Add some more unit tests for: new course settings fields, 
section content getting the settings, and more course
settings edge cases, such as when the JSON is valid but
unexpected, such as the empty string, the empty list, etc.

HEEDLS-279 Add section customisation back end

---

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/SectionContentViewModelTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/TutorialCardViewModelTests.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/SectionContentViewModel.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/TutorialCardViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/Section/Section.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Section/_ConsolidationExerciseCard.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Section/_TutorialCard.cshtml

Add show percentage, show learning status, and consolidation exercise
settings to section page.
Add some unit tests, tested in Google Chrome

HEEDLS-280 Add section customisation front end

---

DigitalLearningSolutions.Data.Tests/Services/DiagnosticAssessmentServiceTests.cs
DigitalLearningSolutions.Data/Models/DiagnosticAssessment/DiagnosticTutorial.cs
DigitalLearningSolutions.Data/Services/DiagnosticAssessmentService.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/DiagnosticAssessmentViewModelTests.cs

Remove change the C# code that was discarding tutorials with
`CustomisationTutorials.Status = 0` for the diagnostic assessment page.
Remove unneeded `CustomisationTutorials.Status` from `DiagnosticTutorial` object
Amend tests due to type change, remove an incorrect test and add a regression test

HEEDLS-281 Fix bug of hiding tutorials with status 0

---

DigitalLearningSolutions.Web.Tests/Helpers/DurationFormattingHelperTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/IntitialMenuViewModelTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/TutorialCardViewModelTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/TutorialTimeSummaryViewModelTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/TutorialViewModelTests.cs
DigitalLearningSolutions.Web/Helpers/DurationFormattingHelper.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/InitialMenuViewModel.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/TutorialCardViewModel.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/TutorialTimeSummaryViewModel.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/TutorialViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/Section/_TutorialCard.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Shared/_TutorialTimeSummary.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/Tutorial.cshtml

Take time summary used by tutorial card and put it in a partial, for
use in tutorial card and also tutorial page.
Amend tests for these view models, move time summary tests into the
partial's view model tests.
Pages tested in Chrome, Firefox, Edge, and IE11, using a screen reader and a narrow viewport.

HEEDLS-248 Make time summary partial for tutorial page

---

DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/Tutorial.cshtml

Update button to open content viewer on tutorial page to say "Start tutorial" instead of launch. This makes it more consistent with the assessment pages.

HEEDLS-291 Improve wording on button on tutorial page

---

DigitalLearningSolutions.Web/Styles/learningMenu/tutorial.scss
DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/Tutorial.cshtml

Use care cards instead of a details expander to show objectives on the tutorial overview page.
Tested in Chrome and IE11, using a screenreader and no JS.

HEEDLS-287 Use care cards for tutorial objectives

---

DigitalLearningSolutions.Data.Tests/Helpers/TutorialContentTestHelper.cs
DigitalLearningSolutions.Data.Tests/Services/CourseCompletionServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/CourseContentServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/TutorialContentServiceTests.cs
DigitalLearningSolutions.Data/Services/CourseCompletionService.cs
DigitalLearningSolutions.Data/Services/CourseContentService.cs
DigitalLearningSolutions.Data/Services/TutorialContentService.cs

Ignore archived tutorials and sections in data services by adding filters to `WHERE` clauses in various queries. Service changed for this ticket:
* Tutorial content
* Course content
* Course completion
This includes changes from review comments in #152.
Remove tests that depend on the old stored procedures, and replace them with new tests. Add tests to check correcting ignoring of archived sections and tutorials.

HEEDLS 294 Fix archived tutorials in course and tutorials services

---

DigitalLearningSolutions.Data.Tests/Services/DiagnosticAssessmentDataServiceTests.cs

No non-testing changes made
Amend diagnostic tests to not use the old stored procedure that handles
archived tutorials incorrectly.
No changes required from review comments in #152.

HEEDLS-295 Amend diagnostic tests for archived tutorials

---

DigitalLearningSolutions.Data.Tests/Helpers/SectionContentTestHelper.cs
DigitalLearningSolutions.Data.Tests/Services/SectionContentServiceTests.cs
DigitalLearningSolutions.Data/Services/SectionContentService.cs

Ignore archived sections in the tutorial list of the section page,
and account for this when looking for the next section. 
This includes changes from review comments in #152.
Amend tests to not use incorrect old stored procedure, apply this
change for both the sections, and the next section as well.

HEEDLS-295 Ignore archived tutorials in section service

---

DigitalLearningSolutions.Data.Tests/Helpers/TutorialContentTestHelper.cs
DigitalLearningSolutions.Data.Tests/Services/TutorialContentServiceTests.cs
DigitalLearningSolutions.Data/Services/TutorialContentService.cs

Get next section IDs when sections just have diagnostic assessments,
or just have post learning assessments (previously it was only displayed
if there was tutorial learning for that next section).
Add some unit tests to cover these cases.

HEEDLS-282 Fix the tutorial page next button back end

---

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/TutorialViewModelTests.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/TutorialViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/Section/_TutorialCard.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Shared/_TutorialTimeSummary.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/Tutorial.cshtml

Change tutorial time summary styling to make spacing consistent when
information is hidden. Tweak tutorial card styling to work around these
changes (there should be no discernable difference in tutorial card
styling after this PR).
Add some tests for this new data. Tested in Chrome and IE11, using high zoom and a screenreader.
These should be the same as last time, but some changes were required to keep them the same

HEEDLS-299 Add tutorial customisation front end

---

DigitalLearningSolutions.Data.Tests/Helpers/CourseCompletionTestHelper.cs
DigitalLearningSolutions.Data.Tests/Helpers/CourseContentTestHelper.cs
DigitalLearningSolutions.Data.Tests/Helpers/SectionContentTestHelper.cs

Tidy up some imports, and remove some test helper methods that were
made redundant during the test rewrites of HEEDLS-288 that I forgot to
remove.
No tests required, test suite still all pass.

HEEDLS-NONE Remove some redundant test helper methods

---

DigitalLearningSolutions.Web/DigitalLearningSolutions.Web.csproj
DigitalLearningSolutions.Web/Scripts/learningMenu/postLearningContentViewer.ts
DigitalLearningSolutions.Web/Scripts/spec/postLearningContentViewer.spec.ts
DigitalLearningSolutions.Web/Views/LearningMenu/PostLearning/PostLearningContent.cshtml

Add TypeScript for automatic page close.
Add unit tests for TypeScript.
Ran and passed all unit tests, tested close function via console on Firefox.

HEEDLS-297 Post learning assessment launch page close

---

DigitalLearningSolutions.Data/Services/DiagnosticAssessmentDataService.cs
DigitalLearningSolutions.Data/Services/DiagnosticAssessmentService.cs
DigitalLearningSolutions.Data/Services/TutorialContentService.cs

Remove `public` from some interface methods.

HEEDLS-NONE Remove interface access modifiers

---

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/CompletionSummaryCardViewModelTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/IntitialMenuViewModelTests.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/CompletionSummaryCardViewModel.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/InitialMenuViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/Index.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Shared/_CompletionSummaryCard.cshtml

Refactor the completion summary card out of the initial menu view and
view model, into its own partial view.
Rearrange some tests to reflect the refactoring. Tested in Chrome, UI should appear the same as before the PR.

HEEDLS-301 Extract completion summary card into partial

---

DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs
DigitalLearningSolutions.Web.Tests/TestHelpers/CourseContentHelper.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/IntitialMenuViewModelTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/SectionContentViewModelTests.cs
DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/SectionContentViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/Section/Section.cshtml

* Amend initial menu action to redirect to the section page if the course has only one section.
* Add completion data to section view model, to be shown if it is the only section in the course, and to flag to record whether this is the only section or not. Also hide the next button in this case.
Amend tests to reflect these changes to the initial menu action, and these additions to the section content view model. 
Tested in Chrome, IE11, using a screenreader. The tags are a bit weird with a screenreader in IE11 (the opening and closing `<strong>` tags get read), but this problem is present on the NHS design system website as well.

HEEDLS-302 Add single section front end

---

DigitalLearningSolutions.Web/Styles/learningMenu/index.scss
DigitalLearningSolutions.Web/Styles/learningMenu/section.scss
DigitalLearningSolutions.Web/Views/LearningMenu/Section/Section.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Section/_DiagnosticAssessmentCard.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Section/_PostLearningAssessmentCard.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Section/_TutorialCard.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Shared/_CompletionSummaryCard.cshtml

Regular view
Mobile view
Had to use float: right as the normal methods had some problems with text overflowing during resizing. I checked with kevin and david and they were happy with how it looked

HEEDLS-307-Section Page Show DIagnostic Recommendation Status Frontend

---

DigitalLearningSolutions.Web/DigitalLearningSolutions.Web.csproj
DigitalLearningSolutions.Web/Scripts/learningMenu/contentViewer.ts
DigitalLearningSolutions.Web/Scripts/learningMenu/diagnosticContentViewer.ts
DigitalLearningSolutions.Web/Scripts/learningMenu/fullscreen.ts
DigitalLearningSolutions.Web/Scripts/learningMenu/postLearningContentViewer.ts
DigitalLearningSolutions.Web/Scripts/spec/learningMenu/contentViewer.spec.ts
DigitalLearningSolutions.Web/Scripts/spec/learningMenu/diagnosticContentViewer.spec.ts
DigitalLearningSolutions.Web/Scripts/spec/learningMenu/fullscreen.spec.ts
DigitalLearningSolutions.Web/Scripts/spec/learningMenu/postLearningContentViewer.spec.ts
DigitalLearningSolutions.Web/Styles/learningMenu/contentViewer.scss
DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/ContentViewer.cshtml

Added support for moving to and from fullscreen on the tutorial content viewer page. It will only work with js enabled.
Tested on Chrome, Firefox and IE11. Tested with voice over. Tested on mobile size screen.
Adding it to the assessment pages should be pretty simple, just calling the fullscreen setup function and adding the buttons in the cshtml files.

HEEDLS-309 Implement fullscreen on tutorial content viewer

---

DigitalLearningSolutions.Web/Views/LearningMenu/Section/_TutorialCard.cshtml

Fixing a bug where the completion status and recommendation tag were on the same line if recommendation status was "Optional"
Normal view:
Mobile view:

HEEDLS-307 - Section Page Show Diagnostic Recommendation Status Fix

---

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/PostLearningAssessmentViewModelTests.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/PostLearningAssessmentViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/PostLearning/PostLearning.cshtml

Move the hidden text to be within the parentheses.
Ran and passed all unit tests. Could not replicate the bug but there should no longer be a colon followed by a bracket.

HEEDLS-314 Post learning assessment improve voice over fix

---

DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/PostLearningAssessmentViewModelTests.cs
DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/PostLearningAssessmentViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/PostLearning/PostLearning.cshtml

* Amend section action to redirect to the post learning assessment page if the course only has a post learning assessment.
* Add completion data to post learning assessment view model, to be shown if it is the item in the course, and flags to record whether this is the only section, and only item in the section.
* Hide the next button if this is the only item in the section.
* Modify the mobile-only back breadcrumb to have a more helpful name,
depending on if there are other sections in the course or not.
Amend tests for this new information, and new learning menu controller behaviour. Tested in Chrome and IE11 using a screen reader and no JS.

Add single post learning assessment front end

---

DigitalLearningSolutions.Web/Scripts/learningMenu/contentViewer.ts
DigitalLearningSolutions.Web/Scripts/spec/learningMenu/contentViewer.spec.ts

Small modification to the regex to account for URL after enabling fullscreen.
Add test for URL after enabling fullscreen.
Ran and passed all unit tests, manually tested on Firefox by using `closeMpe()` in fullscreen and after exiting fullscreen.

HEEDLS-322 Tutorial content viewer close not working after fullscreen

---

DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/DiagnosticAssessmentViewModelTests.cs
DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/DiagnosticAssessmentViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/Diagnostic/Diagnostic.cshtml

* Amend section action to redirect to the diagnostic assessment page if the course only has a diagnostic assessment.
* Add completion data to diagnostic assessment view model, to be shown if it is the only item in the course, and flags to record whether this is the only section, and only item in the section.
* Hide the next button if this is the only item in the section.
* Modify the mobile-only back breadcrumb to have a more helpful name, depending on if there are other sections in the course or not.
Add unit tests, tested in Google Chrome

HEEDLS-320 Add single diagnostic assessment front end

---

DigitalLearningSolutions.Data.Tests/Services/SectionContentServiceTests.cs
DigitalLearningSolutions.Data/Models/SectionContent/SectionTutorial.cs
DigitalLearningSolutions.Data/Services/SectionContentService.cs
DigitalLearningSolutions.Web.Tests/TestHelpers/SectionContentHelper.cs
DigitalLearningSolutions.Web.Tests/TestHelpers/SectionTutorialHelper.cs
DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/TutorialCardViewModelTests.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/SectionContentViewModel.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/TutorialCardViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/Section/_TutorialCard.cshtml

No new tests have been added, all the diffs in the test files are to fix existing tests under the new section tutorial constructor. 
Diagnostic Status and diagnostic attempts are now using the per tutorial values rather than per section values which means the status tag will be displayed/removed in the correct situations. 
For the view, changes have been made so that in the case where there is no time information and no recommendation status, the learn status will appear on the same row as the title. Unfortunately due to the nature of float right it would require a lot of messy logic to have the learn status replace the recommendation status (if recommendation status is not shown and time information is) so in that case there will be white space where the recommendation status would have …

HEEDLS-284 - Section Page Show Diagnostic Recommendation Status Fix

---

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/TutorialViewModelTests.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/TutorialViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/Section/Section.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/Tutorial.cshtml

* Change mobile breadcrumbs' "Return ..." button to point to a page that won't redirect to the current page, either the initial menu or the current activities.
* Update the view models to help decide whether to change the breadcrumbs
Update the unit tests, tested in Chrome using a screenreader.

HEEDLS-321 Change only tutorial or section mobile breadcrumbs

---

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/PostLearningAssessmentViewModelTests.cs
DigitalLearningSolutions.Web/Styles/learningMenu/index.scss
DigitalLearningSolutions.Web/ViewModels/LearningMenu/PostLearningAssessmentViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/PostLearning/PostLearning.cshtml

Change post learning status text on the post learning page to green
when the assessment has been completed successfully.
The text size does not need to be changed, already it is 24px on the
narrowest of displays.
Add some unit tests, tested in Chrome, Firefox, Edge and IE11, and using a screenreader.

HEEDLS-325 Change post learning page status text to green

---

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/SectionContentViewModelTests.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/SectionContentViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/Section/_DiagnosticAssessmentCard.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Section/_PostLearningAssessmentCard.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Section/_TutorialCard.cshtml

* Make all section card status text larger
* Change post learning status text in the post learning card on the section page to green when the assessment has been completed successfully.
*  Fix text wrapping issues for completed diagnostic assessments, in the diagnostic assessment card on the section page.
Add some unit tests, tested in Chrome, Firefox, Edge and IE11, and using a screenreader.

HEEDLS-324 Post learning card status text colour

---

DigitalLearningSolutions.Web/Scripts/learningMenu/fullscreen.ts
DigitalLearningSolutions.Web/Scripts/spec/learningMenu/fullscreen.spec.ts
DigitalLearningSolutions.Web/Styles/learningMenu/contentViewer.scss
DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/ContentViewer.cshtml

Add wrapper for responsive sizing on iframe. The iframe now maintains a 4:3 ratio.
Change fullscreen scripts.
Modify fullscreen tests.
Issue with padding on sides is also resolved.
Browser size
Mobile size
Issue on Firefox where the height of content inside the iframe is too big.

HEEDLS-323 Content viewer smaller height on mobile

---

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/PostLearningAssessmentViewModelTests.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/PostLearningAssessmentViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/PostLearning/PostLearning.cshtml

Change post learning assessment start button to say restart instead of start when the assessment has already been attempted.
Add some more unit tests. Tested in Chrome, Firefox, Edge and IE11, using high zoom and a screen reader.

Change post learning start button text

---

DigitalLearningSolutions.Web/Views/LearningMenu/Section/Section.cshtml

Add green styling to the post learning status displayed in headings at the top of the course.
Tested in Chrome, using a screen reader and no JS.

HEEDLS-324 Add some missed styling to title text

---

DigitalLearningSolutions.Web/Scripts/learningMenu/diagnosticContentViewer.ts
DigitalLearningSolutions.Web/Scripts/spec/learningMenu/contentViewer.spec.ts
DigitalLearningSolutions.Web/Scripts/spec/learningMenu/diagnosticContentViewer.spec.ts
DigitalLearningSolutions.Web/Views/LearningMenu/Diagnostic/DiagnosticContent.cshtml

Add fullscreen functionality to diagnostic content page.
The add responsive resizing; maintaining a 4:3 ratio.
Modify typescript to work after entering fullscreen.
Add tests for close page function after entering fullscreen.
Issue with padding on sides is also fixed.
There is an issue on Firefox where the height of content inside the iframe is too big.
Browser
Browser fullscreen
Mobile
Mobile fullscreen

HEEDLS-329 Diagnostic assessment fullscreen

---

DigitalLearningSolutions.Web/Scripts/learningMenu/postLearningContentViewer.ts
DigitalLearningSolutions.Web/Scripts/spec/learningMenu/postLearningContentViewer.spec.ts
DigitalLearningSolutions.Web/Views/LearningMenu/Diagnostic/DiagnosticContent.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/PostLearning/PostLearningContent.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Shared/_IFrameWithFullscreen.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/ContentViewer.cshtml

Add fullscreen functionality to post learning content page.
The add responsive resizing; maintaining a 4:3 ratio.
Modify typescript to work after entering fullscreen.
Add tests for close page function after entering fullscreen.
Issue with padding on sides is also fixed.
There is an issue on Firefox where the height of content inside the iframe is too big.
Browser
Browser fullscreen
Mobile
Mobile fullscreen

HEEDLS-330 Post learning assessment fullscreen

---

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/SectionCardViewModelTest.cs
DigitalLearningSolutions.Web/ViewModels/LearningMenu/SectionCardViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/_SectionCard.cshtml

- Tweak the formatting of the learning completion text in the view model
- Tweak styling to accommodate longer learning completion text.
Amend relevant unit tests, tested in Chrome, Firefox, Edge and IE11, using a screenreader and high zoom.

HEEDLS-331 Reword section card learning completion

---

DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/TutorialViewModelTests.cs
DigitalLearningSolutions.Web/Styles/learningMenu/index.scss
DigitalLearningSolutions.Web/ViewModels/LearningMenu/TutorialViewModel.cs
DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/Tutorial.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/_TutorialNextLink.cshtml

- Change tutorial next link to button
- Only show this next button if the tutorial has been completed.
- Tweak some CSS to deal with the long row of buttons. We can't use the NHS width classes unfortunately because we need to switch to the vertical list of buttons when the screen is narrower than ~1030px but the widest NHS width class (`large-desktop`) is only 990px wide. 
Add some unit tests, tested in Chrome, Firefox, Edge and IE11, using a screenreader and high zoom.

HEEDLS-332 Change tutorial next link to button

---

DigitalLearningSolutions.Web/Views/LearningMenu/PostLearning/PostLearning.cshtml

Show the next button when the assessment is locked from having too many attempts.
Ran and passed all unit tests, screenshot taken in Google Chrome.

HEEDLS-334 Post learning assessment show next button when locked

---

DigitalLearningSolutions.Data.Tests/Helpers/SessionTestHelper.cs
DigitalLearningSolutions.Data.Tests/Services/CourseContentServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/SessionDataServiceTests.cs

Previously, default session was created not using UTC time. Hence, the clock changes made the tests failed because the expected time was +1 hour from UTC (British Summer Time).

HEEDLS-NONE: Fix broken tests - use UTC time.

---

DigitalLearningSolutions.Web.IntegrationTests/AuthenticationTests.cs
DigitalLearningSolutions.Web.IntegrationTests/CustomWebApplicationFactory.cs
DigitalLearningSolutions.Web.IntegrationTests/DigitalLearningSolutions.Web.IntegrationTests.csproj
DigitalLearningSolutions.Web.IntegrationTests/Properties/launchSettings.json
DigitalLearningSolutions.Web/Controllers/LearningSolutionsController.cs
DigitalLearningSolutions.Web/DigitalLearningSolutions.Web.csproj
DigitalLearningSolutions.sln

Set up basic integration tests:
1. Spin up a test server against which we can run some tests.
2. Use test database when running the tests.
3. Add some basic tests around authentication.
4. Make LearningSolution pages (accessibility help, terms) unauthenticated.
Further work:
Add running these tests to CI/CD pipeline.
Note that the build won't pass atm as some tests are broken due to the clocks change (fixing this is next thing on my list)

HEEDLS-362: Integration tests

---

DigitalLearningSolutions.Web/ViewComponents/LogoViewComponent.cs

Workaround on test environment to prevent app from crashing. This change is also required for the future, where a user could be authenticated using OpenID, but not be associated with any centres.

HEEDLS-NONE: Render custom logo only if user is linked to a centre.

---

DigitalLearningSolutions.Data.Tests/Helpers/EmailTestHelper.cs
DigitalLearningSolutions.Data.Tests/Helpers/UserTestHelper.cs
DigitalLearningSolutions.Data.Tests/Services/EmailServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/PasswordResetServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/UnlockServiceTests.cs
DigitalLearningSolutions.Data/Exceptions/EmailAddressNotFoundException.cs
DigitalLearningSolutions.Data/Exceptions/ResetPasswordInsertException.cs
DigitalLearningSolutions.Data/Mappers/AdminUserMap.cs
DigitalLearningSolutions.Data/Mappers/DelegateUserMap.cs
DigitalLearningSolutions.Data/Mappers/MapperHelper.cs
DigitalLearningSolutions.Data/Models/Email/Email.cs
DigitalLearningSolutions.Data/Models/User/AdminUser.cs
DigitalLearningSolutions.Data/Models/User/DelegateUser.cs
DigitalLearningSolutions.Data/Models/User/User.cs
DigitalLearningSolutions.Data/Services/ConfigService.cs
DigitalLearningSolutions.Data/Services/EmailService.cs
DigitalLearningSolutions.Data/Services/NotificationService.cs
DigitalLearningSolutions.Data/Services/PasswordResetService.cs
DigitalLearningSolutions.Data/Services/UserService.cs
DigitalLearningSolutions.Web.Tests/Controllers/ForgotPassword/ForgotPasswordControllerTests.cs
DigitalLearningSolutions.Web/Controllers/ForgotPasswordController.cs
DigitalLearningSolutions.Web/Startup.cs
DigitalLearningSolutions.Web/ViewModels/ForgotPassword/ForgotPasswordViewModel.cs
DigitalLearningSolutions.Web/Views/ForgotPassword/Confirm.cshtml
DigitalLearningSolutions.Web/Views/ForgotPassword/Index.cshtml

ForgotPassword controller has the post functionality implemented with some basic validation. This is hooked up to a new PasswordResetService that does most of the logic. A new basic UserService for getting AdminUsers or Delegates (Candidates) was introduced, as has an EmailService. 
Note that the NotificationService has been modified to now use the EmailService and has been sanity checked, but not properly tested.
Succeeded tests of:
- Manually tested IE11, Edge, Chrome, Firefox*
- Manually tested Chrome mobile view
- Manually tested No JS
- Tested with screen reader
- Ran all unit tests successfully.
*Firefox has a very old bug (see: https://bugzilla.mozilla.org/show_bug.cgi?id=308064 ) that prevents the error summary link from focusing on the input textbox as required by the NHS error …

HEEDLS-354 - Reset Password email sending implemented.

---

DigitalLearningSolutions.Web.IntegrationTests/AuthenticationTests.cs
DigitalLearningSolutions.Web/Controllers/LoginController.cs
DigitalLearningSolutions.Web/ViewModels/Login/LoginViewModel.cs
DigitalLearningSolutions.Web/Views/Login/Index.cshtml

The page at /Login now has a basic form for entering details, however the actual logging in functionality does not exist. The error display also has been implemented. Entering the username as "TestUsernameError" or "TestPasswordError" will prevent the automatic log in and allows the UI to display the appropriate errors. The "Remember Me" checkbox is also present, but is non-functional as that will also be dealt with in a different ticket.
Tested with:
- IE11, Edge, Chrome, Firefox
- Chrome mobile view
- No javascript
- With Screen Reader
- Ran all unit tests
There are a couple of things worth noting: 
- Keyboard Focus is not set to the Error Summary when it is first displayed.
- When using NV Access screen reader in Browse Mode, the visual/keyboard focus can differ from normal when …

HEEDLS-363 - Basic login form with error display created

---

DigitalLearningSolutions.Web/Views/ForgotPassword/Index.cshtml
DigitalLearningSolutions.Web/Views/Register/Index.cshtml

Added the Sign In and Register links between the Register and ForgotPassword pages and checked the existing ones on the Login page.
Checked that they display and work OK in Chrome/Firefox/IE and on Edge with no JS, and that there is no layout strangeness at mobile sizes.
ForgotPassword:
Register:

HEEDLS-352 Add Sign In/Register links between login pages

---

DigitalLearningSolutions.Data.Tests/Services/CentresServiceTests.cs
DigitalLearningSolutions.Data/Services/CentresService.cs
DigitalLearningSolutions.Web/Controllers/MyAccountController.cs
DigitalLearningSolutions.Web/Styles/myAccount/myAccount.scss
DigitalLearningSolutions.Web/ViewModels/MyAccount/MyAccountViewModel.cs
DigitalLearningSolutions.Web/Views/MyAccount/Index.cshtml

This creates the MyAccount page as specified on HEEDLS-344. It doesn't create any way to get to that page except by entering the URL directly, as one wasn't specified on the ticket and I assumed it was to be added later.

HEEDLS-344: Add 'My Account' page without details expandable

---

DigitalLearningSolutions.Web/Views/ForgotPassword/Index.cshtml
DigitalLearningSolutions.Web/Views/Login/Index.cshtml
DigitalLearningSolutions.Web/Views/Register/Index.cshtml

Added the button role to the links styled as buttons added between the Login, Register and Forgot Password screens. This makes screen readers read them out as buttons rather than links, matching their styling. Checked that they were read out as expected.

HEEDLS-352 Add the role button to links styled as buttons

---

DigitalLearningSolutions.Web/Views/ForgotPassword/Index.cshtml
DigitalLearningSolutions.Web/Views/MyAccount/Index.cshtml
DigitalLearningSolutions.Web/Views/Register/Index.cshtml
DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml

Replace "Sign in" with "Log in" and "Sign out" with "Log out" across the site.
I did not change the "Login" into "Log in" on the landing page, because this will be handled as part of HEEDLS-338.

HEEDLS-387: Use consistent wording for logging in and out across site.

---

DigitalLearningSolutions.Web/Controllers/FindYourCentreController.cs
DigitalLearningSolutions.Web/Controllers/LearningContentController.cs
DigitalLearningSolutions.Web/Controllers/PricingController.cs
DigitalLearningSolutions.Web/Styles/index.scss
DigitalLearningSolutions.Web/ViewComponents/BackLinkViewComponent.cs
DigitalLearningSolutions.Web/ViewModels/Common/BackLinkViewModel.cs
DigitalLearningSolutions.Web/ViewModels/LearningContent/LearningContentViewModel.cs
DigitalLearningSolutions.Web/Views/FindYourCentre/Index.cshtml
DigitalLearningSolutions.Web/Views/LearningContent/Index.cshtml
DigitalLearningSolutions.Web/Views/Pricing/Index.cshtml
DigitalLearningSolutions.Web/Views/Shared/Components/BackLink/Default.cshtml
DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml

Added several new controllers to display content from the old site in iframes. Added a view component for the nhsuk back link.
I've tested the responsive sizing of the iframe across a few browsers and with the chrome devtools devices. There is currently an issue that the size of the main nhsuk-width-container is 960px, the exact breakpoint for the old site, so we get the tablet(?) layouts in the iframe which have some slightly odd layout behaviour as you resize the window. We also currently have double margins (the main layout plus the margins in the iframe) which would ease some of this layout behaviour.
The FindYourCentre iframe content doesn't fully work with javascript off (tested in Edge), the GoogleMaps map doesn't load.
The screen reader gets into the iframe correctly, but we are …

Heedls 341 old content in iframes

---

DigitalLearningSolutions.Web/Controllers/MyAccountController.cs
DigitalLearningSolutions.Web/Styles/index.scss
DigitalLearningSolutions.Web/ViewModels/MyAccount/MyAccountViewModel.cs
DigitalLearningSolutions.Web/Views/MyAccount/Index.cshtml

Added an expandable container with basic account details in it populating them the same way as the existing fields from the basic version.
Checked that the contents of the page display/resize correctly in Chrome and with Chrome devices, and checked that it worked fine with Edge no javascript. Also checked that the screen reader was able to read out the contents of the expander.
Changed the way the email was being retrieved as the existing version didn't seem to work.

Heedls 391 add basic myaccount details

---

DigitalLearningSolutions.Web/Styles/index.scss
DigitalLearningSolutions.Web/Views/Pricing/Index.cshtml

Added the h1 to the pricing page and sorted out the resulting layout issues.
Checked that the layout works OK with Chrome devices.

HEEDLS-398 Add h1 to Pricing page

---

DigitalLearningSolutions.Data/Services/LoginService.cs
DigitalLearningSolutions.Data/Services/UserService.cs
DigitalLearningSolutions.Web.Tests/Controllers/Login/LoginControllerTests.cs
DigitalLearningSolutions.Web/Controllers/LoginController.cs
DigitalLearningSolutions.Web/Views/Login/Index.cshtml

Made changes to the Log in Index page so that the links to Privacy and Terms of Use now open in new tabs.
Also modified the log in controller to grab delegate accounts associated with an admin account if only the admin account specific log in was used. Similar logic was already set up for grabbing admin accounts from delegate specific login.
Tested:
- Ran all unit tests
- Manually tested different log ins
- Tested log in and link opening in chrome.

HEEDLS-339 - Fixed log in links and admin user id login.

---

DigitalLearningSolutions.Data/Services/FrameworkNotificationService.cs
DigitalLearningSolutions.Data/Services/NotificationService.cs
DigitalLearningSolutions.Data/Services/PasswordResetService.cs

Added an extra slash in the forgot password url if it isn't already there before appending the ResetPassword part of the path.
The port it being added because we are just using string interpolation on the UriBuilders rather than on UriBuilder.Uri. I've removed it from the password url by changing the string interpolation values.
I've checked elsewhere in the solution and there are also similar instances of this being done in the same way (UriBuilder in string interpolation) in the NotificationService and FrameworkNotificationService. I've not seen emails generated from those, but we may want to also update those to be using .Uri as well.
Checked that the url was correct in debug locally, i.e. this doesn't remove the port from localhost.
Ran all unit tests.

Heedls 406 fix forgot password email url

---

DigitalLearningSolutions.Web/Views/Pricing/Index.cshtml

Added a nhsuk-grid-column-full around the Pricing h1 so that there are the correct margins on mobile

HEEDLS-398 Add extra containing div to Pricing title

---

DigitalLearningSolutions.Web/Controllers/NotificationPreferencesController.cs
DigitalLearningSolutions.Web/Helpers/CustomClaimHelper.cs
DigitalLearningSolutions.Web/Helpers/UserTypes.cs
DigitalLearningSolutions.Web/Styles/myAccount/updateNotificationPreferences.scss
DigitalLearningSolutions.Web/ViewModels/MyAccount/NotificationPreferencesViewModel.cs
DigitalLearningSolutions.Web/ViewModels/MyAccount/UpdateNotificationPreferencesViewModel.cs
DigitalLearningSolutions.Web/Views/NotificationPreferences/Index.cshtml
DigitalLearningSolutions.Web/Views/NotificationPreferences/UpdateNotificationPreferences.cshtml
DigitalLearningSolutions.Web/Views/NotificationPreferences/_NotificationPreferenceExpander.cshtml
DigitalLearningSolutions.Web/Views/NotificationPreferences/_NotificationPreferenceList.cshtml

This partial review covers making the update notification preferences page accessible by user type. Currently no notification information is displayed, though it is fetched from the database.
Update 29/04/21: this is being expanded to a complete review for the frontend of this ticket

Heedls 349 edit notification preferences

---

DigitalLearningSolutions.Data/Services/NotificationPreferencesDataService.cs

The 'TRIM()' function used here isn't present in the version of SQL Server used for the UAT DB, and its predecessors can only trim spaces not arbitrary characters.

HEEDLS-346: move whitespace trimming from database to memory

---

DigitalLearningSolutions.Data.Tests/DataServices/CustomPromptsDataServiceTests.cs
DigitalLearningSolutions.Data.Tests/Models/CustomPromptTests.cs
DigitalLearningSolutions.Data.Tests/Services/CustomPromptsServiceTests.cs
DigitalLearningSolutions.Data/DataServices/CustomPromptsDataService.cs
DigitalLearningSolutions.Data/Models/CustomPrompts/CustomPrompt.cs
DigitalLearningSolutions.Data/Services/CustomPromptsService.cs

Changed the options returned from the CustomPromptsService from a nullable string to a List<string> and moved the DataService to the DataServices folder.
I've tried this against all centres in the database, and the only one that wasn't either successfully split or null (empty list) was centre ID 435 which has an F1Options with a single option in it. i.e. we shouldn't have any issues with unexpected characters not splitting

HEEDLS-426 Split the custom prompts option strings

---

DigitalLearningSolutions.Data.Tests/DataServices/CentresDataServiceTests.cs
DigitalLearningSolutions.Data/DataServices/CentresDataService.cs
DigitalLearningSolutions.Data/Models/Centre.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CentreConfigurationViewModel.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/Index.cshtml

Tested:
- Ran all unit tests
- Checked in Chrome, IE11, Firefox, Edge,
- Checked Mobile view/zoom/screenreader/no js
Screenshots of new expander on centre config page:

HEEDLS-376 - Centre manager details added to centre config page

---

DigitalLearningSolutions.Web/Attributes/AdminOnlyAttribute.cs
DigitalLearningSolutions.Web/Attributes/DelegateOnlyInaccessibleAttribute.cs
DigitalLearningSolutions.Web/Controllers/ApplicationSelectorController.cs
DigitalLearningSolutions.Web/Controllers/FindYourCentreController.cs
DigitalLearningSolutions.Web/Controllers/HomeController.cs
DigitalLearningSolutions.Web/Controllers/LearningContentController.cs
DigitalLearningSolutions.Web/Controllers/PricingController.cs

This is a partial review for HEEDLS-359 that covers the redirection of delegate-only accounts to the Learning Portal, but not changes to the navigation bar.

Heedls 359 application selector portal redirect

---

DigitalLearningSolutions.Web.Tests/Controllers/Login/LoginControllerTests.cs
DigitalLearningSolutions.Web/Controllers/LoginController.cs
DigitalLearningSolutions.Web/Startup.cs
DigitalLearningSolutions.Web/ViewModels/Login/LoginViewModel.cs
DigitalLearningSolutions.Web/Views/Login/Index.cshtml

This uses the returnUrl implementation from https://github.com/TechnologyEnhancedLearning/DLSV2/commit/78d49feed4ec0ce443ec9b51c3ef811be1a16de7
and passes it through the login process, including login failures and choosing a centre.

HEEDLS-421: redirect to former page when logging in

---

DigitalLearningSolutions.Web.Tests/ViewModels/FindYourCentre/FindYourCentreViewModelTests.cs
DigitalLearningSolutions.Web/Controllers/FindYourCentreController.cs
DigitalLearningSolutions.Web/ViewModels/FindYourCentre/FindYourCentreViewModel.cs
DigitalLearningSolutions.Web/Views/FindYourCentre/Index.cshtml

Passes through a centreid parameter on the Find Your Centre page to the iframe, so we can load it already focussed on a particular centre if necessary. This isn't the whole ticket but other tickets rely on this working, so I'm putting it up and getting it merged early.
Tested in Firefox, Chrome, Edge and IE

HEEDLS-400 Added optional centreid parameter to Find Your Centre page

---

DigitalLearningSolutions.Web/ServiceFilter/RedirectEmptySessionData.cs
DigitalLearningSolutions.Web/Views/Frameworks/Shared/_NavMenuItems.cshtml

There are a couple of places in code where we rely on actions with certain names existing on controllers in generic code (extensions, service filters etc.). ReSharper doesn't like us doing this because if those actions don't exist on a controller we might get a runtime error.
I've added comments suppressing those errors where they already exist in code because I got sick of seeing the squiggly lines in my IDE.
Tested by doing ordinary development with these changes for over a week, I'm just pushing it in case it's useful to anyone else.

HEEDLS-NONE Add comment suppressions to ReSharper errors

---

DigitalLearningSolutions.Data.Tests/Helpers/CustomPromptsTestHelper.cs
DigitalLearningSolutions.Data.Tests/Models/CustomPromptTests.cs
DigitalLearningSolutions.Data.Tests/Services/CustomPromptsServiceTests.cs
DigitalLearningSolutions.Data/Models/CustomPrompts/CentreCustomPromptsWithAnswers.cs
DigitalLearningSolutions.Data/Models/CustomPrompts/CustomPrompt.cs
DigitalLearningSolutions.Data/Models/CustomPrompts/CustomPromptWithAnswer.cs
DigitalLearningSolutions.Data/Services/CustomPromptsService.cs
DigitalLearningSolutions.Web.Tests/ViewModels/MyAccount/MyAccountViewModelTests.cs
DigitalLearningSolutions.Web/Controllers/MyAccountController.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/CentreConfigurationController.cs
DigitalLearningSolutions.Web/Styles/index.scss
DigitalLearningSolutions.Web/Styles/learningMenu/index.scss
DigitalLearningSolutions.Web/ViewModels/MyAccount/MyAccountViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CustomPromptManagementViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/DisplayRegistrationPromptsViewModel.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/Index.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/RegistrationPrompts.cshtml

Added a screen to display the currently set custom registration prompts and a new button link on the CentreConfiguration
Checked the layout works down to mobile. 
I've put a message in slack to confirm the text for the free text prompts, so will potentially have to update that.

Heedls 380 manage registration prompts

---

DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/RegistrationPrompts.cshtml

Added role="text" to the child div of the summary so that it is all read out in one go rather than as 2 separate elements. Added as visually hidden span so that when reading it out it doesn't sound like clicking the button is mandatory.

HEEDLS-380 Add role text to expander button contents

---

DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests.cs
DigitalLearningSolutions.Web/Views/NotificationPreferences/_NotificationPreferenceList.cshtml

Changed the dl element in the notification list that had no child dt/dd elements to a div. Style should still be the same as I've not changed the css classes.
Added Notification preferences pages to accessibility tests now they pass.
Checked the layout wasn't broken by this change and the expanders etc. still work.

HEEDLS-455 Change dl element with no dt children to a div

---

DigitalLearningSolutions.Web/Styles/index.scss
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CentreConfiguration/AddRegistrationPromptConfigureAnswersViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CentreConfiguration/EditRegistrationPromptViewModel.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/RegistrationPrompts/AddRegistrationPromptConfigureAnswers.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/RegistrationPrompts/EditRegistrationPrompt.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/RegistrationPrompts/_RegistrationPromptAnswerTable.cshtml

Bug fixes for 383. Remove buttons in the answer table are now vertically aligned, and I've added the 'Configured answers:' caption to the table for the Edit screen.

HEEDLS-383 Change spacing around buttons and add table caption

---

DigitalLearningSolutions.Data.Tests/DataServices/RegistrationDataServiceTests.cs

I had originally misdiagnosed the reason the test was failing: it wasn't because it couldn't delete the test user it was making; it was because a user with the same email and centre ID already existed! For some reason this made it throw an exception before the stored procedure returned - which would have given this away since it always returns -4 when a user already exists.
I've changed the centre ID used in the test and everything's dandy now.

HEEDLS-367 Changed centre id of RegistrationDataService test

---

DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/RegistrationPrompts/EditRegistrationPrompt.cshtml

Fixed the wrapping of long prompt names on the edit screen

HEEDLS-383 Fix wrapping for long prompt names

---

DigitalLearningSolutions.Web/Styles/trackingSystem/centreConfiguration.scss

Make the largest size that the centre configuration placeholder image can be 300 x 150px

HEEDLS-471 Make default size of the placeholder image smaller

---

DigitalLearningSolutions.Web.Tests/Helpers/CustomClaimHelperTests.cs
DigitalLearningSolutions.Web/Controllers/NotificationPreferencesController.cs
DigitalLearningSolutions.Web/Helpers/CustomClaimHelper.cs
DigitalLearningSolutions.Web/Helpers/CustomPolicies.cs

Modify GetCandidateId method to return null if the delegate id claim is 0, as the old site sets delegate id claim to 0 for admin-only users.
Refactor usage of GetClaimAsInt for LearnCandidateId into GetCandidateId.
Add a test. All tests are passing.

HEEDLS-481 Handle delegate id from old site claims

---

DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/RegistrationPrompts/AddRegistrationPromptConfigureAnswers.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/RegistrationPrompts/EditRegistrationPrompt.cshtml

Made the default action on enter on both the Edit Prompt and Add prompt configure answers screen Add prompt. This only gets triggered when an input is selected and enter is pressed. This is fine on the Add prompt screen as the Add Answer is only input.
For the Edit Prompt screen, this may cause some unexpected form posts if you hit enter when you have the Mandatory checkbox selected, but I think that is probably relatively unlikely compared to the fairly common behaviour to enter something in a textbox and hit enter to submit it.

HEEDLS-383 Make default action on enter Add prompt

---

DigitalLearningSolutions.Web/ViewComponents/SelectListViewComponent.cs
DigitalLearningSolutions.Web/ViewModels/Common/SelectListViewModel.cs
DigitalLearningSolutions.Web/Views/MyAccount/EditDetails.cshtml
DigitalLearningSolutions.Web/Views/Register/Index.cshtml
DigitalLearningSolutions.Web/Views/Register/LearnerInformation.cshtml
DigitalLearningSolutions.Web/Views/Shared/Components/SelectList/Default.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/RegistrationPrompts/AddRegistrationPromptSelectPrompt.cshtml

Fixes the bug reported by Jonathan on the ticket: "When registering, if you have an optional field with a specified list of options, once you've selected one you can't then unselect it and blank the field without going back a page and starting over."
Tested by going through the registration journey with a centre that has some mandatory and some optional select custom prompts, all were displayed and only the optional prompts could be deselected.

HEEDLS-367 Add option to select list view component to make default optional selectable

---

DigitalLearningSolutions.Data.Tests/TestHelpers/UserTestHelper.cs
DigitalLearningSolutions.Web.Tests/Controllers/Login/LoginControllerTests.cs
DigitalLearningSolutions.Web/Controllers/LoginController.cs

Changed the login method that was calling HttpContext.SignInAsync to await that and propagated up the async/awaits in the login controller and unit tests of it.
Ran all unit tests and did a quick sanity check that login still works.

HEEDLS-487 await SignInAsync in login POST

---

DigitalLearningSolutions.Web/Styles/trackingSystem/centreDashboard.scss
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Dashboard/_DashboardTopCardGroup.cshtml

Added a style nhsuk-card--not-clickable matching the nhsuk-card--clickable except it's hover properties so that the admin card looks the same as the other cards but has no hover/clickable properties

HEEDLS-482 Add style for non clickable card to look like clickable card

---

DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/RegistrationPrompts/RemoveRegistrationPrompt.cshtml

Moved the hidden input used to preserve the prompt name on failed validation of the checkbox inside the form tag.

HEEDLS-381 Move hidden input for prompt name inside form

---

DigitalLearningSolutions.Web/Views/MyAccount/EditDetails.cshtml
DigitalLearningSolutions.Web/Views/NotificationPreferences/Index.cshtml
DigitalLearningSolutions.Web/Views/NotificationPreferences/UpdateNotificationPreferences.cshtml

Refactored the html in the my account edit details screen and the 2 manage notification screens to fix the spacing before the back links. I've changed the html in the update notification preferences relatively significantly as VS was complaining about invalid html (legend inside div). This means that the page does look a bit different to before, but it now looks more like the rest of the pages in the system.
All the automated accessibility tests still pass + checked with chrome lighthouse for 100 rating on accessibility on the update notification page.

HEEDLS-525 Refactor my account views to fix inconsistent spacing

---

DigitalLearningSolutions.Data.Tests/DataServices/CourseDataServiceTests.cs
DigitalLearningSolutions.Data/DataServices/CourseDataService.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/AvailableTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/CompletedTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/CurrentTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/LearningPortalControllerTests.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/Available.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/Completed.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/Current.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/LearningPortalController.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/DashboardController.cs
DigitalLearningSolutions.Web/Startup.cs

HEEDLS-470 - Refactored CourseService into CourseDataService

---

DigitalLearningSolutions.Web/Scripts/learningPortal/available.ts
DigitalLearningSolutions.Web/Scripts/learningPortal/completed.ts
DigitalLearningSolutions.Web/Scripts/learningPortal/current.ts
DigitalLearningSolutions.Web/Scripts/searchSortAndPaginate/searchSortAndPaginate.ts
DigitalLearningSolutions.Web/Scripts/spec/searchSortAndPaginate.spec.ts
DigitalLearningSolutions.Web/Scripts/trackingSystem/centreAdministrators.ts
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Administrator/Index.cshtml

Added back a method to figure out an endpoint from the specified endpoint so that it works with the site hosted in a subdirectory.

HEEDLS-415 Fix path so it works with site hosted in subdirectory

---

DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/RegistrationPrompts/AddRegistrationPromptConfigureAnswers.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/RegistrationPrompts/AddRegistrationPromptSelectPrompt.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/RegistrationPrompts/BulkRegistrationPromptAnswers.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/RegistrationPrompts/EditRegistrationPrompt.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/RegistrationPrompts/Index.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/RegistrationPrompts/RemoveRegistrationPrompt.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/RegistrationPrompts/_CustomPromptExpander.cshtml

Changed all the pages in the manage registration prompt area to have approximately equal spacing between the h1 elements and the page content and the bottom of the content and the back link view component.

HEEDLS-524 Refactor prompt management pages for consistent spacing

---

DigitalLearningSolutions.Web/Views/ChangePassword/Index.cshtml

Changed the spacing after the h1 and before the back link to make it consistent with other pages.

HEEDLS-530 Fix spacing before back link on change password page

---

DigitalLearningSolutions.Web/Views/Register/LearnerInformation.cshtml
DigitalLearningSolutions.Web/Views/Register/Password.cshtml
DigitalLearningSolutions.Web/Views/Register/PersonalInformation.cshtml

Refactored the Registration journey pages to make spacing consistent:
Personal information - increased spacing after h1
Learner info - fixed spacing before back link
Password - fixed spacing before back link

HEEDLS-529 Fix back link spacing for Register journey pages

---

DigitalLearningSolutions.Web/Views/Register/Confirmation.cshtml

Google Lighthouse was complaining about having an h3 directly beneath an h1, so I've changed it to an h2. Hasn't had any effect on styling since that was all being set by the `nhsuk-warning-callout__label` class anyway.
Appearance before:
Appearance after:

HEEDLS-523 Changed h3 to h2 to not have out of order headings

---

DigitalLearningSolutions.Web/Scripts/searchSortAndPaginate/sort.ts
DigitalLearningSolutions.Web/Scripts/spec/sort.spec.ts

Round 2 with actually correct filter text. Should have checked more closely that they were actually working.

Heedls 415 admin page pagination

---

DigitalLearningSolutions.Data.Tests/DataServices/ActivityDataServiceTests.cs
DigitalLearningSolutions.Data.Tests/Helpers/DateHelperTests.cs
DigitalLearningSolutions.Data.Tests/Services/ActivityServiceTests.cs
DigitalLearningSolutions.Data/DataServices/ActivityDataService.cs
DigitalLearningSolutions.Data/Helpers/DateHelper.cs
DigitalLearningSolutions.Data/Models/TrackingSystem/MonthOfActivity.cs
DigitalLearningSolutions.Data/Services/ActivityService.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Reports/ReportsController.cs
DigitalLearningSolutions.Web/Startup.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Reports/ReportsViewModel.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Dashboard/_DashboardBottomCardGroup.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Reports/Index.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Reports/_ActivityTable.cshtml

I think it's probably the case that the reports want to be in an expandable, 12 months is a lot.

Heedls 459 usage stats report

---

DigitalLearningSolutions.Web/Styles/trackingSystem/centreConfiguration.scss

Ran all unit tests
Screen shot of new large-desktop size screen on centre config page for centre 121 (the centre used in the ticket's screen shot)

HEEDLS-534 - changed centre config image max sizes

---

DigitalLearningSolutions.Web/Styles/index.scss
DigitalLearningSolutions.Web/Styles/shared/cardWithButtons.scss
DigitalLearningSolutions.Web/Styles/shared/centreInfo.scss
DigitalLearningSolutions.Web/Views/Shared/Components/CentreContactInfo/Default.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateApprovals/_unapprovedDelegateExpandable.cshtml

Changed all usages of word-break: break-word to word-break: break-all
IE screens the ticket was raised for:

HEEDLS-542 Replace break-word with break-all

---

DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Ranking/Index.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Ranking/_RankingStandardUserTable.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Ranking/_RankingSuperAdminTable.cshtml

Increased the spacing between the table and the no activity text on the admin table. Also added aria-current to the highlighted row (which I think is the right attribute?)

HEEDLS-468 Increase spacing on admin table and add screen reader

---

DigitalLearningSolutions.Web/Styles/shared/searchableElements.scss
DigitalLearningSolutions.Web/Styles/trackingSystem/centreAdministrators.scss
DigitalLearningSolutions.Web/Views/Shared/SearchablePage/_Pagination.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Administrator/Index.cshtml

Changed the pagination to use divs instead of ul/li since the custom layout/styling needed container divs which weren't allowed in the ul element.
Fixed the highlighting on the previous page button
Improved the layout of the buttons on mobile - particularly on the admins page where the 3/4 column layout was making the problem worse. For the admin page I've increased the point at which the buttons collapse the arrows to below the text. Wasn't able to get the arrow on the Next button to push right properly, but it's probably close enough.
Desktop admins
Large tablet/small desktop admins (1024px)
Mobile admins
Large tablet/small desktop courses (1024px)

Heedls 522 fix pagination invalid html

---

DigitalLearningSolutions.Web/Views/ForgotPassword/Confirm.cshtml
DigitalLearningSolutions.Web/Views/Register/Confirmation.cshtml

Added 'Check your Junk folder if the email doesn't arrive.' to the reset password confirmation page and the register confirmation page.

HEEDLS-550 Add check junk mail text to confirmation pages

---

DigitalLearningSolutions.Data.Tests/Models/User/UserAccountSetTests.cs
DigitalLearningSolutions.Data.Tests/Services/UserServiceTests.cs
DigitalLearningSolutions.Data/Models/User/UserAccountSet.cs
DigitalLearningSolutions.Data/Services/UserService.cs
DigitalLearningSolutions.Web.Tests/Controllers/ChangePasswordControllerTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/Login/LoginControllerTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/MyAccount/MyAccountControllerTests.cs
DigitalLearningSolutions.Web/Controllers/ChangePasswordController.cs
DigitalLearningSolutions.Web/Controllers/MyAccountController.cs

Moved the validation of the password if it isn't null before the ModelState.IsValid check for both the ChangePassword and MyAccount EditDetails so that the user is shown the invalid current password error even if they also have other validation errors.

HEEDLS-350 Validate password if not null before ModelState validation

---

DigitalLearningSolutions.Web.Tests/Helpers/DisplayStringHelperTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/TrackingSystem/Centre/ContractDetailsViewModelTests.cs
DigitalLearningSolutions.Web/Helpers/DisplayStringHelper.cs

Changed the units on the byte string and removed the decimal place from the lower sizes.

HEEDLS-467 Change units and remove decimal place below gigabytes

---

DigitalLearningSolutions.Web/Styles/myAccount/notificationPreferences.scss
DigitalLearningSolutions.Web/Views/MyAccount/Index.cshtml
DigitalLearningSolutions.Web/Views/MyAccount/_AccountSummaryCard.cshtml
DigitalLearningSolutions.Web/Views/MyAccount/_BasicContentCard.cshtml
DigitalLearningSolutions.Web/Views/MyAccount/_MyDetailsCard.cshtml
DigitalLearningSolutions.Web/Views/NotificationPreferences/_NotificationPreferenceList.cshtml

My details as card and view notification preferences.
Notification preferences not as tags

Heedls 544 my account user feedback

---

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs

The different Count values in the course statistics were previously not restricted to candidates the specified centre. Now, the candidates should only count towards the Count values when the record's CentreID matches. This should correct some courses with the "AllCentres" flag from appearing to have more delegates taking the course then are at the centre.

HEEDLS-470 - Corrected course statistics count from query

---

DigitalLearningSolutions.Data.Tests/Services/RegistrationServiceTests.cs
DigitalLearningSolutions.Data/DataServices/RegistrationDataService.cs
DigitalLearningSolutions.Data/Models/Register/DelegateRegistrationModel.cs
DigitalLearningSolutions.Data/Models/Register/RegistrationModel.cs
DigitalLearningSolutions.Data/Services/RegistrationService.cs
DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests/RegistrationJourneyAccessibilityTests.cs
DigitalLearningSolutions.Web.AutomatedUiTests/TestHelpers/DriverHelper.cs
DigitalLearningSolutions.Web.Tests/Controllers/Register/RegisterDelegateByCentreControllerTests.cs
DigitalLearningSolutions.Web/Controllers/Register/RegisterDelegateByCentreController.cs
DigitalLearningSolutions.Web/Helpers/RegistrationMappingHelper.cs
DigitalLearningSolutions.Web/ViewModels/Register/RegisterDelegateByCentre/ConfirmationViewModel.cs
DigitalLearningSolutions.Web/ViewModels/RegisterDelegateByCentre/ConfirmationViewModel.cs
DigitalLearningSolutions.Web/Views/RegisterDelegateByCentre/Confirmation.cshtml

**Confirmation page (welcome email was SET)**
**Confirmation page (welcome email was NOT SET, password was NOT SET)**
**Confirmation page (welcome email was NOT SET, password was SET)**

HEEDLS-547 All delegates - register delegate - registration and confirmation

---

DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests.cs
DigitalLearningSolutions.Data/DataServices/UserDataService.cs
DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests/BasicAccessibilityTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/TrackingSystem/Delegates/AllDelegates/DelegateInfoViewModelTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/TrackingSystem/Delegates/AllDelegates/ViewDelegateViewModelTests.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/AllDelegatesController.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ViewDelegateController.cs
DigitalLearningSolutions.Web/Styles/trackingSystem/viewDelegate.scss
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CentreConfiguration/CentreConfigurationViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/DelegateInfoViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/SearchableDelegateViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/ViewDelegateViewModel.cs
DigitalLearningSolutions.Web/Views/MyAccount/_AccountSummaryCard.cshtml
DigitalLearningSolutions.Web/Views/MyAccount/_MyDetailsCard.cshtml
DigitalLearningSolutions.Web/Views/Shared/_CustomPromptSummaryListRow.cshtml
DigitalLearningSolutions.Web/Views/Shared/_SummaryFieldValue.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Dashboard/_DashboardCentreDetails.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/_CentreConfigurationCentreContentDetails.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/_CentreConfigurationCentreDetails.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CentreConfiguration/_CentreConfigurationCentreManagerDetails.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/AllDelegates/_SearchableDelegateCard.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ViewDelegate/Index.cshtml

HEEDLS-554 View delegate page - delegate info

---

DigitalLearningSolutions.Web/Controllers/ApplicationSelectorController.cs

A small bug fix - I changed the tracking system access to accept users who are User Admins, Centre Managers, or Centre Admins, rather than assuming that if a user is a Centre Admin they have those other permissions.

HEEDLS-558 Show tracking system to UserAdmin

---

DigitalLearningSolutions.Data.Tests/DataServices/CentresDataServiceTests.cs
DigitalLearningSolutions.Data/DataServices/CentresDataService.cs
DigitalLearningSolutions.Web/Controllers/Register/RegisterController.cs

Small fix - I added one line to exclude centres with kbSelfRegister=0 from the select options in the delegate self-registration journey.

HEEDLS-548 Exclude centres from self registration

---

DigitalLearningSolutions.Data.Migrations/202107221605_ChangeEmailMaxLengthOnAdminUsers.cs
DigitalLearningSolutions.Data.Migrations/202107221606_ChangeEmailMaxLengthOnAdminUsers.cs
DigitalLearningSolutions.Web/ViewModels/MyAccount/EditDetailsViewModel.cs
DigitalLearningSolutions.Web/ViewModels/Register/PersonalInformationViewModel.cs

[HEEDLS-557](https://softwiretech.atlassian.net/browse/HEEDLS-557)
I created a migration that changed the maximum length of the Email column on AdminUsers table from 250 to 255 characters, so it is consistent with the Candidates table. The migration also deletes and recreates the AdminUsers_Email index accordingly as it depends the Email column.
I also modified two view models so the form input for Email will have the same max length.
I will document these changes in the release notes after merge!

Heedls 557 email length consistency

---

DigitalLearningSolutions.Web.AutomatedUiTests/SeleniumServerFactory.cs

The issue we are experiencing is unexpected failures when running Automated UI tests, specifically when multiple pipelines are running at the same time. The exception raised is a failure to bind to the address `http://127.0.0.1:5000/` when starting the web host in `SeleniumServerFactory`.
We have four executors on a single Windows machine. When running the Automated UI tests, the address `http://127.0.0.1:5000/` is in use. When a second build comes onto that stage at the same time, it is unable to bind to the address and thus the second pipeline fails at that stage. This is the cause of the failure.
The proposed fix is to specify a url to use when creating the `WebHostBuilder`. The IP address chosen is `127.0.0.1` to be consistent with the previous configuration, but the port is set to …

HEEDLS-NONE Fix socket clashes when running UI tests for multiple builds simultaneously

---

DigitalLearningSolutions.Web/Styles/trackingSystem/viewDelegate.scss
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ViewDelegate/Index.cshtml

HEEDLS-493
Use `div`s with `card-filter-tag` to surround tags, in order to fix spacing issue
-----
I have:

HEEDLS-493 Fix tags spacing issue

---

DigitalLearningSolutions.Web/Views/Shared/Components/DateInput/Default.cshtml

HEEDLS-497
Make DateInput-VC year input shorter so the day/month/year inputs fit onto a single line.
-----
I have:

HEEDLS-497 Make DateInput VC year input shorter

---

DigitalLearningSolutions.Web/Scripts/trackingSystem/reports.ts
DigitalLearningSolutions.Web/Styles/trackingSystem/reports.scss

https://softwiretech.atlassian.net/browse/HEEDLS-458
The chartist chart was not displaying in IE. This turned out to be due to a problem parsing the data. However, once this problem was fixed it revealed that the label styling does not work in IE due to how it handles SVG text, rendering the labels illegible. After investigation, the solution adopted was to recreate as much of the styling as possible in JavaScript.
The solution has slight text alignment errors on tablet and desktop, and larger errors on mobile, but it was agreed with client in Show & Tell (30/07/21) that the use case of running IE in an extremely narrow window is marginal enough that it is not worth potentially significant development time to fix.
Rendering in IE should be specifically checked when future work is done on …

Heedls 458 Chartist IE issues

---

DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/EditAdminField.cshtml

[HEEDLS-437](https://softwiretech.atlassian.net/browse/HEEDLS-437)
Just a small wording change, replacing the word prompt with field to match the wireframe for the page.
-----
I have:

HEEDLS-437 Replace the word prompt with field in view

---

DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateGroups/_SearchableDelegateGroupCard.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-506
Add word break css to the delegate group cards to fix long names breaking the layout
-----
I have:

HEEDLS-506 Add word break to the delegate groups cards

---

DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/ManageCourse/_CourseSummaryCard.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/ManageCourse/_LearningPathwayDefaultsExpandable.cshtml

https://softwiretech.atlassian.net/secure/RapidBoard.jspa?rapidView=671&modal=detail&selectedIssue=HEEDLS-435
Updated a couple of course details displays to display a dash when null.
-----
I have:

HEEDLS-435 - Updated displays for nullable course details

---

DigitalLearningSolutions.Web.Tests/Controllers/ForgotPassword/ForgotPasswordControllerTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/MyAccount/MyAccountControllerTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Centre/Configuration/CentreConfigurationControllerTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Centre/Configuration/RegistrationPromptsControllerTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/CourseSetup/AdminFieldsControllerTests.cs
DigitalLearningSolutions.Web/Controllers/ForgotPasswordController.cs
DigitalLearningSolutions.Web/Controllers/MyAccountController.cs
DigitalLearningSolutions.Web/Controllers/Register/RegisterController.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Configuration/ConfigurationController.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Configuration/RegistrationPromptsController.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/CourseSetup/AdminFieldsController.cs

https://softwiretech.atlassian.net/browse/HEEDLS-531
Replaced any Redirects to the LearningSolutions Error page to be a StatusCodeResult(500). Looking through the individual cases, they all seemed to be random errors that occurred rather than forbidden or not found pages, so I only used StatusCodeResult(500)
N/A
-----
I have:

HEEDLS-531 - replaced all error redirects with StatusCodeResults

---

DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateGroups/_DelegateGroupsSideNavMenu.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-513
Added the word-break css class to the sidebar heading since it could contain long group names
-----
I have:

HEEDLS-513 Add word break class to sidebar heading

---

DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests/RegistrationJourneyAccessibilityTests.cs
DigitalLearningSolutions.Web.AutomatedUiTests/TestHelpers/DriverHelper.cs
DigitalLearningSolutions.Web.Tests/ControllerHelpers/DateValidatorTests.cs
DigitalLearningSolutions.Web/Controllers/Register/RegisterDelegateByCentreController.cs
DigitalLearningSolutions.Web/Helpers/DateValidator.cs
DigitalLearningSolutions.Web/Models/DelegateRegistrationByCentreData.cs
DigitalLearningSolutions.Web/Views/RegisterDelegateByCentre/WelcomeEmail.cshtml

[HEEDLS-497](https://softwiretech.atlassian.net/browse/HEEDLS-497)
Set default welcome email date to today's date (and should send by default).
Update DateValidator to accept today's date (previously only accepted dates in the future).
Modify relevant accessibility test to ignore the axe violation caused by aria-expanded on `#ShouldSendEmail` (nhs-tested component).
No visible frontend changes to see.
-----
I have:

HEEDLS-497 All delegates - register - welcome email default

---

DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Configuration/RegistrationPrompts/RemoveRegistrationPrompt.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/RemoveAdminField.cshtml

[HEEDLS-439](https://softwiretech.atlassian.net/browse/HEEDLS-439)
Just a small MR to change the title of the page to Delete course admin field and remove the word 'all' from the messages on the page so they make grammatical sense when there are only 2 responses, e.g. ‘and 2 admin responses’ rather than ‘and all 2 admin responses’. I have also changed this wording on the Remove registration prompts page to make it consistent.
Screenshot for wording change
-----
I have:

Heedls 439 remove course admin fields

---

DigitalLearningSolutions.Data/DataServices/GroupsDataService.cs

https://softwiretech.atlassian.net/browse/HEEDLS-516
Changed the course count on the group cards to match the query being used to get the courses for the Group Courses page - filtering to only course that have GroupCustomisations.InactivatedDate null, Customisations.Active true and Application.ArchivedDate null.
N/A
-----
I have:

HEEDLS-516 Change the course count on the group expanders

---

DigitalLearningSolutions.Web/Styles/index.scss
DigitalLearningSolutions.Web/Views/MyAccount/EditDetails.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Configuration/EditCentreDetails.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Configuration/RegistrationPrompts/AddRegistrationPromptConfigureAnswers.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Configuration/RegistrationPrompts/EditRegistrationPrompt.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/EditAdminField.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-488
Styled the hidden submits to not be hidden on IE, but pushed off the screen so that IE recognises it as the default button to hit when Enter is pressed. I've applied the change to anywhere the hidden-submit css class could be found, so if there are other areas that have been missed with unique classes, do let me know.
N/A
-----
I have:

HEEDLS-488 - implemented IE fix for hidden submit buttons

---

DigitalLearningSolutions.Web/Attributes/NoCachingAttribute.cs
DigitalLearningSolutions.Web/Attributes/NoStoreAttribute.cs
DigitalLearningSolutions.Web/Controllers/MyAccountController.cs
DigitalLearningSolutions.Web/Controllers/Register/RegisterAdminController.cs
DigitalLearningSolutions.Web/Controllers/Register/RegisterController.cs
DigitalLearningSolutions.Web/Controllers/Register/RegisterDelegateByCentreController.cs

https://softwiretech.atlassian.net/browse/HEEDLS-577
Add an ActionFilterAttribute to add Cache-Control 'no-store, max-age=0' headers to pages where the attribute is set against their action.
Note that this is likely to be overruled for some pages as there is some built in asp.net(?) functionality setting the header to no-store, no-cache on pages with forms. (I've made a note of this on the ticket too)
-----
I have:

HEEDLS-577 Add no store attribute for cache control

---

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Centre/SystemNotificationControllerTests.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/SystemNotificationsController.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/SystemNotifications/Index.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-519
Updated the SystemNotificationController so that the cookie set when first visiting the page (Show Later link no longer needs to be clicked, allowing the user to immediately return to the dashboard). Also deleted the cookie when no more unacknowledged notifications exist.
N/A
-----
I have:

HEEDLS-519 - Change system notification cookie management

---

DigitalLearningSolutions.Data.Migrations/202109080846_FixCompetencyIDFKConstraint.cs
DigitalLearningSolutions.Web/Styles/frameworks/frameworksShared.scss
DigitalLearningSolutions.Web/Views/Frameworks/Developer/AssessmentQuestionConfirm.cshtml
DigitalLearningSolutions.Web/Views/Frameworks/Developer/AssessmentQuestionLevelDescriptor.cshtml
DigitalLearningSolutions.Web/Views/Frameworks/Developer/AssessmentQuestionOptions.cshtml
DigitalLearningSolutions.Web/Views/Frameworks/Developer/AssessmentQuestionScoring.cshtml

DLSV2-301
DLSV2-301 adds back navigation to the assessment question flow.
DLSV2-300 Imports searchable css to the Frameworks scss to make sure styles for pagination etc are picked up in frameworks
DLSV2-299 Migration to fix broken constraint

DLSV2-301 Adds back navigation to the add/edit assessment question flow

---

DigitalLearningSolutions.Data/DataServices/RegistrationDataService.cs
DigitalLearningSolutions.Data/DataServices/UserDataService/DelegateUserDataService.cs
DigitalLearningSolutions.Data/Models/DelegateUpload/DelegateTableRow.cs
DigitalLearningSolutions.Data/Models/Register/DelegateRegistrationModel.cs
DigitalLearningSolutions.Data/Services/DelegateUploadFileService.cs
DigitalLearningSolutions.Web/Attributes/MaxFileSizeAttribute.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/BulkUploadController.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/UploadDelegatesViewModel.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/BulkUpload/StartUpload.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/BulkUpload/UploadCompleted.cshtml

[HEEDLS-505](https://softwiretech.atlassian.net/browse/HEEDLS-505)
- Checking 'send welcome email' reveals the datepicker pre-populated with today's date.
- File upload has a 5000KB limit.
- “File with update information” changed to “… updated information”.
- Potential errors are checked sequentially in correct order.
- Unexpected error message shown for single row update error instead of redirecting to 500.
- Unexpected error message shown for single row create error instead of redirecting to 500.
- AliasID is included when fetching existing delegate user, and in compariosn to check if update is needed.
- Correct singular/plural wording in Upload complete page.
**Note:**
- One of the bugs identified was that when registering a new delegate, if a value is too long it gets silently …

HEEDLS-505 All delegates - bulk upload journey - fix

---

DigitalLearningSolutions.Web/ViewComponents/CurrentFiltersViewComponent.cs

[HEEDLS-492](https://softwiretech.atlassian.net/browse/HEEDLS-492)
If a filter contains duplicate filter values, and we attempt to filter by one of those values, a 500 error is thrown. Fix it.
N/A
-----
I have:

HEEDLS-492 All delegates - Filter - fix 2

---

DigitalLearningSolutions.Data.Tests/Services/DelegateUploadFileServiceTests.cs
DigitalLearningSolutions.Data/Models/DelegateUpload/BulkUploadResult.cs
DigitalLearningSolutions.Data/Models/DelegateUpload/DelegateTableRow.cs
DigitalLearningSolutions.Web/Helpers/CommonValidationErrorMessages.cs
DigitalLearningSolutions.Web/ViewModels/ForgotPassword/ForgotPasswordViewModel.cs
DigitalLearningSolutions.Web/ViewModels/MyAccount/EditDetailsViewModel.cs
DigitalLearningSolutions.Web/ViewModels/Register/PersonalInformationViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/BulkUploadResultsViewModel.cs

[HEEDLS-505](https://softwiretech.atlassian.net/browse/HEEDLS-505)
- Add further validation and error messages:
- Length checks for FirstName, LastName, AliasId, Email, Answer1-6
- Email format check
- Identical to validation in normal registration, except Email maxlength here is 250 instead of 255 to match the stored procedure.
N/A
-----
I have:

HEEDLS-505 All delegates - Bulk upload journey - more validation

---

DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/BulkUploadResultsViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/UploadDelegatesViewModel.cs

[HEEDLS-505](https://softwiretech.atlassian.net/browse/HEEDLS-505)
- Change max filesize to 5MiB
- Use excel sheet header names in bulk upload error messages
N/A
-----
I have:

HEEDLS-505 All delegates - Bulk upload journey - fix 2

---

DigitalLearningSolutions.Web/Controllers/LearningContentController.cs
DigitalLearningSolutions.Web/Styles/index.scss
DigitalLearningSolutions.Web/ViewModels/LearningContent/LearningContentViewModel.cs
DigitalLearningSolutions.Web/Views/LearningContent/Index.cshtml

[HEEDLS-586](https://softwiretech.atlassian.net/browse/HEEDLS-586)
Added extra padding to iframes with long titles. Previously the "Terminology and classifications delivery service" page's iframe was running over the footer because its title goes onto a second line. I've added logic that checks if the page title is long, and if so, doubles the padding-bottom which makes the space between the iframe and the footer identical to those with shorter titles on desktop, with negligible differences on tablet and mobile. I also made the padding-bottom on all learning content iframes a bit wider as it looked a bit too close to me.
Iframe with long title:
Iframe with short title:
-----
I have:

HEEDLS-586 Add extra padding to iframes with long titles

---

DigitalLearningSolutions.Data.Migrations/202109201529_AddCompetencyGroupIdToCandidateAssessmentOptionalCompetencies.cs
DigitalLearningSolutions.Data.Tests/Services/SelfAssessmentServiceTests.cs
DigitalLearningSolutions.Data.Tests/TestHelpers/SelfAssessmentHelper.cs
DigitalLearningSolutions.Data/Models/SelfAssessments/Competency.cs
DigitalLearningSolutions.Data/Services/FrameworkService.cs
DigitalLearningSolutions.Data/Services/SelfAssessmentService.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs
DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/ManageOptionalCompetenciesViewModel.cs
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/ManageOptionalCompetencies.cshtml

DLSV2-331
Fixes issue with optional competencies where competency appears more than once in a self assessment.
Uses SelfAssessmentStructure.ID as unique identifier for selected optional competencies, rather than Competencies.ID (because a given competencies.ID can appear more than once in a self-assessment and is therefore not unique)

DLSV2-331 Fixes issue with optional competencies

---

DigitalLearningSolutions.Data.Migrations/202109221053_SelfAssessmentsAddUseDescriptionExpanders.cs
DigitalLearningSolutions.Data/Models/SelfAssessments/SelfAssessment.cs
DigitalLearningSolutions.Data/Services/SelfAssessmentService.cs
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentCompetency.cshtml

DLSV2-336
Makes expanders for competency descriptions optional per self-assessment.
- Migration to add UseDescriptionExpanders bit field to SelfAssessments table
- Reads new field into self assessment model / view model and interprets it in view

DLSV2-336 Makes expanders for competency descriptions optional per self-assessment

---

DigitalLearningSolutions.Data/Services/SelfAssessmentService.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/SelfAssessmentTests.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentCompetency.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml

DLSV2-333
- Adds expanders to the competency groups on the self-assessment overview page.
- Uses an optional competency group id parameter to auto expand the required competency group on load.
- Fixes issues with competency navigation layout and loading DLSV2-340.

DLSV2-333 Competency group expanders on overview page

---

DigitalLearningSolutions.Web/Styles/index.scss

[_HEEDLS-586_](https://softwiretech.atlassian.net/browse/HEEDLS-586)
Previously I added the class "responsive-iframe-wrapper-extra-padding" which doubled the padding-bottom on iframes with long titles, but this didn't account for medium length titles that break over two lines on mobile. I have now doubled the padding-bottom on all iframes which still looks like a suitable amount of spacing, and multiplied that by 1.5 for iframes with long titles. This way if an iframe has TitleIsLong = false, there will be enough spacing for the title to break over 2 lines, and for iframes with TitleIsLong = true,  there will be enough spacing for the title to break over 2 or 3 lines. Since adding extra adding causes the height of the iframe to decrease, I've adjusted it accordingly.
Long title on desktop …

HEEDLS-586 Adjust padding on iframes

---

DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests/DelegateUserDataServiceTests.cs
DigitalLearningSolutions.Data/DataServices/UserDataService/DelegateUserDataService.cs
DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs
DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/ViewDelegateControllerTests.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ViewDelegateController.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ViewDelegate/Index.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-499
The deactivate button on the view delegate page now deactivates the delegate account in question and refreshes the page.
No visual changes.
-----
I have:
- [] Updated/added documentation in Swiki and/or Readme.
- [] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.

Heedls 499 deactivate delegate

---

DigitalLearningSolutions.Web/Scripts/searchSortFilterAndPaginate/filter.ts
DigitalLearningSolutions.Web/Scripts/trackingSystem/emailDelegates.ts
DigitalLearningSolutions.Web/Styles/trackingSystem/delegates/emailDelegates.scss
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/EmailDelegates/_SearchableDelegateCheckbox.cshtml

[HEEDLS-585](https://softwiretech.atlassian.net/browse/HEEDLS-585)
- Fix JS bug: If I add a filter, and then go to add a different filter, but leave it on the default value of “Select [filter name]” and hit the Add Filter button then nothing happens as expected. However, I then cannot add any new filters until I clear all the filters.
- Word break for really long delegate checkbox labels
- Read out results count when selecting/deselect all
Word wrap:
-----
I have:

HEEDLS-585 All delegates - welcome emails - filter - fix

---

DigitalLearningSolutions.Web/Views/Supervisor/Shared/_AssessmentQuestionCells.cshtml

To allow them to wrap
DLSV2-352
Small fix to allow question column text to wrap to avoid squashing competency column.

DLSV2-352 Removes status-tag span class from questions

---

DigitalLearningSolutions.Data.Tests/DataServices/CourseAdminFieldsDataServiceTests.cs
DigitalLearningSolutions.Data.Tests/DataServices/CourseDataServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/CourseAdminFieldsServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/CourseServiceTests.cs
DigitalLearningSolutions.Data/DataServices/CourseAdminFieldsDataService.cs
DigitalLearningSolutions.Data/DataServices/CourseDataService.cs
DigitalLearningSolutions.Data/Services/CourseAdminFieldsService.cs
DigitalLearningSolutions.Data/Services/CourseService.cs
DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests/AddCourseAdminFieldsAccessibilityTests.cs
DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests/EditCourseAdminFieldsAccessibilityTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/CourseSetup/AdminFieldsControllerTests.cs
DigitalLearningSolutions.Web.Tests/ServiceFilter/VerifyAdminUserCanAccessCourseTests.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/CourseSetup/AdminFieldsController.cs
DigitalLearningSolutions.Web/Extensions/HtmlHelperExtensions.cs
DigitalLearningSolutions.Web/ServiceFilter/VerifyAdminUserCanAccessCourse.cs
DigitalLearningSolutions.Web/Startup.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/AddAdminFieldViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/AddBulkAdminFieldAnswersViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/AdminFieldAnswersViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/BulkAdminFieldAnswersViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/EditAdminFieldViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/RemoveAdminFieldViewModel.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/AddAdminField.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/AddBulkAdminFieldAnswers.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/BulkAdminFieldAnswers.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/EditAdminField.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/Index.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/RemoveAdminField.cshtml

[_HEEDLS-438_](https://softwiretech.atlassian.net/browse/HEEDLS-438)
Added a check in AdminFieldsController that verifies the user can access the selected course on the following pages: Manage admin fields, Edit admin field, Configure answers in bulk (in edit and add journeys), Remove admin field, and Add admin field. Only AdminUsers with the correct CentreID and CategoryID should be able to access these pages. This means that they have the same CentreID as the customisation, and either have the same CategoryID as the customisation's course category OR CategoryID = 0, which means they can manage all courses. If a customisationID that the user cannot access is entered in the url they should be directed to a NotFound page.
I also fixed the capitalization of the (ViewData["Title"]) on all …

HEEDLS-438 Fix user permissions for course admin fields pages

---

DigitalLearningSolutions.Data.Tests/Helpers/LinkedFieldHelperTests.cs
DigitalLearningSolutions.Data.Tests/Services/GroupServiceTests/GroupsServiceSynchroniseGroupsTests.cs
DigitalLearningSolutions.Data.Tests/Services/GroupServiceTests/GroupsServiceTests.cs
DigitalLearningSolutions.Data/Helpers/LinkedFieldHelper.cs
DigitalLearningSolutions.Data/Models/LinkedFieldChange.cs
DigitalLearningSolutions.Data/Services/GroupsService.cs

https://softwiretech.atlassian.net/browse/HEEDLS-556
Fixed the two bugs mentioned in the ticket.
The first (not being added/removed from group) was due to the group labels stored in the DB containing the prompt name for the example tested. The fix for this involves grabbing the prompt name and adding it to the answer given if the answer alone does not match the group label.
The second (progress record not being removed) was due to GroupDelegateRecords being deleted before they had a chance to be used in the RemoveProgress... query. Swapping the order in which these are performed resolves this.
N/A
-----
I have:

HEEDLS-556 - fix bugs in limit admin roles processing

---

DigitalLearningSolutions.Web/Controllers/ApplicationSelectorController.cs

https://softwiretech.atlassian.net/browse/HEEDLS-622
Changed the permissions on the Content Creator application selection from Centre manager to Content Creator. (also ran the formatter)
Checked that the card now only appears when AdminUsers.ContentCreator = 1.
N/A
-----
I have:

HEEDLS-622 Change content creator application selector permissions

---

DigitalLearningSolutions.Data/Helpers/ConfigHelper.cs
DigitalLearningSolutions.Web.Tests/Controllers/Support/SupportControllerTests.cs
DigitalLearningSolutions.Web/Controllers/Support/SupportController.cs
DigitalLearningSolutions.Web/ViewModels/Support/SupportViewModel.cs
DigitalLearningSolutions.Web/Views/Support/Shared/_SupportSideNavMenu.cshtml
DigitalLearningSolutions.Web/Views/Support/Support.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-624
Add links to the text of the support page, linking to the same place as the side nav menu items.
-----
I have:

HEEDLS-624 Add links that are the same as the side nav to support text

---

DigitalLearningSolutions.Data/Models/SelfAssessments/CurrentSelfAssessment.cs
DigitalLearningSolutions.Data/Services/SelfAssessmentService.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs
DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/VerificationPickSupervisorViewModel.cs
DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/VerificationSummaryViewModel.cs
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/VerificationPickResults.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/VerificationPickSupervisor.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/VerificationSummary.cshtml

DLSV2-368 and DLSV2-367
DLSV2-367 - Uses name of activity in place of "this activity" in sign-off request not available text
DLSV2-368 - Reads sign-off and verifier roles in for self-assessment and uses them in place of generic "supervisor" throughout sign-off and verification flows.

DLSV2-368 and DLSV2-367 Improved labelling in self assessment interface

---

DigitalLearningSolutions.Data.Migrations/202110121601_UpdateSelfAssessmentStructureOrdering.cs
DigitalLearningSolutions.Data.Tests/TestHelpers/SelfAssessmentHelper.cs
DigitalLearningSolutions.Data/Services/SelfAssessmentService.cs

DLSV2-368 DLSV2-369
DLSV2-368 Adds missing fields to service tests
DLSV2-369 Migration to update SelfAssessmentStructure Ordering where necessary (for entries created prior to ordering being added)

DLSV2-368 DLSV2-369 Fixes relating to broken tests from previous merge

---

DigitalLearningSolutions.Web/ViewComponents/SingleCheckboxViewComponent.cs
SQLScripts/20211103_SetUpDelegateGroupMember.sql

[HEEDLS-512](https://softwiretech.atlassian.net/browse/HEEDLS-512)
Got a 500 error when only checking the DeleteEnrolments checkbox on the delete group confirmation page. This was because we were trying to access index 0 of an empty list, I have added a check so that we skip that if the list is empty.
I also added the SQL script that sets up data for this ticket's tests.
Nothing has changed visually since the last review.
-----
I have:

Heedls 512 delete delegate group

---

DigitalLearningSolutions.Data/Models/SelfAssessments/CurrentSelfAssessment.cs
DigitalLearningSolutions.Data/Services/SelfAssessmentService.cs
DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/SelfAssessmentDescriptionViewModel.cs
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_OverviewTable.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/Shared/_AssessmentQuestionOverviewCells.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/Shared/_AssessmentQuestionStatusTag.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/Shared/_AssessmentQuestionResponse.cshtml

https://hee-dls.atlassian.net/browse/DLSV2-409
The following tweaks are required to the Learning Portal / Self Assessment / Overview view:
- In the “My Response” column, remove the “No response” default status (leave blank instead).
- Relabel the “My response” column header “Self-assessment”
- In the “Status” column, remove the status tags “Not started” and “Self assessed” and leave the column blank when the criteria for these statuses are met.
- Hide the “Status” column if SelfAssessments.SupervisorResultsReview = 0 for the current self assessment. 
- Relabel the “Status” column “Verification status”
How it should look after changes
-----
For a given self assessment check that:

DLSV2-409 Changes to Overview table My response and status columns

---

DigitalLearningSolutions.Data.Migrations/202111081225_ReduceGroupsGroupDescriptionLength.cs

https://softwiretech.atlassian.net/browse/HEEDLS-631
Migration to reduce the size of Groups.GroupDescription from nvarchar(max) to nvarchar(1000), truncating any values over this limit (there should hopefully still be none by the time this makes it live)
N/A
-----
I have:

HEEDLS-631 Add migration to reduce the GroupDescription column length

---

DigitalLearningSolutions.Web.Tests/ViewModels/TrackingSystem/Delegates/DelegateGroups/DelegateGroupsViewModelTests.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateGroupsController.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/DelegateGroups/DelegateGroupsViewModel.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateGroups/Index.cshtml

[https://softwiretech.atlassian.net/browse/HEEDLS-623](https://softwiretech.atlassian.net/browse/HEEDLS-623)
Add search by group label field to delegate groups page.
(Includes a non-Javascript version)
**Desktop**
**Desktop - No JS version**
**Tablet**
**Mobile**
-----
I have:

HEEDLS-623 Add search function to delegate groups

---

DigitalLearningSolutions.Data.Tests/Services/ActivityServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/CourseServiceTests.cs
DigitalLearningSolutions.Data/Services/ActivityService.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Reports/ReportsController.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Reports/EditFilters.cshtml

[_HEEDLS-541_](https://softwiretech.atlassian.net/browse/HEEDLS-541)
The start date is now stored in a hidden field in the view model so passed properly back on POST. The time component is also discarded when read from DB to avoid issues with picking the first day of data.
N/A
-----
I have:

HEEDLS-541 fix start date validation

---

DigitalLearningSolutions.Web/DigitalLearningSolutions.Web.csproj
DigitalLearningSolutions.Web/Scripts/checkboxes.ts
DigitalLearningSolutions.Web/Scripts/common.ts
DigitalLearningSolutions.Web/Scripts/learningPortal/selfAssessment.ts
DigitalLearningSolutions.Web/Scripts/learningPortal/verificationPickResults.ts
DigitalLearningSolutions.Web/Scripts/supervisor/verifyMultipleResults.ts
DigitalLearningSolutions.Web/Scripts/trackingSystem/editCourseContent.ts
DigitalLearningSolutions.Web/Scripts/trackingSystem/emailDelegates.ts

https://hee-dls.atlassian.net/browse/DLSV2-418
Move the code for selecting and deselecting checkboxes into a common location: checkboxes.ts.
-----
Class Checkboxes in checkboxes.ts provides two ways for selecting and deselecting checkboxes: by group or by selector (e.g. a css class). 
Checks:
Check that the right method is being invoked when using the library. If it's passing a class, should be using selectAll and deselectAll. If it's a group, should use selectAllInGroup, deselectAllinGroup. 
There are some special cases like emailDelegates.ts. Originally it was importing two methods from common.ts and selecting by class name. When emailDelegates.ts calls setUpSelectAndDeselectButtons(), that is a local implementation, not the one originally in common which was not being imported here. So …

DLSV2-418 Consolidate the two JS select-all methods into one TS file

---

DigitalLearningSolutions.Data/Services/SelfAssessmentService.cs

https://hee-dls.atlassian.net/browse/DLSV2-415
1. If a SelfAssessmentResult exists for the same candidate, assessment, result, competency and question, then update it with the new comment and dateTime. 
2. If it doesn't exist, insert a new one. 
3. If there are already not one but multiple results for the same candidate, assessment, result, competency and question, then update only the most recent.
-----
For a given candidate, assessment, competency and question, I have:

DLSV2-415 Prevent SelfAssessment result duplicate entries

---

DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/ManageCourse/Index.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateGroups/EditDescription.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateGroups/GroupDelegatesRemove.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateProgress/EditSupervisor.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ViewDelegate/ConfirmRemoveFromCourse.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ViewDelegate/Index.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-620
Adds the word-break css class to various elements to prevent long course, group or delegate names overflowing the layout
-----
I have:

HEEDLS-620 Add word-break to several h1 elements with dynamic content

---

DigitalLearningSolutions.Data.Migrations/202111231427_IncreaseSelfassessmentSignOffRequestorStatementLength.cs
DigitalLearningSolutions.Data.Migrations/202111231708_IncreaseSelfassessmentSignOffSupervisorStatementLength.cs

[DLSV2-424](https://hee-dls.atlassian.net/browse/DLSV2-424)
Added new migration to increase SignOffRequestorStatement and SignOffSupervisorStatement fields length from nvarchar(1000) to nvarchar(2000) on Selfassessment table
-----
I have:

Added new migration to increase length on self assessment tbl

---

DigitalLearningSolutions.Data.Migrations/202111241539_AddPrnToCandidateTable.cs

_HEEDLS-684_
Add a migration to add ProfessionalRegistrationNumber and HasBeenPromptedForPrn to the candidates table
-----
I have:

HEEDLS-684 add prn and hasBeenPromptedForPrn to candidates table

---

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/RequestSignOff.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/SignOffProfileAssessment.cshtml

[DLSV2-431](https://hee-dls.atlassian.net/browse/DLSV2-431)
Tiny tweak to allow html markup in sign-off label (delegate sign-off request) and hint text (supervisor sign-off)

DLSV2-431 Tweak to allow html in sign-off declarations

---

DigitalLearningSolutions.Data/Models/Supervisor/DelegateSelfAssessment.cs
DigitalLearningSolutions.Data/Services/SupervisorService.cs
DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs
DigitalLearningSolutions.Web/ViewModels/Supervisor/ReviewSelfAssessmentViewModel.cs
DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/Shared/_AssessmentQuestionCells.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/Shared/_AssessmentQuestionReviewCells.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/Shared/_AssessmentQuestionStatusTag.cshtml

https://hee-dls.atlassian.net/browse/DLSV2-428
Apply same changes requested in [DLSV2-409](https://hee-dls.atlassian.net/browse/DLSV2-409) to Supervisor / Review SelfAssessment.
Verification status displaying blank rather than in progress or not started. Learner response renamed as Self-assessment and status renamed as verification status.
-----
Check that:
- Changes in LearningPortal/Self Assessment/Overview view are now available in **Supervisor/ReviewSelfAssessment** view.
- Change the value of SupervisorResultsReview in SelfAssessment database table and verify that the column "Verfication status" on the view is visible for True and hidden for False.

DLSV2-428 Update supervisor interface to bring into line with DLSV2-409

---

DigitalLearningSolutions.Data/Services/ImportCompetenciesFromFileService.cs

[DLSV2-434](https://hee-dls.atlassian.net/browse/DLSV2-434)
Updates max framework competency group ID after insert to ensure count of inserted groups is accurate.

DLSV2-434 Updates max framework competency group ID after insert

---

DigitalLearningSolutions.Data/Services/SupervisorService.cs

[DLSV2-413](https://hee-dls.atlassian.net/browse/DLSV2-413)
Removes unnecessary and broken WHERE clauses from update service that were preventing storage of a rejected SelfAssessmentResultSupervisorVerification

DLSV2-429 Update SupervisorService to fix missing rejected status

---

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml

[DLSV2-425](https://hee-dls.atlassian.net/browse/DLSV2-425)
In self assessment overview, the wording of the statement provided explaining why Request sign-off is unavailable has been tweaked to indicate some competency assessment statements may be excluded.

DLSV2-425 Tweaks request sign-off unavailable to wording

---

DigitalLearningSolutions.Data.Tests/DataServices/CourseDataServiceTests.cs

[_HEEDLS-501_](https://softwiretech.atlassian.net/browse/HEEDLS-501)
Quick extension of the time to 500ms to make sure it passes even when run singly. 0.5s time difference should have no practical significance for the way the system is actually used.
N/A
-----
I have:

extend data service test timing to 500ms

---

DigitalLearningSolutions.Web/Views/Supervisor/AddMultipleSupervisorDelegates.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/DelegateProfileAssessments.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/EnrolDelegateOnProfileAssessment.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/EnrolDelegateSetCompleteBy.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/EnrolDelegateSummary.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/EnrolDelegateSupervisorRole.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/MyStaffList.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/ReviewCompetencySelfAsessment.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/SignOffHistory.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/SignOffProfileAssessment.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/VerifyMultipleResults.cshtml

[DLSV2-427](https://hee-dls.atlassian.net/browse/DLSV2-427)
Implements the previously missing backlinks to the breadcrumb navbar throughout the Supervisor interface for mobile layout fallback. These are a feature of the [NHS Design System Breadcrumb navigation](https://service-manual.nhs.uk/design-system/components/breadcrumbs) component.
-----
I have:
- [y ] Run the formatter and made sure there are no IDE errors.
- [ y] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ y] Updated my Jira ticket with information about other parts of the system that were …

DLSV2-427 Added mobile breadcrumb back links to Supervisor pages

---

DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/CourseDetails/CourseOptionsViewModel.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/ManageCourse/_CourseOptionsExpandable.cshtml

[https://softwiretech.atlassian.net/browse/HEEDLS-661](https://softwiretech.atlassian.net/browse/HEEDLS-661)
Hide diagnostic checkbox within course options, under course setup when the underlying application diagnostics is set to false.
Diagnostic checkbox is hidden when required:
-----
I have:

HEEDLS-661 Hide diagnostics on course setup

---

DigitalLearningSolutions.Web/Controllers/Register/RegisterController.cs

[https://softwiretech.atlassian.net/browse/HEEDLS-690](https://softwiretech.atlassian.net/browse/HEEDLS-690)
Added a check on the email validation to check that the centre id value is set as this value is required for the validation.
Correct model validation now present when no centre is selected:
-----
I have:

HEEDLS-690 Fix 500 error if centre not set in registration

---

DigitalLearningSolutions.Data.Migrations/202111261305_AddLearningHubAuthIdToCandidates.cs

[https://softwiretech.atlassian.net/browse/HEEDLS-679](https://softwiretech.atlassian.net/browse/HEEDLS-679)
Add a new LearningHubAuthId (int) column to the Candidates tables to store the LH Auth Id once DLS and LH accounts have been linked.
-----
I have:

HEEDLS-679 Add LearningHubAuthId column to candidates

---

DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs
DigitalLearningSolutions.Web/Views/Supervisor/EnrolDelegateOnProfileAssessment.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/EnrolDelegateSummary.cshtml

[DLSV2-449](https://hee-dls.atlassian.net/browse/DLSV2-449)
- If there are no profile assessments in the ViewModel, we display a message saying “No profile assessments are available for enrolment for this member of staff.” and remove the “Next” button.
- Also replaced references to "profile assessment" with "self assessment" in enrol flow.
- Implements validation on choose self-assessment screen.

Develop/fixes/DLSV2-449 Enrol on self assessment none available profile assessments better

---

DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateGroups/ConfirmDeleteGroup.cshtml

…and increase margin between group name and body on delete group confirmation page
[HEEDLS-512](https://softwiretech.atlassian.net/browse/HEEDLS-512)
Fixed the issue raised in testing where, on the delete group confirmation page, there was a large margin between the title and the group name and not much of one below the group name. I have increased the margin below the group name, but most of the margin below the title came from the `nhsuk-heading-xl` class which I don't want to remove or mess with, so that margin hasn't decreased by much. See the screenshots (and compare to the one on the ticket) for details.
Desktop:
Tablet:
Mobile:
-----
I have:

HEEDLS-512 Reduce margin between title and group name

---

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/CourseSetup/ManageCourseControllerTests.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/CourseSetup/ManageCourseController.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/CourseDetails/EditCourseDetailsFormData.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/ManageCourse/EditCourseDetails.cshtml

[_HEEDLS-444_](https://softwiretech.atlassian.net/browse/HEEDLS-444)
Sorted out some confusion I had about course names - the Application name is now displayed under course name, and the editable box edits the Customisation name as it should be.
The only UI change is that I shifted the course name input box over because the Application names tend to be long, and usually split onto a second line with a smaller width to the column
This is the previous column width. I thought this looked a bit weird, but shout if you prefer it:
-----
I have:

HEEDLS-444 Fix course name

---

DigitalLearningSolutions.Data.Tests/Services/ActionPlanServiceTests.cs
DigitalLearningSolutions.Data/ApiClients/LearningHubApiClient.cs
DigitalLearningSolutions.Data/Models/External/LearningHubApiClient/BulkResourceReferences.cs
DigitalLearningSolutions.Data/Models/External/LearningHubApiClient/Catalogue.cs
DigitalLearningSolutions.Data/Models/External/LearningHubApiClient/ResourceMetadata.cs
DigitalLearningSolutions.Data/Models/External/LearningHubApiClient/ResourceReference.cs
DigitalLearningSolutions.Data/Models/External/LearningHubApiClient/ResourceReferenceWithResourceDetails.cs
DigitalLearningSolutions.Data/Models/External/LearningHubApiClient/ResourceSearchResult.cs
DigitalLearningSolutions.Data/Models/LearningResources/ActionPlanItem.cs

https://softwiretech.atlassian.net/browse/HEEDLS-701
Moved the LearningHubApiClient models into the Models/External folder
N/A
-----
I have:

HEEDLS-701 Move LearningHubApiClient models into External folder

---

DigitalLearningSolutions.Data/Services/FrameworkService.cs

[DLSV2-451](https://hee-dls.atlassian.net/browse/DLSV2-451)
Adds missing assessment question fields to dapper query to populate competency preview comments custom prompt and hint text.

DLSV2-451 Fixes competency preview comments prompt and hint

---

DigitalLearningSolutions.Data/Services/FrameworkService.cs

DLSV2-452
Adds missing ORDER BY clause to query returning competency assessment questions for competency preview.

DLSV2-452 Fixes competency preview assessment question ordering

---

DigitalLearningSolutions.Web/Views/LearningPortal/Current/Current.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/Current/CurrentCourseCard/_CurrentCourseCard.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/Current/_CurrentLearningResourceCard.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_SelfAssessmentCard.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/Shared/_Dates.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-659
Minor changes to the buttons and Banner text on the Current page to make it more accessible.
N/A
-----
I have:

HEEDLS-659 - fix accessibility issues on Current page and cards

---

DigitalLearningSolutions.Data.Tests/TestHelpers/UserTestHelper.cs
DigitalLearningSolutions.Data/DataServices/UserDataService/DelegateUserDataService.cs
DigitalLearningSolutions.Data/Models/User/DelegateUser.cs
DigitalLearningSolutions.Web.Tests/ViewModels/MyAccount/MyAccountViewModelTests.cs
DigitalLearningSolutions.Web/ViewModels/MyAccount/MyAccountViewModel.cs
DigitalLearningSolutions.Web/Views/MyAccount/_MyDetailsCard.cshtml

_HEEDLS-685_(https://softwiretech.atlassian.net/jira/software/c/projects/HEEDLS/boards/671?modal=detail&selectedIssue=HEEDLS-685&assignee=6065c334b30f0d00704264d4)
Add the professional registration number to the my account page. 
- Shows "Not yet registered" if they have not yet been asked for their PRN. 
- "Not professionally registered" if they have been asked for their PRN but it is null
- And the professional registration number if they have been asked for and provided one
-----
I have:

HEEDLS-685 show professional registration number on My Account page

---

DigitalLearningSolutions.Data.Tests/Services/ActionPlanServiceTests.cs
DigitalLearningSolutions.Data/Services/ActionPlanService.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/CurrentTests.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/Current.cs

https://softwiretech.atlassian.net/browse/HEEDLS-671
In 671 I mistakenly removed a Signposting config check from a method that it should not have been removed from. This MR adds the check back.
N/A
-----
I have:

HEEDLS-671 - disable resource retrieval when signposting disabled

---

DigitalLearningSolutions.Data.Migrations/202112141120_AddLearningResourceReferencesTable.cs
DigitalLearningSolutions.Data.Migrations/202112141159_AlterTablesToUseLearningResourceReferences.cs
DigitalLearningSolutions.Data.Tests/DataServices/CompetencyLearningResourcesDataServiceTests.cs
DigitalLearningSolutions.Data.Tests/DataServices/LearningLogItemsDataServiceTests.cs
DigitalLearningSolutions.Data.Tests/DataServices/LearningResourceReferenceDataServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/ActionPlanServiceTests.cs
DigitalLearningSolutions.Data.Tests/TestHelpers/CompetencyLearningResourcesTestHelper.cs
DigitalLearningSolutions.Data.Tests/TestHelpers/LearningLogItemsTestHelper.cs
DigitalLearningSolutions.Data/DataServices/CompetencyLearningResourcesDataService.cs
DigitalLearningSolutions.Data/DataServices/LearningLogItemsDataService.cs
DigitalLearningSolutions.Data/DataServices/LearningResourceReferenceDataService.cs
DigitalLearningSolutions.Data/Models/LearningResources/CompetencyLearningResource.cs
DigitalLearningSolutions.Data/Models/LearningResources/LearningLogItem.cs
DigitalLearningSolutions.Data/Services/ActionPlanService.cs
DigitalLearningSolutions.Web/Startup.cs

https://softwiretech.atlassian.net/browse/HEEDLS-706
2 migrations to add the new LearningResourceReferences table, and update related tables to use this new table.
Refactoring of the data services and calling code that use these tables.
I've refactored the AddToActionPlan method despite it currently being uncalled from the front end here. I think the logic there is now correct, but it is probably subject to change when I get around to actually calling it in 648/652
N/A
-----
I have:

Heedls 706 refactor competency resource links

---

DigitalLearningSolutions.Web/Startup.cs

https://softwiretech.atlassian.net/browse/HEEDLS-698
Fix lost view location preventing old Filtered pages from finding the self assessment layout
Page now loads again:
-----
I have:

HEEDLS-698 Fix lost view location so old filtered views can find layout

---

DigitalLearningSolutions.Data.Migrations/202112170755_CompetenciesAlwaysShowDescription.cs
DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs
DigitalLearningSolutions.Data/Models/SelfAssessments/Competency.cs
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentCompetency.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_OverviewTable.cshtml

DLSV2-454
Adds option to make competency description visible on the SelfAssessmentOverview table
This is decided per competency option, by a new flag “AlwaysShowDescription” on the competencies table.
We read the flag into the competency model and page ViewModel. If it is true, we display the competency description below the competency name on the SelfAssessmentOverview table and in the competency review screen.

DLSV2-454 competencies always show description

---

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_OverviewTable.cshtml

[DLSV2-465](https://hee-dls.atlassian.net/browse/DLSV2-465)
Removes duplicated heading within competency group expander on the overview page:

DLSV2-465 Removes duplicated heading within expander

---

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentCompetency.cshtml

[DLSV2-472](https://hee-dls.atlassian.net/browse/DLSV2-472)
Adds a conditional warning to the self assessment competency view to tell user that their result has been verified and that changing it will cause their verification to be reset.

DLSV2-472 Adds verified result warning to self assessment questions

---

DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/Index.cshtml

[https://softwiretech.atlassian.net/browse/HEEDLS-640](https://softwiretech.atlassian.net/browse/HEEDLS-640)
The work done for HEEDLS-640 required an "Add" button be placed to the right of the title.
This was missed from the original work.
This PR addresses that by adding the button.
**Desktop**
**Mobile**
-----
I have:

HEEDLS-640 Super Admin Centres - Add missing Add Button

---

DigitalLearningSolutions.Data.Migrations/202201111458_LearningResourceReferencesOriginalRatingField.cs

[DLSV2-471](https://hee-dls.atlassian.net/browse/DLSV2-471)
Migration to add OriginalRating field to LearningResourceReferences table. This will be populated when creating new LearningResourceReferences records and used as a fallback value if the Learning Bub API is unavailable.

DLSV2-471 Migration to add OriginalRating field

---

DigitalLearningSolutions.Data/Services/FrameworkService.cs

[DLSV2-468](https://hee-dls.atlassian.net/browse/DLSV2-468)
Fixes error with adding framework default question where the framework contains multiple FrameworkCompetencies with the same CompetencyID. This is achieved by selecting **DISTINCT** CompetencyID in the insert query. The query already ignores any competencies that already have the assessment question associated so the initial suspicions about the cause of the error were a red herring.

DLSV2-468 Fixes error with adding framework default question

---

Jenkinsfile

Added line to Jenkinsfile to pull in LH API key from Jenkins credentials.
Also fixed some whitespace in the file.
-----
I have:
- [Swiki Secrets in Jenkins section](https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/19902234654/Secret+config+settings#Secrets-in-Jenkins)

Heedls add learning hub api key to jenkins

---

DigitalLearningSolutions.Data.Tests/DataServices/CompetencyLearningResourcesDataServiceTests.cs
DigitalLearningSolutions.Data.Tests/DigitalLearningSolutions.Data.Tests.csproj
DigitalLearningSolutions.Data.Tests/Extensions/EnumerableExtensionsTests.cs
DigitalLearningSolutions.Data.Tests/Services/RecommendedLearningServiceTests.cs
DigitalLearningSolutions.Data.Tests/TestHelpers/CompetencyLearningResourcesTestHelper.cs
DigitalLearningSolutions.Data/DataServices/CompetencyLearningResourcesDataService.cs
DigitalLearningSolutions.Data/Extensions/EnumerableExtensions.cs
DigitalLearningSolutions.Data/Models/SelfAssessments/CompetencyResourceAssessmentQuestionParameter.cs
DigitalLearningSolutions.Data/Services/RecommendedLearningService.cs

https://softwiretech.atlassian.net/browse/HEEDLS-711
Filtering of resources where the delegate answer falls outside the range of results specified in CompetencyResourceAssessmentQuestionParameters. Refactored and added new unit tests to accommodate these changes.
-----
I have:

Heedls 711 filter results outside range

---

DigitalLearningSolutions.Data.Migrations/202201111021_ChangeCompetencyAssessmentQuestionRoleRequirementsPrimaryKey.cs
DigitalLearningSolutions.Data.Migrations/202201120821_ChangeUniqueConstraintsOnCompetencyAssessmentQuestionRoleRequirements.cs
DigitalLearningSolutions.Data.Migrations/202201171115_UndoPreviousConstraintMigrationsForCompetencyAssessmentQuestionRoleRequirements.cs
DigitalLearningSolutions.Data.Migrations/202201171130_AddUniqueConstraintToCompetencyAssessmentQuestionRoleRequirements.cs
DigitalLearningSolutions.Data.Migrations/202217011130_AddUniqueConstraintToCompetencyAssessmentQuestionRoleRequirements.cs
DigitalLearningSolutions.Web.AutomatedUiTests/SeleniumServerFactory.cs

https://softwiretech.atlassian.net/browse/HEEDLS-741
Created two new migrations, one to undo the previous constraint-introducing migrations (depending on the state the DB is in), and one to add the new unique constraint.
I also commented out the previous migrations to prevent them from causing more errors when migrating past them. The "Undo" migration takes this into account.
I also modified one of the automated test files, as the set up of a fake server was causing errors when it tried to migrate up as it didn't have a config file to take a connection string from. I suspect it could probably be made more efficient in future.
N/A
-----
I have:

Heedls 741 fix migrations for competency assessment question role requirements constraints

---

DigitalLearningSolutions.Data/Models/BaseSearchableItem.cs
DigitalLearningSolutions.Data/Models/User/DelegateUser.cs
DigitalLearningSolutions.Web.Tests/Helpers/GenericSearchHelperTests/AllDelegatesSearchTests.cs
DigitalLearningSolutions.Web.Tests/Helpers/GenericSearchHelperTests/CoursesSearchTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/Support/FaqsPageViewModelTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/Support/SearchableFaqTests.cs
DigitalLearningSolutions.Web/Helpers/GenericSearchHelper.cs
DigitalLearningSolutions.Web/Scripts/trackingSystem/allDelegates.ts
DigitalLearningSolutions.Web/ViewModels/Support/Faqs/SearchableFaq.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/AllDelegates/_SearchableDelegateCard.cshtml

[https://softwiretech.atlassian.net/browse/HEEDLS-691](https://softwiretech.atlassian.net/browse/HEEDLS-691)
Add the ability to search all delegates by their candidate number as well as their name.
This adds the ability to search across multiple properties on a model.
A slight refactor of the first version of this concept which affects support FAQs.
-----
I have:

Heedls 691 search all delegates candidate number

---

DigitalLearningSolutions.Web/Styles/shared/searchableElements/itemsPerPage.scss

[https://softwiretech.atlassian.net/browse/HEEDLS-536](https://softwiretech.atlassian.net/browse/HEEDLS-536)
Fix the missing right border on the "select items per page" dropdown.
**JS Enabled**
**JS Disabled**
-----
I have:

HEEDLS-536 Custom items per page - css fix

---

DigitalLearningSolutions.Data/DataServices/CompetencyLearningResourcesDataService.cs
DigitalLearningSolutions.Web/Controllers/FrameworksController/Signposting.cs
DigitalLearningSolutions.Web/ViewModels/Frameworks/CompetencyResourceSummaryViewModel.cs
DigitalLearningSolutions.Web/Views/Frameworks/Developer/AddCompetencyLearningResourceSummary.cshtml
DigitalLearningSolutions.Web/Views/Frameworks/Developer/_SignpostingResourceCard.cshtml

Store description, link, catalogue, resource type and rating to LearningResourceReferences when inserting a record.
https://hee-dls.atlassian.net/browse/DLSV2-469
-----
In Frameworks, Framework Structure
- Manage resource signposting
- Add resource
- Search for "test"
- Select one resource
Check that:
- Parameters can be created after adding a learning resource reference.
- The application does not attempt insert duplicates in LearningResourceReferences.
- The foreign key on table CompetencyLearningResources is correctly set for existing a newly created LearningResourceReferences.
- Html markup returned by LH api is not being inserted into LearningResourceReferences original description.

DLSV2-469 Store additional fields in LearningResourceReferences

---

DigitalLearningSolutions.Data.Tests/DataServices/CompetencyLearningResourcesDataServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/ActionPlanServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/RecommendedLearningServiceTests.cs
DigitalLearningSolutions.Data.Tests/TestHelpers/CompetencyLearningResourcesTestHelper.cs
DigitalLearningSolutions.Data/DataServices/CompetencyLearningResourcesDataService.cs
DigitalLearningSolutions.Data/Services/ActionPlanService.cs
DigitalLearningSolutions.Data/Services/RecommendedLearningService.cs

https://softwiretech.atlassian.net/browse/HEEDLS-749
Prevented Removed CompetencyLearningResources from being used in the resource recommendation algorithm. Also prevented them from being extracted when adding a resource to learning log items.
N/A - all backend
-----
I have:

HEEDLS-749 - Exclude removed competency learning resources

---

DigitalLearningSolutions.Web.Tests/Controllers/Support/SupportTicketsControllerTests.cs
DigitalLearningSolutions.Web/Attributes/SetDlsSubApplicationAttribute.cs
DigitalLearningSolutions.Web/Controllers/Support/SupportTicketsController.cs

_[HEEDLS-608](https://softwiretech.atlassian.net/browse/HEEDLS-608)_
The SubApplication validation attribute has now been implemented on the Support Tickets controller, resolving the Support-specific test failures. The SetDlsSubApplication attribute has been modified to prevent it throwing when given an unfamiliar application.
N/A
-----
I have:

Heedls 608a implement on support page

---

DigitalLearningSolutions.Web/Views/Signposting/LearningHubLoginWarning.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-709
Changed the tab title and added role=link to the launch resource button so that it as announced as a link.
N/A - no visual changes made
-----
I have:

HEEDLS-709 - change tab title and button role

---

DigitalLearningSolutions.Data/Services/FrameworkService.cs

Ignore removed competency learning resources in "Manage resource signposting" resource count.
https://hee-dls.atlassian.net/browse/DLSV2-488
Added a filter in FrameworkService sql query to ignore competency learning resources that are soft deleted in table CompetencyLearningResources.
-----
- Checked with hard deleted resources: delete a resource without parameters or logs.
- Checked with soft deleted resources: delete a resource with parameter.

DLSV2-488 Ignore removed competency learning resources in manage resource signposting count

---

DigitalLearningSolutions.Data/Models/Frameworks/CompetencyResourceAssessmentQuestionParameter.cs
DigitalLearningSolutions.Data/Services/FrameworkService.cs
DigitalLearningSolutions.Web/Controllers/FrameworksController/Signposting.cs
DigitalLearningSolutions.Web/Models/SessionCompetencyLearningResourceSignpostingParameter.cs
DigitalLearningSolutions.Web/ViewModels/Frameworks/SignpostingCardViewModel.cs
DigitalLearningSolutions.Web/Views/Frameworks/Developer/EditCompetencyLearningResources.cshtml
DigitalLearningSolutions.Web/Views/Frameworks/Developer/_SignpostingCard.cshtml

https://hee-dls.atlassian.net/browse/DLSV2-477
When listing competency resources, also call learning hub api to ensure it has up-to-date information in the database about the resource. If the api is unavailable, use database information. 
Other related data like e.g. parameters are always stored in database, so api is used to override some resource fields likely to change as name or description.
Switch application, go to Frameworks, Framework Structure and click on "Manage resource signposting".
-----
- Checked that Learning Hub api "is unavailable" warning message is in place when no internet connection.
- Checked that data retrieved in Swagger overrides database data for resources.
- Checked that unmatched resource is in place: add a record in LearningResourceReferences for …

DLSV2-477 Learning Hub api to populate EditCompetencyLearningResources view

---

DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests/DelegateUserDataServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/RegistrationServiceTests.cs
DigitalLearningSolutions.Data/DataServices/UserDataService/DelegateUserDataService.cs
DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs
DigitalLearningSolutions.Data/Services/RegistrationService.cs
DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests/RegistrationJourneyAccessibilityTests.cs
DigitalLearningSolutions.Web.AutomatedUiTests/TestHelpers/DriverHelper.cs
DigitalLearningSolutions.Web.Tests/Controllers/Register/RegisterControllerTests.cs
DigitalLearningSolutions.Web/Controllers/Register/RegisterController.cs
DigitalLearningSolutions.Web/Models/DelegateRegistrationData.cs
DigitalLearningSolutions.Web/ViewModels/Common/IEditProfessionalRegistrationNumbers.cs
DigitalLearningSolutions.Web/ViewModels/MyAccount/MyAccountEditDetailsFormData.cs
DigitalLearningSolutions.Web/ViewModels/Register/LearnerInformationViewModel.cs
DigitalLearningSolutions.Web/ViewModels/Register/SummaryViewModel.cs
DigitalLearningSolutions.Web/Views/Register/LearnerInformation.cshtml
DigitalLearningSolutions.Web/Views/Register/Summary.cshtml
DigitalLearningSolutions.Web/Views/Shared/_EditRegistrationNumber.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-687
Added the PRN fields to the Learner Information page of the delegate self registration journey by moving the partial created for the My Account Edit Details page to a shared location and using that. 
Added an entry for this new value in the Summary view
Updated the service logic to make a call to save the provided value rather than updating the register candidate stored procedure.
-----
I have:

Heedls 687 self registration prn

---

DigitalLearningSolutions.Web.Tests/Helpers/ProfessionalRegistrationNumberHelperTests.cs
DigitalLearningSolutions.Web/Helpers/ProfessionalRegistrationNumberHelper.cs

_HEEDLS-XXXX_
Fixed the error message for invalid characters in PRNs
-----
I have:

HEEDLS-687 Fix error message for invalid characters

---

DigitalLearningSolutions.Web/Views/LearningPortal/Completed/CompletedActionPlanResourceCard/_CompletedActionPlanResourceCard.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/Current/_CurrentLearningResourceCard.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-747
Small adjustments to the margins and padding so closed resource cards for deleted resources have reduced space.
-----
I have:

HEEDLS-747 - change padding and margin on deleted resource cards

---

DigitalLearningSolutions.Web/ViewModels/Support/Faqs/FaqsPageViewModel.cs

[https://softwiretech.atlassian.net/browse/HEEDLS-520](https://softwiretech.atlassian.net/browse/HEEDLS-520)
Reverse the previous change made to the cutoff score for searching FAQs with FuzzySharp.
-----
I have:

HEEDLS-520 FAQ search - reverse cutoff score change

---

DigitalLearningSolutions.Data.Tests/Services/UnlockServiceTests.cs
DigitalLearningSolutions.Data/Exceptions/ConfigValueMissingException.cs
DigitalLearningSolutions.Data/Services/NotificationService.cs

[_HEEDLS-595_](https://softwiretech.atlassian.net/jira/software/c/projects/HEEDLS/boards/671?modal=detail&selectedIssue=HEEDLS-595&assignee=6065c334b30f0d00704264d4)
little change to get the url from the config rather than the database, throw an error if what's returned is empty rather than null
-----
I have:

HEEDLS-595 test fail, fix email urls

---

DigitalLearningSolutions.Data/Services/LearningHubLinkService.cs
DigitalLearningSolutions.Web/Views/SignpostingSso/LinkLearningHubSso.cshtml

_[HEEDLS-678](https://softwiretech.atlassian.net/browse/HEEDLS-678)_
A fix to the signposting link and the encoding of the login hash.
N/A
-----
I have:

HEEDLS-678 fix signposting link and hashing of login link

---

DigitalLearningSolutions.Web.Tests/Controllers/Signposting/SignpostingControllerTests.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/Current.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/RecommendedLearningController.cs
DigitalLearningSolutions.Web/Controllers/Signposting/SignpostingController.cs

https://softwiretech.atlassian.net/browse/HEEDLS-767
Applied the FeatureGate to any signposting endpoints that don't already have it (or some dynamic equivalent). This should be all of them, but if you can think of any others, do let me know.
Also moved the Signposting controller into the Signposting folder.
N/A
-----
I have:

HEEDLS-767 - apply signposting featuregates to relevant endpoints

---

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs

[DLSV2-497](https://hee-dls.atlassian.net/browse/DLSV2-497)
If existing verification request of assessment results is more than 1 week old, the user is able to request verification again.

DLSV2-497 Ignores open requests that are more than 1 week old

---

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_OverviewActionButtons.cshtml

DLSV2-480
In response to a request from IV Passport testers, we have duplicated the action buttons (Manage optional competencies, Request verification, Export to Excel) below the list of competencies. This has been done by moving the buttons to a partial.

DLSV2-480 Moves action buttons to a partial and repeats

---

DigitalLearningSolutions.Data/Services/ActionPlanService.cs
DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests/BasicAuthenticatedAccessibilityTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/Signposting/SignpostingControllerTests.cs
DigitalLearningSolutions.Web/Controllers/Signposting/SignpostingController.cs
DigitalLearningSolutions.Web/ViewComponents/LearningResourceWarningViewComponent.cs
DigitalLearningSolutions.Web/Views/LearningPortal/Completed/Completed.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/Current/Current.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/Current/MarkActionPlanResourceAsComplete.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/Current/RemoveCurrentActionPlanResourceConfirmation.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/Current/SetCompleteByDate.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/RecommendedLearning/RecommendedLearning.cshtml
DigitalLearningSolutions.Web/Views/Shared/Components/LearningResourceWarning/Default.cshtml
DigitalLearningSolutions.Web/Views/Signposting/LearningHubLoginWarning.cshtml

[_HEEDLS-744_](https://softwiretech.atlassian.net/browse/HEEDLS-744)
Made various fixes from issues from failed testing and from merge conflicts with HEEDLS-747:
- Adjusted spacing on warnings on Current and Completed pages so they look okay on tablet and mobile
- Added a config check so that the learning resource warnings will only be displayed is Signposting is used
- Fixed bugs in controllers so that when a resource is removed, the Mark as complete page and the Remove from action plan page will show a page with a warning, while the Set complete by date and Launch learning resource page will show NotFound.
Spacing on warning: (identical for Completed activities page)
-----
I have:

HEEDLS-744 Fix learning resource warning bugs

---

DigitalLearningSolutions.Web/Controllers/FrameworksController/Signposting.cs
DigitalLearningSolutions.Web/ViewModels/Frameworks/CompetencyResourceSummaryViewModel.cs
DigitalLearningSolutions.Web/Views/Frameworks/Developer/AddCompetencyLearningResourceSummary.cshtml
DigitalLearningSolutions.Web/Views/Frameworks/Developer/_SignpostingResourceCard.cshtml

Allow to handle multiple catalogues for each resource on Learning Hub resource search page.
https://hee-dls.atlassian.net/browse/DLSV2-469
Rolled back a previous change on this branch that assumes there's only one catalogue for each Learning Hub resource. This could not be the case for some searches.
-----
From Switch application/Frameworks/Manage my frameworks/Manage signposting/"Add resource" button:
1. Search for "covid".
2. Expand third result that contains multiple catalogues.
3. Select the last one and confirm.
4. Repeat for first one and confirm.
5. Check in the database table LearningResourceReferences that OriginalCatalogueName updated correctly.
Note: the resource would be added if it's not already in the table.

DLSV2-469 Handle multiple catalogues for each resource

---

DigitalLearningSolutions.Web/ViewComponents/TopLinkViewComponent.cs
DigitalLearningSolutions.Web/ViewModels/Common/ViewComponents/TopLinkViewModel.cs
DigitalLearningSolutions.Web/Views/Shared/Components/TopLink/Default.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml

[DLSV2-484](https://hee-dls.atlassian.net/browse/DLSV2-484)
Adds a top of page link to the supervisor review self assessment view. Because this is likely to be required elsewhere, it has been implemented as a view component with two parameters - link text and id of top element.

DLSV2-484 Adds top link as view component and includes in view

---

DigitalLearningSolutions.Data.Tests/Services/LearningHubSsoSecurityServiceTests.cs
DigitalLearningSolutions.Data/Services/LearningHubSsoSecurityService.cs

_[HEEDLS-XXXX](https://softwiretech.atlassian.net/browse/HEEDLS-678)_
Added handling for throwing and logging if the secret key is invalid.
N/A
-----
I have:

HEEDLS-678 throw and log on too-short secret key

---

DigitalLearningSolutions.Web/Views/Frameworks/Developer/_SignpostingPaginationNav.cshtml

Fixes problem with pagination url for navigating to "Next" and "Previous" page in Learning Hub Signposting resource search results page.
https://hee-dls.atlassian.net/browse/DLSV2-440
Using `asp-route` and `asp-action` attributes for the application to find the right controller method instead of relying on `Url.Content` method. Previous code not working probably because url not starting with `~` and deployment target was not the root folder. 
-----
- Pagination navigation link work after the change
- In debug mode checked that all attributes passed with `asp-route` are being received in controller method  `SearchLearningResources`

DLSV2-440 Fixes problem with pagination url

---

DigitalLearningSolutions.Data.Tests/DataServices/CourseAdminFieldsDataServiceTests.cs
DigitalLearningSolutions.Data.Tests/DataServices/CourseDataServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/CourseAdminFieldsServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/CourseServiceTests.cs
DigitalLearningSolutions.Data/DataServices/CourseAdminFieldsDataService.cs
DigitalLearningSolutions.Data/DataServices/CourseDataService.cs
DigitalLearningSolutions.Data/Helpers/CustomPromptHelper.cs
DigitalLearningSolutions.Data/Models/Courses/CourseStatistics.cs
DigitalLearningSolutions.Data/Models/Courses/CourseStatisticsWithAdminFieldResponseCounts.cs
DigitalLearningSolutions.Data/Models/Courses/DelegateCourseAdminFieldAnswers.cs
DigitalLearningSolutions.Data/Models/CustomPrompts/CustomPromptWithResponseCounts.cs
DigitalLearningSolutions.Data/Models/CustomPrompts/ResponseCount.cs
DigitalLearningSolutions.Data/Models/CustomPrompts/ResponseCounts.cs
DigitalLearningSolutions.Data/Services/CourseAdminFieldsService.cs
DigitalLearningSolutions.Data/Services/CourseService.cs
DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/CourseSetup/CourseSetupControllerTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/TrackingSystem/CourseSetup/CourseSetupViewModelTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/TrackingSystem/CourseSetup/CourseStatisticsViewModelFilterOptionsTests.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/CourseSetup/CourseSetupController.cs
DigitalLearningSolutions.Web/Helpers/FilterOptions/CourseFilterOptions.cs
DigitalLearningSolutions.Web/Styles/trackingSystem/courseSetup.scss
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/AllCourseStatisticsViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/CourseSetupViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/CourseStatisticsViewModelFilterOptions.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/SearchableCourseStatisticsViewModel.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/_CentreCourseCard.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/_CentreCourseCardAdminFields.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/_CentreCourseCardDetails.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-763
Added admin fields and answer counts for them to the course cards in Course Setup. Add Has Admin Fields to the filters.
-----
I have:

Heedls 763 filter by course admin fields

---

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/CourseDelegatesControllerTests.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/CourseDelegatesController.cs
DigitalLearningSolutions.Web/Helpers/GenericSortingHelper.cs
DigitalLearningSolutions.Web/Scripts/searchSortFilterAndPaginate/sort.ts
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/CourseDelegates/_SearchableCourseDelegateCard.cshtml

[https://softwiretech.atlassian.net/browse/HEEDLS-564](https://softwiretech.atlassian.net/browse/HEEDLS-564)
- Set the "Active Status" filter to on and "true" by default
- Add sort by Delegate ID to the sorting options.
-----
I have:

Heedls 564 set active filter as default

---

DigitalLearningSolutions.Web/Scripts/searchSortFilterAndPaginate/searchSortFilterAndPaginate.ts
DigitalLearningSolutions.Web/Views/Shared/PaginatedPage/_PaginationNav.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-761
Tackled the comments in the ticket so that the page number is announced when loading the page, and the matching result count is not read out twice. This does impact how things are announced in other circumstances, which I have detailed on comments at the relevant changes. Do let me know if we think any of these side effects should be avoided.
N/A
-----
I have:

HEEDLS-761 - screen reader pagination announcement fixes

---

DigitalLearningSolutions.Web/Styles/layout.scss
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_Layout.cshtml
DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml

DLSV2-503
To meet GDS assessment requirements, we need to mark all parts of the Frameworks Service as Beta. This change adds a beta label to the header in the layout pages. There is a light (standard) and dark styling class to give a high contrast label for both white and blue background headers.

DLSV2-503 Adds Beta label to Framework Service sub-applications

---

DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml

[DLSV2-503](https://hee-dls.atlassian.net/browse/DLSV2-503)
Beta branding changes introduced a null property reference error when no viewdata/application existed. This adds a null check to prevent errors.

DLSV2-503 Fix for unhandled null property ref in beta branding

---

DigitalLearningSolutions.Web/Views/Shared/SearchablePage/_ItemsPerPageSelect.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-625
Changed the aria label on the items per page dropdown and change the no JS behaviour to bring the user back to the first page in line with the JS behaviour.
This change affects all 3 pages with the custom items per page, Centre admins, Course Setup and All delegates.
N/A
-----
I have:

Heedls 625 centre admins results per page

---

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/CourseDelegatesController.cs
DigitalLearningSolutions.Web/Scripts/searchSortFilterAndPaginate/sort.ts

https://softwiretech.atlassian.net/browse/HEEDLS-565
Fix the broken course delegate name Javascript sorting caused by previous refactoring, and incorrect parameter order causing exception when trying to load the page.
N/A
-----
I have:

HEEDLS-565 Fix Sorting by name on Course Delegates page and parameter order

---

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs

[DLSV2-496](https://hee-dls.atlassian.net/browse/DLSV2-496)
When a self assessment is set to enforce role requirements we should prevent the user from requesting verification for any results for required questions where the role requirements are not being met. We do this by adjusting the query to only return results that are valid for verification.

DLSV2-496 Prevent verification when not meeting requirements

---

DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests/BasicAuthenticatedAccessibilityTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/TrackingSystem/Delegates/AllDelegates/DelegateCourseInfoViewModelTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/TrackingSystem/Delegates/DelegateProgress/DelegateProgressViewModelTests.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/CourseDelegates/DelegateProgressViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/ViewDelegate/DelegateCourseInfoViewModel.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/CourseDelegates/_SearchableCourseDelegateCard.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateProgress/EditCompletionDate.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateProgress/_DelegateProgressSummary.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ViewDelegate/_DelegateCourseInfoCard.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-649
Made changes to the Course Delegates cards, the View Delegate course cards, and the Delegate Progress page to make the names and display of various fields consistent. I'll comment on 567's PR to make sure the Detailed Progress page also has consistent names where appropriate.
Delegate progress page:
View delegate course card:
Course delegate card:
-----
I have:

HEEDLS-649 - make delegate progress field names consistent

---

DigitalLearningSolutions.Web/Scripts/searchSortFilterAndPaginate/search.ts
DigitalLearningSolutions.Web/Scripts/searchSortFilterAndPaginate/searchSortFilterAndPaginate.ts
DigitalLearningSolutions.Web/Styles/layout.scss
DigitalLearningSolutions.Web/ViewComponents/LoadingSpinnerViewComponent.cs
DigitalLearningSolutions.Web/ViewModels/Common/ViewComponents/LoadingSpinnerViewModel.cs
DigitalLearningSolutions.Web/Views/LearningPortal/Available/Available.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/Completed/Completed.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/Current/Current.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/RecommendedLearning/RecommendedLearning.cshtml
DigitalLearningSolutions.Web/Views/Shared/Components/LoadingSpinner/Default.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/MyStaffList.cshtml
DigitalLearningSolutions.Web/Views/Support/Faqs/Faqs.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Administrator/Index.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/Index.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/AllDelegates/Index.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/CourseDelegates/Index.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateGroups/Index.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/EmailDelegates/Index.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/GroupCourses/AddCourseToGroupSelectCourse.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/GroupDelegates/SelectDelegate.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-597
A bug was occurring on the supervisor staff list page when trying to set the link return pages when no data was available. This caused an exception, preventing the JS from reaching the point where the loading spinner stops. The cause was the return page code not being able to handle a case where the Search Box does not exist (not rendered when no data is found).
Because of this bug, the initial loading spinner commits were reverted. As part of this PR, I've reverted those two revertions (first two commits). In the third commit, I've made the JS more robust, so it should be able to handle any further pages where the search box is not rendered.
N/A
-----
I have:
- …

Heedls 597 make return page logic more robust

---

DigitalLearningSolutions.Web/Controllers/FrameworksController/FrameworksController.cs
DigitalLearningSolutions.Web/Views/Frameworks/Shared/_NavMenuItems.cshtml

https://hee-dls.atlassian.net/browse/DLSV2-366
Added a link to Support from the Nav Bar of the Frameworks application. When visiting the support page from Frameworks, the Frameworks nav bar should remain in place.
-----
- Looked into similar change for adding Support to Tracking System in [commit/abc4a47a](https://github.com/TechnologyEnhancedLearning/DLSV2/commit/abc4a47a) including `TrackingSystem/Shared/_NavMenuItems.cshtml` though controller decorator was added in a different commit after a merge.
- Checked that Framework Support behaves the same as Tracking System Support after my changes despite some links are broken when running in development environment.

DLSV2-366 Add Support tab to Frameworks

---

DigitalLearningSolutions.Web/Controllers/FrameworksController/Signposting.cs
DigitalLearningSolutions.Web/ViewModels/Common/SearchablePage/BasePaginatedViewModel.cs
DigitalLearningSolutions.Web/ViewModels/Frameworks/BaseSignpostingViewModel.cs
DigitalLearningSolutions.Web/ViewModels/Frameworks/CompetencyResourceSignpostingViewModel.cs
DigitalLearningSolutions.Web/Views/Frameworks/Developer/AddCompetencyLearningResources.cshtml

https://hee-dls.atlassian.net/browse/DLSV2-491
Created override methods in CompetencyResourceSignpostingViewModel for using Shared\SearchablePage\_Pagination.cshtml and inherited from BasePaginatedViewModel. The urls and behaviuor should be the same as the implemented in Delegates/All Delegates.
Furthermore this change fixes problem with controller method preserving page number when user runs new search, as it could result in a different number of pages. So it makes more sense to reset current page to 1 when search button is clicked or user presses enter key on search field. 
```asp
<button class="nhsuk-search__submit sort-submit" type="submit" asp-route-page="1">
Search
</button>
```
-----
Pagination works either when
- Arriving by clicking on "Add resource" button (no parameters …

DLSV2-491 Rework Learning Hub resource search to reuse existing pagination

---

DigitalLearningSolutions.Data.Tests/Services/UserServiceTests.cs
DigitalLearningSolutions.Data/Models/User/DelegateUser.cs
DigitalLearningSolutions.Data/Models/User/EditDelegateDetailsData.cs
DigitalLearningSolutions.Data/Services/UserService.cs
DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/EditDelegateControllerTests.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/EditDelegateController.cs
DigitalLearningSolutions.Web/Helpers/AccountDetailsDataHelper.cs
DigitalLearningSolutions.Web/ViewModels/Common/EditDetailsFormData.cs
DigitalLearningSolutions.Web/ViewModels/MyAccount/MyAccountEditDetailsFormData.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/EditDelegate/EditDelegateFormData.cs
DigitalLearningSolutions.Web/Views/Shared/_EditRegistrationNumber.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/EditDelegate/Index.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-794
Added the Edit PRN form fields to the Manage Delegate Edit screen
-----
I have:

HEEDLS-794 Add PRN edit to Manage Delegate Edit screen

---

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_CompetencySummary.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_OverviewActionButtons.cshtml

Provide summary of competencies to be self-assessed in Overview expander headings.
https://hee-dls.atlassian.net/browse/DLSV2-476
Added partial view and logics similar to `SelfAssessments/_MeanScores` and used logics for counting in competency search in [DLSV2-293](https://hee-dls.atlassian.net/browse/DLSV2-293).
-----
- Only `Required` questions are counted
- Count summary visible both when group collapsed and expanded
- Count for verified questions is shown only when self assessment is supervised

DLSV2-476 Summary of competencies in overview expander headings

---

DigitalLearningSolutions.Data.Tests/DataServices/CourseDelegatesDataServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/CourseDelegatesServiceTests.cs
DigitalLearningSolutions.Data/DataServices/CourseDelegatesDataService.cs
DigitalLearningSolutions.Data/Helpers/FilteringHelper.cs
DigitalLearningSolutions.Data/Models/CourseDelegates/CourseDelegate.cs
DigitalLearningSolutions.Data/Models/CourseDelegates/CourseDelegatesData.cs
DigitalLearningSolutions.Data/Services/CourseDelegatesService.cs
DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/CourseDelegatesControllerTests.cs
DigitalLearningSolutions.Web.Tests/ViewModels/TrackingSystem/Delegates/CourseDelegates/CourseDelegateViewModelFilterOptionsTests.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/CourseDelegatesController.cs
DigitalLearningSolutions.Web/Helpers/AdminFieldsHelper.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/CourseDelegates/AllCourseDelegatesViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/CourseDelegates/CourseDelegateViewModelFilterOptions.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/CourseDelegates/SearchableCourseDelegateViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/CourseDelegates/SelectedCourseDetailsViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/Shared/DelegatesViewModelFilters.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/CourseDelegates/_SearchableCourseDelegateCard.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-786
Added admin fields to the course delegates cards. Also implemented filtering on these fields, with new functionality for free-text fields.
-----
I have:

HEEDLS-786 - add admin fields to course delegates page

---

DigitalLearningSolutions.Web/Scripts/trackingSystem/addNewCentreCourseSelectCourse.ts

[_HEEDLS-551_](https://softwiretech.atlassian.net/browse/HEEDLS-551)
Fix bug with clearing filters on select course page. Selecting "All categories" or "All topics" should successfully clear the respective filter applied when selected.
(No UI changes)
-----
I have:

HEEDLS-551 Fix bug with clearing filters on select course page

---

DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/ViewDelegate/RemoveFromCourseViewModel.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ViewDelegate/ConfirmRemoveFromCourse.cshtml

_[HEEDLS-796](https://softwiretech.atlassian.net/browse/HEEDLS-796)_
_Corrects styling issues and incorrect title found through testing._
-----
I have:

HEEDLS-796 : Update "All Delegates - Remove course" styling fixes

---

DigitalLearningSolutions.Web/Controllers/MyAccountController.cs
DigitalLearningSolutions.Web/Helpers/PromptsService.cs

_HEEDLS-510_
Ensure the user's registration prompt answers get retained on the Edit details page if an error occurs.
No UI changes
-----
I have:

HEEDLS-510 Retain registration prompt answers when error occurs

---

DigitalLearningSolutions.Data.Tests/DataServices/CourseDataServiceTests.cs
DigitalLearningSolutions.Data.Tests/TestHelpers/GroupTestHelper.cs
DigitalLearningSolutions.Data/DataServices/CourseDataService.cs
DigitalLearningSolutions.Data/DataServices/CourseDelegatesDataService.cs
DigitalLearningSolutions.Data/DataServices/GroupsDataService.cs
DigitalLearningSolutions.Data/DataServices/UserDataService/DelegateUserDataService.cs
DigitalLearningSolutions.Data/Models/CourseDelegates/CourseDelegate.cs
DigitalLearningSolutions.Data/Models/Courses/DelegateCourseInfo.cs
DigitalLearningSolutions.Data/Models/DelegateGroups/GroupDelegate.cs
DigitalLearningSolutions.Data/Models/DetailedProgress.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/AllDelegates/SearchableDelegateViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/CourseDelegates/DelegateProgressViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/CourseDelegates/SearchableCourseDelegateViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/DelegateApprovalsViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/DelegateProgress/DetailedCourseProgressViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/GroupDelegates/GroupDelegateViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/RejectDelegateViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/Shared/DelegateInfoViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/ViewDelegate/ViewDelegateViewModel.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/AllDelegates/_SearchableDelegateCard.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/GroupDelegates/_AddGroupDelegateCard.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ViewDelegate/Index.cshtml

[_HEEDLS-795_](https://softwiretech.atlassian.net/browse/HEEDLS-795)
Makes the PRN display format consistent across the site. This is: show the PRN is the user has provided one, show "Not professionally registered" if they have been prompted for a PRN but have not provided one, and show "Not yet provided" if the user has not been prompted for one.
I think I caught all the places the PRN is shown, My Account and Manage Delegate already had the required format.
Here's a list of where the PRN is displayed:
- My account
- All delegates
- Delegate progress
- Detailed progress
- Manage delegate
- Group delegates 
- Add delegate to group
- Course delegates
- Approve registrations
- Reject registration confirmation
-----
I …

HEEDLS-795 Use display PRN string helper throughout the site

---

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs

Admin users active check in Manage Supervisors causes a SQL error.
https://hee-dls.atlassian.net/browse/DLSV2-522
Added Active column to `group by` list, so it can be used in `select` statement. 
-----
Checked that it works with active and inactive admins.

DLSV2-522 Admin users active check in Manage Supervisors causes a Sql error

---

DigitalLearningSolutions.Data.Tests/DataServices/CourseDataServiceTests.cs
DigitalLearningSolutions.Data/DataServices/CourseDataService.cs

[_HEEDLS-700_](https://softwiretech.atlassian.net/browse/HEEDLS-700)
Exclude all archived applications from the dashboard course count so it is consistent with the number of active courses shown on the Course Setup page. To make them exactly consistent it was also necessary to join on CentreApplications and take only CentreApplications at the centre.
No UI changes
-----
I have:

HEEDLS-700 Exclude archived applications from dashboard count

---

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_CompetencySummary.cshtml
DigitalLearningSolutions.Web/appsettings.Development.json
DigitalLearningSolutions.Web/appsettings.SIT.json
DigitalLearningSolutions.Web/appsettings.Test.json
DigitalLearningSolutions.Web/appsettings.json

Add overall progress summary to Sign-off area on SelfAssessmentOverview.cshtml.
https://hee-dls.atlassian.net/browse/DLSV2-518
Created total counters for self-assessed and confirmed (verified) questions in SelfAssessmentOverview.cshtml. Passing partial counts to _CompetencySummary.cshml by means of a `ViewDataDictionary`.
-----
Checked that totals match the addition of all cards for self assessed and confirmed questions.

DLSV2-518 Add overall progress summary on SelfAssessmentOverview

---

DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/LearningPortalControllerTests.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentCompetency.cshtml

When a user submits a comment without responding to the assessment question an error is thrown.
https://hee-dls.atlassian.net/browse/DLSV2-519
Since the model for getting and posting back the form is different, I am using `TempData` and redirecting to the original view when an error is detected. In addition, radio buttons are generated dynamically,. So in order to use standard validation applied trough the application, the controller method could predict html tag `id` for the first option button for the competency that's throwing the error and insert and error in `ModelState` for this element.
-----
Inserted data for reproducing the error and checked that standard error validation used in the application is shown when comment is provided but not radio button is selected for a competency.

DLSV2-519 When user submits comment without selecting a question, an error is thrown

---

DigitalLearningSolutions.Web/Scripts/searchSortFilterAndPaginate/searchSortFilterAndPaginate.ts
DigitalLearningSolutions.Web/Scripts/trackingSystem/courseDelegates.ts
DigitalLearningSolutions.Web/Views/Supervisor/RemoveConfirm.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/CourseDelegates/Index.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-621
Fixed the Staff List return page issue for the removal confirmation page, but the link to the page is strangely set up and will point to a bad action when the user has no self assessments.
Fixed the course delegates page by modifying the JS to take query in a whitelisted query parameter and preserve any that match. 
Have not been able to fix the screen reader issue. 
N/A
-----
I have:

HEEDLS-621 - fix course delegates URL and Staff List return pages

---

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/ViewDelegateControllerTests.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ViewDelegateController.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/ViewDelegate/RemoveFromCourseViewModel.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ViewDelegate/ConfirmRemoveFromCourse.cshtml

_[HEEDLS-797](https://softwiretech.atlassian.net/browse/HEEDLS-797)_
_An issue cropped up during testing where the user wasn't being returned to the correct page on Course Delegates when they used the cancel link on the remove confirmation page._
-----
I have:

HEEDLS-797 : Fix return page on remove delegate

---

DigitalLearningSolutions.Web/Views/Shared/_SearchableSummaryFieldValue.cshtml

_[HEEDLS-800](https://softwiretech.atlassian.net/browse/HEEDLS-800)_
Fixing a silly oversight in the value display for the new partial.
-----
I have:

HEEDLS-800 fix display of values in searchable summary value

---

DigitalLearningSolutions.Web.Tests/ViewComponents/CurrentFiltersViewComponentTests.cs
DigitalLearningSolutions.Web/ViewComponents/CurrentFiltersViewComponent.cs
DigitalLearningSolutions.Web/ViewModels/Common/SearchablePage/CurrentFiltersViewModel.cs
DigitalLearningSolutions.Web/Views/Shared/Components/CurrentFilters/Default.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-647
Fixes the Clear Filters button also clearing the sort and items per page for no JS.
I don't think the rest of the issues raised are to be fixed here, but if they are I'll just raise a new PR.
-----
I have:

HEEDLS-647 Fix Clear Filters resetting sort and items per page

---

DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml

Make competency descriptions visible on the supervisor verification view
https://hee-dls.atlassian.net/browse/DLSV2-502
Implemented same approach taken in LearningPortal\SelfAssessments\SelfAssessmentCompetency.cshtml for the ReviewSelfAssessment.cshtml view.
First two competencies having `AlwaysShowDescription` set to True in `Competencies` table:
First two competencies always show description while the last two contain an expandable description that is visible when user clicks on the competency name link.
-----
- Checked different scenarios including null Description combined with AlwaysShowDescription set to True or False

DLSV2-502 Make competency descriptions visible on the supervisor verification view

---

DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs

Allow a Supervisor to remove a self assessment from a staff member if it has not been started.
https://hee-dls.atlassian.net/browse/DLSV2-521
**Remove link changes: We're leaving it as it is for the being.**
The code for displaying remove link was already in place on partial view _DelegateProfileAssessmentGrid. But Remove link is shown when `CandidateAssessments.LaunchCount` is zero. In regards to property `LastAccessed` its value can be CandidateAssessments.LastAccessed or CandidateAssessments.StartedDate if the former is null (see SupervisorService.cs, line 236, method: `GetSelfAssessmentsForSupervisorDelegateId`). 
**Changes made:** On view Supervisor\DelegateProfileAssessments.cshtml, if admin was promoted to supervisor, `IsNominated` property should return false, so it doesn't …

DLSV2-521 Allow a Supervisor to remove a self assessment from a staff member if it has not been started

---

DigitalLearningSolutions.Web/Scripts/searchSortFilterAndPaginate/searchSortFilterAndPaginate.ts
DigitalLearningSolutions.Web/Scripts/trackingSystem/centreCourseSetup.ts
DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/_CentreCourseCard.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-809
Fixed the copy course link button to copy the course link again. Details of the issue are in the comment on the ticket.
Not sure if the modifications to the SearchSortFilterPaginate JS are the best approach here. Do let me know if you have a better suggestion.
N/A
-----
I have:

HEEDLS-809 - fixed the copy course button

---

DigitalLearningSolutions.Web/Scripts/support/faqs.ts
DigitalLearningSolutions.Web/Views/Support/Faqs/Faqs.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-840
Changed the FAQs AllItems URL generation in JS to no longer use the Regex to extract the sub application, but to grab it from a new hidden span.
N/A
-----
I have:

HEEDLS-840 - replace FAQs URL generation with simpler methodolgy

---

DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests/SelfAssessmentAccessibilityTests.cs

Re-enabling a test that should be working now after database migration executed in master. 
https://hee-dls.atlassian.net/browse/DLSV2-520
Re-enabled test `SelfAssessment_journey_has_no_accessibility_errors` that should be working now after database migration executed in master. This change was requested by Stephen Jackson in Slack on March 14th 2022.
-----
- Checked that the test passed in TestView after above change

DLSV2-520 Re-enabling one test after migration

---

DigitalLearningSolutions.Data.Tests/DataServices/ProgressDataServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/ProgressServiceTests.cs
DigitalLearningSolutions.Data.Tests/TestHelpers/ProgressTestHelper.cs
DigitalLearningSolutions.Data/DataServices/ProgressDataService.cs
DigitalLearningSolutions.Data/Exceptions/InvalidPromptNumberException.cs
DigitalLearningSolutions.Data/Models/Courses/DelegateCourseInfo.cs
DigitalLearningSolutions.Data/Services/ProgressService.cs
DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests/BasicAuthenticatedAccessibilityTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/DelegateProgressControllerTests.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateProgressController.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/DelegateProgress/EditDelegateCourseAdminFieldFormData.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/DelegateProgress/EditDelegateCourseAdminFieldViewModel.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/CourseDelegates/_SearchableCourseDelegateCard.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateProgress/EditDelegateCourseAdminField.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateProgress/_DelegateProgressSummary.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ViewDelegate/_DelegateCourseInfoCard.cshtml

[_HEEDLS-780_](https://softwiretech.atlassian.net/browse/HEEDLS-780)
Allow admins to edit a course admin field for a delegate. The page shows radio buttons or a free text field depending on whether the admin field has options. Admins can leave the field blank or select the "Leave blank" radio button.
There are a few known issues I'll wait to resolve once HEE has given us an answer about whether we are keeping the Delegate Progress page. These are:
- The breadcrumbs in the view not accounting for accessing the page from the cards on the Course Delegates or View Delegate pages (bypassing the Delegate Progress page)
- The redirect upon save from Course delegates page - currently if you click save when accessing the page from the Course delegates page, it takes you to the Delegate progress …

HEEDLS-780 Edit course admin field for delegate

---

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentCompetency.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SetSupervisorRole.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SignOffHistory.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SupervisorComments.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/VerificationPickResults.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/VerificationPickSupervisor.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/VerificationSummary.cshtml

https://hee-dls.atlassian.net/browse/DLSV2-537
Added requested extra words to breadcrumbs under LearningPortal/Selfassessments. 
Also in SupervisorComments.cshtml changed `Model.SupervisorComment.Verified.Value.ToShortDateString()` to `Model.SupervisorComment.Verified?.ToShortDateString()` because I was getting null reference error when it calls `.Value` on null object. 
LearningPortal\SelfAssessments\SelfAssessmentOverview.cshtml
LearningPortal\SelfAssessments\SupervisorComments.cshtml

DLVSV2-537 Tweak the breadcrumbs in Self Assessment navigation

---

DigitalLearningSolutions.Web/Scripts/checkboxes.ts
DigitalLearningSolutions.Web/Scripts/learningPortal/selfAssessment.ts
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentCompetency.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_RadioQuestion.cshtml

Add "Clear" result button for self assessed competency assessment questions
https://hee-dls.atlassian.net/browse/DLSV2-538
Updated existing typescript code to cover both checkbox and radio button group deselect all. Basically, assuming the element is checked, replacing `checkbox.click()` by `checkbox.checked = false` should work both for radios and checkboxes. But I also refactored the code and remove some redundancy.
-----
- Clear button works with multiple groups of radio buttons on the same page and only clear the selection for current group.
- When Javascript is disabled, Clear button is not present on the page.
- Change not causing issues in "Choose optional capabilities" that uses same typescript class "Checkboxes" I have modified in this PR
"Choose optional capabilities" should not …

DLSV2-538 Add Clear result button for self assessed questions

---

DigitalLearningSolutions.Data/Services/FrameworkService.cs
DigitalLearningSolutions.Web/Controllers/FrameworksController/Frameworks.cs
DigitalLearningSolutions.Web/ViewModels/Frameworks/CollaboratorsViewModel.cs
DigitalLearningSolutions.Web/Views/Frameworks/Developer/Collaborators.cshtml

[DLSV2-541](https://hee-dls.atlassian.net/browse/DLSV2-541)
Fixes a bug with the Frameworks add contributor function. The data service method for retrieving info about the chosen administrator referred to a column (FrameworkCollaborators.Active) that wasn't present.
This method also relies on the email address matching a registered admin user but failed quietly if there wasn't one. This change introduces a validator error message to the page explaining why they weren't added.
-----
I have:

DLSV2-541 Fixes error and adds validation to add contributor

---

DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Configuration/_CentreConfigurationCentreDetails.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-816
Reverted the Preview Certificate back to a link to the old site version.
-----
I have:

HEEDLS-816 Revert Preview button to old site link

---

DigitalLearningSolutions.Web.Tests/ControllerHelpers/ControllerContextHelper.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/TutorialTests.cs
DigitalLearningSolutions.Web.Tests/TestHelpers/TutorialContentHelper.cs
DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs
DigitalLearningSolutions.Web/Controllers/LoginController.cs

https://softwiretech.atlassian.net/browse/HEEDLS-813
Returned the normal login expiry to normal and added a longer expiry before a user accesses a long tutorial, conditional on the average tutorial duration.
N/A
-----
I have:

HEEDLS-813 Move longer sign in duration to the problem tutorial endpoint

---

DigitalLearningSolutions.Data.Tests/DataServices/PasswordDataServiceTests.cs
DigitalLearningSolutions.Data.Tests/TestHelpers/UserTestHelper.cs
DigitalLearningSolutions.Data/DataServices/PasswordDataService.cs

[_HEEDLS-855_](https://softwiretech.atlassian.net/browse/HEEDLS-855)
Changed the PasswordDataService queries to reference the new users tables.
It's possible we'll want to change SetPasswordByCandidateNumber and SetPasswordForUsersAsync when more refactoring of the registration logic has been done. SetPasswordByCandidateNumber could become SetPasswordByUserId and SetPasswordForUsersAsync may want to include Auth Users as a User type?
-----
I have:

HEEDLS-855 fix queries in password data service

---

DigitalLearningSolutions.Data.Migrations/202205061441_SeparateCentreEmailsTable.cs
DigitalLearningSolutions.Data/DataServices/RegistrationDataService.cs

_[HEEDLS-895](https://softwiretech.atlassian.net/browse/HEEDLS-895)_
_In early UAR we added email fields on `AdminAccounts` and `DelegateAccounts` for centre-specific notifications. Rather than allowing an admin to have a primary email, an email for their delegate account and an email for their admin account, we should only allow them to have a single secondary email. We’ll pull Email out of `AdminAccounts` and `DelegateAccounts` and put it in a new table called `UserCentreDetails`_
-----
I have:

HEEDLS-895 : UAR Migration 7: Pull centre emails out into separate table

---

DigitalLearningSolutions.Web/Scripts/searchSortFilterAndPaginate/searchSortFilterAndPaginate.ts
DigitalLearningSolutions.Web/Views/Shared/SearchablePage/_ResultCountAndPageAlerts.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-861
Changed how the combination alert message was being updated so that it can only ever fire a single time.
N/A
-----
I have:

HEEDLS-861 Refactor alert message updating for the combo alert

---

DigitalLearningSolutions.Data.Tests/DataServices/ActivityDataServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/ActivityServiceTests.cs
DigitalLearningSolutions.Data/DataServices/ActivityDataService.cs
DigitalLearningSolutions.Data/Services/ActivityService.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Reports/ReportsController.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Reports/EditFiltersViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Reports/ReportsViewModel.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Reports/EditFilters.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Reports/Index.cshtml

[HEEDLS-866](https://softwiretech.atlassian.net/jira/software/c/projects/HEEDLS/boards/753?modal=detail&selectedIssue=HEEDLS-866)
On the reports page, if there was no activity at the centre, the query inside the `ActivityDataService.GetStartOfActivityForCentre` method was returning null. This caused the change filters and download buttons to give an error. I added a check and if there is no activity at the centre/for the course category that the current user has access to, I don't display the buttons and instead show an informative message.
No activity for all course categories:
No activity for the specific course category the user has access to:
-----
I have:

HEEDLS-866 Refactor reports page when there is no activity at the centre

---

DigitalLearningSolutions.Data.Tests/DataServices/CourseAdminFieldsDataServiceTests.cs
DigitalLearningSolutions.Data/DataServices/CourseAdminFieldsDataService.cs
DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests/AddCentreRegistrationPromptsAccessibilityTests.cs
DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests/AddCourseAdminFieldsAccessibilityTests.cs
DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests/EditCentreRegistrationPromptsAccessibilityTests.cs
DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests/EditCourseAdminFieldsAccessibilityTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Centre/Configuration/RegistrationPromptsControllerTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/CourseSetup/AdminFieldsControllerTests.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Configuration/RegistrationPromptsController.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/CourseSetup/AdminFieldsController.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Configuration/RegistrationPrompts/AddRegistrationPromptConfigureAnswersViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/AdminFieldAnswersViewModel.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Configuration/RegistrationPrompts/AddRegistrationPromptConfigureAnswers.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Configuration/RegistrationPrompts/AddRegistrationPromptSummary.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Configuration/RegistrationPrompts/BulkRegistrationPromptAnswers.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Configuration/RegistrationPrompts/EditRegistrationPrompt.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Configuration/RegistrationPrompts/_CentreRegistrationPromptExpander.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Configuration/RegistrationPrompts/_NoConfiguredAnswers.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Configuration/RegistrationPrompts/_RegistrationPromptAnswerTable.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/AddAdminField.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/AddBulkAdminFieldAnswers.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/BulkAdminFieldAnswers.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/EditAdminField.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/_AdminFieldAnswerTable.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/_AdminFieldCard.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/_NoConfiguredAnswers.cshtml

[HEEDLS-896](https://softwiretech.atlassian.net/browse/HEEDLS-896)
On `/TrackingSystem/CourseSetup/:customisationId/AdminFields` pages:
* Attempts to add an admin field that is already present for the course will display the error message "That field name already exists for this course" when the Save button is pressed
* Attempts to add answers which match existing answers (case-insensitively, when trimmed) will display the error message "Each answer must be unique", either in single or bulk edit mode
---
---
-----
I have:

HEEDLS-896 Disallow duplicate admin fields

---

DigitalLearningSolutions.Data/Services/ActivityService.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Reports/ReportsController.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Reports/ReportsViewModel.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Reports/Index.cshtml

[HEEDLS-866](https://softwiretech.atlassian.net/jira/software/c/projects/HEEDLS/boards/753?modal=detail&selectedIssue=HEEDLS-866)
I replaced the entire content of the reports page with the no activity message for centres with no activity.
-----
I have:

Heedls 866 fix reports page actions for no activity centres

---

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Centre/Configuration/RegistrationPromptsControllerTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/CourseSetup/AdminFieldsControllerTests.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Configuration/RegistrationPromptsController.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/CourseSetup/AdminFieldsController.cs

https://softwiretech.atlassian.net/browse/HEEDLS-896
Addressing Alex's test failure report:
* Changed error messages for course admin interface to match those in custom prompts
* Highlight the correct field when there's an error with duplicate responses
* Changed the custom prompts bulk answers journey so that an error is displayed on the bulk edit screen when duplicate entries are submitted
---
---
-----
I have:

Heedls 896 prompt journey fixes

---

DigitalLearningSolutions.Data.Tests/DataServices/CourseDataServiceTests.cs
Jenkinsfile

[_HEEDLS-852_](https://softwiretech.atlassian.net/browse/HEEDLS-852)
Changed the delegate email in the ExpectedCourseInfo used for tests to the Guid generated during migrations
Changed the inputs for GetNumsOfRecentProgressRecordsForBrand_returns_expected_dict, which was failing because this accessibility test LearningMenu_interface_has_no_accessibility_errors was updating a progress record's SubmittedTime, interfering with the expected results.
Commented back in the data tests in the jenkins file
-----
I have:

UAR-852 Fix remaining db queries

---

DigitalLearningSolutions.Web/DigitalLearningSolutions.Web.csproj
Jenkinsfile

https://softwiretech.atlassian.net/browse/HEEDLS-904
The Jenkins pipeline failed when running `Deploy to test`: https://jenkins2.softwire.com/job/HEE/job/HEE%20DLS/job/master/1265/console
This commit hopefully fixes that stage of the pipeline, as well as `Deploy to UAT`. It also switches to using `yarn install --frozen-lockfile` in both those circumstances.
Note: there is no way to be sure that this will work without merging this PR.
-----
I have:

HEEDLS-904 Hopefully fix Jenkins pipeline (again)

---

DigitalLearningSolutions.Data.Tests/Services/LoginServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/UserVerificationServiceTests.cs
DigitalLearningSolutions.Data/Models/User/UserEntity.cs
DigitalLearningSolutions.Data/Models/User/UserEntityVerificationResult.cs
DigitalLearningSolutions.Data/Services/LoginService.cs
DigitalLearningSolutions.Data/Services/UserVerificationService.cs
DigitalLearningSolutions.Web/Controllers/LoginController.cs
DigitalLearningSolutions.Web/Helpers/CustomPolicies.cs
DigitalLearningSolutions.Web/Startup.cs
DigitalLearningSolutions.Web/Views/Login/AccountLocked.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-898
Fixes some incorrect logic around inactive accounts and DelegateAccounts with no old password and adds an action link to the Account Locked screen.
Documentation has been sorted as well https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/19467173889/Sign+in
-----
I have:

Uar 898 fix login

---

DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Reports/_EditCourseCategoryFilters.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-927
When logged in as an admin user whose CategoryId is not zero, on /TrackingSystem/Centre/Reports/EditFilters the "Choose a course filter" option is now retained when you press the "Apply filters" button
-----
I have:

HEEDLS-927 Fixed course filter on centre reports for admins with non-zero category id

---

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/CourseDelegatesController.cs

https://softwiretech.atlassian.net/browse/HEEDLS-862
Add missed `AS AnswerX` to SQL query where we are trimming the answers. This was causing answers to never appear.
Added NoCaching to the All Items endpoint just in case.
-----
I have:

HEEDLS-862 Add missed AS from SQL query with LTRIM/RTRIM

---

DigitalLearningSolutions.Data.Migrations/202205261100_IncreaseCompetencyGroupsDescriptionLength.cs
DigitalLearningSolutions.Data/Models/Frameworks/CompetencyGroupBase.cs

https://hee-dls.atlassian.net/browse/DLSV2-544
Added migration and removed view model decorator that limited the number of characters for competency group description.
Validation for name still in place. 
-----
- Checked that competency group description allows more than 1000 characters and no error messages are reported.
- Checked that Validation for "Name" field is still in place, as I have added error summary in previous PR.
- Checked that description is not mandatory.

DLSV2-544 Removed length restrictions for competency group description

---

DigitalLearningSolutions.Data/Models/Courses/DelegateCourseInfo.cs

https://softwiretech.atlassian.net/browse/HEEDLS-862
Fixed the DelegateCourseInfo constructor setting the wrong AnswerX properties. This fixes the issue seen where the answer gets populated from the other answers when reaching the edit screen.
-----
I have:

HEEDLS-862 Fix constructor setting the wrong properties

---

DigitalLearningSolutions.Data.Tests/DataServices/SessionDataServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/StoreAspProgressServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/TrackerActionServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/TrackerServiceTests.cs
DigitalLearningSolutions.Data/DataServices/SessionDataService.cs
DigitalLearningSolutions.Data/Enums/TrackerEndpointAction.cs
DigitalLearningSolutions.Data/Enums/TrackerEndpointResponse.cs
DigitalLearningSolutions.Data/Enums/TrackerEndpointSessionVariable.cs
DigitalLearningSolutions.Data/Services/StoreAspProgressService.cs
DigitalLearningSolutions.Data/Services/TrackerActionService.cs
DigitalLearningSolutions.Data/Services/TrackerService.cs
DigitalLearningSolutions.Web/Startup.cs

https://softwiretech.atlassian.net/browse/HEEDLS-411
Implemented the new StoreASPProgressNoSession tracker endpoint. As a lot of the logic is shared with the StoreASPProgressV2 endpoint, a good chunk of these changes are just moving that endpoint's methods and tests into a reusable format.
Note that there are still a few questions regarding differences in ticket scope vs the old code that are awaiting answers from Kevin when he gets back.
N/A
-----
I have:

HEEDLS-411 - implement StoreASPProgressNoSession tracker endpoint

---

DigitalLearningSolutions.Data/Models/Supervisor/SupervisorDelegateDetail.cs
DigitalLearningSolutions.Data/Services/FrameworkNotificationService.cs
DigitalLearningSolutions.Data/Services/SupervisorService.cs
DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs
DigitalLearningSolutions.Web/ViewModels/Supervisor/AllStaffListViewModel.cs
DigitalLearningSolutions.Web/ViewModels/Supervisor/SupervisorDelegateDetailViewModel.cs
DigitalLearningSolutions.Web/Views/Supervisor/Shared/_StaffDetails.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/Shared/_StaffMemberCard.cshtml

[DLSV2-530](https://hee-dls.atlassian.net/browse/DLSV2-530)
When accessing the supervisor interface, the “Staff list” should display the candidate Professional Registration Number (PRN) if the logged in user is a Supervisor.
-----
I have:

DLSV2-530 Make PRN number of Staff visible for Supervisors only

---

DigitalLearningSolutions.Web/Scripts/searchSortFilterAndPaginate/searchSortFilterAndPaginate.ts

https://softwiretech.atlassian.net/browse/HEEDLS-943
In the pagination interface, when javascript is enabled, manually changing the page number in the URL to be either < 1 or > the maximum number of pages leads to bad results (see Jira for screenshots).
This PR causes the browser to change the URL to `/1` in these scenarios, so the first page of results is displayed.
-----
I have:

HEEDLS-943 Pagination - redirect out-of-bounds pages to page 1

---

DigitalLearningSolutions.Web/Scripts/searchSortFilterAndPaginate/filter.ts
DigitalLearningSolutions.Web/Scripts/spec/filter.spec.ts

https://softwiretech.atlassian.net/browse/HEEDLS-960
Escape double quotes in data-filter-value selector
-----
I have:

HEEDLS-960 Escape double quotes in data-filter-value selector

---

DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests/UserDataServiceTests.cs
DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs
DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Centre/Administrator/AdministratorControllerTests.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Administrator/AdministratorController.cs

[HEEDLS-920](https://softwiretech.atlassian.net/jira/software/c/projects/HEEDLS/boards/753?modal=detail&selectedIssue=HEEDLS-920)
Changed the unlock account button from the tracking system to call the new method `ResetFailedLoginCountByUserId`
-----
I have:

UAR-920 Unlock account via tracking system

---

DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/AddSupervisor.cshtml

[DLSV2-559](https://info.hl7.org/orientation-station)
Fixes bug validating first step pf the add supervisor flow in self assessment manage supervisors. The model being passed back to the view on error was incomplete.
-----
I have:

DLSV2-559 Fixes validation on choose supervisor

---

DigitalLearningSolutions.Web/Controllers/ApplicationSelectorController.cs
DigitalLearningSolutions.Web/Helpers/CustomClaimTypes.cs
DigitalLearningSolutions.Web/Helpers/CustomPolicies.cs
DigitalLearningSolutions.Web/Helpers/LoginClaimsHelper.cs
DigitalLearningSolutions.Web/Models/AdminLoginDetails.cs

[DLSV2-562](https://hee-dls.atlassian.net/browse/DLSV2-562)
Makes the app tile for Supervisor interface available to Nominated Supervisors. Adds nominated supervisor role into claims and authorisation policies to allow them to properly access the supervisor interface.
(note: no add staff button)
-----
I have:

DLSV2-562 Handles the nominated supervisor role in claims and policies

---

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Configuration/RegistrationPromptsController.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Configuration/RegistrationPrompts/AddRegistrationPromptConfigureAnswersViewModel.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Configuration/RegistrationPrompts/AddRegistrationPromptConfigureAnswers.cshtml

[HEEDLS-962](https://softwiretech.atlassian.net/browse/HEEDLS-962)
I added the prompt name on the ConfigureAnswers page in the add registration prompt journey.
-----
I have:

HEEDLS-962 Add prompt name on ConfigureAnswers page

---

DigitalLearningSolutions.Web/Styles/verifyEmail/verifyEmail.scss
DigitalLearningSolutions.Web/Views/VerifyEmail/_NavMenuItems.cshtml

[HEEDLS-926](https://softwiretech.atlassian.net/browse/HEEDLS-926)
Fixed the failing test comments: made the logout button be read as a link by the screen reader and change pointer to a hand when hovering over it.
-----
I have:

HEEDLS-926 Make logout button have link role and change pointer on hover

---

DigitalLearningSolutions.Data.Tests/TestHelpers/UserTestHelper.cs
DigitalLearningSolutions.Data/DataServices/UserDataService/DelegateUserDataService.cs
DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs
DigitalLearningSolutions.Data/Models/User/UserCentreDetails.cs
DigitalLearningSolutions.Data/Services/UserService.cs
DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/EditDelegateControllerTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/ViewDelegateControllerTests.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/EditDelegateController.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/EditDelegate/Index.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-951
- Fix incorrect typing on UserCentreDetails.EmailVerified causing exception in Edit Delegate page
- Move Job group above PRN to match the Edit details page
- Change data service so Users.DetailsLastChecked is not updated in this journey
- Adjust email saving logic so if the admin does not edit the centre email from the primary email default, no new centre email is saved. But if the admin changes a delegate's centre email to match the primary email, this is saved as their centre email rather than clearing the value.
-----
I have:

HEEDLS-951 Fix incorrect property type in UserCentreDetails

---

DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateCourseProgressButtons.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-971
Add missing customisationId route parameter from unlock link
N/A
-----
I have:

HEEDLS-971 Fix missing route parameter on unlock link

---

DigitalLearningSolutions.Data.Migrations/202202140841_AddReviewerCommentsFieldToSelfassessment.cs
DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs
DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs
DigitalLearningSolutions.Data/Models/SelfAssessments/CurrentSelfAssessment.cs
DigitalLearningSolutions.Data/Models/SelfAssessments/SupervisorComment.cs
DigitalLearningSolutions.Data/Models/Supervisor/DelegateSelfAssessment.cs
DigitalLearningSolutions.Data/Services/SupervisorService.cs
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SignOffHistory.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SupervisorComments.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/ReviewCompetencySelfAsessment.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/Shared/_SignOffHistory.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/Shared/_SupervisorSignOffSummary.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/SignOffHistory.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/SignOffProfileAssessment.cshtml

[DLSV2-482](https://hee-dls.atlassian.net/browse/DLSV2-482)
Adds a new field to self assessments table to store a custom label for reviewer comments. When populated this custom label is used in place of the default "Reviewer comments" text throughout the supervisor and self assessment interface. The Excel export hasn't been updated because this is due to be replaced with PDF export soon.
I have:

DLSV2-482 Custom self asssessment reviewer comments label

---

DigitalLearningSolutions.Data.Migrations/202202140841_AddReviewerCommentsFieldToSelfassessment.cs
DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs
DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs
DigitalLearningSolutions.Data/Models/SelfAssessments/CurrentSelfAssessment.cs
DigitalLearningSolutions.Data/Models/SelfAssessments/SupervisorComment.cs
DigitalLearningSolutions.Data/Models/Supervisor/DelegateSelfAssessment.cs
DigitalLearningSolutions.Data/Services/SupervisorService.cs
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SignOffHistory.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SupervisorComments.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/ReviewCompetencySelfAsessment.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/Shared/_SignOffHistory.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/Shared/_SupervisorSignOffSummary.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/SignOffHistory.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/SignOffProfileAssessment.cshtml

[DLSV2-482](https://hee-dls.atlassian.net/browse/DLSV2-482)
Adds a custom reviewer comments label field to self assessments. Displays custom label text in place of default "Reviewer comments" text when custom label field is populated throughout the supervisor and self assessment views. Excel export not updated because we plan to replace this with PDF export soon.
-----
I have:

DLSV2-482 Custom self assessment reviewer comments label

---

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentCompetency.cshtml

[DLSV2-568](https://hee-dls.atlassian.net/browse/DLSV2-568)
Minor link label tweak on self assessment competency view
-----
I have:

DLSV2-568 Fixes return link label to include "home"

---

DigitalLearningSolutions.Data.Migrations/RecurringSqlJobs/DeleteResetPasswordRecordsOlderThan4Days.sql

[_HEEDLS-959_](https://softwiretech.atlassian.net/browse/HEEDLS-959)
Clear ResetPasswordIDs on AdminUsers as well as Candidates.
-----
I have:

HEEDLS-959 Clear old ResetPasswordIDs on admins

---

DigitalLearningSolutions.Web.Tests/Controllers/MyAccount/MyAccountControllerTests.cs
DigitalLearningSolutions.Web.Tests/Helpers/StringHelperTests.cs
DigitalLearningSolutions.Web/Controllers/MyAccountController.cs
DigitalLearningSolutions.Web/Helpers/StringHelper.cs
DigitalLearningSolutions.Web/Startup.cs

https://softwiretech.atlassian.net/browse/HEEDLS-879
Fixed crash when switch centres to an account that would force a details check. 
The returnUrl to /Home/Welcome when switching centres would be UrlEncoded when it didn't need to be. So when the forced details check occurred and tried to grab the sub application from the return URL, it could not find any forward slashes (as they were encoded), and therefore crashed. We no longer needed the encoding here, so I've moved that logic out of the common helper method.
N/A
-----
I have:

UAR-879 - fix return url encoding when switching centres

---

DigitalLearningSolutions.Web/Controllers/FrameworksController/ImportCompetencies.cs
DigitalLearningSolutions.Web/Views/Frameworks/Developer/_Structure.cshtml

[_HEEDLS-XXXX_](https://hee-dls.atlassian.net/browse/DLSV2-557)
tabname parameter added to FrameworksController and cancel link in View
-----
I have:

DLSV2-557 - DLSV2-557-crash-when-cancelling-import-competencies-to-framework

---

DigitalLearningSolutions.Data.Migrations/202206291527_AddContactUsConfigRecord.cs
DigitalLearningSolutions.Data/DataServices/ConfigDataService.cs
DigitalLearningSolutions.Web/Controllers/LearningSolutions/LearningSolutionsController.cs
DigitalLearningSolutions.Web/ViewModels/LearningSolutions/ContactViewModel.cs
DigitalLearningSolutions.Web/Views/LearningSolutions/Contact.cshtml
DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml

[DLSV2-575](https://hee-dls.atlassian.net/browse/DLSV2-575)
Adds a contact us page linked to from the site layout template footer. The text for the contact us page is stored as a HTML string to the config table in the database and a migration is used to populate a starter config string.
Also adds visually hidden text to footer links to tell screenreader users that the links will open in new browser windows.
-----
I have:

DLSV2-575 Adds contact us page linked from site footer

---

DigitalLearningSolutions.Data/Enums/SelfAssessmentCompetencyFilter.cs
DigitalLearningSolutions.Data/Services/FrameworkService.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs
DigitalLearningSolutions.Web/Extensions/EnumExtensions.cs
DigitalLearningSolutions.Web/Extensions/EnumerableExtensions.cs
DigitalLearningSolutions.Web/Helpers/CompetencyFilterHelper.cs
DigitalLearningSolutions.Web/ViewModels/Common/SearchablePage/AppliedFilterViewModel.cs
DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/SearchSelfAssessmentOvervieviewViewModel.cs
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_SearchSelfAssessmentOverview.cshtml
DigitalLearningSolutions.Web/Views/Shared/SearchablePage/_AppliedFilterTag.cshtml
DigitalLearningSolutions.Web/Views/Shared/_ComperencyFlags.cshtml

https://hee-dls.atlassian.net/browse/DLSV2-561
The dropdown of filters was reworked to allow any integer value instead of being restricted to values in the enum `SelfAssessmentCompetencyFilter`. The enum is still being used in the code to identify requirement filters and response filters by their negative values. If positive, the flag filter represents a flagId on table CompetencyFilters. This change only affects the dropdown, as the view itself still uses `AppliedFilterViewModel` object. Also created helper class `CompetencyFilterHelper` to organise the code.
-----
Tried multiple combinations of searches for texts with requirements filters, response filters and competency flag filters. Ran searches from Learning Portal application while edit the items from the Framework application. …

DLSV2-561 Filter self assessment competencies by flag

---

DigitalLearningSolutions.Data.Migrations/202206291720_AddIncludeRequirementsFiltersToSelfAssessmentsTable.cs
DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs
DigitalLearningSolutions.Data/Enums/SelfAssessmentCompetencyFilter.cs
DigitalLearningSolutions.Data/Models/SelfAssessments/CurrentSelfAssessment.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/SelfAssessmentTests.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs
DigitalLearningSolutions.Web/Extensions/EnumExtensions.cs
DigitalLearningSolutions.Web/Helpers/CompetencyFilterHelper.cs
DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/SearchSelfAssessmentOvervieviewViewModel.cs
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_SearchSelfAssessmentOverview.cshtml

https://hee-dls.atlassian.net/browse/DLSV2-563
Updated views, controller,  helper class and enums. Added migration for creating new column `IncludeRequirementsFilters` with default value `false`. Rebased against release branch 22.7.1.
-----
I have checked that:
- Items on filter dropdown appear in the required order.
- When `IncludeRequirementsFilters` field is set to `true` in table SelfAssessments:
- requirements filters are included in the filters dropdown.
- When `IncludeRequirementsFilters` field is set to `false` in table SelfAssessments:
- requirements filters are not included in the filters dropdown.
- Filter functionality still works after rebasing above changes for [DLSV2-561] included in [PR 1234](https://github.com/TechnologyEnhancedLearning/DLSV2/pull/1243) coming from …

DLSV2-563 Final adjustments to self assessment overview filters

---

DigitalLearningSolutions.Web/Controllers/FrameworksController/Competencies.cs

Fixes bug: when creating a new competency with flags, the flags are not added to the competency.
https://hee-dls.atlassian.net/browse/DLSV2-523
Calling the method `UpdateCompetencyFlags` for updating/inserting flags, after inserting a new competency and newFrameworkCompetency in Competencies.cs.
-----
Created new competency from scratch including flags.

DLSV2-523 Fixes bug: flags not being added when creating new competency

---

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentCompetency.cshtml

[DLSV2-568](https://hee-dls.atlassian.net/browse/DLSV2-568)
Appends the word " home" to the return link on self assess competency view for non-linear navigation self asssessments.
-----
I have:

DLSV2-568 Appends home to link text for non-linear self assessment

---

DigitalLearningSolutions.Web/Controllers/FrameworksController/ImportCompetencies.cs

[DLSV2-557](https://hee-dls.atlassian.net/browse/DLSV2-557)
Small fix which tweaks http post url template for import competencies to include the tabname parameter to ensure cancel button passes this to the ViewFramework method.
-----
I have:

DLSV2-557 Adds tabname to url template for http post

---

DigitalLearningSolutions.Data/Services/FrameworkService.cs

[DLSV2-544](https://hee-dls.atlassian.net/browse/DLSV2-544)
The code which checks for the use of the competency group in other frameworks before updating has been tweaked to handle the new competency group description field.
-----
I have:

DLSV2-544 Handles competency groups when checking for use in other frameworks

---

DigitalLearningSolutions.Data.Tests/Services/UserServiceTests.cs
DigitalLearningSolutions.Data/Services/UserService.cs
DigitalLearningSolutions.Web/Controllers/MyAccountController.cs

_[HEEDLS-970](https://softwiretech.atlassian.net/browse/HEEDLS-970)_
Added checks for delegate account activity to MyAccountController methods and ShouldForceDetailsCheck
N/A
-----
I have:

Heedls 970 myaccount not show inactive delegates

---

DigitalLearningSolutions.Data/Services/FrameworkService.cs
DigitalLearningSolutions.Web/appsettings.json

[DLSV2-544](https://hee-dls.atlassian.net/browse/DLSV2-544)
Fixes problem with null propagation in SQL script that resulted in failing to match a competency group if the competency group description was null.
Also, resets appsettings Unit test connection string inadvertently checked in after being changed by another dev on this branch.
-----
I have:

DLSV2-544 Fixes relating to failed service test and reverts changes to appsettings

---

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs
DigitalLearningSolutions.Data/Models/SelfAssessments/SupervisorComment.cs
DigitalLearningSolutions.Data/Services/SelfAssessmentService.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs
DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/SupervisorCommentsViewModel.cs
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SupervisorComments.cshtml

[DLSV2-558](https://hee-dls.atlassian.net/browse/DLSV2-558)
Removes get supervisor for self assessment service and reference to it in supervisor comments view model. Adds supervisor name and role to the SupervisorComments model and adds them to the query in the existing data service. Updates the view to use the name and role from the supervisor comments model.
-----
I have:

DLSV2-558 Fixes reading of supervisor details for supervisor comment VM

---

DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs
DigitalLearningSolutions.Web/Views/Supervisor/ReviewCompetencySelfAsessment.cshtml

https://hee-dls.atlassian.net/browse/DLSV2-578
Retrieved the competency flags for a self assessment result and displayed them using existent shared partial view for rendering flags on a view.
-----
I have:
Tested cases when there are no flags, one flag and multiple flags for a self assessment result.

DLSV2-578 Competency tags missing on the Self Assessment Results page

---

DigitalLearningSolutions.Data.Tests/DataServices/PasswordResetDataServiceTests.cs
DigitalLearningSolutions.Data.Tests/DataServices/RegistrationConfirmationDataServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/DelegateUploadFileServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/LearningHubSsoSecurityServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/PasswordResetServiceTests.cs
DigitalLearningSolutions.Data/DataServices/RegistrationConfirmationDataService.cs
DigitalLearningSolutions.Data/DataServices/UserDataService/DelegateUserDataService.cs
DigitalLearningSolutions.Data/Models/Auth/RegistrationConfirmationModel.cs
DigitalLearningSolutions.Data/Models/Auth/ResetPasswordCreateModel.cs
DigitalLearningSolutions.Data/Models/User/DelegateAccount.cs
DigitalLearningSolutions.Data/Services/ClockService.cs
DigitalLearningSolutions.Data/Services/DelegateUploadFileService.cs
DigitalLearningSolutions.Data/Services/PasswordResetService.cs
DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests/RegistrationJourneyAccessibilityTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/Register/RegisterDelegateByCentreControllerTests.cs
DigitalLearningSolutions.Web.Tests/Models/DelegateRegistrationByCentreDataTests.cs
DigitalLearningSolutions.Web/Controllers/Register/RegisterDelegateByCentreController.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/BulkUploadController.cs
DigitalLearningSolutions.Web/Models/DelegateRegistrationByCentreData.cs
DigitalLearningSolutions.Web/Startup.cs
DigitalLearningSolutions.Web/ViewModels/Register/RegisterDelegateByCentre/ConfirmationViewModel.cs
DigitalLearningSolutions.Web/ViewModels/Register/RegisterDelegateByCentre/SummaryViewModel.cs
DigitalLearningSolutions.Web/ViewModels/Register/RegisterDelegateByCentre/WelcomeEmailViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/UploadDelegatesViewModel.cs
DigitalLearningSolutions.Web/Views/RegisterDelegateByCentre/Confirmation.cshtml
DigitalLearningSolutions.Web/Views/RegisterDelegateByCentre/Summary.cshtml
DigitalLearningSolutions.Web/Views/RegisterDelegateByCentre/WelcomeEmail.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/BulkUpload/StartUpload.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-982
* It is now mandatory to send welcome emails to delegates created by the bulk upload and register-by-admin journeys
* The label for email delivery date in the UI has been changed so that it makes sense now that the optional checkbox has been removed
* The welcome email will link to /CompleteRegistration, which is currently not implemented
* RegistrationConfirmationHash and RegistrationConfirmationHashCreationDateTime are populated in the database for new DelegateAccounts during these journeys, and for other journeys where welcome emails are sent, rather than creating a reset password record
* The register-by-admin summary page now always shows whether a password has been set
Bulk upload journey - start upload step
Register by admin …

Heedls 982 update welcome emails

---

DigitalLearningSolutions.Web/Helpers/PromptsService.cs
DigitalLearningSolutions.Web/ViewModels/Common/EditAccountDetailsFormDataBase.cs
DigitalLearningSolutions.Web/ViewModels/Common/EditDetailsFormData.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/EditDelegate/EditDelegateFormData.cs

https://softwiretech.atlassian.net/browse/HEEDLS-1006
This bug was caused by changes made in https://softwiretech.atlassian.net/browse/HEEDLS-973: the new user is created with a primary email which is a GUID, which is present in a hidden field on the edit delegate page. Validation then takes place on this field, which fails because the format of the email address is incorrect.
To fix this, I have changed the `EditDelegateFormData` ViewModel so that it no longer inherits from the `EditDetailsFormData`, ViewModel which is where the primary email validation was taking place. As these two ViewModels are very similar, I have created a new abstract base class (`EditAccountDetailsFormDataBase`), which they now both inherit from
-----
(Leave tasks unticked if they haven't been appropriate for …

HEEDLS-1006 Fixed being unable to edit delegate details when primary email is a GUID

---

DigitalLearningSolutions.Web.Tests/Controllers/MyAccount/MyAccountControllerTests.cs
DigitalLearningSolutions.Web/Controllers/MyAccountController.cs

_[HEEDLS-970](https://softwiretech.atlassian.net/browse/HEEDLS-970)_
The centre-specific details are no longer validated if the delegate account is inactive. 
N/A
-----
I have:

Heedls 970b fix validation missing delegate

---

DigitalLearningSolutions.Data.Tests/Services/RegistrationServiceTests.cs
DigitalLearningSolutions.Data/DataServices/NotificationDataService.cs

[DLSV2-598](https://hee-dls.atlassian.net/browse/DLSV2-598)
Fixes the notification service, get recipients for notification query and related data tests.
-----
I have:

DLSV2-598 Fixes get recipient query and data tests

---

DigitalLearningSolutions.Web.Tests/Controllers/Register/RegisterDelegateByCentreControllerTests.cs
DigitalLearningSolutions.Web/Controllers/Register/RegisterDelegateByCentreController.cs
DigitalLearningSolutions.Web/Services/PasswordResetService.cs
DigitalLearningSolutions.Web/Services/RegistrationService.cs

https://softwiretech.atlassian.net/browse/HEEDLS-982
When an admin registers a new delegate at a centre, always send them a welcome email, regardless of whether the admin set a password or not.
Note: there was a bad unit test for this functionality: it only tested that an email is scheduled when a password is not set, despite the code in the service (both now and in the commit when the test was written) being 
```
if (password is set) { set password in the database } 
else if (notify date is set) { schedule welcome email }
```
Since I have changed this to two separate if statements, the test is no longer problematic, and doesn't need to be changed
-----
I have:

Heedls 982 send email when password set

---

DigitalLearningSolutions.Web.Tests/Services/RegistrationServiceTests.cs
DigitalLearningSolutions.Web/Controllers/Register/RegisterInternalAdminController.cs
DigitalLearningSolutions.Web/Services/RegistrationService.cs

[HEEDLS-902](https://softwiretech.atlassian.net/browse/HEEDLS-902)
I fixed the exception that was being thrown when creating the delegate account during the internal admin self registration journey.
I am a bit unsure if I should change `RegistrationService.ValidateCentreEmail` to have the `idOfRegistrantIfAlreadyExisting
` non nullable. Currently, both uses of this function provide an id, but I am inclined to leave it as it is to be more general for future use.
-----
I have:

HEEDLS-902 Fix registration of delegate when registering internal admin

---

DigitalLearningSolutions.Data/Models/User/AdminEntity.cs

[HEEDLS-1007](https://softwiretech.atlassian.net/browse/HEEDLS-1007)
There was a bug on the admins page, when the user was writing some text in the search bar and then refreshing. An exception was being thrown in `GenericSearchHelper.SearchItems`, on line 65: `var query = Activator.CreateInstance(typeof(T)) as BaseSearchableItem;`. The exception was saying that `AdminEntity` (which was the type `T` in this case) has no parameterless constructor.
-----
I have:

HEEDLS-1007 Add parameterless constructor to AdminEntity

---

DigitalLearningSolutions.Web/Views/RegisterAtNewCentre/Confirmation.cshtml

[HEEDLS-1009](https://softwiretech.atlassian.net/browse/HEEDLS-1009)
Changed text and button on the confirmation page after registration at a new centre.
-----
I have:

HEEDLS-1009 Tell registrants to swiych centre rather than log out

---

DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests/UserCentreDetailsDataServiceTests.cs
DigitalLearningSolutions.Data/DataServices/RegistrationDataService.cs
DigitalLearningSolutions.Data/DataServices/UserDataService/UserCentreDetailsDataService.cs
DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs
DigitalLearningSolutions.Web.Tests/Controllers/Register/RegisterInternalAdminControllerTests.cs
DigitalLearningSolutions.Web.Tests/Services/ClaimAccountServiceTests.cs
DigitalLearningSolutions.Web.Tests/Services/DelegateUploadFileServiceTests.cs
DigitalLearningSolutions.Web.Tests/Services/UserServiceTests.cs
DigitalLearningSolutions.Web/Services/UserService.cs

[HEEDLS-966](https://softwiretech.atlassian.net/browse/HEEDLS-966)
I added a new parameter for the `emailVerified` date to `UserCentreDetailsDataService.SetCentreEmail`.
-----
I have:

HEEDLS-966 Mark centre email verified if set by admin

---

DigitalLearningSolutions.Web/Controllers/ApplicationSelectorController.cs
DigitalLearningSolutions.Web/Controllers/VerifyEmailController.cs
DigitalLearningSolutions.Web/Helpers/CustomClaimHelper.cs
DigitalLearningSolutions.Web/Helpers/CustomPolicies.cs
DigitalLearningSolutions.Web/Startup.cs
DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml

_[HEEDLS-996](https://softwiretech.atlassian.net/browse/HEEDLS-996)_
Added appropriate policies to ApplicationSelectorController and VerifyEmailController so that they are no longer. Also involves a new policy and a refactor of the CustomPolicies to de-duplicate code.
N/A
-----
I have:

HEEDLS-996 add authorisation policies to bare authorised pages

---

DigitalLearningSolutions.Data/Models/User/RegistrationFieldAnswers.cs
DigitalLearningSolutions.Web.Tests/Services/GroupServiceTests/GroupsServiceSynchroniseGroupsTests.cs
DigitalLearningSolutions.Web.Tests/Services/RegistrationServiceTests.cs
DigitalLearningSolutions.Web.Tests/Services/UserServiceTests.cs
DigitalLearningSolutions.Web/Services/GroupsService.cs
DigitalLearningSolutions.Web/Services/RegistrationService.cs
DigitalLearningSolutions.Web/Services/UserService.cs

_[HEEDLS-874](https://softwiretech.atlassian.net/browse/HEEDLS-874)_
The groups to synchronise with are now properly selected for new registrations or edits to established users, and a bug in the composition of the `RegistrationFieldAnswers` object in the `UserService` has been fixed.
Some simple new methods have not had tests added. 
N/A
-----
I have:

Heedls 874b fix synchronisation

---

DigitalLearningSolutions.Web/Views/Supervisor/RemoveConfirm.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/Shared/_StaffMemberCard.cshtml

https://hee-dls.atlassian.net/browse/DLSV2-560
Fixing unsupported operation (http 405 error) caused by a mismatch of parameters being submitted to controller action `RemoveSupervisorDelegate()` method. Confirmation dialog is shown only when there are candidate assessments. So, depending on if there are candidate assessments, I am rendering a link to RemoveConfirm.cshtml or a post button for removing the delegate straightaway. 
Despite views _StaffMemberCard.cshtml and RemoveConfirm.cshtml are using different models, I can call the same post method, since `Hidden` helper in the view allows me to set the name of individual fields in the post  (unlike `HiddenFor` that takes the name from model).
-----
Checked both scenarios: deleting a delegate straightaway or deleting with confirmation. …

DLSV2-560 Remove Staff member from my staff list results in error

---

DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests/AdminUserDataServiceTests.cs
DigitalLearningSolutions.Data/DataServices/UserDataService/AdminUserDataService.cs
DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs
DigitalLearningSolutions.Web.Tests/Controllers/MyAccount/MyAccountControllerTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/Register/RegisterAdminControllerTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/Register/RegisterInternalAdminControllerTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Centre/Administrator/AdministratorControllerTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/EditDelegateControllerTests.cs
DigitalLearningSolutions.Web.Tests/Helpers/RegistrationEmailValidatorTests.cs
DigitalLearningSolutions.Web.Tests/Services/CentresServiceTests.cs
DigitalLearningSolutions.Web.Tests/Services/RegisterAdminServiceTests.cs
DigitalLearningSolutions.Web/Controllers/MyAccountController.cs
DigitalLearningSolutions.Web/Controllers/Register/RegisterAdminController.cs
DigitalLearningSolutions.Web/Controllers/Register/RegisterAtNewCentreController.cs
DigitalLearningSolutions.Web/Controllers/Register/RegisterController.cs
DigitalLearningSolutions.Web/Controllers/Register/RegisterDelegateByCentreController.cs
DigitalLearningSolutions.Web/Controllers/Register/RegisterInternalAdminController.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Administrator/AdministratorController.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/EditDelegateController.cs
DigitalLearningSolutions.Web/Helpers/CommonValidationErrorMessages.cs
DigitalLearningSolutions.Web/Helpers/RegistrationEmailValidator.cs
DigitalLearningSolutions.Web/Services/CentresService.cs
DigitalLearningSolutions.Web/Services/RegisterAdminService.cs
DigitalLearningSolutions.Web/Views/Register/Index.cshtml
DigitalLearningSolutions.Web/Views/RegisterInternalAdmin/Index.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-902
* Redirect from `/RegisterAdmin?centreId=1` to `/RegisterInternalAdmin?centreId=1` when the user is logged in
* Added word-wrap to a couple of views which display CentreName
* Redirect to access denied when trying to access the internal admin registration journey as a user who is already an admin at the centre
* Changes to registration journey error messages:
- Internal admin registration journey (/RegisterInternalAdmin):
- If you enter a centre email which is already in use at the centre, the error message has changed:
- from "A user with this email address is already registered; if this is you, please log in and register at this centre via the My Account page"
- to "This email is in already use by another user at the centre"
- …

Heedls 902 bug fixes

---

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/DCSAReportDataService.cs
DigitalLearningSolutions.Data/Models/SelfAssessments/Export/DCSADelegateCompletionStatus.cs
DigitalLearningSolutions.Data/Models/SelfAssessments/Export/DCSAOutcomeSummary.cs
DigitalLearningSolutions.Data/Services/SelfAssessmentReportService.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Reports/ReportsController.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/SelfAssessmentReports/SelfAssessmentReportsController.cs
DigitalLearningSolutions.Web/Models/Enums/CentrePage.cs
DigitalLearningSolutions.Web/Startup.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/SelfAssessmentReports/Index.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Shared/_CentreSideNavMenu.cshtml

[DLSV2-597](https://hee-dls.atlassian.net/browse/DLSV2-597)
Implements a new "Self assessment reports" view with a link to the temporary digital capability self assessment report (rebuilt with additional enrolled month and enrolled year fields).
-----
I have:

DLSV2-597 TS Self assessment report view with DCSA report link

---

DigitalLearningSolutions.Web/Views/Frameworks/Developer/AddCompetencyLearningResources.cshtml

This fixes reported bug by indicating when a catalogue is restricted in the Catalogues dropdown.
https://hee-dls.atlassian.net/browse/DLSV2-573
Added the text _" (Restricted)"_ to the catalogue name when a catalogue is restricted in the Catalogues dropdown. The flag `IsRestricted `is populated with the information retrieved from LearningHub api.
-----
Checked that "Restricted" text:
* Is added when LearningHub api returns isRestricted for a catalogue
* Is only added to the dropdown items and is not shown elsewhere in the application.

DLSV2-573 Add catalogue filtering to Signposting

---

DigitalLearningSolutions.Web.Tests/Controllers/Login/LoginControllerTests.cs
DigitalLearningSolutions.Web/Controllers/LoginController.cs
DigitalLearningSolutions.Web/Views/Shared/Components/VerifyEmailWarningIfAppropriate/Default.cshtml
DigitalLearningSolutions.Web/Views/VerifyYourEmail/Index.cshtml

[_HEEDLS-923_](https://softwiretech.atlassian.net/browse/HEEDLS-923)
Added route value to the redirect to Verify Email page in the ChooseCentre endpoint, and added word-break to the verify email warnings and verify email page
-----
I have:

HEEDLS-923 handle unverified emails

---

DigitalLearningSolutions.Web/Views/RegisterAtNewCentre/LearnerInformation.cshtml

https://softwiretech.atlassian.net/browse/HEEDLS-877
Fixed back link on `/RegisterAtNewCentre/LearnerInformation` so that it uses the `RegisterAtNewCentre` controller instead of the `Register` controller.
-----
I have:

HEEDLS-877 Fixed Back link on RegisterAtNewCentre/LearnerInformation

---

DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests/UserCentreDetailsDataServiceTests.cs
DigitalLearningSolutions.Data/DataServices/UserDataService/UserCentreDetailsDataService.cs

https://softwiretech.atlassian.net/browse/HEEDLS-1044
`GetAllCentreEmailsForUser` is only used by the `MyAccountController` to display/edit the list of centre emails when a user is not logged in to a centre. I have changed the query so that centre emails for centres where the user only has an inactive admin account are not returned.
-----
I have:

HEEDLS-1044 Make GetAllCentreEmailsForUser omit emails from inactive admin accounts

---

DigitalLearningSolutions.Web.Tests/Services/DelegateUploadFileServiceTests.cs
DigitalLearningSolutions.Web/Services/DelegateUploadFileService.cs

https://softwiretech.atlassian.net/browse/HEEDLS-874
The previous code was using the wrong job group id when calling `UpdateSynchronisedDelegateGroupsBasedOnUserChanges` - it was using the id from before the update, rather than after. As a result, job group id changes in bulk upload did not trigger group changes in the database, although Answer[n] column changes did.
-----
I have:

HEEDLS-874 Use new job group id when updating delegate groups in bulk upload

---

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_SelfAssessmentOverallProgress.cshtml

Repeat overall progress for self assessment at top of overview page.
https://hee-dls.atlassian.net/browse/DLSV2-564
So far, totals were being calculated as the page is rendered and each competency group is displayed. For that reason, we cannot simply copy/paste "Overall Progress" section to the beginning of the page, since totals are zero at that point. So I have generated counts I need beforehand and passed them to a new partial view for displaying that "Overall Progress" section on top and bottom of the page.
-----
- Checked that counts displayed on the page for each competency group were the same before and after my changes. 
Because the new implementation uses an enumerator and I am assuming competency groups order wouldn't change, I did a screen capture and checked counts displayed …

DLSV2-564 Repeat overall progress for self assessment at top of overview page

---

DigitalLearningSolutions.Data.Migrations/202208101435_AddMaxSignpostedResourcesConfigValue.cs
DigitalLearningSolutions.Data.Tests/Services/LearningHubResourceServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/RecommendedLearningServiceTests.cs
DigitalLearningSolutions.Data/DataServices/ConfigDataService.cs
DigitalLearningSolutions.Data/Services/LearningHubResourceService.cs
DigitalLearningSolutions.Data/Services/RecommendedLearningService.cs
DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests/BasicAuthenticatedAccessibilityTests.cs
DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests/ReportsControllerAccessibilityTests.cs

https://softwiretech.atlassian.net/browse/HEEDLS-1036
* Migration to add `MaxSignpostedResources` = 150 to the Config database table.
* Limit the number of resource ids given to `learningHubResourceService.GetBulkResourcesByReferenceIds` to `Config.MaxSignpostedResources`
* Order resources returned from the API by descending `RecommendationScore`
-----
I have:

HEEDLS-1036 Only request 150 resources from Learning Hub API

---

DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs

When adding new supervisor, `TempDataKey` should be used for checking existing session.
https://hee-dls.atlassian.net/browse/DLSV2-604
MultiPageFormService.cs uses `feature.TempDataKey` as key to find session in database. Attempting to pass `feature` instead of `feature.TempDataKey` would result in session not found and causes a redirection to "You don't have permission" page (http 403 forbidden).
https://localhost:44363/LearningPortal/SelfAssessment/1/Supervisors
- Checked that session is retrieved correctly after applying the fix
- Searched for other cases where `TempData[MultiPageFormDataFeature` is used instead of `TempData[MultiPageFormDataFeature.TempDataKey` causing similar error in other parts of the application

DLSV2-604 When adding new supervisor, TempDataKey should be used for checking existing session

---

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs

[DLSV2-625](https://hee-dls.atlassian.net/browse/DLSV2-625)
Adds an INNER JOIN to CompetencyAssessmentQuestions to the Row Number part of the GetNthCompetency query to ensure a 1-1 match with the competencies in the result set. this ensures that the links on the self assessment overview are valid and matched.
-----
I have:

DLSV2-625 Fixes broken self assessment overview links

---

DigitalLearningSolutions.Data/ApiClients/LearningHubApiClient.cs

[_HEEDLS-1035_](https://softwiretech.atlassian.net/browse/HEEDLS-1035)
Adjusted the bulk endpoint in the LearningHubApiClient to call the new BulkJson endpoint with a Json of the reference Ids.
-----
I have:

Heedls 1035 bulk resource json endpoint

---

DigitalLearningSolutions.Web/Views/Supervisor/SignOffProfileAssessment.cshtml

[_HEEDLS-XXXX_](https://hee-dls.atlassian.net/browse/DLSV2-614)
In Supervisor → My Staff → Review Self Assessment where a self assessment has a sign off request, reviewing the sign-off request loads some HTML from db, when it does, this text is displayed as plain text with HTML tags instead of as HTML
-----
I have:
- [X ] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [X ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.

DLSV2-614 Sign-off profile self-assessment text - HTML tags visible

---

DigitalLearningSolutions.Data.Tests/DataServices/CourseDataServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/CourseServiceTests.cs
DigitalLearningSolutions.Data/DataServices/CourseAdminFieldsDataService.cs
DigitalLearningSolutions.Data/DataServices/CourseDataService.cs
DigitalLearningSolutions.Data/Services/CourseService.cs

_[HEEDLS-1038](https://softwiretech.atlassian.net/browse/HEEDLS-1038)_
A number of methods have been changed to no longer exclude Archived courses. Some methods have been split into exclusionary and non-exclusionary versions. Only endpoints associated with the CourseSetup section of the Tracking System should exclude archived courses. Methods addressing a specific customisation or progress entry by ID should not exclude archived courses regardless of section. This ticket only pertains to the Tracking System.
N/A
-----
I have:

Heedls 1038 reinstate archived courses

---

DigitalLearningSolutions.Data.Tests/Services/RegistrationServiceTests.cs
DigitalLearningSolutions.Data/Services/RegistrationService.cs
DigitalLearningSolutions.Data/Services/SupervisorService.cs
DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests/BasicAuthenticatedAccessibilityTests.cs
DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs
DigitalLearningSolutions.Web/Controllers/SupervisorController/SupervisorController.cs
DigitalLearningSolutions.Web/ViewModels/Supervisor/SupervisorDelegateViewModel.cs
DigitalLearningSolutions.Web/Views/Supervisor/NominateSupervisor.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/RemoveConfirm.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/Shared/_StaffDetails.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/Shared/_StaffMemberCard.cshtml

[DLSV2-619](https://hee-dls.atlassian.net/browse/DLSV2-619)
Implements an interface for full Supervisors to promote members of their staff to the Nominated Supervisor role. This is available from the expanded staff card on the supervisor staff list for any member of staff who has "Learner" role. A confirmation screen is included and shares its view model with the similar remove staff member confirm screen.
Nominate supervisor button (for full supervisors only and for staff who are DLS role = learner only):
Confirmation page:
Confirm validation:
Nominated supervisor role granted:
-----
I have:

DLSV2-619 Supervisor promote staff to nominated supervisor

---

DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/SelfAssessmentTests.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs
DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/SelfAssessmentOverviewViewModel.cs
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_SearchSelfAssessmentOverview.cshtml

Learner - Adding a filter has enabled request sign off.
https://hee-dls.atlassian.net/browse/DLSV2-616
Button sign-off should be visible or not regardless of the filter applied by user. So I am running validation `AllQuestionsVerifiedOrNotRequired` on unfiltered competencies. 
-----
Checked that given a selfassessment that doesn't display sign-off button, user cannot make the button to appear by searching for confirmed competencies

DLSV2-616 Learner - Adding a filter has enabled request sign off

---

DigitalLearningSolutions.Data/Enums/LoginAttemptResult.cs
DigitalLearningSolutions.Data/Models/User/DelegateAccount.cs
DigitalLearningSolutions.Web.Tests/Controllers/Login/LoginControllerTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/Register/RegisterAdminControllerTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/Register/RegisterDelegateByCentreControllerTests.cs
DigitalLearningSolutions.Web.Tests/Helpers/RegistrationEmailValidatorTests.cs
DigitalLearningSolutions.Web.Tests/Services/DelegateUploadFileServiceTests.cs
DigitalLearningSolutions.Web.Tests/Services/LoginServiceTests.cs
DigitalLearningSolutions.Web.Tests/Services/PasswordResetServiceTests.cs
DigitalLearningSolutions.Web.Tests/Services/RegistrationServiceTests.cs
DigitalLearningSolutions.Web.Tests/Services/UserServiceTests.cs
DigitalLearningSolutions.Web/Controllers/LoginController.cs
DigitalLearningSolutions.Web/Controllers/Register/RegisterAdminController.cs
DigitalLearningSolutions.Web/Controllers/Register/RegisterDelegateByCentreController.cs
DigitalLearningSolutions.Web/Helpers/RegistrationEmailValidator.cs
DigitalLearningSolutions.Web/Helpers/RegistrationMappingHelper.cs
DigitalLearningSolutions.Web/Services/DelegateUploadFileService.cs
DigitalLearningSolutions.Web/Services/LoginService.cs
DigitalLearningSolutions.Web/Services/PasswordResetService.cs
DigitalLearningSolutions.Web/Services/RegistrationService.cs
DigitalLearningSolutions.Web/Services/UserService.cs

[_HEEDLS-1042_](https://softwiretech.atlassian.net/browse/HEEDLS-1042)
Tweaks to Register By Centre:
* Make user entity tied to unclaimed delegate active
* Prevent login to unclaimed delegate
* Prevent registration-by-centre of an email address which is being used as primary email by someone who already has a delegate account at the centre.
Upload where email matches primary email of existing delegate at centre
Register where email matches primary email of existing delegate at centre
-----
I have:

Heedls 1042 tweaks to register by centre

---

DigitalLearningSolutions.Web/Views/Shared/Components/NumericInput/Default.cshtml
DigitalLearningSolutions.Web/Views/Shared/Components/TextArea/Default.cshtml
DigitalLearningSolutions.Web/Views/Shared/Components/TextInput/Default.cshtml

[DLSV2-548](https://hee-dls.atlassian.net/browse/DLSV2-548)
Fixes missing aria reference issues found in testing by ensuring that error message ids are populated in view components that match the aria-labelledby of the control.
-----
I have:

DLSV2-548 Adds id to error div in view components

---

DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs

After deleting a delegate in Supervisor application (with confirmation prompt), prevent error as user navigates back by clicking browser's Back button.
https://hee-dls.atlassian.net/browse/DLSV2-560
Check that delegate is not null before returning delete confirmation page. If delegate is null, return to My Staff list, as the delegate is already deleted or it doesn't exists. 
-----
After confirming deletion, back button redirects to My Staff list.

DLSV2-560 Prevent error when navigating back after deleting a delegate

---

DigitalLearningSolutions.Data.Tests/DataServices/SelfAssessmentDataServiceTests/CandidateAssessmentsDataServiceTests.cs
DigitalLearningSolutions.Data.Tests/Services/ActionPlanServiceTests.cs
DigitalLearningSolutions.Data/DataServices/LearningLogItemsDataService.cs
DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs
DigitalLearningSolutions.Data/Models/SelfAssessments/CandidateAssessment.cs
DigitalLearningSolutions.Data/Services/ActionPlanService.cs

[_HEEDLS-1036_](https://softwiretech.atlassian.net/browse/HEEDLS-1036?focusedCommentId=269006)
Bug fix: When resources were being added to an action plan, an entity was being added to CandidateAssessmentLearningLogItems with the _self assessment id_ as the FK to _CandidateAssessments_. This was wrong: it should have been the _candidate assessment id_.
N/A
-----
I have:

HEEDLS-1036: Fix - use candidateAssessmentId instead of selfAssessmentId

---

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/ReviewConfirmationRequests.cshtml

Use competency name instead of competency description in Confirmation Requests view. Description could be blank in the database.
https://hee-dls.atlassian.net/browse/DLSV2-535
Edited `ReviewConfirmationRequests.cshtml` for using competency `Name` property instead of `Description`.
-----
Checked that there are no blank or null competency names in UAT database table Competencies: `select * from Competencies where [Name] is null or trim([Name]) = ''`

DLSV2-535 Use competency name instead of description in confirmation requests view

---

DigitalLearningSolutions.Web/Views/Supervisor/Index.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/NominateSupervisor.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/Shared/_StaffMemberCard.cshtml

[DLSV2-619](https://hee-dls.atlassian.net/browse/DLSV2-619)
Tweaks wording of new views and buttons in response to user feedback. Also removes promote button for not yet registered users.
New button label:
Tweaks to confirm wording:
Not shown for not registered staff:
-----
I have:

DLSV2-619 Tweaks to wording following feedback

---

DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests/UserCentreDetailsDataServiceTests.cs
DigitalLearningSolutions.Data/DataServices/UserDataService/UserCentreDetailsDataService.cs
DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs
DigitalLearningSolutions.Data/Models/EmailVerificationTransactionData.cs
DigitalLearningSolutions.Web.Tests/Controllers/VerifyEmailControllerTests.cs
DigitalLearningSolutions.Web.Tests/Services/UserServiceTests.cs
DigitalLearningSolutions.Web/Controllers/VerifyEmailController.cs
DigitalLearningSolutions.Web/Services/UserService.cs

[_HEEDLS-1024_](https://softwiretech.atlassian.net/browse/HEEDLS-1024?focusedCommentId=268685)
Fixed bug found with ticket.
When a user had the same email used at multiple centres / as primary email and as a centre-specific email, the verification logic would fail because it expected to verify only one account at a time.
I've made changes so that it will verify all instances of the email as long as they're of the same user.
N/A
-----
I have:
- I've moved tests around - it could be useful to think more carefully about tests, but this isn't a priority right now.

Heedls 1024 verify multiple accounts together

---

DigitalLearningSolutions.Data/ApiClients/LearningHubApiClient.cs

[DLSV2-649](https://hee-dls.atlassian.net/browse/DLSV2-649)
Adds missing parameter name to Resources/bulkJson API endpoint requests.
-----
I have:

DLSV2-649 Fixes LH OpenAPI client BulkJson requests

---

DigitalLearningSolutions.Web/Controllers/FrameworksController/Signposting.cs
DigitalLearningSolutions.Web/Helpers/SignpostingHelper.cs
DigitalLearningSolutions.Web/Views/Frameworks/Developer/AddCompetencyLearningResourceSummary.cshtml
DigitalLearningSolutions.Web/Views/Frameworks/Developer/_SignpostingCard.cshtml
DigitalLearningSolutions.Web/Views/Frameworks/Developer/_SignpostingResourceCard.cshtml

[DLSV2-648](https://hee-dls.atlassian.net/browse/DLSV2-648)
The new helper handles null and empty strings. We have replaced references to the old method SignpostingHelper.DisplayText() with the new method DisplayStringHelper.RemoveMarkup and removed the old method from the solution.
-----
I have:

DLSV2-648 Replaces and removes html tag removal string in signposting helper

---

DigitalLearningSolutions.Data.Migrations/202208301100_AllowNullSelfAssessmentResults.cs
DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs

This pull request is intended to fix a bug reported in Jira ticket comment. There was a previous PR for developing this functionality and it's already merged.
https://hee-dls.atlassian.net/browse/DLSV2-538
Made changes for inserting null result value on table `SelfAssessmentResults` when user clears previous assessment question result. 
Since queries already handle null results to cover a scenario where no result was yet provided, this would have less impact than inserting zeroes (e.g. sql `AVG()` ignores null values). After performing a `left join`, result would be null in both cases (no result ever provided or null result was inserted). Main difference between no result and a null result, is that result `id` is still a number if we have inserted a null result. Tried to find a scenario …

DLSV2-538 Add clear button for competency questions

---

DigitalLearningSolutions.Data/Models/Supervisor/SupervisorDelegate.cs
DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs

'Reviewed' field is missed with the details of the reviewed when Supervisor reviewed the results of self assessment on the 'Competency Self Assessment Results' Page.
https://hee-dls.atlassian.net/browse/DLSV2-606
Added supervisor name and verified date to the model before passing it to the view.
-----
- Confirmed multiple results and as a supervisor, followed the confirmation link.

DLSV2-606 Reviewed missing details

---

DigitalLearningSolutions.Data/Services/SupervisorService.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs

Manage Supervisor/Remove Supervisor, fails to remove the supervisor and it results in error.
https://hee-dls.atlassian.net/browse/DLSV2-569
**Introduction:** Since I cannot connect VS to UAT database I am guessing what the problem is based on database table relations and the code available.  There is a soft-delete on `SupervisorDelegates` and hard delete on `CandidateAssessmentSupervisor`. The later may be causing an error if the table is referenced from another table.
**Suggested solution:** Soft-delete `CandidateAssessmentSupervisors` if there are no records pointing to that table from `CandidateAssessmentSupervisorVerifications` nor `SelfAssessmentResultSupervisorVerifications`. Otherwise, a hard delete can be performed.
Any matching record in …

DLSV2-569 Remove Supervisor fails and results in an error

---

DigitalLearningSolutions.Web/Views/Frameworks/Developer/ImportCompleted.cshtml

[DLSV2-654](https://hee-dls.atlassian.net/browse/DLSV2-654)
Removes add tabname item to cancelLinkData dictionary because it already exists and threw an error when trying to load the import summary page.
-----
I have:

DLSV2-654 Fixes error after importing competencies

---

DigitalLearningSolutions.Data/Services/SupervisorService.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs

https://hee-dls.atlassian.net/browse/DLSV2-569
Added filter for removing supervisor delegate only for current selfassessment in Manage Supervisor view.
-----
Checked that: 
- It works when deleting same supervisor from two different selfassessments, so deleting one doesn't have any effect on the other one.
- Deleted supervisor then appears on quick add list.

DLSV2-569 Remove supervisor only for current selfassessment

---

DigitalLearningSolutions.Data.Tests/Services/FrameworkServiceTests.cs
DigitalLearningSolutions.Data/Services/FrameworkService.cs

https://hee-dls.atlassian.net/jira/software/projects/DLSV2/boards/1?selectedIssue=DLSV2-640
Where the user clicked the 'Add as Contributor' or 'Add as Reviewer' button on the 'Choose working group members' page, without entering an email address in the textbox, the system crashed with an unhandled null exception error and did not display a validation warning to the user.
The AddCollaboratorToFramework method in FrameworkService.cs was being passed in a null rather than empty string for userEmail, which is possible as it is directly called by the HttpPost AddCollaborator method in Frameworks.cs.
I updated the code to allow a null userEmail parameter and handle the error gracefully with a user validation error (see attached screenshots).
Screenshots attached.
-----
I have:
- …

DLSV2-640 Fixed validation on null userEmail

---

DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml

https://hee-dls.atlassian.net/browse/DLSV2-523
Self-assessment with multiple flags collapse without spacing
-----
I have:

DLSV2-523 competencies tags collapse issue

---

DigitalLearningSolutions.Web/Views/Frameworks/Developer/AddCompetencyLearningResources.cshtml

https://hee-dls.atlassian.net/jira/software/projects/DLSV2/boards/1?assignee=6321797ece3e476e42ac8a00&selectedIssue=DLSV2-646
Moved search results count text above new top pagination toolbar.
Expanded search textbox and dropdown to full width.
Screenshot attached
-----
I have:

Updated Add Competency Learning Resource search page layout.

---

DigitalLearningSolutions.Data/Services/FrameworkService.cs
DigitalLearningSolutions.Web/Controllers/FrameworksController/Competencies.cs

https://hee-dls.atlassian.net/browse/DLSV2-675
The sanitization has been removed from the service layer due to the need to use html utility in decoding the html string before performing a null or whitespace check. The sole reason for this is to ensure I dont use web components in the service layer.
A video of my test is in the corresponding jira page
-----
I have:

DLSV2-675 multiple empty space in framework description fix

---

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs
DigitalLearningSolutions.Data/Models/SelfAssessments/AssessmentQuestion.cs
DigitalLearningSolutions.Data/Services/SupervisorService.cs
DigitalLearningSolutions.Web/Views/Supervisor/ReviewCompetencySelfAsessment.cshtml

[DLSV2-682](https://hee-dls.atlassian.net/browse/DLSV2-682)
Display the name of the supervisor the assessment result has been submitted to, and the date it was submitted, Particularly when the supervisor viewing is not the one assigned to the assessment.
-----
I have:

DLSV2-682 supervisor pending confirmation results should display the name of the assessor that confirmation has been requested from

---

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs

DLSV2-682
Fixes issue with SupervisorName being missing from the LatestAssessmentResults query used to load data for the self assessment pages. Returns as null because supervisor name isn't currently used in the self assessment interface.
-----
I have:

DLSV2-682 Adds SupervisorName field to Query (Null return)

---

DigitalLearningSolutions.Web.Tests/Helpers/FilterableTagHelperTests.cs
DigitalLearningSolutions.Web/Helpers/FilterOptions/AdminFilterOptions.cs
DigitalLearningSolutions.Web/Helpers/FilterableTagHelper.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Administrator/AdministratorsViewModelFilterOptions.cs

[DLSV2-681](https://hee-dls.atlassian.net/browse/DLSV2-681)
Switch application → Tracking system → Administrators
Displays all admins at a centre with tags showing their admin roles.
The list can be filtered by role.
The screenshots can be found at https://hee-dls.atlassian.net/browse/DLSV2-681
-----
I have:

DLSV2-681 Add Centre Manager role tag and filtering to Centre Admins page

---

DigitalLearningSolutions.Data/Services/FrameworkService.cs

JIRA link
https://hee-dls.atlassian.net/browse/DLSV2-659
Description
Skipped adding framework competency to the competency group when it is null.
Screenshots
A screenshot is attached to the Jira ticket.
I have:
- [x ] Run the formatter and made sure there are no IDE errors.
- [x ] Manually tested my work with and without JavaScript
- [x ] Tested any Views or partials created or changed with [Wave Chrome plugin]

Skipped adding framework competency to the competency group when it is null.

---

DigitalLearningSolutions.Web/Views/Frameworks/Developer/_MyFrameworks.cshtml
DigitalLearningSolutions.Web/Views/Frameworks/Shared/_BrandedFrameworkTable.cshtml

JIRA link
[DLSV2-703](https://hee-dls.atlassian.net/browse/DLSV2-703)
Description
Search result count checks are implemented prior to displaying results. 
Screenshots
I have:

DLSV2-703 Search result count check implemented prior to display result.

---

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/EnrolController.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ViewDelegate/Index.cshtml

https://hee-dls.atlassian.net/browse/DLSV2-581
after UAT changes given for while delegate is inactive hide the button for the enrol and resolved the query issue for the submit.
The screenshots can be found at https://hee-dls.atlassian.net/browse/DLSV2-581
-----
I have:

DLSV2-581 removed enrol delegate button while the delegate is inactive and query

---

DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs
DigitalLearningSolutions.Web/Helpers/CommonValidationErrorMessages.cs
DigitalLearningSolutions.Web/ViewModels/Supervisor/AddMultipleSupervisorDelegatesViewModel.cs
DigitalLearningSolutions.Web/Views/Supervisor/AddMultipleSupervisorDelegates.cshtml

**JIRA link**
[https://hee-dls.atlassian.net/browse/DLSV2-695](url)
DataAnnotation added to model property 'DelegateEmails'. Code modified to handle email validation.
Screenshots
-----
I have:

DataAnnotation added to model property 'DelegateEmails'.

---

DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Enrol/EnrolDelegateSupervisor.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Enrol/Index.cshtml

https://hee-dls.atlassian.net/browse/DLSV2-712
in mobile view screens for enrol delegate is not showing proper
the screenshots can be found on https://hee-dls.atlassian.net/browse/DLSV2-712
-----
I have:

DLSV2-712 enrol delegate mobile responsive-design changes

---

DigitalLearningSolutions.Web/Views/Supervisor/AddMultipleSupervisorDelegates.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/MyStaffList.cshtml

**JIRA link**
https://hee-tis.atlassian.net/browse/TD-675
Missing hint text added to text box controls.
-----
I have:

Missing hint text added.

---

DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs
DigitalLearningSolutions.Web/ViewModels/Supervisor/SupervisorDelegateViewModel.cs
DigitalLearningSolutions.Web/Views/Supervisor/Shared/_StaffMemberCard.cshtml

[TD-572](https://hee-tis.atlassian.net/browse/TD-572)
Error message not displayed when trying to remove staff with no assessment
The name of the staff being removed is not displayed on the confirmation page when the staff has no assessment.
Kindly check the video on Jira
-----
I have:

Fix for Validation error when removing staff that has no assessment

---

DigitalLearningSolutions.Web/Controllers/FrameworksController/Comments.cs
DigitalLearningSolutions.Web/Controllers/FrameworksController/Review.cs

[TD-575](https://hee-dls.atlassian.net/browse/TD-575)
Error thrown when comment field is empty.
Kindly check the jira link for a video
-----
I have:

empty framework comment validation

---

DigitalLearningSolutions.Data/Services/FrameworkService.cs
DigitalLearningSolutions.Web/Controllers/FrameworksController/Competencies.cs

**JIRA link**
https://hee-tis.atlassian.net/browse/TD-570
The attribute route is modified to work when frameworkgroupId is null. SQL query updated to retrieve ungrouped competencies.
N/A
-----
I have:

TD-570 - Framework - Preview option resulted in error

---

DigitalLearningSolutions.Web/Views/Supervisor/AddMultipleSupervisorDelegates.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/MyStaffList.cshtml

**JIRA link**
https://hee-tis.atlassian.net/browse/TD-675
Description
Hint text modified.
-----
I have:
[x] Run the formatter and made sure there are no IDE errors.
[ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
[x] Manually tested my work with and without JavaScript
[x] Tested any Views or partials created or changed with [Wave Chrome plugin]
[ ] Updated/added documentation in [Confluence]
[ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken
[ ] Scanned over my own MR to ensure everything is as expected and it looks right in the browser

TD-675 hint text update

---

DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs
DigitalLearningSolutions.Web/Views/Shared/Components/TextInput/Default.cshtml

[TD-191](https://hee-dls.atlassian.net/browse/TD-191)
Prevent supervisor adding self to staff list
-----
I have:

TD-191 prevent user adding themself as a supervised member of staff

---

DigitalLearningSolutions.Data/Models/Frameworks/FrameworkCompetency.cs
DigitalLearningSolutions.Data/Services/FrameworkService.cs
DigitalLearningSolutions.Web/Controllers/FrameworksController/Competencies.cs
DigitalLearningSolutions.Web/ViewModels/Frameworks/SimilarCompetencyViewModel.cs
DigitalLearningSolutions.Web/Views/Frameworks/Developer/SimilarCompetency.cshtml

https://hee-tis.atlassian.net/browse/TD-499
When the user attempts to add a competency that matches an existing one, a warning message is displayed but the user is still allowed to create a duplicate competency if they wish to. Also, all the duplicate competencies are displayed to the user before they choose to create a duplicate.
Video is attached to the jira; https://hee-tis.atlassian.net/browse/TD-499
-----
I have:

TD-499 Fix problems with competency insert logic

---

DigitalLearningSolutions.Data.Tests/Services/EnrolServiceTest.cs
DigitalLearningSolutions.Data.Tests/Services/GroupServiceTests/GroupsServiceTests.cs
DigitalLearningSolutions.Data/Services/EnrolService.cs
DigitalLearningSolutions.Data/Services/GroupsService.cs

[TD-690](https://hee-tis.atlassian.net/browse/TD-690)
To prevent circular service references which were causing a build fail.
Fail details:
-----
I have:

TD-690 Replaces user and course service refs with data service refs

---

DigitalLearningSolutions.Web.Tests/Models/Enums/DlsSubApplicationTests.cs
DigitalLearningSolutions.Web/Models/Enums/DlsSubApplication.cs
DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml
DigitalLearningSolutions.Web/Views/Support/Shared/_SupportSideNavMenu.cshtml

[TD-721](https://hee-tis.atlassian.net/browse/TD-721)
Removal of the help link on the top menu bar and side navigation
-----
I have:

TD-721 : Removal of the Help menu item

---

DigitalLearningSolutions.Web/Views/Shared/_SetPasswordFields.cshtml

https://hee-tis.atlassian.net/browse/TD-776
Added the required attribute in password and confirm password vc:textinput. As password and confirm password fields are not showing over there.
https://hee-tis.atlassian.net/browse/TD-776
-----
I have:

TD-776: No Password Fields During Registration

---

DigitalLearningSolutions.Web.Tests/Controllers/Login/LoginControllerTests.cs
DigitalLearningSolutions.Web/Controllers/LoginController.cs

JIRA link
https://hee-tis.atlassian.net/browse/TD-761
Code added to check active centre count.
Screenshots
N/A
-----
I have:

TD-761-users-with-one-active-centre-UAR

---

DigitalLearningSolutions.Data/Extensions/StringExtensions.cs
DigitalLearningSolutions.Data/Models/SearchSortFilterPaginate/SearchSortFilterAndPaginateOptions.cs
DigitalLearningSolutions.Data/Services/SearchSortFilterPaginateService.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/AllDelegatesController.cs

**JIRA link**
https://hee-tis.atlassian.net/browse/TD-669
Delegate search implemented by Linq instead of Fuzzysharp.
-----
I have:

TD-669-Investigate reported problems with Delegate Search

---

DigitalLearningSolutions.Web/ViewModels/Register/SummaryViewModel.cs
DigitalLearningSolutions.Web/Views/Register/Summary.cshtml

**JIRA link**
https://hee-tis.atlassian.net/browse/TD-787
Password field added in the summary page.
Updated in Jira ticket
-----
I have:

TD-787-Password field missing in the External Register Summary Page.

---

DigitalLearningSolutions.Data/DataServices/CourseContentService.cs

https://hee-tis.atlassian.net/browse/TD-682
All queries that return navigation data within the learning menu should exclude any Applications, Sections and Tutorial records that have an Archived date that is not null.
No Screenshots
-----
I have:

TD-682 Courses displaying navigation to archived/incorrect content

---

DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs
DigitalLearningSolutions.Web/Views/Supervisor/RemoveConfirm.cshtml

https://hee-tis.atlassian.net/browse/TD-798
Fixed Error message missing on 'Confirm Remove Staff Member' when clicked Remove' button before confirming it
https://hee-tis.atlassian.net/browse/TD-798
-----
I have:

TD-798 : Fixed Error message missing on 'Confirm Remove Staff Member

---

DigitalLearningSolutions.Data.Migrations/202206281724_AddUniquenessConstraintsToCandidateAssessmentsAndSupervisorDelegates.cs

_[TD-825](https://hee-tis.atlassian.net/browse/TD-825)_
Adds script to remove duplicate data that breaks the constraints introduced by the migration.
-----
I have:

 TD-825 fix data for constraints

---

DigitalLearningSolutions.Data/Services/PasswordResetService.cs

_[TD-830](https://hee-tis.atlassian.net/browse/TD-830)_
Tweaks wording of welcome email.
-----
I have:

TD-830 update welcome email wording

---

DigitalLearningSolutions.Web/Controllers/FrameworksController/Frameworks.cs

**JIRA link**
https://hee-tis.atlassian.net/browse/TD-834
HttpStatusCode changed to 410.
-----
I have:
[TD-834]: https://hee-tis.atlassian.net/browse/TD-834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-834 UAR: Console '404' error on 'Frameworks Details' section when navigating browser back button

---

DigitalLearningSolutions.Data.Tests/Services/SupervisorServiceTest.cs
DigitalLearningSolutions.Data/Models/Supervisor/DelegateSelfAssessment.cs
DigitalLearningSolutions.Data/Services/SupervisorService.cs
DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs
DigitalLearningSolutions.Web/Views/Supervisor/SelectDelegateSupervisorRole.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/SelectDelegateSupervisorRoleSummary.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/Shared/_DelegateProfileAssessmentGrid.cshtml

[TD-202](https://hee-tis.atlassian.net/browse/TD-202)
Allow supervisor to see self-assessments that their staff are already on and assign themselves as supervisor.
- The assessment count on staff list page now shows the sum of assessment assigned to the supervisor and assessment not asigned to any supervisor
- The list of assessment of a staffer shows assessment assigned to the logged in supervisor as well as assessment not assigned to any supervisor
-----
I have:

TD-202 allow supervisor to see self assessments that their staff are already on

---

DigitalLearningSolutions.Data.Tests/DataServices/SelfAssessmentDataServiceTests/CompetencyDataServiceTests.cs
DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentExportDataService.cs
DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs
DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs
DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs
DigitalLearningSolutions.Data/DataServices/SupervisorService.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/CurrentTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/RecommendedLearningControllerTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/SelfAssessmentTests.cs
DigitalLearningSolutions.Web.Tests/Services/ActionPlanServiceTests.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/Current.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/RecommendedLearningController.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs
DigitalLearningSolutions.Web/ServiceFilter/VerifyDelegateUserCanAccessSelfAssessment.cs
DigitalLearningSolutions.Web/Services/ActionPlanService.cs
DigitalLearningSolutions.Web/Services/CandidateAssessmentDownloadFileService.cs
DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs

**JIRA link**
https://hee-tis.atlassian.net/browse/TD-260
For self assessment, service methods used 'delegateUserId' instead of CandidateId or DelegateId. SQL queries updated accordingly.
-----
I have:
[TD-260]: https://hee-tis.atlassian.net/browse/TD-260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-260-Passporting - Fix Learning Portal and Self Assessment functionality broken by migration

---

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Centre/Administrator/AdministratorControllerTests.cs
DigitalLearningSolutions.Web.Tests/ServiceFilter/VerifyAdminUserCanAccessAdminUserTests.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Administrator/AdministratorController.cs
DigitalLearningSolutions.Web/ServiceFilter/VerifyAdminUserCanAccessAdminUser.cs

**JIRA link**
https://hee-tis.atlassian.net/browse/TD-844
HttpStatusCode changed to 410. Test cases result updated to 410 status code.
-----
I have:
[TD-844]: https://hee-tis.atlassian.net/browse/TD-844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-844-UAR: Console '404' error when deactivating an admin account and clicking browser back button

---

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/DelegateProgressControllerTests.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateProgressController.cs

**JIRA link**
https://hee-tis.atlassian.net/browse/TD-843
HttpStatusCode changed to 410.
-----
I have:

TD-843-Console '404' error on the screen when clicking browser back button after remove delegate

---

DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs

JIRA link
https://hee-tis.atlassian.net/browse/TD-876
Retrieved competencies having supervisor names (not empty)
-----
I have:

TD-876-Self-assessment - Proficiency Confirmation request page displays blank

---

DigitalLearningSolutions.Data.Migrations/202301101342_AddSelfAssessmentResultDelegateUserID.cs
DigitalLearningSolutions.Data.Tests/DataServices/LearningLogItemsDataServiceTests.cs
DigitalLearningSolutions.Data.Tests/DataServices/SelfAssessmentDataServiceTests/CompetencyDataServiceTests.cs
DigitalLearningSolutions.Data/DataServices/LearningLogItemsDataService.cs
DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentExportDataService.cs
DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs
DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs
DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs
DigitalLearningSolutions.Data/DataServices/SupervisorService.cs
DigitalLearningSolutions.Data/Models/SelfAssessments/SelfAssessmentResult.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/CompletedTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/CurrentTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/RecommendedLearningControllerTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/SelfAssessmentTests.cs
DigitalLearningSolutions.Web.Tests/Controllers/Signposting/SignpostingControllerTests.cs
DigitalLearningSolutions.Web.Tests/Services/ActionPlanServiceTests.cs
DigitalLearningSolutions.Web.Tests/Services/RecommendedLearningServiceTests.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/Completed.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/Current.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/RecommendedLearningController.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs
DigitalLearningSolutions.Web/Controllers/Signposting/SignpostingController.cs
DigitalLearningSolutions.Web/Services/ActionPlanService.cs
DigitalLearningSolutions.Web/Services/RecommendedLearningService.cs
DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs

JIRA link
https://hee-tis.atlassian.net/browse/TD-912
DelegateUserId column added to SelfAssessmentResults populated with userId based on CandidateID
Code modified to replace CandidateID
-----
I have:

TD-912-Modify SelfAssessmentResults to link to DelegateUser instead of CandidateID

---

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/PromoteToAdminController.cs

https://hee-tis.atlassian.net/browse/TD-849
Implements validation message when user roles are not selected during promote to admin.
https://hee-tis.atlassian.net/browse/TD-849
-----
I have:

TD-849 validation message when user roles are not selected during promote to admin

---

DigitalLearningSolutions.Data.Migrations/202301101342_AddSelfAssessmentResultDelegateUserID.cs

[TD-912](https://hee-tis.atlassian.net/browse/TD-912)
Makes column nullable before renaming to avoid issue with history column of same name not being renamed when running migration.
-----
I have:
[TD-912]: https://hee-tis.atlassian.net/browse/TD-912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-912 resequence migration steps

---

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentExportDataService.cs
DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs
DigitalLearningSolutions.Data/Services/SupervisorService.cs

[TD-1005](https://hee-tis.atlassian.net/browse/TD-1005)
Excluded self assessment result verification request that are marked as Superceded[sic] from all SELECT queries.
-----
I have:
[TD-1005]: https://hee-tis.atlassian.net/browse/TD-1005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-1005 Updates select queries to exclude Superseded requests

---

DigitalLearningSolutions.Data/Services/SupervisorService.cs

[TD-1030](https://hee-tis.atlassian.net/browse/TD-1030)
Updates SQL to mark all previous results superseded
-----
I have:
[TD-1030]: https://hee-tis.atlassian.net/browse/TD-1030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-1030 Updates SQL to mark all previous results superseded

---

DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/SearchableCourseStatisticsViewModel.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/_CentreCourseCard.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateCourseProgressDetails.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateCourseProgressDetailsWithStatusTags.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ViewDelegate/Index.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ViewDelegate/_DelegateCourseInfoCard.cshtml

https://hee-tis.atlassian.net/jira/software/c/projects/TD/boards/165?selectedIssue=TD-707
Created new partial view _DelegateCourseProgressDetailsWithStatusTags as the Delegate Details panel was being used by both the CourseDelegates route and also ViewDelegate, hence the tag rendering issue.
Added logic to Centre Course Setup view to hide buttons if course inactive.
-----
I have:

TD-707 Archived Courses Tag more work

---

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs

[TD-1031](https://hee-tis.atlassian.net/browse/TD-1031)
After previous changes to this ticket to fix duplicate result rows, the controller requesting results for confirmation requests was passing the wrong value into the query (userId instead of delegated). This fixes that.
Previously no items were listed.
-----
I have:
[TD-1031]: https://hee-tis.atlassian.net/browse/TD-1031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-1031 Fix confirmation pick results

---

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs

[TD-268](https://hee-tis.atlassian.net/browse/TD-268)
Handles admin accounts where category ID is Null when loading list of admins to select as supervisor.
-----
I have:
[TD-268]: https://hee-tis.atlassian.net/browse/TD-268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-268 Handles admin accounts where category ID is Null

---

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs

[TD-1044](https://hee-tis.atlassian.net/browse/TD-1044)
Adds missing bracket to get valid supervisor for activity query and excludes admin records that have GUID as email address
-----
I have:
[TD-1044]: https://hee-tis.atlassian.net/browse/TD-1044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-1044 Fix get valid supervisor query

---

DigitalLearningSolutions.Data/Models/SessionData/Supervisor/SessionEnrolOnRoleProfile.cs
DigitalLearningSolutions.Data/Models/SessionData/Tracking/Deligate/Enrol/SessionEnrolDelegate.cs

https://hee-tis.atlassian.net/browse/TD-850
Id column has been removed from below models
1. SessionEnrolDelegate
2. SessionEnrolOnRoleProfile
1.  Supervise → Enrol staff member on self assessment transaction
Before:
After:
2. Tracking System → Delegates → Enrol on activity transaction.
Before:
After:
-----
I have:

TD-850: Enrol delegate on activity/assessment tempdata model Id problem

---

DigitalLearningSolutions.Web/Helpers/FilterableTagHelper.cs

https://hee-tis.atlassian.net/jira/software/c/projects/TD/boards/165?modal=detail&selectedIssue=TD-707
Updated TrackingSystem/CourseSetup course status tags to be consistent with Delegates/Courses page. Previously the tags were displayed as a combined 'Inactive/archived' tag; now they are displayed individually (Active or Inactive or Archived).
-----
I have:

TD-707 Updated CourseSetup page status tags for consistency

---

DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/CloseTests.cs
DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/Available.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/Completed.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/Current.cs
DigitalLearningSolutions.Web/Views/LearningMenu/Completion/Completion.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/CoursePassword.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Diagnostic/Diagnostic.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Diagnostic/DiagnosticContent.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Index.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/PostLearning/PostLearning.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/PostLearning/PostLearningContent.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Section/Section.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/ContentViewer.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/Tutorial.cshtml
DigitalLearningSolutions.Web/Views/LearningMenu/Tutorial/TutorialVideo.cshtml

**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1046
Activity link updated for Current, Completed, and Available learning activities.
-----
I have:

TD-1046-Passporting: Issue with the Completed/Available Activities links on the 'Learning Portal'

---

DigitalLearningSolutions.Data/DataServices/SupervisorService.cs

[TD-1079](https://hee-tis.atlassian.net/jira/software/c/projects/TD/boards/165?modal=detail&selectedIssue=TD-1079)
Fixed the supervisor enrol delegate on assessment mechanism to use DelegateUserID instead of CandidateID
-----
I have:
[TD-1079]: https://hee-tis.atlassian.net/browse/TD-1079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-1079 Updated EnrolDelegateOnAssessment to use DelegateUserId

---

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs
DigitalLearningSolutions.Data/Models/StartedLearningItem.cs
DigitalLearningSolutions.Web/ViewModels/LearningPortal/StartedLearningItemViewModel.cs
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_SelfAssessmentCard.cshtml

https://hee-tis.atlassian.net/browse/TD-265
The Delegates are shown all of their self-assessments for each centre. Currently the centre's are not displayed.
https://hee-tis.atlassian.net/browse/TD-265
-----
I have:

TD-265 Show which centre self-assessments were enrolled by

---

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAsssessmentReportDataService.cs
DigitalLearningSolutions.Data/Models/SelfAssessments/Export/SelfAssessmentReportData.cs
DigitalLearningSolutions.Data/Models/SelfAssessments/SelfAssessmentSelect.cs
DigitalLearningSolutions.Data/Services/SelfAssessmentReportService.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/SelfAssessmentReports/SelfAssessmentReportsController.cs
DigitalLearningSolutions.Web/DigitalLearningSolutions.Web.csproj
DigitalLearningSolutions.Web/Startup.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/SelfAssessmentReports/SelfAssessmentReportsViewModel.cs
DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/SelfAssessmentReports/Index.cshtml

[TD-1098](https://hee-tis.atlassian.net/browse/TD-1098)
Implements downloadable Excel nursing passport centre reports available from Tracking System -> Centre -> Self assessment reports. Reworks the view for that page to present all reports in link list.
-----
I have:
[TD-1098]: https://hee-tis.atlassian.net/browse/TD-1098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-1098 Nursing passport centre report

---

DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs

[TD-1106](https://hee-tis.atlassian.net/browse/TD-1106)
We added code to prevent supervisors from adding themselves as a member of staff (same email address validation). This reverts that change (leaving code in comments to allow easy reinstatement).
-----
(Leave tasks unticked if they aren't appropriate for your ticket.)
I have:
[TD-1106]: https://hee-tis.atlassian.net/browse/TD-1106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-1106 Allow supervisor self enrolment

---

DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/EmailDelegates/Index.cshtml

https://hee-tis.atlassian.net/browse/TD-1083
Fixed error link not clickable
https://hee-tis.atlassian.net/browse/TD-1083
-----
I have:

TD-1083 Fixed error link not clickable

---

DigitalLearningSolutions.Data/Services/GroupsService.cs

[TD-872](https://hee-tis.atlassian.net/browse/TD-872)
Fixes the problem with enrolling group delegates on courses added to the group by passing the correct delegateID param value into EnrolDelegateOnGroupCourse service method
-----
I have:
[TD-872]: https://hee-tis.atlassian.net/browse/TD-872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-872 Fix bug with add course to group logic

---

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAsssessmentReportDataService.cs
DigitalLearningSolutions.Data/Models/SelfAssessments/Export/SelfAssessmentReportData.cs
DigitalLearningSolutions.Data/Services/SelfAssessmentReportService.cs

TD-1128
Adds LearnerActive column to self assessment report
-----
I have:

TD-1128 Adds LearnerActive column to self assessment report

---

DigitalLearningSolutions.Data/DataServices/SupervisorService.cs
DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs
DigitalLearningSolutions.Web/Views/Supervisor/DelegateProfileAssessments.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/Shared/_StaffMemberCard.cshtml

[TD-262](https://hee-tis.atlassian.net/jira/software/c/projects/TD/boards/165?modal=detail&selectedIssue=TD-262)
Added sql call to ensure delegate details are retrieved and delegate name/job details correctly displayed in all supervisor views.
-----
I have:
[TD-262]: https://hee-tis.atlassian.net/browse/TD-262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-262 Supervisor passporting fixes

---

DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs
DigitalLearningSolutions.Web/Views/Supervisor/Shared/_StaffMemberCard.cshtml

[TD-1141](https://hee-tis.atlassian.net/browse/TD-1141)
Implements missing controller method for Resend Invite in supervisor interface. Sends the invite and updates the invite sent date before reloading the view.
-----
I have:
[TD-1141]: https://hee-tis.atlassian.net/browse/TD-1141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-1141 Implements missing controller method for Resend Invite

---

DigitalLearningSolutions.Web/Program.cs

[TD-1146](https://hee-tis.atlassian.net/browse/TD-1146)
Changes the SQL SeriLog logging minimum level to "Error" to avoid log table bloat.
-----
I have:
- [Confluence - Tech stack notes](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3469443077/DLS+Tech+Stack+Notes)
[TD-1146]: https://hee-tis.atlassian.net/browse/TD-1146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-1146 Sets SQL logging level to Error

---

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs
DigitalLearningSolutions.Data/DataServices/SupervisorService.cs
DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/VerificationPickSupervisor.cshtml
DigitalLearningSolutions.Web/Views/LearningPortal/Shared/_SupervisorsCard.cshtml

**JIRA link**
[TD-264](https://hee-tis.atlassian.net/browse/TD-264)
Centre name added for Activity supervisors and Request proficiency confirmation.
-----
I have:
[TD-264]: https://hee-tis.atlassian.net/browse/TD-264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-264-Passporting - LearningPortal: Show supervisors' centres on self assessments

---

DigitalLearningSolutions.Web.IntegrationTests/EndpointTests.cs
DigitalLearningSolutions.Web/Startup.cs

[TD-276](https://hee-tis.atlassian.net/browse/TD-276)
A number of missing Security Headers are missing from the application. This branch adds the required headers.
-----
I have:
[TD-276]: https://hee-tis.atlassian.net/browse/TD-276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added security headers to http responses

---

DigitalLearningSolutions.Web.Tests/Attributes/CommonPasswordsAttributeTests.cs
DigitalLearningSolutions.Web.Tests/Attributes/UserNameAttributeTests.cs
DigitalLearningSolutions.Web/Attributes/CommonPasswordsAttribute.cs
DigitalLearningSolutions.Web/Attributes/UserNameAttribute.cs
DigitalLearningSolutions.Web/Helpers/CommonValidationErrorMessages.cs
DigitalLearningSolutions.Web/Startup.cs
DigitalLearningSolutions.Web/ViewModels/Common/ConfirmPasswordViewModel.cs
DigitalLearningSolutions.Web/ViewModels/Common/PasswordViewModel.cs
DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/SetDelegatePassword/SetDelegatePasswordViewModel.cs
DigitalLearningSolutions.Web/Views/RegisterDelegateByCentre/Password.cshtml
DigitalLearningSolutions.Web/Views/Shared/_SetPasswordFields.cshtml
DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/SetDelegatePassword/Index.cshtml

[TD-274](https://hee-tis.atlassian.net/browse/TD-274)
Code has been modified to enforce ‘strong’ passwords standards - 8 characters or more, numbers, characters, mixed case characters.
-----
I have:
[TD-274]: https://hee-tis.atlassian.net/browse/TD-274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-274 Added code to enforce stronger passwords

---

DigitalLearningSolutions.Web/Views/LearningPortal/Shared/_SupervisorsCard.cshtml

**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1153
Supervisor count check added in the view.
-----
I have:

TD-1153-On "Activity Supervisors" list, show first 3 supervisors with "+X more"

---

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs
DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs
DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/CurrentTests.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/Current.cs
DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs

[TD-1143](https://hee-tis.atlassian.net/jira/software/c/projects/TD/boards/165?modal=detail&selectedIssue=TD-1143)
Added the centreId for the currently logged in user as a filter for the self-assessment list population. Also joined to table CentreSelfAssessments in the same SQL expression.
-----
I have:
[TD-1143]: https://hee-tis.atlassian.net/browse/TD-1143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-1143 Hide unpublished for centre self assessments

---

DigitalLearningSolutions.Data/DataServices/SessionDataService.cs
DigitalLearningSolutions.Web.Tests/ServiceFilter/VerifyAdminUserCanProceedTests.cs
DigitalLearningSolutions.Web/Controllers/LoginController.cs
DigitalLearningSolutions.Web/Controllers/LogoutController.cs
DigitalLearningSolutions.Web/ServiceFilter/VerifyAdminUserCanProceed.cs
DigitalLearningSolutions.Web/Services/SessionService.cs

[TD-275](https://hee-tis.atlassian.net/browse/TD-275)
The admin user session information has been moved from TempData to a User claim. This gets around the issue that we were having where several controllers were performing a TempData.Clear() operation.
-----
I have:
[TD-275]: https://hee-tis.atlassian.net/browse/TD-275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-275 Moved the storage of AdminSessionID from TempData to User.Claims

---

DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs
DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/PromoteToAdminControllerTests.cs
DigitalLearningSolutions.Web.Tests/Services/RegistrationServiceTests.cs
DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs
DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/PromoteToAdminController.cs
DigitalLearningSolutions.Web/Services/RegistrationService.cs

[TD-1168](https://hee-tis.atlassian.net/jira/software/c/projects/TD/boards/165?modal=detail&selectedIssue=TD-1168)
Added param to promote method so now Promote To Nominated Supervisor merges the new admin role with any existing roles for the delegate.
-----
I have:
[TD-1168]: https://hee-tis.atlassian.net/browse/TD-1168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-1168 Promote nominated supervisor rework

---

DigitalLearningSolutions.Web.Tests/ServiceFilter/VerifyAdminUserCanProceedTests.cs
DigitalLearningSolutions.Web/ServiceFilter/VerifyAdminUserCanProceed.cs

[TD-275](https://hee-tis.atlassian.net/browse/TD-275)
A check for a user being a Centre Admin has been added to the check to User Admin, when determining if an Admin User session should be logged out.
-----
I have:
[TD-275]: https://hee-tis.atlassian.net/browse/TD-275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added check for User Centre Admin when determining session status

---

DigitalLearningSolutions.Data.Tests/Services/SupervisorServiceTest.cs
DigitalLearningSolutions.Data/DataServices/SupervisorService.cs
DigitalLearningSolutions.Data/Models/Supervisor/DelegateSelfAssessment.cs
DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs
DigitalLearningSolutions.Web/Views/Supervisor/SelectDelegateSupervisorRole.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/SelectDelegateSupervisorRoleSummary.cshtml
DigitalLearningSolutions.Web/Views/Supervisor/Shared/_DelegateProfileAssessmentGrid.cshtml

[TD-899](https://hee-tis.atlassian.net/browse/TD-899)
Merge TD-202 changes, as well as further query changes(centre check, supervisor check and SelfAssessments.National check)
-----
I have:
[TD-899]: https://hee-tis.atlassian.net/browse/TD-899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-899 allow supervisors to supervise self assessments a user is already enrolled on (TD-202 for UAR)

---

DigitalLearningSolutions.Data.Migrations/202303071200_AddUniqueConstraintToCandidateAssessmentSupervisors.cs
DigitalLearningSolutions.Data/DataServices/SupervisorService.cs

https://hee-tis.atlassian.net/browse/TD-1166
Quick Add - Same Supervisors are added multiple times : I can't replicate the issue locally. But there is a chance to insert duplicate records into the table CandidateAssessmentSupervisors if users click the add button multiple times due to network failure or delay. So I added unique constraints to eliminate the duplicate records.
Before Change:
We can add duplicate entries to the table CandidateAssessmentSupervisors. If we add any duplicate entries to the table, then the Manage Supervisor page will display duplicate entries on the page.
After Change:
Added unique constraints to the table to eliminate the duplicate entries.
-----
I have:

TD-1166 quick add same supervisors are added multiple times

---

DigitalLearningSolutions.Data/Helpers/UserPermissionsHelper.cs

**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1105
Deactivate button made available for adminAccount having centre manager role.
N/A
-----
I have:

TD-1105- UAR: 'Deactivate admin account' button is not visible

---

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAsssessmentReportDataService.cs
DigitalLearningSolutions.Data/Models/SelfAssessments/Export/SelfAssessmentReportData.cs
DigitalLearningSolutions.Data/Services/SelfAssessmentReportService.cs

[TD-1222](https://hee-tis.atlassian.net/browse/TD-1222)
Report counts were returning a number that was always 1 too many because `COUNT DISTINCT` was including 0 in the count. This fixes that problem. Also renames the OptionalProficiencies column in the report to OptionalProficienciesAssessed because they are only included in the count if they have been self assessed.
-----
I have:
[TD-1222]: https://hee-tis.atlassian.net/browse/TD-1222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-1222 Fix self assessment report counts

---

DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/SelfAssessmentTests.cs
DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs

[TD-1204](https://hee-tis.atlassian.net/jira/software/c/projects/TD/boards/165?modal=detail&selectedIssue=TD-1204)
When updating the answer to a self-assessment question, the system now only checks if the current question already has a confirmed/sign-off by the supervisor. Previously it checked if *any* of the answers in the group were signed-off, so redirected to the 'Confirm sign-off overwrite' page spuriously.
Also fixed existing issue where system threw 404 error due to incorrect routing after the user confirmed the sign-off override.
-----
I have:
[TD-1204]: https://hee-tis.atlassian.net/browse/TD-1204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-1204 Overwrite confirmed self assessment fix for live

---

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs

[TD-1253](https://hee-tis.atlassian.net/browse/TD-1253)
Prevents clearing of optional competencies for other self assessments when submitting selected optional proficiencies by fixing SQL query error.
-----
I have:
[TD-1253]: https://hee-tis.atlassian.net/browse/TD-1253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-1253 Prevents clearing of optional competencies

---

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_Layout.cshtml
DigitalLearningSolutions.Web/Views/Shared/_DlsFooter.cshtml
DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml

[TD-1277](https://hee-tis.atlassian.net/browse/TD-1277)
Moved the footer element of the layout pages to a shared partial and replaced the copyright notice with copyright NHS England in prep for transition.
Change for master (live):
-----
I have:
[TD-1277]: https://hee-tis.atlassian.net/browse/TD-1277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-1277 Changes site footer copyright notice to NHS England

---

DigitalLearningSolutions.Data/DataServices/SupervisorService.cs
DigitalLearningSolutions.Web/Views/Supervisor/Shared/_StaffDetails.cshtml

[TD-1152](https://hee-tis.atlassian.net/jira/software/c/projects/TD/boards/165?modal=detail&selectedIssue=TD-1152)
The staff delegate panel was in some use cases displaying an empty Job Group Name row. This was previously hidden if customparam2 was empty, so this is effectively now reinstated for the new hardcoded JobGroupName html elements.
-----
I have:
[TD-1152]: https://hee-tis.atlassian.net/browse/TD-1152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TD-1152 Reinstated check for empty delegate JobGroupName display.
