TechnologyEnhancedLearning/DLSV2

DigitalLearningSolutions.Web.Tests/Controllers/MyAccount/MyAccountControllerTests.cs, DigitalLearningSolutions.Web/Controllers/MyAccountController.cs, DigitalLearningSolutions.Web/Controllers/Register/RegisterController.cs
https://hee-tis.atlassian.net/browse/TD-1154
Added validation for email address uniqueness for primary email and centre email in register page and my account page
-----
I have:
=> TD-1154-Centre Email address should not be same as Primary email address

DigitalLearningSolutions.Web/Styles/layout.scss, DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml, DigitalLearningSolutions.Web/appsettings.Development.json, DigitalLearningSolutions.Web/appsettings.json
TD-1313
Implements a site-wide alert banner. Content and switching is handled in appsettings.
-----
I have:
=> TD-1313 Implements side-wide alert banner

DigitalLearningSolutions.Web/Styles/layout.scss, DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml, DigitalLearningSolutions.Web/appsettings.Development.json, DigitalLearningSolutions.Web/appsettings.json
[TD-1313](https://hee-tis.atlassian.net/browse/TD-1313)
Implements a site-wide alert banner in the layout template. Visibility and content of this banner are set in appsettings.  This will be used to display the NHS England merger banner content initially.
-----
I have:
[TD-1313]: https://hee-tis.atlassian.net/browse/TD-1313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1313 Implement site-wide alert banner

DigitalLearningSolutions.Data/DataServices/TutorialContentDataService.cs
[TD-1315](https://hee-tis.atlassian.net/browse/TD-1315)
Fixes query returning data for the tutorial screen by ensuring that the OtherTutorials section of the query only returns tutorials for the course (ApplicationID) referenced in the Customisation.
-----
I have:
[TD-1315]: https://hee-tis.atlassian.net/browse/TD-1315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1315 Tutorial menu Next section bug fix

DigitalLearningSolutions.Web/Scripts/learningMenu/keepSessionAlive.ts, DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml
[TD-296](https://hee-tis.atlassian.net/browse/TD-269)
The ajax calls to the keep alive ping have been modified to ensure that they use the correct sub domain when making the call.
-----
I have:
[TD-296]: https://hee-tis.atlassian.net/browse/TD-296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Modified keep alive ping to use Url.Action

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAsssessmentReportDataService.cs
[TD-1284](https://hee-tis.atlassian.net/browse/TD-1284)
Fixes query to join between latest assessment results (LAR) and main query to fix competency counts. Sets the field alias for delegate account Active to 'LearnerActive' to ensure it maps properly.
-----
I have:
[TD-1284]: https://hee-tis.atlassian.net/browse/TD-1284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1284 Fixes excel export query to resolve problems identified by testers

DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs
[TD-1285](https://hee-tis.atlassian.net/browse/TD-1285)
Removes the unnecessary controller method `FilteredSelfAssessmentGroupsBookmark` bypassing the redirect to it in `AddSelfAssessmentOverviewFilter` and decorates existing controller methods with correct route templates. This appears to fix all problems with routing relating to the proficiencies menu and filtering.
-----
I have:
[TD-1285]: https://hee-tis.atlassian.net/browse/TD-1285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1285 Fix self assessment controller routing

DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml
[TD-296](https://hee-tis.atlassian.net/browse/TD-269)
The hidden input ID=keepAlivePingPath has been re added to _Layout.cshtml.
-----
I have:
[TD-296]: https://hee-tis.atlassian.net/browse/TD-296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Reinstated the keepAlivePingPath hidden input

DigitalLearningSolutions.Web/Services/LoginService.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1390
check added to compare failed login count.
N/A
-----
I have:
=> TD-1390-Failed to show account is locked on login screen when users failed login count exceeds the expected count

DigitalLearningSolutions.Web/Views/CookieConsent/CookieConfirmation.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1393
mobile view back link updated to Cookie Policy.
-----
I have:
=> TD-1393-Issue with 'Back to signposting' link in Mobile view on 'Your cookie settings have been saved' page

DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/AddSupervisor.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelectSupervisorCentre.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1380
Back button link updated.
N/A
-----
I have:
=> TD-1380-Back button error in mobile view returning to self assessment menu

DigitalLearningSolutions.Web/Services/FrameworkNotificationService.cs
TD-1289
Replaces Health Education England with NHS England throughout framework notifications. No other examples of HEE or Health Education England found in email notifications.
-----
I have:
=> TD-1289 Replaces email notifications to NHS England

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/AddSupervisorSummary.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SetSupervisorRole.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1396
Links are updated accordingly.
-----
I have:
=> TD-1396-Issue with back links in Mobile view when adding a supervisor for the assessments in Learning Portal

DigitalLearningSolutions.Web/DigitalLearningSolutions.Web.csproj, DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/_ReviewSelfAssessmentOverallProgress.cshtml
https://hee-tis.atlassian.net/browse/TD-1185
Added Progress bar on supervisor review self assessment screen by adding code to ReviewSelfAssessment.cshtml and creating a partial view _ReviewSelfAssessmentOverallProgress.cshtml
After code changes, the UI shows the progress bar-
-----
I have:
=> TD-1185- Progress bar on supervisor review self assessment screen added

DigitalLearningSolutions.Data.Migrations/DigitalLearningSolutions.Data.Migrations.csproj, DigitalLearningSolutions.Data.Tests/DigitalLearningSolutions.Data.Tests.csproj, DigitalLearningSolutions.Web/DigitalLearningSolutions.Web.csproj
[TD-1405](https://hee-tis.atlassian.net/browse/TD-1405)
Dependabot created a PR in update Microsoft.Data.SqlClient from 2.0.0 to 2.1.2. This caused build failures because the update was only being applied to one project in the solution. This update has now been applied to all projects in the solution and the build is now completing without errors.
-----
I have:
[TD-1405]: https://hee-tis.atlassian.net/browse/TD-1405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Upgraded Microsoft.Data.SqlClient from 2.0.0 to 2.1.2

DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml
https://hee-tis.atlassian.net/browse/TD-1185
Removed the condition of 5 groups limit in the supervisor view. This solves the test fail for Adult Critical Care Passport.
-----
I have:
=> TD-1185-Removed the condition of 5 groups limit in the supervisor view.

DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs
https://hee-tis.atlassian.net/browse/TD-1166
Implemented the functionality to display the 410 error on the browser's back button after adding the supervisor. [Added missed scenario]
-----
I have:
=> TD-1166: Quick Add - Same Supervisors are added multiple times

DigitalLearningSolutions.Web/Views/SuperAdmin/AdminAccounts/_SearchableAdminAccountsCard.cshtml
[TD-1400](https://hee-tis.atlassian.net/browse/TD-1400)
Adds missing logic for displaying the locked tag to the admin account partial view.
-----
I have:
[TD-1400]: https://hee-tis.atlassian.net/browse/TD-1400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1400 Adds logic for displaying the locked tag to the admin account partial view

DigitalLearningSolutions.Data.Migrations/202304191130_Delete_SelfAssessmentResult_SupervisorVerifications.cs, DigitalLearningSolutions.Web/Helpers/MigrationHelperMethods.cs
The unique index implemented as part of previous work on TD-1220 failed when published to UAR-TEST because the SelfAssessmentResultsHistory table had a column name (CandidateID) mismatch with the SelfAssessmentResults table (CandidateID_deprecated).
This change introduces a check for the incorrect column name and updates it if required.
The DELETE queries were also triggering a command timeout. We increase the global command timeout to 360 seconds in this change.
-----
I have:
[TD-1220]: https://hee-tis.atlassian.net/browse/TD-1220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …
=> TD-1220 Renames CandidateID table in SelfAssessmentResultsHistory

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs
Updates the self assessment result datetime when updating a result and removes **any** associated self assessment result supervisor verification record.
-----
I have:
=> TD-1220 Fixes to update self assessment result logic

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs
Reintroduces the insert self assessment result logic when result doesn't already exist
-----
I have:
=> TD-1220 Reintroduces the insert self assessment result logic

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs
The rework of the SetResultForCompetency data service method prevented null results from being stored (because of SQL NULL propagation). This tweaks the data service to allow null results to be stored (i.e. when a learner clears a previously stored result).
-----
I have:
=> TD-1220 Tweaks  competency data service to store null results after clearing

DigitalLearningSolutions.Data/DataServices/SupervisorService.cs, DigitalLearningSolutions.Data/Enums/SelfAssessmentCompetencyFilter.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Extensions/EnumExtensions.cs, DigitalLearningSolutions.Web/Helpers/SupervisorCompetencyFilterHelper.cs, DigitalLearningSolutions.Web/ViewModels/Supervisor/ReviewSelfAssessmentViewModel.cs, DigitalLearningSolutions.Web/ViewModels/Supervisor/SearchSupervisorCompetencyViewModel.cs, DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/Shared/_SearchSupervisorCompetency.cshtml
https://hee-tis.atlassian.net/browse/TD-207
1. Search filter has been implemented in Supervisor view. 
2.'Confirmation requested’ filter option has been  replaced with ‘Awaiting confirmation’ and ‘Pending confirmation’ filter options in dropdown.
Please note: SelfAssessment page will not get affected by filter option change.
**Supervisor page before implementation:**
**Supervisor page after implementation:**
**SelfAssessment page:**
-----
I have:
=> TD-207:supervisor-review-profile-assessment-allow-searching-and-filtering-of-competencies

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml
https://hee-tis.atlassian.net/browse/TD-1451
Changed the Linq query to get the correct status of self-assessments
-----
I have:
=> TD-1451-When self assessment result is cleared (is null) it should not be included in the counts for the group or overall count

DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Scripts/learningPortal/supervisorList.ts, DigitalLearningSolutions.Web/Scripts/searchSortFilterAndPaginate/paginate.ts, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/AddSupervisor.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-161
The search bar has aligned. To display all supervisors, the number… of supervisors per page is set to 9999
-----
I have:
=> TD-161-Provide searchable list of supervisors when adding a supervisor from the self assessment manage supervisors view

DigitalLearningSolutions.Data/DataServices/FrameworkService.cs, DigitalLearningSolutions.Web/Controllers/FrameworksController/Competencies.cs
[TD-1485](https://hee-tis.atlassian.net/browse/TD-1485)
Duplicates allowed without showing error msg on the screen if added the competency with the name of existing one in frameworks.  This was as a result of the duplicate competency being attached to a different admindId. The query now fetches all competencies from the database irrespective of the attached adminId.
-----
I have:
[TD-1485]: https://hee-tis.atlassian.net/browse/TD-1485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1485 Duplicates allowed without showing error msg on the screen 

DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml
https://hee-tis.atlassian.net/browse/TD-1395
The _ga and _hj cookies never expired when the user consented yes. Fixed the bug
-----
I have:
=> Fixed the bug, the cookie expiry date was never expiring

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1445
set SQL query to return active supervisors only.
-----
I have:
=> TD-1445-Inactive admins are listed in Request Proficiency Confirmation screen

DigitalLearningSolutions.Data/Models/Tracker/TrackerEndpointQueryParams.cs, DigitalLearningSolutions.Web.Tests/Helpers/SystemEndpointHelperTests.cs, DigitalLearningSolutions.Web.Tests/Services/TrackerServiceTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/ContentViewerViewModelTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/DiagnosticContentViewModelTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/PostLearningContentViewModelTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/TrackerController.cs, DigitalLearningSolutions.Web/Helpers/SystemEndpointHelper.cs, DigitalLearningSolutions.Web/Services/TrackerService.cs
[TD-1555](https://hee-tis.atlassian.net/browse/TD-1555)
Reverts to legacy tracker endpoint because the new endpoint doesn't support posting data. Also improves param mapping for time which is passed in as a double but stored as an integer for when we do move to new endpoint.
-----
I have:
[TD-1555]: https://hee-tis.atlassian.net/browse/TD-1555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1555 Reverts to legacy tracker endpoint and improves param mapping

DigitalLearningSolutions.Web/Views/Supervisor/ReviewCompetencySelfAsessment.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1444
Removed 'UserIsVerifier' condition to show 'Supervisor' and 'Confirmation requested' row in the view.
-----
I have:
=> TD-1444-Add 'Supervisor' and 'Confirmation date requested' row to proficiency self assessment result view for 'confirmation requested' proficiencies

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_OverviewActionButtons.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1449
Button text changed.
-----
I have:
=> TD-1449-Change wording of 'Proficiencies confirmation' button to 'Manage confirmation requests' in Learning Portal

DigitalLearningSolutions.Web/Controllers/FrameworksController/Competencies.cs, DigitalLearningSolutions.Web/ViewModels/Frameworks/SimilarCompetencyViewModel.cs, DigitalLearningSolutions.Web/Views/Frameworks/Developer/SimilarCompetency.cshtml
[TD-1608](https://hee-tis.atlassian.net/browse/TD-1608)
competency flags get lost when adding a new competency with a name similar to an existing name.
check ticket link for a video
-----
I have:
[TD-1608]: https://hee-tis.atlassian.net/browse/TD-1608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1608 Issue with flags when added the competencies

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs, DigitalLearningSolutions.Data/DataServices/SupervisorService.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs
https://hee-tis.atlassian.net/browse/TD-1496
Issues addressed in this commit - 
1.Updating the CandidateAssessmentSupervisors table setting removed = null when removing a delegate from the supervisor interface solves the issues.
2. Removed the similar method GetSupervisorsForSelfAssessmentId which solves the count mismatch issue on supervisor list
Using ‘madhavi.martha@hee.nhs.uk’
Issue 1(a) – For the dev testing centre, supervisor added with assessor role and we can see in activity supervisor list
Before -
After - 
Issue 1(b) – Added as supervisor in dev testing centre with role as educator/manager
After adding the above, here is the New activity supervisor screen which shows that the account we are testing for is not shown anymore.
Issue 2 – Using my own account (Rohit Shrivastava) and …
=> TD-1496 - Issues when adding the supervisors for the self assessments

DigitalLearningSolutions.Web/Controllers/FrameworksController/Competencies.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1631
Converted 'frameworkGroupId' parameter as nullable parameter.
-----
I have:
=> TD-1631-Frameworks: Console '500' error on the 'Duplicate competency name' screen

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/AllDelegatesController.cs
https://hee-tis.atlassian.net/browse/TD-1602
1) Fixed 410 error on click of register after complete registration
[Register-delegate---Summary---Digital-Learning-Solutions.webm](https://github.com/TechnologyEnhancedLearning/DLSV2/assets/111436026/331decaa-06ce-430f-9464-bcd57dbb8115)
-----
I have:
=> TD-1602 Fixed 410 error on click of register after complete registration

DigitalLearningSolutions.Web/Styles/shared/searchableElements/searchableElements.scss, DigitalLearningSolutions.Web/Styles/shared/searchableElements/utils.scss, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/AddSupervisor.cshtml
[TD-1379](https://hee-tis.atlassian.net/jira/software/c/projects/TD/boards/165?modal=detail&selectedIssue=TD-1379)
Added styling to allow supervisor text to wrap to new line (was expanding render width to wider that screen on mobile devices where one or more supervisors had email address or name longer than 29 characters).
-----
I have:
[TD-1379]: https://hee-tis.atlassian.net/browse/TD-1379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1379 Add supervisor mobile render width

DigitalLearningSolutions.Data.Migrations/202306082300_AlterGetActivitiesForDelegateEnrolmentSP.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.Designer.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.resx, DigitalLearningSolutions.Data.Migrations/Scripts/TD-1766-GetActivitiesForDelegateEnrolmentTweak.sql, DigitalLearningSolutions.Data.Migrations/Scripts/TD-1766-GetActivitiesForDelegateEnrolmentTweak_down.sql
https://hee-tis.atlassian.net/browse/TD-1766
Added a migration to alter the stored procedure - to check if add-on name is not present, then removed the hyphen.
Course Setup page-
Enrol delegate to a course- 
Available activities-
-----
I have:
=> TD-1766 Corrected the store procedure to remove the hyphen if no add on is present in course name

DigitalLearningSolutions.Web.Tests/ViewModels/TrackingSystem/CourseSetup/CourseStatisticsViewModelFilterOptionsTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/CourseSetup/CourseSetupController.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/CourseStatisticsViewModelFilterOptions.cs
https://hee-tis.atlassian.net/browse/TD-1498
Updated TrackingSystem/CourseSetup view to make it consistent with DelegateCourses filters. Now has a working combined Inactive+Archived filter for both JS and non-JS modes (<250 records)
-----
I have:
[TD-1498]: https://hee-tis.atlassian.net/browse/TD-1498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1498 Tracking system course setup filters refix

DigitalLearningSolutions.Web/Startup.cs
[TD-1915](https://hee-tis.atlassian.net/browse/TD-1915)
Reduces configured Dapper sql timeout to 60 seconds (double the default but only 1/6 of the previous value)
-----
I have:
[TD-1915]: https://hee-tis.atlassian.net/browse/TD-1915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1915 Reduces dapper sql timeout to 60 seconds

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/AddSupervisor.cshtml
[TD-1379](https://hee-tis.atlassian.net/browse/TD-1379)
Fixed issue with supervisor search no longer working following changes to styling on Add Supervisor view.
Screenshot below
-----
I have:
[TD-1379]: https://hee-tis.atlassian.net/browse/TD-1379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1379 Fixed Add Supervisor search issue.

DigitalLearningSolutions.Web/Controllers/UserFeedbackController.cs, DigitalLearningSolutions.Web/Helpers/FeatureFlags.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_Layout.cshtml, DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml, DigitalLearningSolutions.Web/appSettings.UAT.json, DigitalLearningSolutions.Web/appsettings.Development.json, DigitalLearningSolutions.Web/appsettings.Production.json, DigitalLearningSolutions.Web/appsettings.SIT.json, DigitalLearningSolutions.Web/appsettings.Test.json, DigitalLearningSolutions.Web/appsettings.UarTest.json
[TD-1116](https://hee-tis.atlassian.net/browse/TD-1116)
Added feature flag to control availability of User Feedback mechanism via config files.
Set to true/enabled by default in all environment config files.
Screenshots for enabled/disabled for both headers (main header and SelfAssessments variant header).
-----
I have:
[TD-1116]: https://hee-tis.atlassian.net/browse/TD-1116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1116 Feedback bar feature flag

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/DCSAReportDataService.cs
[TD-1911](https://hee-tis.atlassian.net/browse/TD-1911)
There was a mismatch between the name of fields returned by the query and the cs model. This change updates the field names in the query to match the model. This maps correctly now so that the data is included in the Excl export.
-----
I have:
[TD-1911]: https://hee-tis.atlassian.net/browse/TD-1911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1911 Updates field names in query to match model

DigitalLearningSolutions.Data/DataServices/SupervisorService.cs
https://hee-tis.atlassian.net/browse/TD-1917
1) Fixed false mapping of centre for supervisor while adding it by modifying the dataservice.
-----
I have:
=> TD-1917 Fixed false mapping of centre for supervisor while adding it

DigitalLearningSolutions.Web/Helpers/CompetencyFilterHelper.cs, DigitalLearningSolutions.Web/Helpers/SupervisorCompetencyFilterHelper.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1452
'All' words of search text used for searching  proficiencies. 
-----
I have:
=> TD-1452-Improvements to search within a self assessment and supervisor review self assessment

DigitalLearningSolutions.Data/DataServices/SessionDataService.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Administrators/AdminAccountsController.cs, DigitalLearningSolutions.Web/Services/UserService.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1991
Created a separate method to check admin references.
-----
I have:
=> TD-1991-Super Admin: Admin user accounts should be deactivated for all centres

DigitalLearningSolutions.Data.Migrations/202306260804_AddVersionInfoPrimaryKey.cs
[TD-1438](https://hee-tis.atlassian.net/browse/TD-1438)
Adds a primary key to the existing, unique Version field on the VersionInfo table if it doesn't exist. This is needed for Azure SQL replication.
-----
I have:
[TD-1438]: https://hee-tis.atlassian.net/browse/TD-1438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1438 Migration to add VersionInfo primary key

DigitalLearningSolutions.Data.Migrations/202306271045_AddAddedUpdatedDateFieldsToConfig.cs, DigitalLearningSolutions.Data.Tests/DataServices/ConfigDataServiceTests.cs, DigitalLearningSolutions.Data/DataServices/ConfigDataService.cs
[TD-2054](https://hee-tis.atlassian.net/browse/TD-2054)
Migration to add created and updated date fields to the Config table and populate them with a starter date of today minus 12 months. This will allow us to show the last reviewed date in places where we are reading config values in (such as privacy notice, accessibility statement, terms of conditions etc).
-----
I have:
[TD-2054]: https://hee-tis.atlassian.net/browse/TD-2054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-2054 Adds created and updated date fields to the config table

DigitalLearningSolutions.Data.Migrations/202306260800_AlterGetCurrentCoursesForCandidateSP.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.Designer.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.resx, DigitalLearningSolutions.Data.Migrations/Scripts/TD-1766-GetCurrentCoursesForCandidateTweak.sql, DigitalLearningSolutions.Data.Migrations/Scripts/TD-1766-GetCurrentCoursesForCandidateTweak_down.sql
https://hee-tis.atlassian.net/browse/TD-1766
Corrected the stored procedure GetCurrentCoursesForCandidate_V2 by putting a condition to check if a customisation name is present or not and based on the result, appending it to the course name.
Before code changes - 
After code changes
-----
I have:
=> TD-1766 Corrected the stored procedure GetCurrentCoursesForCandidate_V2

DigitalLearningSolutions.Data/Models/UserFeedback/UserFeedbackTempData.cs, DigitalLearningSolutions.Web.Tests/Controllers/UserFeedbackControllerTest.cs, DigitalLearningSolutions.Web/Controllers/UserFeedbackController.cs, DigitalLearningSolutions.Web/Views/UserFeedback/GuestFeedbackStart.cshtml, DigitalLearningSolutions.Web/Views/UserFeedback/UserFeedbackTaskAttempted.cshtml
[TD-1116](https://hee-tis.atlassian.net/browse/TD-1116)
Updated caching and multipageformdata handling to allow for user browser back button.
The code now retains user values when the back button is clicked.
Once the feedback is submitted, the page no longer available message is shown as standard.
-----
I have:
[TD-1116]: https://hee-tis.atlassian.net/browse/TD-1116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1116 user feedback browser nav back issue

DigitalLearningSolutions.Data.Migrations/202307031453_AddReportSelfAssessmentActivityLogTable.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.Designer.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.resx, DigitalLearningSolutions.Data.Migrations/Scripts/TD-2117-CreatePopulateReportSelfAssessmentActivityLog-SP.sql
[TD-2117](https://hee-tis.atlassian.net/browse/TD-2117)
Migration to add a new ReportSelfAssessmentActivityLog table and populate it. Also includes a migration to add a stored procedure to append data to the table when executed by SQL agent job. SQL agent job will need adding to the production and test databases once published.
Table created and populated:
-----
I have:
[TD-2117]: https://hee-tis.atlassian.net/browse/TD-2117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-2117 Adds and populates self assessment activity log table for report data

DigitalLearningSolutions.Data/DataServices/PlatformReportsDataService.cs
[TD-2121](https://hee-tis.atlassian.net/browse/TD-2121)
Updates the queries added in TD-935 to reference the new self assessment activity log table for quicker retrieval.
Old query results vs new query results:
-----
I have:
[TD-2121]: https://hee-tis.atlassian.net/browse/TD-2121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-2121 updates report query to use new activity log table

DigitalLearningSolutions.Web/Controllers/SuperAdmin/Delegates/DelegatesController.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Delegates/ConfirmationViewModel.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Delegates/InactivateDelegateConfirmation.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Delegates/_SearchableDelegatesCard.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-2001
Activate/Inactivate delegate account feature added.
-----
I have:
=> TD-2001 - Activate/Inactivate delegate account feature added

DigitalLearningSolutions.Web/Views/SuperAdmin/Delegates/_SearchableDelegatesCard.cshtml
Remove button will be displayed if Centre email is available.
-----
I have:
=> TD-2000: Remove button will be displayed if Centre email is available.

DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Delegates/_SearchableDelegatesCard.cshtml
https://hee-tis.atlassian.net/browse/TD-2157
1. Issue with Unapproved status resolved
2. Verified tag will be displayed if email is present.
Email status when value present
-----
I have:
=> TD-2157: Issue with Unapproved status resolved. Verified tag will be displayed if email is present.

DigitalLearningSolutions.Web/ViewModels/Supervisor/MyStaffListViewModel.cs, DigitalLearningSolutions.Web/ViewModels/Supervisor/SupervisorDelegateDetailViewModel.cs
https://hee-tis.atlassian.net/browse/TD-1920
1) Fixed issue in Adding staff member functionality by handling null value and made parameters optional in model by modifying the viewmodels.
-----
I have:
=> TD-1920 Issue is fixed in Adding staff member functionality

DigitalLearningSolutions.Web/Controllers/SuperAdmin/Delegates/DelegatesController.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Delegates/DelegatesViewModel.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Delegates/SearchableDelegatesViewModel.cs
Super admin -Unused data fetch from table removed
-----
I have:
=> TD-2000: Super admin -Unused data fetch from table removed

DigitalLearningSolutions.Data.Tests/DataServices/RegistrationDataServiceTests.cs, DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests/DelegateUserDataServiceTests.cs, DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests/UserDataServiceTests.cs, DigitalLearningSolutions.Data/DataServices/RegistrationDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/DelegateUserDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs
https://hee-tis.atlassian.net/browse/TD-1960
Points addressed in this commit - 
1. Remove whitespace before insert during external registration
2. Remove whitespace before insert during internal registration
3. Remove whitespace before update from Tracking system --> Delegates
4. Remove whitespace before update from Super Admin --> Delegates
5. Bulk Upload users
Since this is a backend database change, no screenshot is required
-----
I have:
=> TD-1960 Trimmed whitespaces from usernames before insert or update in Users Table

DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/ViewModels/Supervisor/MyStaffListViewModel.cs
https://hee-tis.atlassian.net/browse/TD-1760
When  "Add myself to try self-assessment" is clicked,  user is not getting listed in the page.  We are losing the self assessment delegate value after the pagination filter is applied when its position is after 10 . 
Before code change:
**After code change:**
-----
I have:
=> TD-1760: Issue in "Add myself to try self-assessment" functionality is resolved

DigitalLearningSolutions.Data.Migrations/202307181724_UpdateAccessibilityStatementRecord.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1512
added 'mailto:' to links.
-----
I have:
=> TD-1512- DLS - Accessibility Statement - link issue fixed

DigitalLearningSolutions.Web/Startup.cs
[TD-2116](https://hee-tis.atlassian.net/browse/TD-2116)
Attempts to fix view not found error on seen on UAT server by adding the super admin reports to the list of MVC razor view locations registered in Startup.cs
N/A
-----
I have:
[TD-2116]: https://hee-tis.atlassian.net/browse/TD-2116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-2116 Adds MVC view location to startup

DigitalLearningSolutions.Data.Migrations/202307101239_AddAcceptableUsePolicyRecord.cs, DigitalLearningSolutions.Web/Controllers/LearningSolutions/LearningSolutionsController.cs, DigitalLearningSolutions.Web/Styles/home/Policies.scss, DigitalLearningSolutions.Web/ViewModels/LearningSolutions/AcceptableUsePolicyViewModel.cs, DigitalLearningSolutions.Web/Views/LearningSolutions/AcceptableUsePolicy.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1751
Heading text changed to bold. Modified variable name according to class/feature.
-----
I have:
=> TD-1751- DLS - Acceptable Use Policy - Heading text changed to bold.

DigitalLearningSolutions.Web/DigitalLearningSolutions.Web.csproj
TD-2116
For some reason the Build Action for the nursing proficiency reports view was set to 'None'. This fix set's the Build Action to 'Content' to fix problems with the view being unavailable when deployed.
-----
I have:
=> TD-2116 Changes build action for nursing proficiency reports page

DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Web/Controllers/Register/RegisterController.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-2177
primary email checked at UserCentreDetails table along with Users table.
-----
I have:
=> TD-2177-two delegate records at the same centre -primary email check at UserCentreDetails table added

DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/Courses.cshtml
https://hee-tis.atlassian.net/browse/TD-952
1. The heading showing on the screen made consistent with other screens 
2. Included missing  "Courses" word on tab in "View courses" page
**_After code change:_**
-----
I have:
=> TD-952:1. The heading showing on the screen made consistent with other screens 

DigitalLearningSolutions.Data/DataServices/SupervisorService.cs
https://hee-tis.atlassian.net/browse/TD-2094
Self assessments not displaying after removing the staff and adding back issue.
Enrolled 2 self-assessment to the staff → Removed the staff and added back → Only one self-assessment is assigned with the staff
**_After code change:_**
-----
I have:
=> TD-2094: Self assessments not displaying after removing the staff and adding back issue has been resolved

DigitalLearningSolutions.Web/Views/SuperAdmin/Delegates/_DelegateStatusTag.cshtml
https://hee-tis.atlassian.net/browse/TD-2284
Corrected spelling for unapproved account as per testing notes.
-----
I have:
=> TD-2284 Corrected spelling for unapproved account

DigitalLearningSolutions.Web/Views/Supervisor/Shared/_SignOffHistory.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/Shared/_SupervisorSignOffSummary.cshtml
[TD-2027](https://hee-tis.atlassian.net/browse/TD-2027)
Shows withdraw and resend links on supervisor sign off and sign off history views only when the status of the sign off request is not signed off.
-----
I have:
[TD-2027]: https://hee-tis.atlassian.net/browse/TD-2027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-2027 Fixes conditions for the display of withdraw and resend

DigitalLearningSolutions.Data/DataServices/CentresDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/CentresControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Centres/ContractTypeViewModel.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/EditContractInfo.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/ManageCentre.cshtml
Super admin-edit centre page issues resolved
1.  Date field null issue 
2.   Dropdown values not retaining
3. Date validation included
-----
I have:
=> TD-988: Super admin-edit centre page- Date field null issue and  Dropdown values not retaining

DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/CentresControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Centres/CentreRoleLimitsViewModel.cs
[TD-989](https://hee-tis.atlassian.net/browse/TD-989)
Fixed issue where Save button needed to be clicked twice under certain validation states.
-----
I have:
[TD-989]: https://hee-tis.atlassian.net/browse/TD-989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TD-989]: https://hee-tis.atlassian.net/browse/TD-989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-989 Super Admin Centre Role Limits Validation Fix

DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateProgress/ConfirmRemoveFromCourse.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateCourseProgressButtons.cshtml
https://hee-tis.atlassian.net/browse/TD-2369
1) Displayed "Remove from course" button when course progress is complete and update the confirmation text by modifying the views.
Note : Error showing in wave plugin is due to "single-checkbox" input component it is not due to my changes. I tried fixing it but the problem is in the view component which will be a separate ticket for investigation.
-----
I have:
=> TD-2369 Displayed "Remove from course" button when course progress is complete and update the confirmation text

DigitalLearningSolutions.Web/Styles/learningPortal/selfAssessment.scss, DigitalLearningSolutions.Web/Views/LearningPortal/Shared/_AssessmentQuestionStatusTag.cshtml
[TD-752](https://hee-tis.atlassian.net/browse/TD-752)
updated the CSS style of the confirmation status tag on self assessment page when viewed on a mobile device
-----
I have:
[TD-752]: https://hee-tis.atlassian.net/browse/TD-752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-752 Confirmation Status Tag style adjustment on mobile view

DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/CentresControllerTests.cs, DigitalLearningSolutions.Web/Controllers/MyAccountController.cs
https://hee-tis.atlassian.net/browse/TD-2281
1) Fixed 500 error while updating centre email of inactive learner by removing active flag criteria in getting email list by modifying the controller.
[Choose-A-Centre---Digital-Learning-Solutions.webm](https://github.com/TechnologyEnhancedLearning/DLSV2/assets/111436026/7db3841d-7bb9-4f3f-ae75-eccc60d7a7d0)
-----
I have:
=> TD-2281 Fixed 500 error while updating centre email of inactive learner by removing active flag criteria in getting email list

DigitalLearningSolutions.Web/Controllers/SuperAdmin/PlatformReports/SupervisedSelfAssessmentReport.cs
[TD-2116](https://hee-tis.atlassian.net/browse/TD-2116)
Sets the supervisor=true parameter in the model passed into the edit filters page after failed validation to ensure that the cancel link navigates to the correct page.
-----
I have:
[TD-2116]: https://hee-tis.atlassian.net/browse/TD-2116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-2116 Fixes the cancel link after failed validation

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml
https://hee-tis.atlassian.net/browse/TD-2459
1) Show sign off button when reconfirmed the results of self assessments by modifying the views.
-----
I have:
=> TD-2459 Show sign off button when reconfirmed the results of self assessments

DigitalLearningSolutions.Data/DataServices/SupervisorService.cs
https://hee-tis.atlassian.net/browse/TD-1758
When user enrol assessments by himself and a supervisor add this user as a staff member, all assessments will be displayed irrespective of centres.
User enrolled with 4 assessments
assessments will be displayed with **_"Supervise"_** link
When removed IV Therapy
When IV Therapy added back
-----
I have:
=> TD-1758: When user enroll himself and a supevisor add this user as staff member, all assessments will be displayed irrespective of centres.

DigitalLearningSolutions.Web/Views/SuperAdmin/PlatformReports/SelfAssessmentsReport.cshtml
[TD-2115](https://hee-tis.atlassian.net/browse/TD-2115) and [TD-2116](https://hee-tis.atlassian.net/browse/TD-2116)
Fixes the name of the reports JavaScript file in the script tag to match the case of the actual file name.
I have:
[TD-2115]: https://hee-tis.atlassian.net/browse/TD-2115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TD-2116]: https://hee-tis.atlassian.net/browse/TD-2116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-2115 & TD-2116 Corrects the case for the script name

DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/CentresControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Centres/CentreRoleLimitsViewModel.cs
[TD-989](https://hee-tis.atlassian.net/browse/TD-989)
Fixed Super Admin centre role limit validation to allow and handle null user inputs.
-----
I have:
[TD-989]: https://hee-tis.atlassian.net/browse/TD-989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-989 Super admin role limits validation fix

DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/CentresControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs
https://hee-tis.atlassian.net/browse/TD-2411
1. Fixed wrong value showing on 'Customise Role limits' screen by modifying the controller.
[Manage-Centre---Digital-Learning-Solutions.webm](https://github.com/TechnologyEnhancedLearning/DLSV2/assets/111436026/a9007806-14b4-4cac-84b4-f647208becb6)
-----
I have:
=> TD-2411 Fixed wrong value showing on 'Customise Role limits' screen

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs
https://hee-tis.atlassian.net/browse/TD-2094
1) Fixed duplicate entry issue when we remove the self assessment and re enrol it from the Tracking system by modifying the dataservice.
-----
I have:
=> TD-2094 Fixed duplicate entry issue when we remove the self assessment and re enrol it from the Tracking system

DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/CourseContent/_CourseSectionExpandable.cshtml
https://hee-tis.atlassian.net/browse/TD-2004
course are not shown in Course Setup for existing customisations
-----
I have:
=> TD_2004 course are not shown in Course Setup for existing customisations

DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs
[TD-989](https://hee-tis.atlassian.net/browse/TD-989)
Fixed issue where centre name was not displayed in the header after a validation failure.
-----
I have:
[TD-989]: https://hee-tis.atlassian.net/browse/TD-989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-989 Fix header text issue on failed validation.

DigitalLearningSolutions.Web/Views/Frameworks/Developer/Type.cshtml
[TD-2507](https://hee-tis.atlassian.net/browse/TD-2507)
Tidies the framework vocabulary list, pluralising "Proficiency" and removing "Requirements" from the drop-down.
I have:
[TD-2507]: https://hee-tis.atlassian.net/browse/TD-2507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-2507 Tidies the framework vocabulary drop down options

DigitalLearningSolutions.Web/Views/Supervisor/Shared/_SupervisorSignOffSummary.cshtml
[TD-2027](https://hee-tis.atlassian.net/browse/TD-2027)
Added conditional render logic so Withdraw sign-off link is not inadvertently displayed on Staff ProfileAssessment page due to use of shared _SupervisorSignOffSummary component.
Screenshot below
-----
I have:
[TD-2027]: https://hee-tis.atlassian.net/browse/TD-2027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-2027 Supervisor sign-off fix for spurious Withdraw sign-off link.

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs
https://hee-tis.atlassian.net/browse/TD-2094
1) Fixed issue occurs when self-assessment removed and then enrolled the same assessment via tracking system by modifying the dataservice.
-----
I have:
=> TD-2094 Fixed issue occurs when self-assessment removed and then enrolled the same assessment via tracking system

DigitalLearningSolutions.Data/Extensions/ConfigurationExtensions.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/BulkUploadController.cs, DigitalLearningSolutions.Web/Helpers/CommonValidationErrorMessages.cs, DigitalLearningSolutions.Web/Services/DelegateUploadFileService.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/UploadDelegatesViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/BulkUpload/Index.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/BulkUpload/StartUpload.cshtml, DigitalLearningSolutions.Web/appSettings.UAT.json, DigitalLearningSolutions.Web/appsettings.Development.json, DigitalLearningSolutions.Web/appsettings.Production.json, DigitalLearningSolutions.Web/appsettings.SIT.json, DigitalLearningSolutions.Web/appsettings.Test.json, DigitalLearningSolutions.Web/appsettings.UarTest.json
https://hee-tis.atlassian.net/browse/TD-2492
1. Added an appsettings entry to store a MaxBulkUploadRows, setting it to 200 to begin with.
2. Changed the text “File with updated information“ on the TrackingSystem/Delegates/BulkUpload/StartUpload page to read “File with updated information (max 200 rows)”
3. Validation message will be shown "File must contain no more than 200 rows"
-----
I have:
=> TD-2492 restrict the number of rows that can be uploaded for bulk update in excel 

DigitalLearningSolutions.Web/Views/Shared/SearchablePage/_Filters.cshtml
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-2855
Non relevant text replaced with filter object property which were causing issues JavaScript filters.
Need to test JavaScript filters option if they are displaying correctly . e.g. JavaScript filter from Tracking System > Admins
-----
I have:
=> TD-2855 non relevant text found in filters cshtml

DigitalLearningSolutions.Data.Tests/DataServices/ActivityDataServiceTests.cs, DigitalLearningSolutions.Data/DataServices/ActivityDataService.cs, DigitalLearningSolutions.Data/DataServices/PlatformReportsDataService.cs, DigitalLearningSolutions.Data/Models/PlatformReports/SelfAssessmentActivity.cs, DigitalLearningSolutions.Data/Models/TrackingSystem/ActivityLog.cs, DigitalLearningSolutions.Web.Tests/Services/ActivityServiceTests.cs, DigitalLearningSolutions.Web/Services/ActivityService.cs, DigitalLearningSolutions.Web/Services/PlatformReportService.cs
[TD-937](https://hee-tis.atlassian.net/browse/TD-937)
Adds SQL grouping to Course and Self Assessment usage data retrieved to reduce the number of rows returned by SQL. This vastly improves the performance of the report pages.
-----
I have:
[TD-937]: https://hee-tis.atlassian.net/browse/TD-937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-937 Groups data returned from DB by date to reduce number of rows retrieved

DigitalLearningSolutions.Web/Views/SuperAdmin/PlatformReports/_CourseActivityTable.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/PlatformReports/_SelfAssessmentActivityTable.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Reports/_ActivityTable.cshtml
[TD-2871](https://hee-tis.atlassian.net/browse/TD-2871)
Adds comma separators to the numbers displayed in report data lists.
-----
I have:
[TD-2871]: https://hee-tis.atlassian.net/browse/TD-2871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-2871 Formats numbers across report grids with comma separators

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/Shared/_SupervisorSignOffSummary.cshtml
https://hee-tis.atlassian.net/browse/TD-2524
1) Show sign off button only when all results are confirmed.
2) Show resend link only when all assessments are in confirmed state.
-----
I have:
=> TD-2524 show resend link only when all assessments are in confirmed state and sign off button when all results are confirmed

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/BulkUploadController.cs, DigitalLearningSolutions.Web/Helpers/CommonValidationErrorMessages.cs
https://hee-tis.atlassian.net/browse/TD-2865
Added an error validation if  bulk upload excel file doesn't contain correct worksheet **_"DelegatesBulkUpload”_**
-----
I have:
=> TD-2865 improve error messages when bulk upload excel file doesn't contain correct worksheet

DigitalLearningSolutions.Data.Tests/DataServices/UserDataServiceTests/AdminUserDataServiceTests.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/AdminUserDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Data/Models/User/AdminEntity.cs, DigitalLearningSolutions.Web.Tests/Helpers/FilterableTagHelperTests.cs, DigitalLearningSolutions.Web.Tests/Services/DashboardInformationServiceTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Administrator/AdministratorController.cs, DigitalLearningSolutions.Web/Helpers/FilterOptions/AdminFilterOptions.cs, DigitalLearningSolutions.Web/Helpers/FilterableTagHelper.cs, DigitalLearningSolutions.Web/Services/DashboardInformationService.cs, DigitalLearningSolutions.Web/Services/UserService.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Administrator/AdministratorsViewModelFilterOptions.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Administrator/SearchableAdminViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Administrator/_SearchableAdminCard.cshtml
https://hee-tis.atlassian.net/browse/TD-2503
1) Displayed admin accounts with inactive user account in 'Centre administrators' section of Tracking system.
2) Added filter options for filter of Centre administrators on the basis of user account status.
3) Added feature reactivating the Centre administrator account.
-----
I have:
=> TD-2503 Displayed admin account with inactive user account ,added filter for user account status and reactivate admin account

DigitalLearningSolutions.Web/Controllers/FindYourCentreController.cs
https://hee-tis.atlassian.net/browse/TD-2868
1) Error: 'Redirected to learning portal when logged in as delegate' is fixed by modifying the controller
[Choose-A-Centre---Digital-Learning-Solutions.webm](https://github.com/TechnologyEnhancedLearning/DLSV2/assets/111436026/d6bea151-5592-4077-8547-bd3322167eaa)
-----
I have:
=> TD-2868 Error: 'Redirected to learning portal when logged in as delegate' is fixed

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml
https://hee-tis.atlassian.net/browse/TD-2459
1) Fixed the visibility issue of a "Request sign off" and "Sign off" button by modifying the views.
-----
I have:
=> TD-1877 And TD-2459 Fixed the visibility issue of a "Request sign off" and "Sign off" button

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateCoursesController.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-2180
search text string is trimmed. SQL search modified in case CustomisationName is null.
Screenshots
N/A
-----
I have:
=> TD-2180-Search text with spaces fixed.

DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Reports/EditFilters.cshtml
https://hee-tis.atlassian.net/browse/TD-2872
1. Added 'frequency' word on 'Course reports' screen of Tracking system by modifying the views.
-----
I have:
=> TD-2872 console errors on independent self assessments and frequency word missing

DigitalLearningSolutions.Web/Views/VerifyYourEmail/_EmailChanged.cshtml
https://hee-tis.atlassian.net/browse/TD-2878
1. Fixed incorrect message showing on confirmation screen when updating centre and primary email by modifying the view.
[Edit-details---Digital-Learning-Solutions.webm](https://github.com/TechnologyEnhancedLearning/DLSV2/assets/111436026/784bac1f-0995-4470-9cee-3464831c4dcc)
-----
I have:
=> TD-2878 Fixed incorrect message showing on confirmation screen when updating centre and primary email

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/BulkUploadController.cs
https://hee-tis.atlassian.net/browse/TD-2865
1. Invalid upload file validation was not working- Issue fixed
Below validations verified
1. Invalid file (tried .xls,pdf files)
2. No file selected
3.  File with more than 200 rows
4. File without “DelegatesBulkUpload” worksheet.
-----
I have:
=> TD-2865: Invalid file format validation not working issue fixed.

DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/CourseDelegates/SelectedCourseDetailsViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/CourseDelegates/Index.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateCoursesBreadcrumbs.cshtml
[TD-1569](https://hee-tis.atlassian.net/browse/TD-1569)
Updated Delegate Course screen to show 'activity' instead of 'course'
-----
I have:
[TD-1569]: https://hee-tis.atlassian.net/browse/TD-1569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TD-1569]: https://hee-tis.atlassian.net/browse/TD-1569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1569 Relabel course delegate view and nav

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-2183
Search text string trimmed prior to execute SQL query.
-----
I have:
=> TD-2183 - Course delegates list to use SQL filtering - search issue fixed.

DigitalLearningSolutions.Data/Models/User/AdminEntity.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Centre/Administrator/AdministratorControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Administrator/AdministratorController.cs, DigitalLearningSolutions.Web/Helpers/FilterOptions/AdminFilterOptions.cs
https://hee-tis.atlassian.net/browse/TD-2503
1) Fixed issue of inactive user not displaying on list and also fixed the color issue of active and inactive tag by modifying the helper,controller and model.
-----
I have:
=> TD-2503 Fixed issue of inactive user not displaying on list and also fixed the color issue of active and inactive tag

DigitalLearningSolutions.Web/Controllers/LoginController.cs
https://hee-tis.atlassian.net/browse/TD-2912
I added the username to the validation
-----
I have:
=> TD-2912 login validation needs to highlight both fields

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Data/Models/Courses/DelegateAssessmentStatistics.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/DelegateCoursesControllerTests.cs, DigitalLearningSolutions.Web.Tests/Services/CourseServiceTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateCoursesController.cs, DigitalLearningSolutions.Web/Helpers/FilterableTagHelper.cs, DigitalLearningSolutions.Web/Services/CourseService.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/DelegateCourses/DelegateCoursesViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/DelegateCourses/SearchableDelegateAssessmentStatisticsViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/DelegateCourses/SearchableDelegateCourseStatisticsViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateCourses/Index.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateCourses/_CentreAssesmentCard.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateCourses/_CentreAssessmentCardDetails.cshtml
https://hee-tis.atlassian.net/browse/TD-1568
1) Show self assessments published to the centre into the "Delegate activities" list by modifying the dataservices,models,controllers,services,viewmodel,tests and helpers.
-----
I have:
=> TD-1568 Show self assessments published to the Centre into the "Delegate activities" List

DigitalLearningSolutions.Data/DataServices/SupervisorService.cs
https://hee-tis.atlassian.net/browse/TD-2933
Need to edit  query to ensure that  delegate that  did not have the same centre Id  with the supervisor did not appear
-----
I have:
=> TD-2933 supervise my staff list view selfassessments page not loading correct data 

DigitalLearningSolutions.Data/DataServices/UserDataService/DelegateUserCardDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Web.Tests/Services/DelegateDownloadFileServiceTests.cs, DigitalLearningSolutions.Web/Services/DelegateDownloadFileService.cs
https://hee-tis.atlassian.net/browse/TD-2184
1. Search term trim implemented 
2. Count mismatch between UI and excel report fixed
UI Count: 84
Excel count: 85 including header
-----
I have:
=> TD-2184:1. Search term trim implemented 2. Count mismatch between UI and excel report fixed

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/RequestSignOff.cshtml
https://hee-tis.atlassian.net/browse/TD-2969
1) Displayed centre name of the 'Educator' when requesting sign off by modifying view.
-----
I have:
=> TD-2969 Displayed centre name of the 'Educator' when requesting sign off

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/ReviewConfirmationRequests.cshtml
https://hee-tis.atlassian.net/browse/TD-2988
1) Fixed overlapping action links on Manage confirmation requests screen by modifying view.
-----
I have:
=> TD-2988 Fixed overlapping action links on Manage confirmation requests screen

DigitalLearningSolutions.Data.Migrations/202310191439_AddAssessmentTypesPK.cs
[TD-3025](https://hee-tis.atlassian.net/browse/TD-3025)
Migration to add the missing primary key to the AssessmentTypes table on the existing AssessmentTypeID column.
-----
I have:
[TD-3025]: https://hee-tis.atlassian.net/browse/TD-3025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3025 Add assessment types table primary key

DigitalLearningSolutions.Data/DataServices/UserDataService/DelegateUserCardDataService.cs
https://hee-tis.atlassian.net/browse/TD-2184
Excel report was not getting sorted when sorting is selected in UI.
**_UI_**
**_Excel report_**
-----
I have:
=> TD-2184: Excel report was not getting sorted when sorting is selected in UI

DigitalLearningSolutions.Data.Migrations/202310181537_AspProgressAddSuspenDataColumn.cs, DigitalLearningSolutions.Data/DataServices/ProgressDataService.cs, DigitalLearningSolutions.Data/Enums/TrackerEndpointAction.cs, DigitalLearningSolutions.Data/Enums/TrackerEndpointResponse.cs, DigitalLearningSolutions.Data/Models/Tracker/TrackerEndpointQueryParams.cs, DigitalLearningSolutions.Web.Tests/Services/ProgressServiceTests.cs, DigitalLearningSolutions.Web/Services/ProgressService.cs, DigitalLearningSolutions.Web/Services/StoreAspService.cs, DigitalLearningSolutions.Web/Services/TrackerActionService.cs, DigitalLearningSolutions.Web/Services/TrackerService.cs
Adds a new field `SuspendData` to the aspProgress table. Implements new StoreSuspendData and GetSuspendData endpoints to store and retrieve bookmark data in the new field.
-----
I have:
=> TD-3009 store and get scorm suspend data Tracker endpoints

DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Configuration/EditCentreManagerDetailsViewModel.cs
https://hee-tis.atlassian.net/browse/TD-2930
1) Added Max/Min character limit validation for 'Contact phone' is missing on 'Edit centre manager details' screen of 'Super Admin' interface by modifying viewmodel.
-----
I have:
=> TD-2930 Added Max/Min character limit validation for 'Contact phone' is missing on 'Edit centre manager details' screen of 'Super Admin' interface

DigitalLearningSolutions.Data/DataServices/GroupsDataService.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateGroupsController.cs, DigitalLearningSolutions.Web/Services/GroupsService.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateGroups/Index.cshtml
https://hee-tis.atlassian.net/browse/TD-2958
1) Fixed heading and also added validation for duplicate group name not allowed by modifying dataservice,service,controller and view.
-----
I have:
=> TD-2958 Fixed heading and also added validation for duplicate group name not allowed

DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/AllDelegates/AllDelegatesViewModelFilterOptions.cs
https://hee-tis.atlassian.net/browse/TD-2993
1) Made status filter dropdown second word first letter of the status filter headings in lower case by modifying viewmodel.
-----
I have:
=> TD-2993 Made status filter dropdown second word first letter of the second word first letter of the status filter headings in lower case

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Data/Helpers/GenericSortingHelper.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/SelfAssessmentDelegate.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/CourseDelegatesControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ActivityDelegatesController.cs, DigitalLearningSolutions.Web/Helpers/FilterOptions/SelfAssessmentDelegateFilterOptions.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/CourseDelegates/SelfAssessmentDelegateViewModelFilterOptions.cs
https://hee-tis.atlassian.net/browse/TD-2972
TD-2972- Feature "Activity Delegates sort and filter options specific to self assessment activities" implemented.
New sort and filter options created for self assessment activities. Modified SQL query accordingly.
-----
I have:
=> TD-2972-Activity Delegates- Sort and filter options added to self assessment activities

DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_OverviewActionButtons.cshtml
https://hee-tis.atlassian.net/browse/TD-3032
1) Fixed downloaded reports file name in self assessment from Learning Portal by modifying view and controller.
-----
I have:
=> TD-3032 Fixed downloaded reports file name in self assessment from Learning Portal

DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Centres/AddCentreSuperAdminViewModel.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Centres/EditCentreDetailsSuperAdminViewModel.cs
https://hee-tis.atlassian.net/browse/TD-2408
1. Placed 250 character limit on Add centre screen
2. Placed consistent IP address validation on both Add centre and Edit Centre so that it accepts IP address as well as IP address Prefix
3. Resolved case sensitive duplicate centres name in add centre screen
4. Trimmed leading and trailing whitespace while entering centre name
-----
I have:
=> TD-2408 Making add centre and edit centre consistent in validations

DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs
https://hee-tis.atlassian.net/browse/TD-2408
Centre name trimming while comparing to existing centre name
-----
I have:
=> TD-2408 edit centre white space validation

DigitalLearningSolutions.Web/Controllers/SuperAdmin/PlatformReports/PlatformReportsController.cs, DigitalLearningSolutions.Web/Services/PlatformUsageSummaryDownloadFileService.cs, DigitalLearningSolutions.Web/Startup.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/PlatformReports/Index.cshtml
https://hee-tis.atlassian.net/browse/TD-936
Added export button to platform usage summary page to export the usage summary to excel file
-----
I have:
=> TD-936 super admin reports overall usage download

DigitalLearningSolutions.Web/Services/CourseService.cs
https://hee-tis.atlassian.net/browse/TD-2891
1) Fixed 404 error on the screen when clicked 'Remove from activity' button for courses marked as Complete by modifying service.
[Activity-delegates---Digital-Learning-Solutions.webm](https://github.com/TechnologyEnhancedLearning/DLSV2/assets/111436026/1ec53a20-1d74-4693-bdf7-eac6c9a8ca66)
-----
I have:
=> TD-2891 Fixed 404 error on the screen when clicked 'Remove from activity' button for courses marked as Complete

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Web/Services/CourseDelegatesDownloadFileService.cs, DigitalLearningSolutions.Web/Services/CourseService.cs
https://hee-tis.atlassian.net/browse/TD-2185
1) Fixed records mismatch between delegates courses records shown in list and records which are exported to excel by modifying dataservice and service.
-----
I have:
=> TD-2185 Fixed records mismatch between delegates courses records shown in list and records which are exported to excel

DigitalLearningSolutions.Data/DataServices/GroupsDataService.cs
https://hee-tis.atlassian.net/browse/TD-3033
1) Fixed data mismatch in delegates list with group filter and delegate count data in delegate groups by modifying dataservice.
-----
I have:
=> TD-3033 Issue with delegates not appearing in the delegate group & not being assigned the courses

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/DCSAReportDataService.cs
https://hee-tis.atlassian.net/browse/TD-1988
1) Fixed the sql query to include all learners irrespective whether they enrolled at a assessment in centre or not by modifying dataservice.
-----
I have:
=> TD-1988 Fixed the sql query to include all learners irrespective whether they enrolled at a assessment in centre or not

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/RemoveSelfAssessmentDelegate.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/SelfAssessmentDelegate.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ActivityDelegatesController.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/DelegateSelfAssessmenteViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/Shared/DelegateSelfAssessmentInfoViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/ActivityDelegates/RemoveDelegateSelfAssessment.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateSelfAssessmentDetails.cshtml
https://hee-tis.atlassian.net/browse/TD-1570
Adding RemoveDelegateSelfAssesment page to user to confirm the action and adding a query which update the status of the delegate from one to two
-----
I have:
=> TD-1570 implement remove from self assessment functionality

DigitalLearningSolutions.Data.Migrations/202311060819_AspProgressAddLessonLocationColumn.cs, DigitalLearningSolutions.Data/DataServices/ProgressDataService.cs, DigitalLearningSolutions.Data/Enums/TrackerEndpointAction.cs, DigitalLearningSolutions.Data/Enums/TrackerEndpointResponse.cs, DigitalLearningSolutions.Data/Models/Tracker/TrackerEndpointQueryParams.cs, DigitalLearningSolutions.Web/Services/ProgressService.cs, DigitalLearningSolutions.Web/Services/StoreAspService.cs, DigitalLearningSolutions.Web/Services/TrackerActionService.cs, DigitalLearningSolutions.Web/Services/TrackerService.cs
Reverts code implementing new endpoints in the Tracker API for getting suspend data and lesson location because they are no longer needed.
-----
I have:
=> TD-3009 Remove redundant tracker GET endpoints

DigitalLearningSolutions.Web.Tests/Helpers/SystemEndpointHelperTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/ContentViewerViewModelTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/DiagnosticContentViewModelTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/LearningMenu/PostLearningContentViewModelTests.cs, DigitalLearningSolutions.Web/Helpers/SystemEndpointHelper.cs
[TD-1555](https://hee-tis.atlassian.net/browse/TD-1555)
Updates the system endpoint helper to return the location of the new tracker API instead of the legacy one.
-----
I have:
[TD-1555]: https://hee-tis.atlassian.net/browse/TD-1555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1555 Pass new tracker url to content player

DigitalLearningSolutions.Data/DataServices/ProgressDataService.cs, DigitalLearningSolutions.Data/Enums/TrackerEndpointResponse.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/DelegateProgressControllerTests.cs, DigitalLearningSolutions.Web.Tests/Services/ProgressServiceTests.cs, DigitalLearningSolutions.Web/Services/ProgressService.cs, DigitalLearningSolutions.Web/Services/StoreAspService.cs, DigitalLearningSolutions.Web/Services/TrackerActionService.cs
The tracker calls are fire and forget, calling void methods in the data service to update progress records. This changes the methods to return an int count of number of records updated. When this is 0 the API returns a new -3 no row updated error. This is needed to test calls to the API effectively.
-----
I have:
=> TD-3009 Tracker API adds no row updated error

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ActivityDelegatesController.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateSelfAssessmentDetails.cshtml
https://hee-tis.atlassian.net/browse/TD-3035
Existing data service used to load the latest assessment results for the candidate assessment and count of 'questions', 'self assessed' and 'confirmed' retried from the result.
-----
I have:
=> TD-3035 - Progress summary added into self assessment card

DigitalLearningSolutions.Data/DataServices/ProgressDataService.cs, DigitalLearningSolutions.Data/Enums/TrackerEndpointAction.cs, DigitalLearningSolutions.Web/Services/ProgressService.cs, DigitalLearningSolutions.Web/Services/StoreAspService.cs, DigitalLearningSolutions.Web/Services/TrackerActionService.cs, DigitalLearningSolutions.Web/Services/TrackerService.cs
Previous implementations stored changes to aspProgress fields in separate endpoint calls. This resulted in lots of database traffic and SQL transaction deadlocks. This new implementation combines updates to all fields into a single UpdateLessonState endpoint which will be called only once to reduce transaction traffic and avoid deadlocks.
-----
I have:
=> TD-3009 Implements combined UpdateLessonState endpoint

DigitalLearningSolutions.Data/DataServices/ProgressDataService.cs, DigitalLearningSolutions.Web/Services/TrackerService.cs
UAT testing revealed that tutorial status and time parameters were being swapped and that an unnecessary clause in the update query was preventing aspProgress records from being updated in most scenarios. This change fixes the mapping of the endpoint and service parameters and removes the unnecessary clause in the update query.
-----
I have:
=> TD-3009 Fix parameter mapping and query clause

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/DelegateCoursesControllerTests.cs, DigitalLearningSolutions.Web.Tests/Services/CourseServiceTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateCoursesController.cs, DigitalLearningSolutions.Web/Services/CourseService.cs
https://hee-tis.atlassian.net/browse/TD-3121
Search, sort and filters applied to delegate activities. Sorting implemented by Linq as self assessments are appended to course object to create one common object.
-----
I have:
- [] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken
=> TD-3121 - Implement search and filter of self assessments in the delegate activities screen

DigitalLearningSolutions.Data.Migrations/202311270911_SwitchOffPeriodFields.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.Designer.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.resx, DigitalLearningSolutions.Data.Migrations/Scripts/TD-2036-SwitchOffPeriodFields-DOWN.sql, DigitalLearningSolutions.Data.Migrations/Scripts/TD-2036-SwitchOffPeriodFields-UP.sql
[TD-2036](https://hee-tis.atlassian.net/browse/TD-2036)
Switches off period fields on system versioned tables in preparation for replication.
-----
I have:
[TD-2036]: https://hee-tis.atlassian.net/browse/TD-2036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-2036 Migration to switch off period fields on system versioned tables

DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateCourses/Index.cshtml
https://hee-tis.atlassian.net/browse/TD-3171
missing side navigation links added to delegate activities view.
-----
I have:
=> TD-3171- Mobile view: side navigation links added on delegate activities

DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateSelfAssessmentDetails.cshtml
https://hee-tis.atlassian.net/browse/TD-3172
Enrolled label changed to 'First enrolled'
-----
I have:
=> TD-3172-Label name changed

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Data/Helpers/GenericSortingHelper.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ActivityDelegatesController.cs
https://hee-tis.atlassian.net/browse/TD-2972
'Submitted' filter issue fixed. 'Self assessed' and 'Confirmed' sort by options has been removed.
-----
I have:
=> TD-2972-Activity Delegates sort and filter options -'submitted' filter issue fixed.

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateCoursesController.cs
[TD-3200](https://hee-tis.atlassian.net/browse/TD-3200)
Changed the URL to 'Activities' instead of 'Courses'
-----
I have:
[TD-3200]: https://hee-tis.atlassian.net/browse/TD-3200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3200 Changed name of link to activities instead of courses

DigitalLearningSolutions.Data.Migrations/202311301431_CreateAssessmentResultsSP.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.Designer.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.resx, DigitalLearningSolutions.Data.Migrations/Scripts/TD-3187-CreateGetAssessmentResultsByDelegate-SP.sql, DigitalLearningSolutions.Data.Migrations/Scripts/TD-3187-CreateGetCandidateAssessmentResultsById-SP.sql, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs
https://hee-tis.atlassian.net/browse/TD-3187
Converted SQL queries to stored procedure. These stored procedure are being used in the views attached in screenshots section.
-----
I have:
=> TD-3187- Move latest self assessment result queries to stored procedures

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateCoursesController.cs
https://hee-tis.atlassian.net/browse/TD-3121
Restricted self assessments when topic and/or admin fields filters are selected.
-----
I have:
=> TD-3121-Restricted self assessments when topic and/or admin fields filters are selected

DigitalLearningSolutions.Web/Styles/layout.scss, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_OverviewTable.cshtml
[TD-752](https://hee-tis.atlassian.net/browse/TD-752)
Fixes mobile view layout issues for the self assessment menu screen.
-----
I have:
[TD-752]: https://hee-tis.atlassian.net/browse/TD-752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-752 Fix self assessment menu mobile view fixes

DigitalLearningSolutions.Web/Controllers/Support/RequestSupportTicketController.cs, DigitalLearningSolutions.Web/Views/Support/RequestSupportTicket/RequestSummary.cshtml
Fixes error when one of many attachments is removed from the ticket before submitting. The code was removing all attachment files when a file was removed. We now match the filename and delete only that file. Also tweaks label of the "summary" field to make it closer to the wireframe.
-----
I have:
=> TD-2286 Fix testing fails - tweak label and fix remove attachment

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/ReviewConfirmationRequests.cshtml
https://hee-tis.atlassian.net/browse/TD-2988
Increased width of table column 'Request'.
-----
I have:
=> TD-2988 overlapping action links- Issue Fix

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ActivityDelegatesController.cs, DigitalLearningSolutions.Web/Services/DelegateActivityDownloadFileService.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs
[TD-2973](https://hee-tis.atlassian.net/browse/TD-2973)
Added competencies count and implemented filters
Activities Delegates screen - 
Exported file- 
Contains only 1 record as per above screenshot (signed off filter applied). Also shows the competencies count
-----
I have:
[TD-2973]: https://hee-tis.atlassian.net/browse/TD-2973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD 2973 Added competencies count and implemented filters

DigitalLearningSolutions.Web/Views/VerifyYourEmail/_EmailChanged.cshtml
https://hee-tis.atlassian.net/browse/TD-2878
Extra message removed.
-----
I have:
=> TD-2878- UAR: Showing incorrect msg on 'Edit details' screen - Fixed

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateCoursesController.cs
https://hee-tis.atlassian.net/browse/TD-3202
Filter variable assigned "NotActive" and "HasAdminFields" filters.
-----
I have:
=> TD-3202-filter issue for Delegate activity export - fixed

DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Views/Supervisor/Shared/_DelegateProfileAssessmentGrid.cshtml
https://hee-tis.atlassian.net/browse/TD-3128
Fixing the bug when clicking ‘supervise’/'Not supervising' links multiple times 
Ensuring the stop supervising link shows only when ‘Educator/Manager’ role is assign to self assessment
-----
I have:
=> TD-3128 Fixing problems with assigning Educator/Manager and Accessor

DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs
[TD-3284](https://hee-tis.atlassian.net/browse/TD-3284)
Reintroduced ucd.ID in the GetAllDelegates service query that was removed as a part of TD-3002.
Smoke tested TD-3002 and it is working fine. Have suggested testers in jira to thoroughly test TD-3002 again.
-----
I have:
[TD-3284]: https://hee-tis.atlassian.net/browse/TD-3284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3284 Introduced ucd.ID in GetAllDelegates query

DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs
https://hee-tis.atlassian.net/browse/TD-3255
Empty string  assigned to 'search' variable when it is null
-----
I have:
=> TD-3255 -Super Admin Centres page - search field if left blank results in 500 error 

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateCoursesController.cs
https://hee-tis.atlassian.net/browse/TD-3304
Updated the filter string before removing the Type filter.
-----
I have:
=> TD-3304-Delegate activities export issue when filters Type: Couse and Staus: Inactive/archived - Fixed

DigitalLearningSolutions.Web/ViewModels/Support/RequestSupportTicket/RequestAttachmentViewModel.cs
Fixes issue found in testing where attaching an mp4 to a support request triggers a validation error. This change simply adds mp4 to the list of allowed extensions in the ViewModel.
-----
I have:
=> TD-2286 Allow mp4 support ticket attachments

DigitalLearningSolutions.Web/Styles/index.scss
[TD-752](https://hee-tis.atlassian.net/browse/TD-752)
Site wide scss fix to ensure tag text is always centre aligned.
-----
I have:
[TD-752]: https://hee-tis.atlassian.net/browse/TD-752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-752 Mobile view tag alignment fix

DigitalLearningSolutions.Data/DataServices/GroupsDataService.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateGroupsController.cs, DigitalLearningSolutions.Web/Services/GroupsService.cs
[TD-2958](https://hee-tis.atlassian.net/browse/TD-2958)
1. Compared group name from group ID with the group name in the existing model. If it is the same (no changes made in group name on edit screen), then proceeded with an update otherwise shows error.
2. Introduced centreID in IsDelegateGroupExist method to check for groups within same centre.
-----
I have:
[TD-2958]: https://hee-tis.atlassian.net/browse/TD-2958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD 2958 Fixed edit same group name issue and included centre in condition

DigitalLearningSolutions.Web/Controllers/Support/RequestSupportTicketController.cs, DigitalLearningSolutions.Web/DigitalLearningSolutions.Web.csproj
The Request Support multi-page form had been implemented using TempData to store the request model across the pages of the request support transaction. This resulted in 'Bad Request' errors once the cookie size had been exceeded. This change moves the Request Support to use the multi-page form service to store the data to SQL (the standard code pattern in DLS). This change also updates the web project to use the latest version of the multi-page form service so that we can take advantage of the generic multi-page form implementation.
-----
I have:
[TD-2286]: https://hee-tis.atlassian.net/browse/TD-2286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVm …
=> TD-2286 Uses the multi-page form service to store transactional data across request support forms

DigitalLearningSolutions.Data/DataServices/GroupsDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/DelegateUserCardDataService.cs, DigitalLearningSolutions.Web/Services/GroupsService.cs
https://hee-tis.atlassian.net/browse/TD-3313
'View delegates' query used to show delegate count.
-----
I have:
=> TD-3313- Issue with 'Delegates' count showing as '0' on 'Delegates Groups' screen for the listed groups

DigitalLearningSolutions.Data/Models/Support/RequestAttachment.cs, DigitalLearningSolutions.Web/Controllers/Support/RequestSupportTicketController.cs, DigitalLearningSolutions.Web/Views/Support/RequestSupportTicket/RequestAttachment.cshtml
Adds the file size to the RequestAttachment model. This is now displayed on the list of uploaded attachments and used to calculate the total size of attached files when uploading in separate batches. This prevents circumventing the file size validation by uploading attachments in separate batches totalling more than 20 MB.
-----
I have:
=> TD-2286 Addresses issues with attaching more than 20 MB in separate uploads

DigitalLearningSolutions.Data/DataServices/SupervisorService.cs, DigitalLearningSolutions.Data/Models/Supervisor/CandidateAssessmentSupervisor.cs, DigitalLearningSolutions.Web.Tests/Controllers/SupervisorController/SupervisorControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/SupervisorController.cs
https://hee-tis.atlassian.net/browse/TD-3128
Removed existing TempData check used for browser post back operation and added check for candidate assessment supervisor if present which handles browser post back situation as well as added new supervisor.
Issue resolved on the following page, when user supervise self assessments one by one.
-----
I have:
=> TD-3128- Supervise link 410 issue - when clicked for next self assessment immediately.

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CentreSelfAssessmentsDataService.cs, DigitalLearningSolutions.Data/Models/SuperAdmin/CentreSelfAssessment.cs, DigitalLearningSolutions.Data/Models/SuperAdmin/SuperAdminDelegateAccount.cs, DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests/EditCourseDetailsAccessibilityTests.cs, DigitalLearningSolutions.Web.AutomatedUiTests/AccessibilityTests/SuperAdminAccessibilityTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/CentresControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs, DigitalLearningSolutions.Web/Services/CentreSelfAssessmentsService.cs, DigitalLearningSolutions.Web/Startup.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Centres/CentreSelfAssessmentsViewModel.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/CourseAdd.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/SelfAssessments.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/_CentreCard.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Delegates/InactivateDelegateConfirmation.cshtml
TD-2318
Implements a super admin -> centres -> self assessments view to list the self assessments published to a centre. Also adds a super admin UI accessibility tests class to test existing super admin UI (and fix associated issues) as well as the new view.
-----
I have:
=> TD-2318 Super admin centre self assessments view

DigitalLearningSolutions.Web/appsettings.json
[TD-2483](https://hee-tis.atlassian.net/browse/TD-2483)
Appsettings contained a base URL for the Learning Hub Test Auth instance. This change replaces it with a reference to the production Auth service.
-----
I have:
[TD-2483]: https://hee-tis.atlassian.net/browse/TD-2483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-2483 Fix Learning Hub SSO base URL setting

DigitalLearningSolutions.Data/DataServices/UserDataService/DelegateUserDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Web.Tests/Services/DashboardInformationServiceTests.cs, DigitalLearningSolutions.Web/Services/DashboardInformationService.cs
[TD-3222](https://hee-tis.atlassian.net/browse/TD-3222)
For the count mismatch on the dashboard, we have used the same service as used for getting delegates count on the delegates page. Now both places will show only the approved delegates that have properly formatted email like (''%@%.__%'')
-----
I have:
[TD-3222]: https://hee-tis.atlassian.net/browse/TD-3222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3222 Tracking system dashboard and delegates page count mismatch solved

DigitalLearningSolutions.Web/Services/TrackerActionService.cs
[TD-3605](https://hee-tis.atlassian.net/browse/TD-3605)
This is a straightforward tweak to the DLSV2 tracker endpoint to check for course completion when tutorial progress is stored. This needs releasing as an urgent hotfix, hence PR to master.
-----
I have:
[TD-3605]: https://hee-tis.atlassian.net/browse/TD-3605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3605 Adds clause to StoreAspProgressNoSession tracker method to check completion

DigitalLearningSolutions.Web/Services/TrackerActionService.cs
[TD-3605](https://hee-tis.atlassian.net/browse/TD-3605)
Adds the call to check for completion and send a completion email to the UpdateLessonState tracker endpoint used by the updated SCORM player. Previous change was to the equivalent endpoint called by the DLS bespoke content.
-----
I have:
[TD-3605]: https://hee-tis.atlassian.net/browse/TD-3605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3605 Calls check for completion in the new UpdateLessonState endpoint

DigitalLearningSolutions.Data.Migrations/202401161703_UpdateCandidateAssessments_SetDateMinValueToNull.cs, DigitalLearningSolutions.Data/DataServices/CourseDataService.cs
https://hee-tis.atlassian.net/browse/TD-3271
This issue was resolved  by TD-1992 and working as expected.
completeByDateDynamic variable is set to null to avoid any chances of inserting empty value (1900-01-01 00:00:00.000) to completeByDate.
Migration code added which updates CandatateAssessments and sets completeByDate date as NULL to '1900-01-01 00:00:00.000'
-----
I have:
=> TD-3271- migration - Date min value is set to null in the CandatateAssessments table

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs
https://hee-tis.atlassian.net/browse/TD-3166
Delegate assessment statistics query modified to return correct count of Enrolled and Submitted/Signed off delegates.
-----
I have:
=> TD-3166- Mismatch of Enrolled and Submitted/Signed off count

DigitalLearningSolutions.Data/DataServices/CourseContentService.cs, DigitalLearningSolutions.Data/DataServices/SessionDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/CompletionSummaryTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/DiagnosticAssessmentTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/DiagnosticContentTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/IndexTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/PostLearningAssessmentTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/PostLearningContentTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/SectionTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/TutorialContentTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/TutorialTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/TutorialVideoTests.cs, DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs, DigitalLearningSolutions.Web/Services/SessionService.cs
[TD-3616](https://hee-tis.atlassian.net/browse/TD-3616)
Waits for return value of update session call before executing update progress call (which counts session records that are otherwise locked). Add WITH (NOLOCK) to queries to avoid deadlocking. Updates related tests to check for update session call rather than update progress call which is now hidden in a conditional.
-----
I have:
[TD-3616]: https://hee-tis.atlassian.net/browse/TD-3616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3616 Fix transaction deadlocks triggered by learning menu controller

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs
https://hee-tis.atlassian.net/browse/TD-3611
Delegate courses - query modified for blank and not-blank filter values.
-----
I have:
=> TD-3611- prompts filter not working

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs
https://hee-tis.atlassian.net/browse/TD-3611
SQL where condition modified for Export report.
-----
I have:
=> TD-3611- Delegate courses-prompt filter export issue

DigitalLearningSolutions.Web/Views/Shared/SearchablePage/_Search.cshtml
[TD-3621](https://hee-tis.atlassian.net/browse/TD-3621)
Changing Text Of Placeholder Text
-----
I have:
[TD-3621]: https://hee-tis.atlassian.net/browse/TD-3621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3621 Changing Text Of Placeholder Text

DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Data/Models/SuperAdmin/SuperAdminDelegateAccount.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Delegates/SearchableDelegatesViewModel.cs
https://hee-tis.atlassian.net/browse/TD-3604
Added the CentreEmailVerified property and referenced the same in the view to display the centre email status.
-----
I have:
=> TD-3604-Centre email not verified is showing as 'Verified' on 'Delegates' section

DigitalLearningSolutions.Data.Migrations/202401250814_DeleteDeprecatedFields.cs
[TD-3068](https://hee-tis.atlassian.net/browse/TD-3068)
During user account refactor work, several fields were deprecated. This migration deletes the deprecated fields. During work on this, the data services project was searched for references to deprecated fields and none were found.
-----
I have:
[TD-3068]: https://hee-tis.atlassian.net/browse/TD-3068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3068 Delete deprecated fields

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ActivityDelegatesController.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/CourseDelegates/SelectedDelegateDetailsViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateSelfAssessmentDetails.cshtml
https://hee-tis.atlassian.net/browse/TD-3610
'submitted' 'signed off' filter and sort options fields displays according to self assessments.
'Submitted' field/filter/sort option will be displayed only for 'Digital Capability Self Assessment' and 
'Signed Off' field/filter/sort option will be displayed for all self assessments other than 'Digital Capability Self Assessment'
-----
I have:
=> TD-3610-Show either "Submitted" or "Signed off" fields and filters.

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/DCSAReportDataService.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/SelfAssessmentReports/SelfAssessmentReportsController.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentReportService.cs
TD-3639
Quick reversion of code for Tracking System -> Centre Reports -> Self assessment reports -> DSAT report to prevent it from returning learners that have no account at the user's centre. Faulty code was introduced in TD-1988.
New code was left in place (though no longer used) to make a correct fix to TD-1988 easier.
-----
I have:
=> TD-3639 Returns pre release .23 code to fix DSAT report

.github/workflows/continuous-integration-workflow.yml, DigitalLearningSolutions.Data.Migrations/202401290942_RenameDeprecatedStoredProcs.cs, DigitalLearningSolutions.Data.Migrations/202401311625_DeleteDeprecatedSPs.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.Designer.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.resx, DigitalLearningSolutions.Data.Migrations/Scripts/TD-3664-RestoreDroppedSPs.sql
[TD-3664](https://hee-tis.atlassian.net/browse/TD-3664)
Migration to drop deprecated stored procedures. Also tweaks the deprecation migration to make the list public and add a missing migration.
-----
I have:
[TD-3664]: https://hee-tis.atlassian.net/browse/TD-3664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3664 drop deprecated stored procedures

DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_CourseDelegatesBreadcrumbs.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_CourseDelegatesProgressBreadcrumbs.cshtml
https://hee-tis.atlassian.net/browse/TD-3168
I change Delegate courses navigation breadcrumb links to Delegate activities on Delegate Progress view and learning log view
-----
I have:
=> TD-3168 Changing Delegate courses Navigation breadcrumb links to Delegate activities

DigitalLearningSolutions.Data.Migrations/202401301650_AddGroupDelegatesConstraints.cs
https://hee-tis.atlassian.net/browse/TD-3640
Migration script added to delete duplicate records from GroupDelegates table and add unique constraint on GroupID and DelegateID.
Duplicate records before migration on dev.:
Constraints on table before migration:
----
Duplicate records after migration on dev.:
Constraints on table after migration:
-----
I have:
=> TD-3640 - Added script to delete duplicate records and add unique constraint.

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ActivityDelegatesController.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/CourseDelegates/ActivityDelegatesViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/CourseDelegates/SelectedDelegateDetailsViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/Shared/DelegateSelfAssessmentInfoViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateSelfAssessmentDetails.cshtml
https://hee-tis.atlassian.net/browse/TD-3610
Validated unsupervised self-assessment from database.
Screen shot below displays 'submitted' filter for unsupervised self assessment.
-----
I have:
=> TD-3610-Validated unsupervised self-assessment from database.

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/SelfAssessmentDelegate.cs, DigitalLearningSolutions.Web/Helpers/FilterableTagHelper.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/Shared/DelegateSelfAssessmentInfoViewModel.cs
https://hee-tis.atlassian.net/browse/TD-3214
I needed to make the self assessment tag to show according to the status of the self assessment
-----
I have:
=> TD-3214 Adding Submitted / Signedoff Status tags

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateCoursesController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateGroupsController.cs, DigitalLearningSolutions.Web/Helpers/FilterHelper.cs
https://hee-tis.atlassian.net/browse/TD-3073
Mismatched filter options have been removed for Topic and Category filters when user change the logged in centre.
Filter options selected at HEE Demo Centre
Filter options at other centre.
-----
I have:
=> TD-3073-Filters applied in one centre affects the other centres

DigitalLearningSolutions.Web/Helpers/FilterableTagHelper.cs
https://hee-tis.atlassian.net/browse/TD-3214
Ensure that all condition for supervisor is meant to show either the self assessment is signoff/not signoff or submitted/not submitted
-----
I have:
=> TD-3214 Taking care of other condition of supervisor

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateCourses/_CentreAssessmentCardDetails.cshtml
https://hee-tis.atlassian.net/browse/TD-3672
SQL query/view modified to show Signed of/Submitted on the delegate activities self assessment card based on supervised/unsupervised self assessment.
_
-----
I have:
=> TD-3672 - Delegate activities self assessment cards submitted signed off fields - issue fix

DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/_CentreCourseCard.cshtml
https://hee-tis.atlassian.net/browse/TD-3667
A condition added in the view to show copy course link for active courses.
-----
I have:
=> TD-3667 - show copy course link to active courses.

DigitalLearningSolutions.Web/Helpers/FilterableTagHelper.cs
https://hee-tis.atlassian.net/browse/TD-3668
A condition added to tag helper class to show 'Visible in Learning portal' tag for active courses.
-----
I have:
=> TD-3668 - condition added to tag helper class to show 'Visible in Learning portal' tag for active courses.

DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/CentresControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/SelfAssessmentAdd.cshtml
[TD-3220](https://hee-tis.atlassian.net/browse/TD-3220)
Fixes issues with submitting the Add self assessment form by changing the post action method name.
-----
I have:
[TD-3220]: https://hee-tis.atlassian.net/browse/TD-3220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3220 Fixes add self assessment by changing method name to make unique

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAsssessmentReportDataService.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/Export/SelfAssessmentReportData.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentReportService.cs
[TD-3619](https://hee-tis.atlassian.net/browse/TD-3619)
Adds "OtherCentres" column to the Centres -> Reports -> Self assessment reports exported to Excel. This uses the existing SQL function to return a comma separated list of other centres.
-----
I have:
[TD-3619]: https://hee-tis.atlassian.net/browse/TD-3619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3619 Includes other centres in centres self assessment report

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/DCSAReportDataService.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentReportService.cs
[TD-1988](https://hee-tis.atlassian.net/browse/TD-1988)
Updates queries returning centre DSAT report data to:
- include centre learners who enrolled on DSAT at a different centre 
- count learning accessed and completed through the new Learning Hub signposting mechanism (as well as the old Filtered one)
Also removes redundant services that don't take centreId parameter and return all data.
-----
I have:
[TD-1988]: https://hee-tis.atlassian.net/browse/TD-1988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-1988 Updates DSAT report to show learners at centre who enrolled on DSAT at another centre

DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Views/Supervisor/MyStaffList.cshtml
https://hee-tis.atlassian.net/browse/TD-3645
Removed 'Please change your search criteria and try again' message for consistency with other searches.
Made non-JavaScript search count equal to JavaScript search.
-----
I have:
=> TD-3645-Removed message, made non-JavaScript search count equal to JavaScript search.

DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/CentresControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Centres/CourseAddViewModel.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/CourseAdd.cshtml
[TD-3217](https://hee-tis.atlassian.net/browse/TD-3217)
Fixes the fails identified by test analysts:
- Validates form inputs in the add course flow
- Fixes page routing
- Fixes mobile alignment of select checkboxes
-----
I have:
[TD-3217]: https://hee-tis.atlassian.net/browse/TD-3217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3217 Fixes super admin centre course add test fails - validation, routing and mobile alignment

DigitalLearningSolutions.Web.AutomatedUiTests/DigitalLearningSolutions.Web.AutomatedUiTests.csproj
[TD-3747](https://hee-tis.atlassian.net/browse/TD-3747)
Updates ChromeDriver version to match NHS E installed version so that tests run. Also commits whitespace changes from Vue component default.cshtml files to suppress Git changes.
-----
I have:
[TD-3747]: https://hee-tis.atlassian.net/browse/TD-3747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3747 Update chrome driver for accessibility tests

DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Centres/AddCentreSuperAdminViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Configuration/EditCentreManagerDetailsViewModel.cs
[TD-3321](https://hee-tis.atlassian.net/browse/TD-3321)
Correcting regex for phone numbers to ignore spaces at the start and end of phone numbers.
-----
I have:
[TD-3321]: https://hee-tis.atlassian.net/browse/TD-3321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3321 Correcting regex for phone numbers

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs, DigitalLearningSolutions.Web/Views/LearningPortal/Current/CompetencySelfAssessmentCertificate.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/Current/DownloadCompetencySelfAssessmentCertificate.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_OverviewActionButtons.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_SelfAssessmentCard.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml
1. Latest Signoff by supervisor and date issue fixed.
2. Fixed 'Certificate generated on' date issue on first page
3. Show/hide certificate button activity based on sign off status.
-----
I have:
=> TD-149-Show/hide certificate button

DigitalLearningSolutions.Data/DataServices/SupervisorService.cs
[TD-3652](https://hee-tis.atlassian.net/browse/TD-3652)
Inactive account was showing as Not Registered when added as a staff member on the supervisor portal. It was because there is a condition on the view - @if (Model.SupervisorDelegateDetail.DelegateUserID == null) then show 'Not registered' tag. The details of Model.SupervisorDelegateDetail are populated from SupervisorDelegates table. 
While adding staff, we had a condition that checked only for active users and hence we were not populating SupervisorDelegates table with correct values. The solution is removing this condition.
-----
I have:
=> TD-3652 fixed inactive account showing as not registered

DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/_CentreCourseCard.cshtml
[TD-3784](https://hee-tis.atlassian.net/browse/TD-3784)
Changing the conditions to show/hide the 'manage course' button. 
If a course is active and not archived, we show the 'manage course' and 'launch course' buttons. 
If The course is inactive and not archived, we show only the 'manage course' button
Active courses - 
Inactive/Archived courses (Inactive courses have manage course button, but archived courses does not) -
-----
I have:
=> TD-3784 Making manage course button available for inactive courses

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs, DigitalLearningSolutions.Data/DataServices/SupervisorService.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/Current.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Helpers/CertificateHelper.cs, DigitalLearningSolutions.Web/Views/LearningPortal/Current/CompetencySelfAssessmentCertificate.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/Current/DownloadCompetencySelfAssessmentCertificate.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_OverviewActionButtons.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml
1. View code moved to controller. Helper method created to check if a learner/supervisor can view certificate button.
2. Modified SQL query to return correct supervisor centre name.
3. Brower back button issue resolved on the certificate view.
4. Back link issue resolved on the certificate view.
N/A
-----
I have:
=> TD-149-Self assessment certificate - supervisor centre name issue fix

DigitalLearningSolutions.Data/DataServices/CourseContentService.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/IndexTests.cs, DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs
[TD-3838](https://hee-tis.atlassian.net/browse/TD-3838)
This simple change uses a coalesce to ensure that the get progress ID query returns a 0 value rather than throwing an exception if progress does not exist. This fixes the problem in dev.
-----
I have:
[TD-3838]: https://hee-tis.atlassian.net/browse/TD-3838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3838 Reworks query to use coalesce to avoid throwing exception

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs, DigitalLearningSolutions.Web/Views/LearningPortal/Current/CompetencySelfAssessmentCertificate.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/Current/DownloadCompetencySelfAssessmentCertificate.cshtml
https://hee-tis.atlassian.net/browse/TD-3876
SQL query modified to return valid assessment question responses count in the certificate.
-----
I have:
=> TD-3876-SQL query modified to return valid assessment question responses count in the certificate

DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs
https://hee-tis.atlassian.net/browse/TD-3822
Redirected page with 410 status code when selfAssessmentSummary found empty.
N/A
-----
I have:
=> TD-3822-Browser back button issue after supervisor signed off

DigitalLearningSolutions.Data/DataServices/CourseContentService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/CompetencySelfAssessmentCertificate.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/IndexTests.cs, DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/Current.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs, DigitalLearningSolutions.Web/ViewModels/LearningPortal/Current/CompetencySelfAssessmentCertificateViewModel.cs, DigitalLearningSolutions.Web/Views/LearningPortal/Current/CompetencySelfAssessmentCertificate.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/Current/DownloadCompetencySelfAssessmentCertificate.cshtml
[Release-2023.26-Hotfix](https://hee-tis.atlassian.net/projects/TD/versions/12686/tab/release-report-all-issues)
Merging release branch to master for production deployment.
=> Release DLS 2023.26-Hotfix merge to production

DigitalLearningSolutions.Web/Styles/learningPortal/selfassessmentcertificate.scss, DigitalLearningSolutions.Web/Views/LearningPortal/Current/CompetencySelfAssessmentCertificate.cshtml
https://hee-tis.atlassian.net/browse/TD-3888
CSS, cshtml modified to fix mobile view issue.
-----
I have:
=> TD-3888- Self assessment certificate mobile view issue

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs
https://hee-tis.atlassian.net/browse/TD-3893
SQL query modified to fetch active supervisors.
N/A
-----
I have:
=> TD-3893- Showing active supervisors for sign off

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/AssessmentQuestion.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/Competency.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/ReviewConfirmationRequests.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/VerificationSummary.cshtml
[TD-3530](https://hee-tis.atlassian.net/browse/TD-3530)
Manage confirmation requests screen - adding a select statement to fetch the centre name and binding it to the newly added property in the view model and using that property in view to populate the centre name.
Request proficiency confirmation screen - using the existing value of the centre name in the supervisor variable and storing it in the selfAssessment variable so that it can be used to populate the model and hence used in the view.
Manage confirmation requests screen -
Request proficiency confirmation screen -
-----
I have:
[TD-3530]: https://hee-tis.atlassian.net/browse/TD-3530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Zh …
=> TD-3530 Adding centre name to supervisor name

DigitalLearningSolutions.Data/DataServices/GroupsDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/DelegateUserCardDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/AllDelegatesControllerTests.cs, DigitalLearningSolutions.Web.Tests/Services/DashboardInformationServiceTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/TrackingSystem/Delegates/AllDelegates/AllDelegatesViewModelFilterOptionsTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/AllDelegatesController.cs, DigitalLearningSolutions.Web/Helpers/FilterHelper.cs, DigitalLearningSolutions.Web/Services/DashboardInformationService.cs, DigitalLearningSolutions.Web/Services/GroupsService.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/AllDelegates/AllDelegateItemsViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/AllDelegates/AllDelegatesViewModelFilterOptions.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/Shared/DelegatesViewModelFilters.cs
https://hee-tis.atlassian.net/browse/TD-3885
All delegates view - groups filter added.
- New groups filter created
- Added groups filter within prompts filter
- Code modified to take care of applied filters when user changes centre.
-----
I have:
=> TD-3885- All delegates view - groups filter added

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs
[TD-3892](https://hee-tis.atlassian.net/browse/TD-3892)
If none of the proficiencies were selected, a validation error would show up on the screen. For populating the model for the validation screen, the method was using wrong delegateID. This has been corrected now.
-----
I have:
[TD-3892]: https://hee-tis.atlassian.net/browse/TD-3892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3892 PopulatingProficienciesOnErrorValidation

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/EnrolController.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/Enrol/EnrolSupervisorViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Enrol/EnrolDelegateSupervisor.cshtml
[TD-3173](https://hee-tis.atlassian.net/browse/TD-3173)
1. Putting validation on supervisor role selection when supervisor is not selected. This is done in the review model
2. Marking the SupervisorList as nullable since it was making the model state invalid.
-----
I have:
[TD-3173]: https://hee-tis.atlassian.net/browse/TD-3173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3173 Putting validation on supervisor role selection

DigitalLearningSolutions.Data.Migrations/202404120935_InactivateDelegateAccountsWithNoEmail.cs, DigitalLearningSolutions.Data/Models/DelegateUpload/DelegateTableRow.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/BulkUploadController.cs, DigitalLearningSolutions.Web/Services/DelegateDownloadFileService.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/BulkUpload/BulkUploadPreProcessViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/BulkUpload/BulkUploadResultsViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/BulkUpload/BulkUploadResults.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/BulkUpload/ProcessBulkDelegates.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/BulkUpload/UploadSummary.cshtml
Changes made in response to test analyst feedback, including:
- Clears the "TRUE" value for the "Active" column in the first data row when downloading a blank template by allowing Active bool in anonymous class to be nullable.
- Corrects the controller and action for the Email link on the upload results page (fixing link)
- Adds a migration to inactivate all delegate accounts with no email address
- Fixes validation of upload to allow blank email only for updated delegates if they are inactive
- Fixes count of rows to process in summary page
- Make results page work as final step in multi-step slow by showing step number 
-----
I have:
- …
=> TD-3835 Fixes testing fails for bulk upload improvements

DigitalLearningSolutions.Web/Controllers/LearningPortalController/Current.cs, DigitalLearningSolutions.Web/Models/Enums/DelegateAccountCard.cs, DigitalLearningSolutions.Web/ViewModels/LearningPortal/Current/CompetencySelfAssessmentCertificateViewModel.cs, DigitalLearningSolutions.Web/Views/LearningPortal/Current/CompetencySelfAssessmentCertificate.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/Current/DownloadCompetencySelfAssessmentCertificate.cshtml
[TD-4048](https://hee-tis.atlassian.net/browse/TD-4048)
The problem loading the Delegates page in Super Admin was caused by another enumerator class with a missing access modifier. This change adds the "public" access modifier to the class. I have also checked that no other enums have a missing access modifier in Web.Models.Enums.
-----
I have:
[TD-4048]: https://hee-tis.atlassian.net/browse/TD-4048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4048 Fix for super admin delegates issue

DigitalLearningSolutions.Web/Styles/learningPortal/selfassessmentcertificate.scss
https://hee-tis.atlassian.net/browse/TD-3888
I handle the mobile view for the self assessments  certificate on the css
-----
I have:
=> TD-3888 mobile view issue on the certificate screen for all the self assessments issue fix

DigitalLearningSolutions.Data.Migrations/202404231652_RemoveDuplicateDelegatesFromDelegateGroups.cs
[TD-3080](https://hee-tis.atlassian.net/browse/TD-3080)
Migration to remove duplicate records from the GroupDelegates table to support work in preventing duplicates.
-----
I have:
[TD-3080]: https://hee-tis.atlassian.net/browse/TD-3080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3080 Remove duplicates from group delegates table

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs
[TD-4093](https://hee-tis.atlassian.net/browse/TD-4093)
Fixes the query joins in the SQL returning data for self assessment certificates to ensure that data is returned even if some non-essential related data does not exist.
-----
I have:
[TD-4093]: https://hee-tis.atlassian.net/browse/TD-4093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4093 Fix for 404 certificate error

DigitalLearningSolutions.Web.Tests/Services/LoginServiceTests.cs, DigitalLearningSolutions.Web/Controllers/LogoutController.cs, DigitalLearningSolutions.Web/Services/LoginService.cs, DigitalLearningSolutions.Web/Startup.cs
[TD-2454](https://hee-tis.atlassian.net/browse/TD-2454)
Fixed the issue where LogIntoCentreAsync was called. Fixed issue when user logs out.
-----
I have:
[TD-2454]: https://hee-tis.atlassian.net/browse/TD-2454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixed issue where LogIntoCentreAsync was called. Fixed Logout issue

DigitalLearningSolutions.Data/Models/DelegateUpload/BulkUploadResult.cs, DigitalLearningSolutions.Data/Models/DelegateUpload/DelegateTableRow.cs, DigitalLearningSolutions.Web.Tests/Services/DelegateUploadFileServiceTests.cs, DigitalLearningSolutions.Web/Controllers/Register/RegisterDelegateByCentreController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/BulkUploadController.cs, DigitalLearningSolutions.Web/Models/BulkUploadData.cs, DigitalLearningSolutions.Web/Services/DelegateUploadFileService.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/BulkUpload/AddToGroupViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/BulkUpload/AddWhoToGroupViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/BulkUpload/BulkUploadPreProcessViewModel.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/BulkUpload/BulkUploadResultsViewModel.cs, DigitalLearningSolutions.Web/Views/RegisterDelegateByCentre/AddToGroup.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/BulkUpload/AddToGroup.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/BulkUpload/AddWhoToGroup.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/BulkUpload/BulkUploadResults.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/BulkUpload/UploadSummary.cshtml
Separates to register and update counts in the model into inactive and active counts. Uses these new counts to indicate how many delegates will be grouped and display appropriate warnings. Change service to only group active delegates. Changes service to group delegates included in the upload even if they are skipped with no updates.
-----
I have:
[TD-3835]: https://hee-tis.atlassian.net/browse/TD-3835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3835 Fixes to grouping - only group active delegates and group all delegates in upload

DigitalLearningSolutions.Web/Views/RegisterDelegateByCentre/AddToGroup.cshtml
[TD-3834](https://hee-tis.atlassian.net/browse/TD-3834)
Fixes the cancel link on the add to group screen to make consistent with other steps in the flow.
-----
I have:
[TD-3834]: https://hee-tis.atlassian.net/browse/TD-3834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3834 Fix cancel link on add to group screen

DigitalLearningSolutions.Data/Extensions/ConfigurationExtensions.cs, DigitalLearningSolutions.Web.Tests/Controllers/UserFeedbackControllerTest.cs, DigitalLearningSolutions.Web/Controllers/UserFeedbackController.cs, DigitalLearningSolutions.Web/ViewModels/UserFeedback/UserFeedbackViewModel.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_Layout.cshtml, DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml, DigitalLearningSolutions.Web/Views/Shared/_UserFeedbackBarPartial.cshtml, DigitalLearningSolutions.Web/Views/UserFeedback/GuestFeedbackComplete.cshtml, DigitalLearningSolutions.Web/Views/UserFeedback/UserFeedbackComplete.cshtml, DigitalLearningSolutions.Web/appsettings.json
https://hee-tis.atlassian.net/browse/TD-3956
I added the new user research URL to the  appsettings config
I replace the old user research URL with the new URL
-----
I have:
=> TD-3956 Replace user research link for participant recruitment on DLS

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/BulkUploadController.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/BulkUpload/AddToGroup.cshtml
The 500 error that we saw while uploading a file was because of malformed URIs when we entered an email like 'sample@'. A well-formed URI does not cause issues. The code was breaking at the point where the code was trying to open a stream to read the contents of the uploaded Excel file and construct a new XLWorkbook object. So I put it inside a try-catch block to handle it.
Issue 2 - Showing an error message when malformed hyperlinks are found.
Issue 3 - Typo corrected.
-----
I have:
[TD-3835]: https://hee-tis.atlassian.net/browse/TD-3835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3835 Handling hyperlinks in excel and fixing a typo

DigitalLearningSolutions.Web/Views/UserFeedback/GuestFeedbackComplete.cshtml
https://hee-tis.atlassian.net/browse/TD-2272
I change the guest feedback page content  to user feedback page content
-----
I have:
=> TD-2272 DLS feedback bar, view in logged out is inconsistent with the view in logged in

DigitalLearningSolutions.Web.Tests/Services/DelegateUploadFileServiceTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/BulkUploadController.cs, DigitalLearningSolutions.Web/Models/BulkUploadData.cs, DigitalLearningSolutions.Web/Services/DelegateUploadFileService.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/BulkUpload/AddWhoToGroupViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/BulkUpload/AddWhoToGroup.cshtml
During testing it was identified that it was not always clear whether delegates skipped because they were in the uploaded sheet but had no changes would be added to the group selected during bulk upload. This change introduces a new option to allow the user to choose whether they should be included and directs all users with sheets containing updated (or possibly updated delegates) through that flow.
There is conditional logic in the page to adjust the options presented depending on whether delegates are also being registered.
With registered delegates and updated delegates in sheet:
With only updated (or existing unchanged) delegates in sheet:
-----
I have:
- …
=> TD-3835 Introduces new add who to group option and logic to bulk upload flow

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/EnrolController.cs
[TD-3173](https://hee-tis.atlassian.net/browse/TD-3173)
If no supervisor is selected, a role will not be set. 
**
**
-----
I have:
[TD-3173]: https://hee-tis.atlassian.net/browse/TD-3173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3173 Handling supervisor role when supervisor is not selected

DigitalLearningSolutions.Web/Scripts/learningMenu/diagnosticContentViewer.ts, DigitalLearningSolutions.Web/Scripts/spec/learningMenu/diagnosticContentViewer.spec.ts
[TD-4130](https://hee-tis.atlassian.net/browse/TD-4130)
Issue 2 in the above ticket related to diagnostic assessments failing to close. Investigation revealed that this was only the case when the course was set to not allow diagnostic objective selection (Course Setup option). We have some code in the diagnosticContentPlayer.ts that carries out URL matching when content is closed to work out where to take the learner after closing. This URL matching did not expect a trailing ? on the URL when no parameters were present. This change tweaks the code to anticipate the trailing ? which exists in the URL in this scenario.
-----
I have:
[TD-4130]: …
=> TD-4130 Fix url matching in close window TypeScript code

DigitalLearningSolutions.Data/DataServices/UserDataService/AdminUserDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/Register/RegisterDelegateByCentreControllerTests.cs, DigitalLearningSolutions.Web/Helpers/RegistrationEmailValidator.cs, DigitalLearningSolutions.Web/Services/UserService.cs
https://hee-tis.atlassian.net/browse/TD-3144
Correcting the Centre email showing as primary email in the super admin delegate page
-----
I have:
=> TD-3144 same email address is showing as Primary email for 2 users in super admin delegate page

DigitalLearningSolutions.Data/Models/DelegateUpload/DelegateTableRow.cs
Fixes a problem where some records were being marked as updated even when they were unchanged in the uploaded spreadsheet. On investigation, this was revealed to be because some string fields included trailing spaces (particularly in the custom field responses). This change trims trailing spaces from the input string and the existing value before comparing to avoid falsely marking records for update.
-----
I have:
[TD-3835]: https://hee-tis.atlassian.net/browse/TD-3835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3835 Fixes issue with delegate records being falsely marked for update

DigitalLearningSolutions.Data/DataServices/UserDataService/DelegateUserCardDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/AllDelegatesControllerTests.cs, DigitalLearningSolutions.Web.Tests/Services/DashboardInformationServiceTests.cs, DigitalLearningSolutions.Web.Tests/Services/DelegateDownloadFileServiceTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/AllDelegatesController.cs, DigitalLearningSolutions.Web/Services/DashboardInformationService.cs, DigitalLearningSolutions.Web/Services/DelegateDownloadFileService.cs
[TD-3885](https://hee-tis.atlassian.net/browse/TD-3885)
Changed the type of groupId to a nullable integer. In the query formation for getting delegate count for the dashboard and delegates for all delegates page, changed condition which deals with filtering based on groupId.
-----
I have:
[TD-3885]: https://hee-tis.atlassian.net/browse/TD-3885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3885 Correcting groups filter in TS dashboard and all delegates page

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/AllDelegatesController.cs
[TD-3885](https://hee-tis.atlassian.net/browse/TD-3885)
We have placed a check for a scenario where we have a filter with groupID that is now deleted. We already had groups that were fetched in the code above. Comparing the currently applied filter to check whether that group is still existent. If NO (that means the group is deleted), we are making groupId null so that we get the correct delegates and delegates count. We are also flushing out the value of the existing filter if it is the case.
-----
I have:
[TD-3885]: https://hee-tis.atlassian.net/browse/TD-3885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …
=> TD-3885 Handling Deleted Group Filter Issue

DigitalLearningSolutions.Web/Helpers/FeatureFlags.cs, DigitalLearningSolutions.Web/Views/Home/Welcome.cshtml, DigitalLearningSolutions.Web/appSettings.UAT.json, DigitalLearningSolutions.Web/appsettings.Development.json, DigitalLearningSolutions.Web/appsettings.Production.json, DigitalLearningSolutions.Web/appsettings.SIT.json, DigitalLearningSolutions.Web/appsettings.Test.json, DigitalLearningSolutions.Web/appsettings.UarTest.json, DigitalLearningSolutions.Web/appsettings.json
[_DLSV2-4164_](https://hee-tis.atlassian.net/browse/TD-4164)
'LoginWithLearningHub' feature flag added to hide 'Log in with Learning Hub' button on Home (log in) page.
Links issues (Products, Learning content) on the log in page has been resolved.
-----
I have:
=> TD-4164-Feature flag the Login with Learning Hub button

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/AllDelegatesController.cs
[TD-3885](https://hee-tis.atlassian.net/browse/TD-3885)
Changed the if condition - The error we got was because we had an AND condition that prevented the code from stepping inside the if block.
Now it should check for two different scenarios - 
[ { (If centre is changed) OR (If UAT-Live is toggled) } AND (If existingFilterString has value) ]
-----
I have:
[TD-3885]: https://hee-tis.atlassian.net/browse/TD-3885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3885 Fixing issue with prompts filter

DigitalLearningSolutions.Web/Controllers/Certificate/CertificateController.cs
[_DLSV2-3890_](https://hee-tis.atlassian.net/browse/TD-3890)
DataServices reference of centreDataService has been removed from the controller code.
-----
I have:
=> TD-3890- Certificate controller - refactor

DigitalLearningSolutions.Web.Tests/Controllers/FindYourCentreControllerTests.cs, DigitalLearningSolutions.Web/Controllers/FindYourCentreController.cs, DigitalLearningSolutions.Web/Services/RegionService.cs, DigitalLearningSolutions.Web/Startup.cs
[_DLSV2-3894](https://hee-tis.atlassian.net/browse/TD-3894)
Removed the DataService reference from the controller.
RegionService class created in web project.
-----
I have:
=> TD-3894 -  FindYourCentreController - refactor

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/AllDelegatesControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/AllDelegatesController.cs
[TD-3885](https://hee-tis.atlassian.net/browse/TD-3885)
**Issue 1.** Issue still can be seen when prompt filter applied in one centre affects the another centre
This has been corrected by correcting the if statement. Now it correctly checks that if the centreId is changed, the prompts filters are cleared out.
**Issue 2.** Applied Delegate group filter in UAT and accessing DLS Live Delegate page results in 500 error
For this, we are using a different name for the cookie variable for UAT and for Live. We are fetching the full current URL from HttpContext.Request.GetDisplayUrl() and checking if it contains the term 'uat' in it. If it contains, we change the cookie variable name.
We will be able to test if this is working or not only when it is deployed to live. @kevwhitt-hee are we willing …
=> TD 3885 correcting issue related to prompt filter and UAT live filter

DigitalLearningSolutions.Web.Tests/Controllers/Register/RegisterAtNewCentreControllerTests.cs, DigitalLearningSolutions.Web.Tests/Helpers/RegistrationEmailValidatorTests.cs, DigitalLearningSolutions.Web/Controllers/Register/RegisterAtNewCentreController.cs, DigitalLearningSolutions.Web/Controllers/Register/RegisterInternalAdminController.cs, DigitalLearningSolutions.Web/Helpers/RegistrationEmailValidator.cs, DigitalLearningSolutions.Web/Services/CentresService.cs
[_DLSV2-3904_](https://hee-tis.atlassian.net/browse/TD-3904)
DataService reference removed from the controller.
Note: RegisterInternalAdminController, RegistrationEmailValidator and RegistrationEmailValidatorTests data service references to be handled in their respective tickets.
-----
I have:
=> TD-3904-RegisterAtNewCentreController - refactor

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/ViewDelegateControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ViewDelegateController.cs, DigitalLearningSolutions.Web/Services/EmailVerificationService.cs, DigitalLearningSolutions.Web/Services/UserService.cs
[TD-3942](https://hee-tis.atlassian.net/browse/TD-3942)
1. Removed reference of the following DataServices from **ViewDelegateControllerTests.cs** and **ViewDelegateController.cs**
using DigitalLearningSolutions.Data.DataServices;
using DigitalLearningSolutions.Data.DataServices.UserDataService;
2. Introduced missing methods in **EmailVerificationService.cs** and **UserService.cs**
-----
I have:
[TD-3942]: https://hee-tis.atlassian.net/browse/TD-3942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD 3942 ViewDelegate Controller Refactor

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/EnrolControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/EnrolController.cs
[_TD-3939_](https://hee-tis.atlassian.net/browse/TD-3939)
DataService reference removed from the controller.
No other relative change is required in the controller code as it is solved by the implementation of ISupervisorService interface in the other ticket.
-----
I have:
=> TD-3939-EnrolController - refactor

DigitalLearningSolutions.Data/DataServices/ProgressDataService.cs, DigitalLearningSolutions.Data/Utilities/ClockUtility.cs, DigitalLearningSolutions.Web.Tests/Services/GroupServiceTests/GroupsServiceEnrolDelegateTests.cs, DigitalLearningSolutions.Web.Tests/Services/GroupServiceTests/GroupsServiceTests.cs, DigitalLearningSolutions.Web.Tests/Services/ProgressServiceTests.cs, DigitalLearningSolutions.Web/Services/EnrolService.cs, DigitalLearningSolutions.Web/Services/GroupsService.cs, DigitalLearningSolutions.Web/Services/ProgressService.cs
https://hee-tis.atlassian.net/browse/TD-3671
I alter the query that update the delegate information to update  FirstSubmittedTime whenever the admin enrol course for delegate
-----
I have:
=> TD-3671 few courses which does not allow self enrolment

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/EmailDelegatesControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/EmailDelegatesController.cs
[_TD-3938_](https://hee-tis.atlassian.net/browse/TD-3938)
DataService reference removed from the controller.
-----
I have:
=> TD-3938-EmailDelegatesController - refactor

DigitalLearningSolutions.Data/DataServices/ProgressDataService.cs, DigitalLearningSolutions.Web.Tests/Services/GroupServiceTests/GroupsServiceEnrolDelegateTests.cs, DigitalLearningSolutions.Web.Tests/Services/GroupServiceTests/GroupsServiceTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/TrackingSystem/Delegates/AllDelegates/DelegateCourseInfoViewModelTests.cs, DigitalLearningSolutions.Web.Tests/ViewModels/TrackingSystem/Delegates/DelegateProgress/DelegateProgressViewModelTests.cs, DigitalLearningSolutions.Web/Services/EnrolService.cs, DigitalLearningSolutions.Web/Services/GroupsService.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/Shared/DelegateCourseInfoViewModel.cs
https://hee-tis.atlassian.net/browse/TD-4218
Ensuring the enrol date is local time instead of using 
-----
I have:
=> TD-4218 'Last access' date and time shouldn't show on the learner record when admin registers the delegate from the 'Tracking system'

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ActivityDelegatesController.cs
[_TD-3929_](https://hee-tis.atlassian.net/browse/TD-3929)
DataService reference removed from the controller. This was the only change.
-----
I have:
=> TD-3929-ActivityDelegatesController - refactor

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Centre/SystemNotificationControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/SystemNotificationsController.cs, DigitalLearningSolutions.Web/Services/SystemNotificationsService.cs, DigitalLearningSolutions.Web/Startup.cs
[_TD-3925_](https://hee-tis.atlassian.net/browse/TD-3925)
DataService reference removed from the controller.  Service class 'SystemNotificationsService' added
Note: Dev testing has been done with dummy data by manipulating DB table data.
-----
I have:
=> TD-3925-SystemNotificationsController - refactor 

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Centre/Administrator/AdministratorControllerTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Administrator/AdministratorController.cs, DigitalLearningSolutions.Web/Services/UserService.cs
[_TD-3919_](https://hee-tis.atlassian.net/browse/TD-3919)
DataService reference removed from the controller. GetAdminsByCentreId(+), DeactivateAdmin(+) added to UserService
-----
I have:
=> TD-3919-AdministratorController - refactor

DigitalLearningSolutions.Web/Controllers/SuperAdmin/Delegates/DelegatesController.cs, DigitalLearningSolutions.Web/Services/UserService.cs
[_TD-3915_](https://hee-tis.atlassian.net/browse/TD-3915)
DataService reference removed from the controller.  
New methods added to UserService :
GetAllDelegates(+)
DeleteUserCentreDetail(+)
ApproveDelegateUsers(+)
-----
I have:
=> TD-3915-DelegatesController - refactor

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/GroupDelegatesController.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/GroupDelegates/SelectDelegateAllItemsViewModel.cs
[TD-4254](https://hee-tis.atlassian.net/browse/TD-4254)
The groups filter values where missing in the 'AllDelegateItemsViewModel'. From the SelectDelegateAllItems in GroupDelegatesController, we are Getting Active Groups and sending it to SelectDelegateAllItemsViewModel which in turn sets the groups property of the base class.
-----
I have:
[TD-4254]: https://hee-tis.atlassian.net/browse/TD-4254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4254 Groups Filter Added To View Model

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/CurrentSelfAssessment.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/EnrolController.cs, DigitalLearningSolutions.Web/Services/EnrolService.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateSelfAssessmentProgressDetails.cshtml
https://hee-tis.atlassian.net/browse/TD-4269
I resolved some unboxing a possible null value warning in some method CourseDataService class
Making the Last access date null when the admin enrol self assessment
Adding right enrolment method 
ensuring the enrol by show the admin name 
-----
I have:
=> TD-4269 Issue with the 'Enrolment method' and 'Last access date' when admin enrolled the self assessment on Tracking system

DigitalLearningSolutions.Web/Controllers/UserFeedbackController.cs, DigitalLearningSolutions.Web/Helpers/ContentUrlHelper.cs
https://hee-tis.atlassian.net/browse/TD-4134
I Added a method that check for the 410 Url and I replace it with the welcome Url to prevent 
-----
I have:
=> Develop/fixes/td 4134 issue adding digital learning solutions page no longer available text to the 'go back 'links on give page feedback screens

DigitalLearningSolutions.Web/ServiceFilter/VerifyAdminUserCanAccessGroup.cs
https://hee-tis.atlassian.net/browse/TD-4207
In the service filter I added a check to see if the group is not in the database then should return error 410
-----
I have:
=> TD-4207 Clicking browser back button after deleting the 'Delegate Group' showing console '404' error instead of '410' error

DigitalLearningSolutions.Web/Helpers/FilterableTagHelper.cs
[TD-4244](https://hee-tis.atlassian.net/browse/TD-4244)
Removed the condition which made the "hidden in learning portal" tag hidden for inactive courses.
-----
I have:
[TD-4244]: https://hee-tis.atlassian.net/browse/TD-4244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4244 Added hidden in learning portal added for inactive courses as well

DigitalLearningSolutions.Web/Controllers/UserFeedbackController.cs, DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml
https://hee-tis.atlassian.net/browse/TD-4137
I hide the ‘Switch application’ link use the user is the logged in user feedback page
-----
I have:
=> TD-4137  switch application navigation link should be removed from give page feedback screens for logged in user

DigitalLearningSolutions.Data/DataServices/SupervisorDataService.cs
[_TD-3939_](https://hee-tis.atlassian.net/browse/TD-3939)
Fixed SQL query column alias space issue.
-----
I have:
=> TD-3939- Enrol course and self assessment issue fixed

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/ManageSupervisors.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/ReviewConfirmationRequests.cshtml
[_TD-4320_](https://hee-tis.atlassian.net/browse/TD-4320)
Supervisor email added to manage supervisor list. CSS classes used to manage mobile view.
-----
I have:
=> TD-4320-Supervisor emails should be shown on 'Manage Supervisors' list/ 'Quick add'

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs
https://hee-tis.atlassian.net/browse/TD-4334
I added the CompleteByDate to the update part of the query that update the CandidateAssessments table 
-----
I have:
=> TD-4334 Issue with 'Complete by' date not showing on self assessment cards 

DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/Shared/DelegateSelfAssessmentInfoViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateSelfAssessmentProgressDetails.cshtml
[TD-4269](https://hee-tis.atlassian.net/browse/TD-4269)
Enrolment method changed to Enrolled by Admin/Supervisor everywhere to avoid confusion
-----
I have:
[TD-4269]: https://hee-tis.atlassian.net/browse/TD-4269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4269 Enrolment method changed to Enrolled by Admin/Supervisor everywhere to avoid confusion

DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs
[_TD-4339_](https://hee-tis.atlassian.net/browse/TD-4339)
null/empty check added for centre name.
-----
I have:
=> TD-4339- Issue showing console '500' error when 'Edit details' on 'Manage centre' screen

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs
https://hee-tis.atlassian.net/browse/TD-4206
I edited the existing query to  count all course which include active, inactive and archived course on Centre dashboard page
I ensure the course count is the same with the count of the Centre course setup page
Bedfordshire Hospitals NHS Foundation Trust course count Centre dashboard
Bedfordshire Hospitals NHS Foundation Trust course count Centre course setup 
##NHS England Demo Centre## count  course Centre dashboard
##NHS England Demo Centre## count courses  on Centre course setup 
-----
I have:
=> TD-4206 Mismatch of count of courses seeing on 'Centre Dashboard' when compared to the 'Centre course set up' screen

DigitalLearningSolutions.Web/Controllers/SuperAdmin/Administrators/AdminAccountsController.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Delegates/DelegatesController.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Users/UsersController.cs
https://hee-tis.atlassian.net/browse/TD-4376
I trimmed the search parameter to remove the whitespace on Administrator, user account and delegate page
-----
I have:
=> TD-4376 Issue with not trimming of the  trailing/leading end spaces on Super Admin search screens

DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/ManageCentre.cshtml
[TD-4354](https://hee-tis.atlassian.net/browse/TD-4354)
Converting Bytes To GB and MB on manage centre screens
-----
I have:
[TD-4354]: https://hee-tis.atlassian.net/browse/TD-4354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4354 Converting Bytes To GB and MB on manage centre screens

DigitalLearningSolutions.Web/Views/UserFeedback/GuestFeedbackStart.cshtml, DigitalLearningSolutions.Web/Views/UserFeedback/UserFeedbackComplete.cshtml, DigitalLearningSolutions.Web/Views/UserFeedback/UserFeedbackTaskAchieved.cshtml, DigitalLearningSolutions.Web/Views/UserFeedback/UserFeedbackTaskAttempted.cshtml, DigitalLearningSolutions.Web/Views/UserFeedback/UserFeedbackTaskDifficulty.cshtml
[TD-4364](https://hee-tis.atlassian.net/browse/TD-4364)
Backlinks For Mobile View Added for user feedback pages.
Mobile view for feedback page that shows the back link is now added-
Wave analysis of the web view that shows nothing is broken-
-----
I have:
[TD-4364]: https://hee-tis.atlassian.net/browse/TD-4364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4364 Back links For Mobile View Added

DigitalLearningSolutions.Data/DataServices/CourseContentDataService.cs, DigitalLearningSolutions.Data/DataServices/ProgressDataService.cs, DigitalLearningSolutions.Web.Tests/Services/GroupServiceTests/GroupsServiceEnrolDelegateTests.cs, DigitalLearningSolutions.Web.Tests/Services/GroupServiceTests/GroupsServiceTests.cs, DigitalLearningSolutions.Web.Tests/Services/ProgressServiceTests.cs, DigitalLearningSolutions.Web/Services/EnrolService.cs, DigitalLearningSolutions.Web/Services/GroupsService.cs, DigitalLearningSolutions.Web/Services/ProgressService.cs
[_TD-4436_](https://hee-tis.atlassian.net/browse/TD-4436)
Removed FirstSubmittedTime from UpdateProgressSupervisorAndCompleteByDate(+)
Created new service method to edit progress supervisor.
Self enrolled
Course added to group
Delegate added to group
Supervisor added
-----
I have:
=> TD-4436 - Issue with the Enrolment date/time for the courses when enrolled by 'Group' 

DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/AddAdminField.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/AddBulkAdminFieldAnswers.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/EditAdminField.cshtml
[TD-4333](https://hee-tis.atlassian.net/browse/TD-4333)
1. AddAdminField - Made the response option mandatory
2. EditAdminField - Made the response option mandatory
3. AddBulkAdminFieldAnswers - Changed the hint text.
1. 
2. 
3. 
-----
I have:
[TD-4333]: https://hee-tis.atlassian.net/browse/TD-4333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4333 Corrections In Course Admin Fields Area

DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/ManageCentre.cshtml
[TD-4354](https://hee-tis.atlassian.net/browse/TD-4354)
Converting MB into GB for per delegate upload space when the value is 1024 MB
-----
I have:
[TD-4354]: https://hee-tis.atlassian.net/browse/TD-4354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4354 Converting MB into GB for per delegate upload space

DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/Shared/_TagRow.cshtml
https://hee-tis.atlassian.net/browse/TD-4322
I added a partial view tag to the supervisor shared folder
I added the optional tag to the ReviewSelfAssessment razor page
-----
I have:
=> td-4322 Introduce "Optional" tag in the learner competencies menu (Overview)

DigitalLearningSolutions.Data/Enums/SelfAssessmentCompetencyFilter.cs, DigitalLearningSolutions.Web/Helpers/SupervisorCompetencyFilterHelper.cs
https://hee-tis.atlassian.net/browse/TD-4324
I added the Optional to the enum 
I added the enum to the filter dropdown
I added the optional filter condition  to the where clause in the linq 
-----
I have:
=> TD-4324 Include "Optional" in the Filter options on the learner competencies menu

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/IndexTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningMenu/LearningMenuControllerTests.cs, DigitalLearningSolutions.Web/Controllers/LearningMenuController/LearningMenuController.cs, DigitalLearningSolutions.Web/Services/CourseService.cs, DigitalLearningSolutions.Web/Views/LearningPortal/Completed/CompletedCourseCard/_CompletedCourseCard.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/Current/CurrentCourseCard/_CurrentCourseCard.cshtml
https://hee-tis.atlassian.net/browse/TD-4238
I added another parameter progressId  to the index action method in the LearningMenuController 
using method overloading to add SetTempData method also include progressId to the parameter
using method overloading to add IsCourseCompleted method also include progressId to the parameter, which enable the query to able to select the right course from the progress table, this fixed the issue of the  back link not showing the right activities 
I also refactor the test method to include the changes on the method
-----
I have:
=> TD-4238 launching few courses from 'current activities' or from 'course setup' seeing back link as completed activities'

DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/RequestSignOffViewModel.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/RequestSignOff.cshtml
https://hee-tis.atlassian.net/browse/TD-4428
I added NumberOfSelfAssessedOptionalCompetencies count to the get and post action method in the SelfAssessmentOverviewViewModel.cs
I added NumberOfSelfAssessedOptionalCompetencies property in   the RequestSignOffViewModel.cs
I introduce a new checkbox that should be displayed only if the self assessment includes optional competencies
I added a label to the checkbox
I added a validation to the checkbox
-----
I have:
=> TD-4428 Additional optional competencies checkbox on the learner signoff request screen

DigitalLearningSolutions.Data.Migrations/202407221645_AlterGetCurrentCoursesForCandidate_V2.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.Designer.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.resx, DigitalLearningSolutions.Data.Migrations/Resources/TD-4243_Alter_GetCurrentCoursesForCandidate_V2_proc_down.sql, DigitalLearningSolutions.Data.Migrations/Resources/TD-4243_Alter_GetCurrentCoursesForCandidate_V2_proc_up.sql
https://hee-tis.atlassian.net/browse/TD-4243
I modify the store procedure by adding CentreApplications table to the store procedure, so that courses that is not publish to the centre will not reflect in the current activities, as it is in Course set up & Delegate activities
-----
I have:
=> TD-4243 Few 'add on' courses showing on 'Learning Portal' not showing on 'Course set up' & 'Delegate activities' screens

DigitalLearningSolutions.Data/DataServices/CentresDataService.cs
[TD-4535](https://hee-tis.atlassian.net/browse/TD-4535)
Changed the column for storing email in the centres table from pwEmail to the AutoRegisterManagerEmail.
Before changes -
After changes and updating the centre email - 
-----
I have:
[TD-4535]: https://hee-tis.atlassian.net/browse/TD-4535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4535 Changed the column for storing email in centres table

DigitalLearningSolutions.Web/Controllers/FrameworksController/Frameworks.cs
https://hee-tis.atlassian.net/browse/TD-4509
I added validation that checked the search parameter and trim the search parameter when it is not null
searching adding whitespace
after searching
-----
I have:
=> TD-4509 Issue with 'Search' showing various search results based on leading/trailing end spaces given on 'All Frameworks' & 'My Frameworks' screens

DigitalLearningSolutions.Data/DataServices/SupervisorDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/AdminUserDataService.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/DelegateProgress/EditSupervisorViewModel.cs
[_TD-4590_](https://hee-tis.atlassian.net/browse/TD-4590)
Sorted supervisor list, added email address and removed centre name
-----
I have:
=> TD-4590- Sorted supervisor list, added email address and removed centre name

DigitalLearningSolutions.Web/appSettings.UAT.json, DigitalLearningSolutions.Web/appsettings.Development.json, DigitalLearningSolutions.Web/appsettings.Production.json, DigitalLearningSolutions.Web/appsettings.SIT.json, DigitalLearningSolutions.Web/appsettings.Test.json, DigitalLearningSolutions.Web/appsettings.UarTest.json, DigitalLearningSolutions.Web/appsettings.json
https://hee-tis.atlassian.net/browse/TD-4595
Change ShowAppCardForLegacyTrackingSystem to false 
-----
I have:
=> TD-4595 Remove the legacy tracking system tile from the application selector

DigitalLearningSolutions.Web/Services/UserService.cs
https://hee-tis.atlassian.net/browse/TD-4502
I added  password set  and unclaimed delegate to the list delegate on the send welcome message
-----
I have:
=> TD-4502 Issue not listing the delegates on 'Send welcome message' screen for whose Password is set and unclaimed

DigitalLearningSolutions.Web/Controllers/Support/RequestSupportTicketController.cs
https://hee-tis.atlassian.net/browse/TD-4515
I check the tempdata to ensure it is not empty then return 401 error
-----
I have:
=> TD-4515 Issue showing console '500' error on the screen when clicked browser back button after submitting request support ticket

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ViewDelegateController.cs
[_TD-4436_](https://hee-tis.atlassian.net/browse/TD-4436)
Removed DateTime conversion for LastUpdated nullable date field.
N/A
-----
I have:
=> TD-4436- Removed DateTime conversion for LastUpdated nullable date field.

DigitalLearningSolutions.Web/DigitalLearningSolutions.Web.csproj, DigitalLearningSolutions.Web/Helpers/DateHelper.cs
[_TD-4436_](https://hee-tis.atlassian.net/browse/TD-4436)
Converted UTC date to local date time using NodaTime package
N/A
-----
I have:
=> TD-4436- Converted utc date to local date time using NodaTime package

DigitalLearningSolutions.Data/DataServices/SupervisorDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/AdminUserDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Web.Tests/Services/UserServiceTests.cs, DigitalLearningSolutions.Web/Services/UserService.cs
[_TD-4591_](https://hee-tis.atlassian.net/browse/TD-4591)
Modified SQL query to get centre email first if exists.
-----
I have:
=> TD-4591-Modified SQL query to get centre email first if exists.

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_OverviewActionButtons.cshtml
https://hee-tis.atlassian.net/browse/TD-4092
Changing the query parameter that gets certificate details on selfassessment controller
Resolve null reference warning on ActivitySummaryCompetencySelfAssesment method
Remove GetCompetencySelfAssessmentCertificate method because is no longer need 
-----
I have:
=> TD-4092 Resolving certificate showing error 403

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Data/DataServices/GroupsDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Data/DataServices/UserDataService/DelegateUserCardDataService.cs
[_TD-4645_](https://hee-tis.atlassian.net/browse/TD-4645)
Pattern for email validation updated in the SQL queries.
Affected area:
1. All delegates - Export delegates
2. Add delegate to group
3. Delegate activities and export
4. Activity delegates and export
5. Delegate groups and view delegates
6. Centre Dashboard - top course (count)
-----
I have:
=> TD-4645-Pattern for email validation updated in the SQL queries

DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/CompetencySelfAssessmentCertificate.cshtml
https://hee-tis.atlassian.net/browse/TD-4702
I change the route to the download certificate action method
I added validation to the action method to ensure that unauthorized persons can not access the action method
-----
I have:
=> TD-4702 Download self-assessment certificate link URL can be manipulated and able to download other user valid certificates

DigitalLearningSolutions.Web/Helpers/CommonValidationErrorMessages.cs
https://hee-tis.atlassian.net/browse/TD-4606
I edited the error message of the admin internal registration, I removed where centre email was mention 
-----
I have:
=> TD-4606 Issue with the error msg showing when registering the admin internally

DigitalLearningSolutions.Data.Migrations/202409110900_AddGroupOptionalCompetenciesToSelfAssessmentStructureTable.cs
[TD-4559](https://hee-tis.atlassian.net/browse/TD-4559)
Added Flag GroupOptionalCompetencies To SelfAssessmentStructure Table with datatype as Bit.
After running the migration on local - 
-----
I have:
[TD-4559]: https://hee-tis.atlassian.net/browse/TD-4559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4559 Added Flag GroupOptionalCompetencies To SelfAssessmentStructure Table

DigitalLearningSolutions.Data/Enums/SelfAssessmentCompetencyFilter.cs
https://hee-tis.atlassian.net/browse/TD-4324
I Changed the position of the optional filter, I ensured the optional filter appeared after confirmation rejected filter 
-----
I have:
=> TD-4324 “Optional“ filter should appear after confirmation rejected filter

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml
https://hee-tis.atlassian.net/browse/TD-4427
I sum the competency questions summary and competency verified summary
I put a check to competency questions summary and competency verified summary are the same before showing the message
[TD-4427.docx](https://github.com/user-attachments/files/16981967/TD-4427.docx)
-----
I have:
=> TD-4427 Check the minimum optional competencies have been added before enabling Request Sign-off

DigitalLearningSolutions.Web/Controllers/UserFeedbackController.cs, DigitalLearningSolutions.Web/Views/UserFeedback/UserFeedbackTaskAchieved.cshtml, DigitalLearningSolutions.Web/Views/UserFeedback/UserFeedbackTaskAttempted.cshtml, DigitalLearningSolutions.Web/Views/UserFeedback/UserFeedbackTaskDifficulty.cshtml
TD-4384 correction for test failed, using GetDirectURL() instead of path property within the context request object
[TD-4384](https://hee-tis.atlassian.net/browse/TD-4384)
BackLinks were failing in UAT, when the user feedback questionnaire was being worked on by the user.
-----
I have:
[TD-4384]: https://hee-tis.atlassian.net/browse/TD-4384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4384 Correction for test failed

DigitalLearningSolutions.Web/Helpers/SupervisorCompetencyFilterHelper.cs
https://hee-tis.atlassian.net/browse/TD-4324
I check the filter option to return the right filter result for the selected filter option
-----
I have:
=> TD-4324 Resolving If Optional filter is applied along with other filters, its not displaying the correct results.

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs, DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/AddOptionalCompetenciesViewModel.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/AddOptionalCompetencies.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/ManageOptionalCompetencies.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentDescription.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_Layout.cshtml
[_TD-4697_](https://hee-tis.atlassian.net/browse/TD-4697)
Added AddOptionalCompetencies veiew
Modified code to redirect to AddOptionalCompetencies view when selected optional competencies less than minimum required competencies.
Service method 'HasMinimumOptionalCompetencies' added to check if self assessments has selected minimum required competencies.
-----
I have:
=> TD-4697- Feature added to display AddOptionalCompetencies page when selected optional competencies less than minimum required.

DigitalLearningSolutions.Data/DataServices/ActivityDataService.cs, DigitalLearningSolutions.Data/Models/TrackingSystem/ActivityLogDetail.cs
[TD-4469](https://hee-tis.atlassian.net/browse/TD-4469)
Replaces the "Registered" column title with "Enrolled" in the Excel detail sheet. Also replaces GUID email addresses with blanks.
-----
I have:
[TD-4469]: https://hee-tis.atlassian.net/browse/TD-4469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4469 fix test fails re enrolled column name and GUID emails

DigitalLearningSolutions.Data/DataServices/SessionDataService.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateProgress/DownloadProgress.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/DelegateProgress/ViewDelegateProgress.cshtml
[_TD-4154_](https://hee-tis.atlassian.net/browse/TD-4154)
Applied retry logic for the UPDATE statement when the process is busy with the previous execution. 
Added condition to show achievement only after passing any section.
Downloaded pdf progress report
-----
I have:
=> TD-4154- Applied retry logic for the UPDATE statement

DigitalLearningSolutions.Web/Views/Supervisor/DelegateProfileAssessments.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/Shared/_DelegateProfileAssessmentGrid.cshtml
[_TD-4764_](https://hee-tis.atlassian.net/browse/TD-4764)
Nominated supervisor role check added to display links accordingly
Supervisor role:
Nominated supervisor role:
-----
I have:
=> TD-4764-Nominated supervisor role check added to display links accordingly

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/AddOptionalCompetencies.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/ManageOptionalCompetencies.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentDescription.cshtml
[_TD-4697_](https://hee-tis.atlassian.net/browse/TD-4697)
'Cancel' link redirected to proficiencies page.
Plural vocabulary added in the AddOptionalCompetencies page text.
Call to AddOptionalCompetencies action updated for button control when self assessments with LinearNavigation is true.
-----
I have:
=> TD-4697-'Cancel' link redirected to proficiencies page.

DigitalLearningSolutions.Data/DataServices/ActivityDataService.cs, DigitalLearningSolutions.Data/Models/TrackingSystem/ActivityLogDetail.cs
[TD-4469](https://hee-tis.atlassian.net/browse/TD-4469)
Corrects the logic for returning the user's email address, using the same approach as the All Delegates query and uses a return field name that matches the filed name in the model to ensure it maps to the exported data.
-----
I have:
[TD-4469]: https://hee-tis.atlassian.net/browse/TD-4469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4469 fix report fails

DigitalLearningSolutions.Data/Models/SelfAssessments/CompetencySummary.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Helpers/CertificateHelper.cs, DigitalLearningSolutions.Web/ViewModels/Supervisor/ReviewSelfAssessmentViewModel.cs, DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml
https://hee-tis.atlassian.net/browse/TD-4598
I refactor CanViewCertificate method to include QuestionsCount and VerifiedCount
I added CompetencySummary class
I added CompetencySummary class  to  ReviewSelfAssessmentViewModel.cs
I remove and replace the check condition in the ReviewSelfAssessment.cshtml to fixed the signoffrequest button showing when the proficiencies are not completed 
I also refactor the certificate action method to remove and replace it with CanViewCertificate method
Adding optional proficiencies after making signoffrequest
-----
I have:
=> TD-4598 Sign off self-assessment appears when filters applied in Supervisor page though proficiencies are not completed

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/Competency.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/ManageOptionalCompetencies.cshtml
https://hee-tis.atlassian.net/browse/TD-4560
I added GroupOptionalCompetencies flag into the Manage optional competencies view model
I display a check box for the group name (H3) as per wireframe
I display the competencies in an expander beneath
Mobile view
-----
I have:
=> TD-4560 Change the Manage optional competencies view to allow selection of competencies by group

DigitalLearningSolutions.Web.Tests/Services/ActivityServiceTests.cs, DigitalLearningSolutions.Web/Services/ActivityService.cs
[TD-4469](https://hee-tis.atlassian.net/browse/TD-4469)
Fixes the date range label for the last row of the summary report.
-----
I have:
[TD-4469]: https://hee-tis.atlassian.net/browse/TD-4469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4469 fix date range labels on summary report

DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs
https://hee-tis.atlassian.net/browse/TD-4702
I refactor the download certificate action method of the supervisor controller to make use of  CanViewCertificate method for the check and count of the proficiency 
-----
I have:
=> TD-4702 fixing error due to early refactoring of the certificate

DigitalLearningSolutions.Web/Controllers/MyAccountController.cs
https://hee-tis.atlassian.net/browse/TD-4755
I exclude the Active from the admin role
-----
I have:
=> TD-4755 My Account - Active value is listed as one of the Admin roles

DigitalLearningSolutions.Data/Helpers/NewlineSeparatedStringListHelper.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/CourseSetup/AdminFieldAnswersViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/AddAdminField.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AdminFields/EditAdminField.cshtml
[TD-4333](https://hee-tis.atlassian.net/browse/TD-4333)
Making course admin fields optional again
-----
I have:
[TD-4333]: https://hee-tis.atlassian.net/browse/TD-4333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4333 Making course admin fields optional again

DigitalLearningSolutions.Data/Helpers/NameQueryHelper.cs, DigitalLearningSolutions.Data/Models/User/AdminEntity.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Administrator/AdministratorController.cs
https://hee-tis.atlassian.net/browse/TD-4471
I trim the search parameter to remove the whitespace
I included the primary and center emails in the search 
-----
I have:
=> TD-4471 Issues with 'Search' functionality when JS turned off on 'Tracking system - Centre administrators' screen

DigitalLearningSolutions.Data.Migrations/202410091524_UpdateCandidateAssessmentSupervisorsDuplicateRows.cs
[_TD-4785_](https://hee-tis.atlassian.net/browse/TD-4785)
Migration code add to Set the Removed date as the current date for old duplicate rows in the table
Before update:
After update:
-----
I have:
=> TD-4785-Set the Removed date as the current date for old duplicate rows in the table

DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/DeactivateDelegateControllerTests.cs
[_TD-4793_](https://hee-tis.atlassian.net/browse/TD-4793)
Unit tests added for deactivate delegate controller
-----
I have:
=> TD-4793-Unit tests added for deactivate delegate controller

DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/SelfAssessmentTests.cs
[_TD-4789_](https://hee-tis.atlassian.net/browse/TD-4789)
Unit tests added for ManageOptionalCompetencies with flags and SelfAssessmentOverview with optional competencies
-----
I have:
=> TD-4789-Unit tests added for ManageOptionalCompetencies with flags and SelfAssessmentOverview with optional competencies

DigitalLearningSolutions.Web/Scripts/learningPortal/selfAssessment.ts, DigitalLearningSolutions.Web/Styles/learningPortal/selfAssessment.scss, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/ManageOptionalCompetencies.cshtml
[TD-4920](https://hee-tis.atlassian.net/browse/TD-4920)
Implements a series of markup and styling fixes to the optional competencies page to bring it into line with the intended design.
Alerts confirmed to be known issues with NHS Design System or false positives.
Desktop
Mobile
-----
I have:
[TD-4920]: https://hee-tis.atlassian.net/browse/TD-4920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4920 Fix optional competency frontend

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs
https://hee-tis.atlassian.net/browse/TD-4879
I modified the query to limit the self-assessment activities so it will only load the course category that matches the logged in user’s admin account course category
-----
I have:
=> TD-4879 Limit the self assessments returned in Delegate Activities by admin course category

DigitalLearningSolutions.Data/DataServices/SupervisorDataService.cs, DigitalLearningSolutions.Data/Models/User/AdminEntity.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Services/SupervisorService.cs
[_TD-4882_](https://hee-tis.atlassian.net/browse/TD-4882)
Role Profiles retrieved based on logged in supervisor category
1. When logged in supervisor with 'All' or 'Nursing proficiency passports' category.
2. When logged in supervisor with 'Digital Workplace' category
-----
I have:
=> TD-4882-Limit the self assessments that a supervisor can enrol staff on to those matching their assigned category

DigitalLearningSolutions.Data/DataServices/SupervisorDataService.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Services/SupervisorService.cs
[_TD-4883_](https://hee-tis.atlassian.net/browse/TD-4883)
Category id passed to GetSelfAssessmentsForSupervisorDelegateId(+) to get self-assessments for a supervisor delegate based on logged in supervisor category
When logged in supervisor with 'All' or 'Nursing proficiency passports' category.
When logged in supervisor with 'Digital Workplace' category
-----
I have:
=> TD-4883-Limit the self assessments returned in the supervisor View self assessments view to those that match their assigned category

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs
[_TD-4888_](https://hee-tis.atlassian.net/browse/TD-4888)
1. Limiting the supervisors while adding new supervisor, is working as expected. No code change required.
2. Removed unused parameter 'centreId' from the service method
Tested for '[uat.dlstester3@gmail.com](mailto:uat.dlstester3@gmail.com)' supervisor for a self-assessment of 'Nursing proficiency passports' category.
1. When 'auldrin.possa@hee.nhs.uk' supervisor with 'All' or 'Nursing proficiency passports' category.
2. When 'auldrin.possa@hee.nhs.uk' supervisor with 'Digital Workplace' category.
-----
I have:
=> TD-4888-Limit the supervisors that are available to add to self assessment from "Manage supervisors" to supervisors with a matching category

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs
[_TD-4972_](https://hee-tis.atlassian.net/browse/TD-4972)
Added comparison of supervisor CategoryID with self-assessment CategoryID in the GetAllSupervisorsForSelfAssessmentId(+) to get supervisors based on category.
Tested for 'delegate.user8@gmail.com' supervisor for a self-assessment of 'Nursing proficiency passports' category.
1. When 'delegate.user8@gmail.com' supervisor with 'All' or 'Nursing proficiency passports' category.
2. When 'delegate.user8@gmail.com' supervisor with 'Digital Workplace' category.
-----
I have:
=> TD-4972-Limit the list of existing supervisors in the Manage Supervisors list to supervisors with a matching category

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs
[_TD-4974_](https://hee-tis.atlassian.net/browse/TD-4974)
Sign off supervisors list filtered based on self-assessment category
Tested for 'auldrinG possa (Development Testing Centre)' supervisor for a self-assessment of 'Nursing proficiency passports' category.
1. When 'auldrinG possa (Development Testing Centre)' supervisor with 'All' or 'Nursing proficiency passports' category.
2. When 'auldrinG possa (Development Testing Centre)' supervisor with 'Digital Workplace' category.
-----
I have:
=> TD-4974-Limit the list of supervisors in the Request sign off view to supervisors with a matching category

DigitalLearningSolutions.Web.Tests/Controllers/SupervisorController/SupervisorControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/SupervisorController.cs, DigitalLearningSolutions.Web/ViewModels/Supervisor/SupervisorDelegateViewModel.cs, DigitalLearningSolutions.Web/Views/Supervisor/NominateSupervisor.cshtml
https://hee-tis.atlassian.net/browse/TD-4889
I added the Learning category drop-down list on the confirm page which only shows when the supervisor categoryId is null if not I pass the supervisor categoryId 
I also ensure that The categories listed are limited to categories that are associated with self assessments that are published to the centre
-----
I have:
=> TD-4889 When a supervisor promotes a learner to the Nominated supervisor role, assign them to the same category as the supervisor

DigitalLearningSolutions.Data.Migrations/202411051212_UpdateCourseCategories.cs, DigitalLearningSolutions.Web/Scripts/searchSortFilterAndPaginate/filter.ts, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Administrator/AdministratorsViewModelFilterOptions.cs
[_TD-4495_](https://hee-tis.atlassian.net/browse/TD-4495)
Filter value text trimmed in the code.
Table column CategoryName (CourseCategories table) updated with trimmed values.
-----
I have:
=> TD-4495-Issue with adding the filters on 'Centre administrators' screen for 'Bedfordshire Hospitals NHS Trust' centre

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs
https://hee-tis.atlassian.net/browse/TD-4973
I modified the GetResultReviewSupervisorsForSelfAssessmentId query to limit the list of supervisors available for selection to only show supervisors/nominated supervisors who have a category that matches the self assessment (or supervisors/nominated supervisors who are not limited to a category)
-----
I have:
=> TD-4973 Limit the list of supervisors in the Request proficiency confirmation view to supervisors with a matching category

DigitalLearningSolutions.Data/DataServices/SupervisorDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/SupervisorController/SupervisorControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Services/SupervisorService.cs
https://hee-tis.atlassian.net/browse/TD-4884
I added adminCategoryId to the method parameter and where the condition of  GetSelfAssessmentsForSupervisorDelegateId method to limit supervisor view to the SelfAssessments that do not belong to the supervisor category 
I added adminCategoryId to the method parameter and where the condition of  GetSelfAssessmentByCandidateAssessmentId method to ensure that the supervisor can not view or review SelfAssessments that do not belong to the supervisor category 
When the admin categoryId is  null
When the admin categoryId is 34
-----
I have:
=> TD-4884 Prevent supervisors from viewing/reviewing self assessments in a category that doesn't match their own

DigitalLearningSolutions.Web.Tests/Controllers/SupervisorController/SupervisorControllerTests.cs
https://hee-tis.atlassian.net/browse/TD-4792
I added a unit test on SupervisorControllerTest to test for optional filter  
-----
I have:
=> TD-4792 Write unit tests for filter added on optional competencies in  the supervisor view

DigitalLearningSolutions.Data/DataServices/SupervisorDataService.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Services/SupervisorService.cs
https://hee-tis.atlassian.net/browse/TD-3656
I added 2 new query GetSupervisorDelegateDetailsForAdminIdWithoutRemovedClause and GetSupervisorDelegateDetailsByIdWithoutRemoveClause which get record without adding the remove to the where condition
I added GetSupervisorDelegateDetailsByIdWithoutRemoveClause  to the MyStaffList action method to return record when the supervisor doesn't have any delegate is supervising 
I added GetSupervisorDelegateDetailsByIdWithoutRemoveClause to get supervisor Delegate Details
-----
I have:
=> TD-3656 Supervise - "Add myself to try self assessment" staff doesn't exist when the educator is removed from the learning portal self-assessment

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/CourseDelegatesControllerTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/DelegateCoursesControllerTests.cs, DigitalLearningSolutions.Web.Tests/Services/CourseServiceTests.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ActivityDelegatesController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/DelegateCoursesController.cs, DigitalLearningSolutions.Web/Services/CourseDelegatesDownloadFileService.cs, DigitalLearningSolutions.Web/Services/CourseService.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs
[TD-4880](https://hee-tis.atlassian.net/browse/TD-4880)
Added a check for the categoryId of the admin users while fetching the self assessments, making sure we only pull the self assessments that matches the categoryId on the admin account of the user, also added an Unauthorized check when anyone tries to manipulate the self assessment delegates using the query string URL being opened.
If there's a categoryId on the admin account of the user, then show self assessments that are specific to the categoryId, if there's no categoryId on the admin account of the user, continue showing all the self assessments.
When categoryId is set to null on the admin account, the user can see all the self assessments and can access delegates from all the self assessments. 
When categoryid has  a value on …
=> Prevent administrators from viewing Activity Delegates for self assessments in a category that doesn't match their own

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs
The fix to TD-4950 allowed learner to see results across self assessments with shared competencies but submitting a new result against the shared competency still resulted in a 500 error. This was because when we checked for an existing result, we limited the results by self assessment ID. This change removes that clause from the check for existing results query and fixes the problem.
-----
I have:
=> TD-4950 Fix submit result fo duplicated competency

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs
Tiny tweak to update the self assessment ID of an existing self assessment result when updating.
-----
I have:
=> TD-4950 Updates self assessment ID when updating results

DigitalLearningSolutions.Data.Migrations/202411120903_CreateOrAlterGetOtherCentresForSelfAssessmentFunction.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.Designer.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.resx, DigitalLearningSolutions.Data.Migrations/Resources/TD-4950-dboGetOtherCentresForSelfAssessmentCreateOrAlter.sql, DigitalLearningSolutions.Data.Migrations/Scripts/TD-4950-dboGetOtherCentresForSelfAssessmentCreateOrAlter.sql, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentExportDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAsssessmentReportDataService.cs
Reworks the CompetencyDataService latest assessment result queries to join to SelfAssessmentStructure tables to determine which results to include instead of filtering by the SelfAssessmentID in the results table. This ensures that the results are returned regardless of whether the result was added in the self assessment that the user is working on.
-----
I have:
=> TD-4950 Limits result sets by self assessment structure rather than self assessment ID in results table

DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs
Overrides the count of verification requests in the query with a count based on the detail in the model using LINQ. This ensures that requests that are not linked to the related candidate assessment supervisor record are considered in the count.
-----
I have:
=> TD-4950 Fix issue with verify m,ultiple competencies button being unavailable

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentExportDataService.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/Export/CandidateAssessmentExportSummary.cs, DigitalLearningSolutions.Web/Services/CandidateAssessmentDownloadFileService.cs
Fixes the counts in the export self assessment summary queries to remove a join on self assessment result self assessment ID which excluded results confirmed in another self assessment. Also relabels "verified" to "confirmed" in the summary sheet to make it consistent with the wording in the platform.
-----
I have:
=> TD-4950 Removes unnecessary join in export assessment summary query and renames field

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs
[_TD-4974_](https://hee-tis.atlassian.net/browse/TD-4974)
Appended table alias to 'CategoryID' field in the SQL query.
-----
I have:
=> TD-4974-Appended table alias to 'CategoryID' field

DigitalLearningSolutions.Data/DataServices/SupervisorDataService.cs
Removes join of SelfAssessmentResults.SelfAssessmentID from a missed query in the supervisor summary data service method.
-----
I have:
=> TD-4950 Removes link to result self assessment ID from supervisor

DigitalLearningSolutions.Data/DataServices/SupervisorDataService.cs
Removes join to result SelfAssessmentResult.SelfAssessmentID from query in data service method that returns summary of supervisors confirming results for the self assessment.
-----
I have:
=> TD-4950 Removes link to result self assessment ID from supervisor from supervisor query

DigitalLearningSolutions.Web/Views/LearningPortal/Shared/_Dates.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateCourseProgressDetailsWithStatusTags.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateSelfAssessmentProgressDetails.cshtml
https://hee-tis.atlassian.net/browse/TD-4395
I changed the enrolled label to First  enrolled   on the Dates partial view and the Index view of view delegate
-----
I have:
=> TD-4395 'Enrolled' field label needs to change to 'First enrolled' same as on 'Delegate activities' for the self assessments

DigitalLearningSolutions.Web/Views/SuperAdmin/Users/UserCentreAccounts.cshtml
[_TD-4406_](https://hee-tis.atlassian.net/browse/TD-4406)
Added check if admin account exists.
-----
I have:
=> TD-4406- Super Admin: Issue not showing the 'Admin' links for the centres when user account is reactivated on 'User centre roles' screen

DigitalLearningSolutions.Web/Controllers/FrameworksController/Competencies.cs
TD-5058
When a new competency is added without any flags that has similar competencies, a 500 error was being thrown because the list of flags was null rather than empty. This change checks for none null rather than non-empty.
-----
I have:
=> TD-5058 Fix add similar competency 500 error

DigitalLearningSolutions.Web/ViewModels/Supervisor/SupervisorDelegateViewModel.cs
https://hee-tis.atlassian.net/browse/TD-5028
I check the validation attributes on the SupervisorDelegateViewModel properties. I ensure that all  properties of SupervisorDelegateViewModel are bound correctly in the RemoveSupervisorDelegateConfirmed action method
-----
I have:
=> TD-5028 Supervise - Remove staff member doesn't remove the supervisor (For Supervisor when added via 'Add myself to try self-assessment')

DigitalLearningSolutions.Data.Migrations/202412020900_UpdateCandidateAssessmentSupervisorsTable.cs
[_TD-4787_](https://hee-tis.atlassian.net/browse/TD-4787)
Changed role from Educator/Manager to Assessor for nominated supervisors.
We have excluded duplicate records from update.
N/A
There is no data available to update such nominated supervisor role on dev and UAT environment.
The current list of nominated supervisors in production is as follows to update.
'SelfAssessmentSupervisorRoleID' is the current one and 'Roleid' is the role to be updated.
[TD-4787-Prod-Data.xlsx](https://github.com/user-attachments/files/17975644/TD-4787-Prod-Data.xlsx)
-----
I have:
=> TD-4787- Changed role from Educator/Manager to Assessor for nominated supervisors

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs
[_TD-5095_](https://hee-tis.atlassian.net/browse/TD-5095)
SupervisorDelegateId check added along with CandidateAssessmentID to update CandidateAssessmentSupervisors
N/A
-----
I have:
=> TD-5095-Tracking system enrol on activity - Enrolling Adult critical care self-assessment resulting in error

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/CurrentTests.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/Current.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ViewDelegateController.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs
Limiting the self assessment shown in the manage delegate section.
[TD-5026](https://hee-tis.atlassian.net/browse/TD-5026)
Added a query check based on the admin categoryID of the logged in user to show the self assessments that match with the specific categoryId for the delegate user in their manage delegate section.
-----
I have:
[TD-5026]: https://hee-tis.atlassian.net/browse/TD-5026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Limit the self assessment activities listed in the manage delegate view to the category associated with the admin

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ActivityDelegatesController.cs, DigitalLearningSolutions.Web/ServiceFilter/VerifyAdminUserCanAccessSelfAssessment.cs, DigitalLearningSolutions.Web/Startup.cs
[_TD-5108_](https://hee-tis.atlassian.net/browse/TD-5108)
Added action filter 'VerifyAdminUserCanAccessSelfAssessment' to restrict access.
N/A
-----
I have:
=> TD-5108-Activity Delegate - Export and Remove self-assessment URL can be still accessed via URL manipulation when admin category doesn't match

DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Helpers/CertificateHelper.cs
https://hee-tis.atlassian.net/browse/TD-5084
I added the CompetencySummation method to sum the assessment Proficiencies 
I added a check in the RequestSignOff action method to ensure the Proficiencies  are completed before requesting signoff
-----
I have:
=> TD-5084 Self-assessments Sign off should not be allowed through URL manipulation 

DigitalLearningSolutions.Data/DataServices/SupervisorDataService.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Services/FrameworkNotificationService.cs, DigitalLearningSolutions.Web/Services/SupervisorService.cs
https://hee-tis.atlassian.net/browse/TD-4884
I added adminCategoryId to the method parameter and where condition query of GetSelfAssessmentBaseByCandidateAssessmentId and  to other places where the method is reference 
I added a check to ReviewCompetencySelfAssessment and VerifyMultipleResults action method to ensure that the supervisor that wanted to confirm the assessment request is eligible to do that 
-----
I have:
=> TD-4884 Prevent supervisors from confirm self assessments in a category that doesn't match their own

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/ViewDelegateController.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs
https://hee-tis.atlassian.net/browse/TD-5026
I used method overloading to  add GetSelfAssessmentsForCandidate method, adminIdCategoryID parament and include the adminIdCategoryID to the where condition in the query so that logged in admin can only see the course category assigned to the admin 
-----
I have:
=> TD-5026 Limit the self assessment activities listed in the manage delegate view to the category associated with the admin

DigitalLearningSolutions.Data.Migrations/202412020900_UpdateCandidateAssessmentSupervisorsTable.cs, DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Data/DataServices/FrameworkDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Data/DataServices/SupervisorDataService.cs, DigitalLearningSolutions.Data/Models/Frameworks/Import/BulkCompetency.cs, DigitalLearningSolutions.Data/Models/Frameworks/Import/CompetencyTableRow.cs, DigitalLearningSolutions.Web.Tests/Controllers/Frameworks/FrameworkControllerTests.cs, DigitalLearningSolutions.Web.Tests/ServiceFilter/RedirectToErrorEmptySessionDataTests.cs, DigitalLearningSolutions.Web/Controllers/FrameworksController/FrameworksController.cs, DigitalLearningSolutions.Web/Controllers/FrameworksController/ImportCompetencies.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Helpers/CommonValidationErrorMessages.cs, DigitalLearningSolutions.Web/Models/BulkCompetenciesData.cs, DigitalLearningSolutions.Web/Models/BulkCompetenciesResult.cs, DigitalLearningSolutions.Web/Services/FrameworkNotificationService.cs, DigitalLearningSolutions.Web/Services/FrameworkService.cs, DigitalLearningSolutions.Web/Services/ImportCompetenciesFromFileService.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs, DigitalLearningSolutions.Web/Services/SupervisorService.cs, DigitalLearningSolutions.Web/ViewModels/Frameworks/ImportCompetenciesPreProcessViewModel.cs, DigitalLearningSolutions.Web/Views/Frameworks/Developer/ImportCompetencies.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/ImportCompleted.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/UploadResults.cshtml
[TD-5153](https://hee-tis.atlassian.net/browse/TD-5153)
-----
I have:
[TD-5153]: https://hee-tis.atlassian.net/browse/TD-5153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5153 bulk upload competencies page

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs
https://hee-tis.atlassian.net/browse/TD-5128
I modified the query of GetResultSupervisorVerifications method to limit the supervisor to the category that matches the category of the SelfAssessments
-----
I have:
=> TD-5128 Manage Confirmation request - Outstanding request should display only the request that is matching the admin category

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentSupervisorDataService.cs
https://hee-tis.atlassian.net/browse/TD-5131
I included checking if the admin have a supervisor or nominated supervisor role to the GetAllSupervisorsForSelfAssessmentId and GetResultReviewSupervisorsForSelfAssessmentId methods where clause query
-----
I have:
=> TD-5131 Self-assessmentManageSupervisorstilldisplaystheSupervisoreventhoughsupervisorroleisremovedfromtheAdministrator

DigitalLearningSolutions.Web/Controllers/FrameworksController/ImportCompetencies.cs, DigitalLearningSolutions.Web/Models/BulkCompetenciesData.cs, DigitalLearningSolutions.Web/ViewModels/Frameworks/Import/AddAssessmentQuestionsFormData.cs, DigitalLearningSolutions.Web/ViewModels/Frameworks/Import/AddAssessmentQuestionsViewModel.cs, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/AddAssessmentQuestions.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/ImportCompleted.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/ImportFailed.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/Index.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/UploadResults.cshtml
[TD-5155](https://hee-tis.atlassian.net/browse/TD-5155)
Implements Add Assessment Questions page to import competencies flow and handles storing of posted values to tempdata model.
-----
I have:
[TD-5155]: https://hee-tis.atlassian.net/browse/TD-5155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5155 Add assessment questions page

DigitalLearningSolutions.Web/Controllers/FrameworksController/ImportCompetencies.cs, DigitalLearningSolutions.Web/Models/BulkCompetenciesData.cs, DigitalLearningSolutions.Web/ViewModels/Frameworks/Import/AddQuestionsToWhichCompetenciesViewModel.cs, DigitalLearningSolutions.Web/ViewModels/Frameworks/Import/ImportCompetenciesPreProcessViewModel.cs, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/AddQuestionsToWhichCompetencies.cshtml
[TD-5158](https://hee-tis.atlassian.net/browse/TD-5158)
Implements add questions to which competencies page with logic to store posted choice to tempdata.
-----
I have:
[TD-5158]: https://hee-tis.atlassian.net/browse/TD-5158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5158 Implements add questions to which competencies page

DigitalLearningSolutions.Data/Models/Frameworks/Import/BulkCompetency.cs, DigitalLearningSolutions.Data/Models/Frameworks/Import/CompetencyTableRow.cs, DigitalLearningSolutions.Data/Models/Frameworks/Import/ImportCompetenciesResult.cs, DigitalLearningSolutions.Web/Controllers/FrameworksController/ImportCompetencies.cs, DigitalLearningSolutions.Web/Services/ImportCompetenciesFromFileService.cs, DigitalLearningSolutions.Web/ViewModels/Frameworks/Import/ImportCompetenciesPreProcessViewModel.cs, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/ImportCompleted.cshtml
[TD-5219](https://hee-tis.atlassian.net/browse/TD-5219)
Adds framework competency ID checking and associated error messages. Also adds details of number of competency groups and flags to the import pre-process summary.
-----
I have:
[TD-5219]: https://hee-tis.atlassian.net/browse/TD-5219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5219 Improvements file uploaded summary and error messages

DigitalLearningSolutions.Data/DataServices/FrameworkDataService.cs, DigitalLearningSolutions.Data/Models/Frameworks/Import/CompetencyTableRow.cs, DigitalLearningSolutions.Data/Models/Frameworks/Import/ImportCompetenciesResult.cs, DigitalLearningSolutions.Web/Controllers/FrameworksController/ImportCompetencies.cs, DigitalLearningSolutions.Web/Models/BulkCompetenciesData.cs, DigitalLearningSolutions.Web/Services/FrameworkService.cs, DigitalLearningSolutions.Web/Services/ImportCompetenciesFromFileService.cs, DigitalLearningSolutions.Web/ViewModels/Frameworks/Import/AddAssessmentQuestionsViewModel.cs, DigitalLearningSolutions.Web/ViewModels/Frameworks/Import/AddQuestionsToWhichCompetenciesViewModel.cs, DigitalLearningSolutions.Web/ViewModels/Frameworks/Import/ApplyCompetencyOrderingViewModel.cs, DigitalLearningSolutions.Web/ViewModels/Frameworks/Import/ImportCompetenciesPreProcessViewModel.cs, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/AddAssessmentQuestions.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/AddQuestionsToWhichCompetencies.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/ApplyCompetencyOrdering.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/ImportCompleted.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/Index.cshtml
[TD-5220](https://hee-tis.atlassian.net/browse/TD-5220)
Checks whether competency order for existing competencies has changed and prompts user to choose whether to store changes to the order or not.
-----
I have:
[TD-5220]: https://hee-tis.atlassian.net/browse/TD-5220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5220 reorder competencies option page

DigitalLearningSolutions.Web/Controllers/FrameworksController/ImportCompetencies.cs, DigitalLearningSolutions.Web/ViewModels/Frameworks/Import/ImportSummaryViewModel.cs, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/AddQuestionsToWhichCompetencies.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/ImportSummary.cshtml
[TD-5162](https://hee-tis.atlassian.net/browse/TD-5162)
Implements the import summary page for the import competencies flow.
-----
I have:
[TD-5162]: https://hee-tis.atlassian.net/browse/TD-5162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5162 import competencies summary page

DigitalLearningSolutions.Data/DataServices/FrameworkDataService.cs, DigitalLearningSolutions.Data/Models/Frameworks/FrameworkCompetency.cs, DigitalLearningSolutions.Data/Models/Frameworks/Import/CompetencyTableRow.cs, DigitalLearningSolutions.Web/Controllers/FrameworksController/Competencies.cs, DigitalLearningSolutions.Web/Controllers/FrameworksController/ImportCompetencies.cs, DigitalLearningSolutions.Web/Models/BulkCompetenciesData.cs, DigitalLearningSolutions.Web/Services/FrameworkService.cs, DigitalLearningSolutions.Web/Services/ImportCompetenciesFromFileService.cs, DigitalLearningSolutions.Web/ViewModels/Frameworks/Import/ImportCompetenciesResultsViewModel.cs, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/ApplyCompetencyOrdering.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/ImportCompleted.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/ImportSummary.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/Index.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/UploadResults.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/_Structure.cshtml
[TD-5163](https://hee-tis.atlassian.net/browse/TD-5163)
Implements the processing of competencies uploaded in the sheet according to the options that the user has selected:
- Updates competencies
- Inserts competencies
- Inserts competency groups (applying DLSFW1 BR)
- Adds flags
- Adds assessment questions
- Reorders competencies
- Reorders competency groups
-----
I have:
Either:
- [Business rules database - DLSFW1](https://hee-tis.atlassian.net/wiki/spaces/TP/database/4286021635?contentId=4286021635&entryId=d66d1789-7052-45c4-8ee9-45b580819049&fieldId=d35293bf-2be7-5871-94c4-c46aad848eb0)
Or:
[TD-5163]: https://hee-tis.atlassian.net/browse/TD-5163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …
=> TD-5163 competency processing and processing complete page

DigitalLearningSolutions.Data/Models/Frameworks/Import/CompetencyTableRow.cs, DigitalLearningSolutions.Data/Models/Frameworks/Import/ImportCompetenciesResult.cs, DigitalLearningSolutions.Web/Services/ImportCompetenciesFromFileService.cs, DigitalLearningSolutions.Web/ViewModels/Frameworks/Import/ImportCompetenciesResultsViewModel.cs, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/ApplyCompetencyOrdering.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/ImportSummary.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/Index.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/UploadResults.cshtml
[TD-5233](https://hee-tis.atlassian.net/browse/TD-5233)
These changes tidy up the bulk upload/download competencies flow to:
- provide a count of competencies reordered
- warn users about the limitations of the import process
- warn users uploading proficiencies to a published framework before processing starts
-----
I have:
Either:
Or:
[TD-5233]: https://hee-tis.atlassian.net/browse/TD-5233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5233 bulk import tidy up tasks

DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/ViewModels/Supervisor/SignOffProfileAssessmentViewModel.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/SignOffProfileAssessment.cshtml
[_TD-5180_](https://hee-tis.atlassian.net/browse/TD-5180)
Added verification if sign-off rejected.
Variable 'IsSignOffverified' is added to maintain radio button status on error.
N/A
-----
I have:
=> TD-5180-When a self assessment sign-off request is rejected, the learner is unable to submit a new one

DigitalLearningSolutions.Data/DataServices/CourseDataService.cs
https://hee-tis.atlassian.net/browse/TD-4435
I added EnrolledByAdminId field  to the update query of EnrolOnActivitySelfAssessment method so that enrolledadminid can be part of the updated field
-----
I have:
Either:
Or:
=> TD-4435 Mismatch of 'Enrolment method' showing on 'Tracking system' & 'Delegate activities' screen for 'Digital skills assessment tool' assessment

.github/dependabot.yml, .github/workflows/auto-merge.yml
Description:
This PR addresses issues where Dependabot fails to create a PR due to connectivity problems with our Tel Azure NuGet source.
Changes include:
Added checks to handle scenarios where Dependabot cannot connect to the NuGet source.
Enhanced validation for auto-merge functionality:
Auto-merge will now wait for pipelines that are not only In_Progress but also in the Queued status, preventing merges when pipelines are stuck in the queue.
This ensures smoother dependency updates and avoids potential CI/CD disruptions.
=> Improved Dependency Update Workflow and Auto-Merge Validation

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/SelfAssessmentReports/SelfAssessmentReportsController.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Reports/SelfAssessmentReportsViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/SelfAssessmentReports/Index.cshtml
https://hee-tis.atlassian.net/browse/TD-5096
I added the AdminCategoryId and CategoryId properties  to the SelfAssessmentReportsViewModel class
I added the GetSelfAssessmentCategoryId to the index action method of the SelfAssessmentReportsController to get the DSAT CategoryId 
I added a check to the index view to hide the link to the DSAT report if the AdminCategoryId did not match the CategoryId and the AdminCategoryId is not NULL
When the adminCategoryId is set to 4
When the adminCategoryId is set to 1
When the adminCategoryId is set to Null
-----
I have:
Either:
Or:
=> TD-5096 Hide the link to the DSAT report if the admin user is in a category that doesn't match

DigitalLearningSolutions.Data/DataServices/SupervisorDataService.cs
[TD-5138](https://hee-tis.atlassian.net/browse/TD-5138)
Made a change to the count query on the dashboard, and used the query that provides the details once the staff number is clicked on the dashboard, used the count function to show the number of staffs.
No screenshots as such since the UI code was not tampered.
-----
I have:
Either:
Or:
[TD-5138]: https://hee-tis.atlassian.net/browse/TD-5138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5138_ Staff count was incorrect on the dashboard and doesn't match when staff list is clicked to navigate the list.

DigitalLearningSolutions.Data/DataServices/CompetencyAssessmentDataService.cs, DigitalLearningSolutions.Data/Models/CompetencyAssessments/CompetencyAssessment.cs, DigitalLearningSolutions.Web/Views/CompetencyAssessments/Shared/_AssessmentsGrid.cshtml
[TD-5286](https://hee-tis.atlassian.net/browse/TD-5286)
Reads linked frameworks into the competency assessments model and displays linked frameworks on the competency assessments table. Also changes View/Edit link to Manage.
-----
I have:
Either:
Or:
[TD-5286]: https://hee-tis.atlassian.net/browse/TD-5286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5286 tweak table

DigitalLearningSolutions.Data/DataServices/FrameworkDataService.cs
[TD-4169](https://hee-tis.atlassian.net/browse/TD-4169)
The user roles returned had multiple rows since the FrameworkCollaborators table has multiple entries for a given adminID and FrameworkID. The ExecuteScalar was returning the topmost row, in this case, userrole=1 (since the first time the enrolment was reviewer). 
We have now added another where clause that would pull out only the current role that has not been deleted.
-----
I have:
Either:
Or:
[TD-4169]: https://hee-tis.atlassian.net/browse/TD-4169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …
=> TD-4169 Framework Contributor Permission Not Working

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_Layout.cshtml, DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml
[TD-5327](https://hee-tis.atlassian.net/browse/TD-5327)
Fixes errors with markup and js referencing that were preventing the more button from collapsing properly.
-----
I have:
Either:
Or:
[TD-5327]: https://hee-tis.atlassian.net/browse/TD-5327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5327 update nhs design system

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs
https://hee-tis.atlassian.net/browse/TD-5265
I added GetSelfAssessmentResultswithSupervisorVerificationsForDelegateSelfAssessmentCompetency method to get the optional proficiencies  added
I added RemoveReviewCandidateAssessmentOptionalCompetencies method to update and remove the optional proficiencies added 
I added GetCandidateAssessmentOptionalCompetencies method to the ManageOptionalCompetencies action method this method used get and  check OptionalCompetencies removed
-----
I have:
Either:
Or:
=> TD-5265 Issue showing 'confirmation requests/confirm self assessments link' when added optional proficiencies are removed

DigitalLearningSolutions.Data/DataServices/FrameworkDataService.cs
[TD-5329](https://hee-tis.atlassian.net/browse/TD-5329)
Corrects the query by moving the check that FrameworkCollaborators IsDeleted flag is false into the LEFT join instead of the WHERE clause to ensure that a value is returned even when there is no record in the FrameworkCollaborators table for the framework.
-----
I have:
Either:
Or:
[TD-5329]: https://hee-tis.atlassian.net/browse/TD-5329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5329 fix get framework admin roles bug

DigitalLearningSolutions.Web/Controllers/FrameworksController/ImportCompetencies.cs
[TD-5329](https://hee-tis.atlassian.net/browse/TD-5329)
Passes the correct ViewModel into the view returned when an error is shown after preprocessing an uploaded framework sheet.
-----
I have:
Either:
Or:
[TD-5329]: https://hee-tis.atlassian.net/browse/TD-5329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5329 fix bug with showing error page after upload

DigitalLearningSolutions.Data/DataServices/FrameworkDataService.cs
[TD-5329](https://hee-tis.atlassian.net/browse/TD-5329)
Fixes bug with returning 0 instead of inserted competency group id when adding a competency group.
-----
I have:
Either:
Or:
[TD-5329]: https://hee-tis.atlassian.net/browse/TD-5329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5329 fix bug with adding competencies to a new group

DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml
[TD-5334](https://hee-tis.atlassian.net/browse/TD-5334)
Pulls the breadcrumb out of the header and into the body to reflect the example usage in the NHS design system.
-----
I have:
Either:
Or:
[TD-5334]: https://hee-tis.atlassian.net/browse/TD-5334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5334 Pulls breadcrumb out of header

DigitalLearningSolutions.Data/DataServices/SupervisorDataService.cs, DigitalLearningSolutions.Data/Models/Supervisor/DelegateSelfAssessment.cs, DigitalLearningSolutions.Web/ViewModels/Supervisor/ReviewSelfAssessmentViewModel.cs, DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/VerifyMultipleResults.cshtml
[TD-4475](https://hee-tis.atlassian.net/browse/TD-4475)
Matching proficiencies count added to screen.
VocabPlural method updated to get vocabulary.
-----
I have:
Either:
Or:
[TD-4475]: https://hee-tis.atlassian.net/browse/TD-4475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-4475-Count of matching proficiencies should be shown on 'Supervisor' section same as on 'Learning Portal' for the self assessments

DigitalLearningSolutions.Web/Controllers/TrackingSystem/CourseSetup/CourseSetupController.cs
https://hee-tis.atlassian.net/browse/TD-5291
I loop through each section inside data.SectionContentData
I Filters out only the tutorials that exist in setCourseContentViewModelNew.Tutorials
I remove the tutorials that does not exist in setCourseContentViewModelNew.Tutorials
I save SectionContentData back into multiPageFormService
-----
I have:
Either:
Or:
=> TD-5291 Issue on 'Course set up' screen when selected Few course content first time and changed to 'All' of them clicking 'change link'

DigitalLearningSolutions.Web/Controllers/TrackingSystem/CourseSetup/CourseSetupController.cs
https://hee-tis.atlassian.net/browse/TD-5292
I check if the EditCourseContent is true, and true is assigned, If editCourseContent null default value is assigned
-----
I have:
Either:
Or:
=> TD-5292 Issue with 'Go back' link when creating a course and adding 'Course content' on 'Course set up' screen

DigitalLearningSolutions.Web/Styles/layout.scss, DigitalLearningSolutions.Web/Views/Shared/_Layout.cshtml
[TD-5345](https://hee-tis.atlassian.net/browse/TD-5345)
Fixes header styling issues:
- max width and flex box layout of service name
- removal of active nav item border indicator
-----
I have:
Either:
Or:
[TD-5345]: https://hee-tis.atlassian.net/browse/TD-5345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5345 Fixes header styling issue

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs
https://hee-tis.atlassian.net/browse/TD-5333
I modified the RemoveReviewCandidateAssessmentOptionalCompetencies method, I removed the query that updates the Result field in SelfAssessmentResults  table 
I also modified the GetSelfAssessmentResultswithSupervisorVerificationsForDelegateSelfAssessmentCompetency method, I added the Verify is Null to the where clause 
-----
I have:
Either:
Or:
=> TD-5333 Issue with optional proficiencies not retaining to previous State when removed and added them back

DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/ViewModels/Supervisor/EnrolDelegateSummaryViewModel.cs, DigitalLearningSolutions.Web/Views/Supervisor/SelectDelegateSupervisorRoleSummary.cshtml
https://hee-tis.atlassian.net/browse/TD-3542
I added validation to supervisorRoles  to take care of NullReferenceException that is causing error 500
I also added validation SelectDelegateSupervisorRoleSummary.cshtml page to show if  no supervisor roles is configured for the self assessment 
-----
I have:
Either:
Or:
=> TD-3542 Console '500' error is seeing on the 'My staff' screen when clicked 'Supervise' link for 'Version_2_Data_Professions framework' assessment

DigitalLearningSolutions.Data/DataServices/CompetencyAssessmentDataService.cs, DigitalLearningSolutions.Data/Models/CompetencyAssessments/CompetencyAssessment.cs, DigitalLearningSolutions.Data/Models/CompetencyAssessments/CompetencyAssessmentBase.cs, DigitalLearningSolutions.Web/Controllers/CompetencyAssessmentsController/CompetencyAssessments.cs, DigitalLearningSolutions.Web/Services/CompetencyAssessmentService.cs, DigitalLearningSolutions.Web/ViewModels/CompetencyAssessments/EditBrandingViewModel.cs, DigitalLearningSolutions.Web/Views/CompetencyAssessments/EditBranding.cshtml, DigitalLearningSolutions.Web/Views/CompetencyAssessments/EditDescription.cshtml, DigitalLearningSolutions.Web/Views/CompetencyAssessments/ManageCompetencyAssessment.cshtml
[TD-5308](https://hee-tis.atlassian.net/browse/TD-5308)
Implements the assessment provider and category MVC page with new provider and category handling and mark task complete checkbox.
-----
I have:
Either:
Or:
[TD-5308]: https://hee-tis.atlassian.net/browse/TD-5308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5308 Implements assessment provider and category page

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Data/DataServices/SupervisorDataService.cs
[TD-5367](https://hee-tis.atlassian.net/browse/TD-5367)
Removed 'Update CandidateAssessmentSupervisors..' when removing self assessment which helps to preserve previously selected supervisors. Updated CandidateAssessmentSupervisor during self-assessment enrolment so that only one supervisor role is active for a candidate assessment. This solves the current problem.
-----
I have:
Either:
- [DLS self assessment enrolment business rules](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/4627398657/DLS+self+assessment+enrolment+business+rules)
Or:
[TD-5367]: https://hee-tis.atlassian.net/browse/TD-5367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5367-Issue showing duplicate self assessments on 'Supervisor Dashboard - My staff' screen

DigitalLearningSolutions.Data/DataServices/CompetencyAssessmentDataService.cs, DigitalLearningSolutions.Web/Controllers/CompetencyAssessmentsController/CompetencyAssessments.cs, DigitalLearningSolutions.Web/Services/CompetencyAssessmentService.cs, DigitalLearningSolutions.Web/ViewModels/CompetencyAssessments/EditVocabularyViewModel.cs, DigitalLearningSolutions.Web/Views/CompetencyAssessments/EditVocabulary.cshtml, DigitalLearningSolutions.Web/Views/CompetencyAssessments/ManageCompetencyAssessment.cshtml
[TD-5309](https://hee-tis.atlassian.net/browse/TD-5309)
Implements the edit assessment vocabulary MVC form. Includes:
- hints for options taken from the Skills for Health report
- validation that an option has been chosen
- mark task as complete checkbox
-----
I have:
Either:
Or:
[TD-5309]: https://hee-tis.atlassian.net/browse/TD-5309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5309 Implements edit assessment vocabulary page

DigitalLearningSolutions.Data/DigitalLearningSolutions.Data.csproj
[TD-5325](https://hee-tis.atlassian.net/browse/TD-5325)
While investigating we found out that the API call was successful and the Freshdesk ticket was being created in Freshdesk. The response mapping was failing because the 'due_by' date sent in the API response was null, and the response model contained a property 'due_by' that was non-nullable. This resulted in the datatype mismatch during deserialization. 
I did some research and found out that recently, Freshdesk addressed this issue in their latest version, PR for this change- 
https://github.com/DaveTCode/FreshdeskApiDotnet/pull/272
Hence updating Freshdesk Api Nuget Package in this PR solves our issue.
-----
I have:
Either:
Or: …
=> TD-5325 Updating Freshdesk Api Nuget Package

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs
[TD-5370](https://hee-tis.atlassian.net/browse/TD-5370)
Added code to remove a pending sign-off request if the self-assessment does not include the minimum optional competencies.
-----
I have:
Either:
Or:
[TD-5370]: https://hee-tis.atlassian.net/browse/TD-5370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5370- Added code to remove a pending sign-off request if the self-assessment does not include the minimum optional competencies.

DigitalLearningSolutions.Data/DataServices/CourseCategoriesDataService.cs, DigitalLearningSolutions.Data/DataServices/CourseDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CompetencyDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Data/DataServices/SupervisorDataService.cs, DigitalLearningSolutions.Data/DigitalLearningSolutions.Data.csproj, DigitalLearningSolutions.Data/Models/Supervisor/DelegateSelfAssessment.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/PromoteToAdminControllerTests.cs, DigitalLearningSolutions.Web.Tests/Services/EmailGenerationServiceTests.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Controllers/SupervisorController/Supervisor.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/Administrator/AdministratorController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/SelfAssessmentReports/SelfAssessmentReportsController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/CourseSetup/CourseSetupController.cs, DigitalLearningSolutions.Web/Controllers/TrackingSystem/Delegates/PromoteToAdminController.cs, DigitalLearningSolutions.Web/Services/CourseCategoriesService.cs, DigitalLearningSolutions.Web/Services/EmailGenerationService.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs, DigitalLearningSolutions.Web/ViewModels/Supervisor/EnrolDelegateSummaryViewModel.cs, DigitalLearningSolutions.Web/ViewModels/Supervisor/ReviewSelfAssessmentViewModel.cs, DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/SelectDelegateSupervisorRoleSummary.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/VerifyMultipleResults.cshtml, DigitalLearningSolutions.Web/Views/TrackingSystem/CourseSetup/AddNewCentreCourse/SetSectionContent.cshtml
[DLS New York Release  1.1.2](https://hee-tis.atlassian.net/projects/TD/versions/12715/tab/release-report-all-issues)
Merging to production for deployment
-----
I have:
Either:
Or:
=> Dls release v1.1.2

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/SelfAssessmentReports/SelfAssessmentReportsController.cs, DigitalLearningSolutions.Web/Helpers/ExternalApis/TableauConnectionHelper.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/SelfAssessmentReports/TableauCompetencyDashboard.cshtml
[TD-5408](https://hee-tis.atlassian.net/browse/TD-5408)
Passes email and admin ID as URL params to Tableau instead of passing email in JWT using the approach [specified here](https://help.tableau.com/current/api/embedding_api/en-us/docs/embedding_api_parameters.html). This was the approach agreed when discussing with the head of data visualisation 06/03/2025. To avoid having to create Tableau users using the service account which was considered too risky.
Documentation to follow if PoC is successful.
-----
I have:
Either:
Or:
[TD-5408]: https://hee-tis.atlassian.net/browse/TD-5408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5408 Passes email and admin ID as URL params to Tableau

DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs
[TD-5391](https://hee-tis.atlassian.net/browse/TD-5391)
A check has been added to verify if any mandatory competencies need to be confirmed. 
If some competencies need to be confirmed or optional competencies are less than required and a sign-off request is pending, the request will be deleted.
N/A
-----
I have:
Either:
Or:
[TD-5391]: https://hee-tis.atlassian.net/browse/TD-5391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5391-A check has been added to verify if any mandatory competencies need to be confirmed.

DigitalLearningSolutions.Data.Migrations/202503111500_AddLastAccessedColumn.cs
[TD-3711](https://hee-tis.atlassian.net/browse/TD-3711)
Fluent migration for adding LastAccessed column in Users, DelegateAccounts and AdminAccounts tables and populating values.
-----
I have:
Either:
Or:
[TD-3711]: https://hee-tis.atlassian.net/browse/TD-3711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3711 Adding Last Accessed Columns To Tables

DigitalLearningSolutions.Data/DataServices/LoginDataService.cs, DigitalLearningSolutions.Web.Tests/Services/LoginServiceTests.cs, DigitalLearningSolutions.Web/Controllers/LoginController.cs, DigitalLearningSolutions.Web/Services/LoginService.cs, DigitalLearningSolutions.Web/Startup.cs
[TD-3712](https://hee-tis.atlassian.net/browse/TD-3712)
Update LastAccessed Date For Users During Login
-----
I have:
Either:
Or:
[TD-3712]: https://hee-tis.atlassian.net/browse/TD-3712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3712 Update LastAccessed Date For Users During Login

DigitalLearningSolutions.Web/Services/DelegateApprovalsService.cs
[TD-5388](https://hee-tis.atlassian.net/browse/TD-5388)
Once rejected by the centre admin, the delegate was not able to re register using the same email ID, so I added a logic to remove the specific record from the user table on delegate rejection.
No screenshots
-----
I have:
Either:
Or:
[TD-5388]: https://hee-tis.atlassian.net/browse/TD-5388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5388 Deleting rejected delegate record from the USER table on rejection by ADMIN

DigitalLearningSolutions.Data/DataServices/LoginDataService.cs, DigitalLearningSolutions.Web/Controllers/LoginController.cs, DigitalLearningSolutions.Web/Services/LoginService.cs
[TD-3713](https://hee-tis.atlassian.net/browse/TD-3713)
Update LastAccessed Date For AdminAccounts And DelegateAccounts
-----
I have:
Either:
Or:
[TD-3713]: https://hee-tis.atlassian.net/browse/TD-3713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3713- Update LastAccessed Date For AdminAccounts And DelegateAccounts

DigitalLearningSolutions.Data/DataServices/UserDataService/DelegateUserCardDataService.cs, DigitalLearningSolutions.Data/Models/User/DelegateAccount.cs, DigitalLearningSolutions.Data/Models/User/DelegateUser.cs, DigitalLearningSolutions.Data/Models/User/DelegateUserCard.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/Shared/DelegateInfoViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/AllDelegates/_SearchableDelegateCard.cshtml
[TD-3714](https://hee-tis.atlassian.net/browse/TD-3714)
Adding LastAccessed Date To Delegates Card In Tracking System
-----
I have:
Either:
Or:
[TD-3714]: https://hee-tis.atlassian.net/browse/TD-3714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3714 Adding LastAccessed Date To Delegates Card In Tracking System

DigitalLearningSolutions.Data/DataServices/UserDataService/AdminUserDataService.cs, DigitalLearningSolutions.Data/Models/User/AdminAccount.cs, DigitalLearningSolutions.Data/Models/User/AdminEntity.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Administrator/SearchableAdminViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Administrator/_SearchableAdminCard.cshtml
[TD-3716](https://hee-tis.atlassian.net/browse/TD-3716)
Adding LastAccessed Date In Admin Card
-----
I have:
Either:
Or:
[TD-3716]: https://hee-tis.atlassian.net/browse/TD-3716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3716 Adding LastAccessed Date In Admin Card

DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/ImportSummary.cshtml
[TD-5158](https://hee-tis.atlassian.net/browse/TD-5158)
Fixes back button logic on import summary screen to only go back to add questions to which competencies if count of existing competencies included in sheet is more than 0.
Also fixes error reported in TD-5154 - adds the text “(or skip if unchanged)” to the updated competencies on the summary page.
-----
I have:
Either:
Or:
[TD-5158]: https://hee-tis.atlassian.net/browse/TD-5158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5158 Fix import summary back button logic

DigitalLearningSolutions.Web/Models/BulkCompetenciesData.cs, DigitalLearningSolutions.Web/ViewModels/Frameworks/Import/AddQuestionsToWhichCompetenciesViewModel.cs
[TD-5155](https://hee-tis.atlassian.net/browse/TD-5155)
Fixes persistence of add assessment question options by setting default value in base class rather than viewmodel.
-----
I have:
Either:
Or:
[TD-5155]: https://hee-tis.atlassian.net/browse/TD-5155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5155 Fixes persistence of add assessment question options

DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/UploadResults.cshtml
[TD-5163](https://hee-tis.atlassian.net/browse/TD-5163)
Uses framework vocabulary in H1 of import complete page instead of hard-coded "competencies"
-----
I have:
Either:
Or:
[TD-5163]: https://hee-tis.atlassian.net/browse/TD-5163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5163 correct import complete vocab on import complete screen

DigitalLearningSolutions.Data/DataServices/UserDataService/AdminUserDataService.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Administrators/SearchableAdminAccountsViewModel.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/AdminAccounts/_SearchableAdminAccountsCard.cshtml
[TD-3718](https://hee-tis.atlassian.net/browse/TD-3718)
Adding LastAccessed Date in SuperAdmin Administrators Card
-----
I have:
Either:
Or:
[TD-3718]: https://hee-tis.atlassian.net/browse/TD-3718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3718 Adding LastAccessed Date in SuperAdmin Administrators Card

DigitalLearningSolutions.Data/DataServices/SupervisorDataService.cs
[TD-5397](https://hee-tis.atlassian.net/browse/TD-5397)
Removed pending request from CandidateAssessmentSupervisorVerifications table when supervisor delegate was removed.
N/A
-----
I have:
Either:
Or:
[TD-5397]: https://hee-tis.atlassian.net/browse/TD-5397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5397-Removed pending sign-off request when supervisor delegate was removed

DigitalLearningSolutions.Web/Views/Frameworks/Developer/FrameworkPrintLayout.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/_Structure.cshtml
Fixes issues identified by testers with the view for print page:
- Renders descriptions as HTML instead of text in ungrouped proficiencies
- Hides the View for print button for empty frameworks
- Adds Razor C# check to make sure competency group isn't empty before rendering
-----
I have:
Either:
Or:
=> TD-5263 Fix framework view for print fails

DigitalLearningSolutions.Data/DataServices/UserDataService/UserDataService.cs, DigitalLearningSolutions.Data/Models/SuperAdmin/SuperAdminDelegateAccount.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Delegates/SearchableDelegatesViewModel.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Delegates/_SearchableDelegatesCard.cshtml
[TD-3719](https://hee-tis.atlassian.net/browse/TD-3719)
Including LastAccessed Date In SuperAdmin Delegates Card
-----
I have:
Either:
Or:
[TD-3719]: https://hee-tis.atlassian.net/browse/TD-3719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3719 Including LastAccessed Date In SuperAdmin Delegates Card

DigitalLearningSolutions.Web/Controllers/FrameworksController/Frameworks.cs
[TD-5443](https://hee-tis.atlassian.net/browse/TD-5443)
Added check for existing flag name prior to add or edit custom flags.
-----
I have:
Either:
Or:
[TD-5443]: https://hee-tis.atlassian.net/browse/TD-5443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5443-Added check for existing flag names prior to add or edit custom flags.

DigitalLearningSolutions.Web/Views/Supervisor/Index.cshtml
[TD-5435](https://hee-tis.atlassian.net/browse/TD-5435)
The 'To Do' section has been moved above the 'Staff' section.
-----
I have:
Either:
Or:
[TD-5435]: https://hee-tis.atlassian.net/browse/TD-5435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5435-'To Do' section has been moved above the 'Staff' section.

DigitalLearningSolutions.Web/Scripts/trackingSystem/tableaureports.ts, DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/SelfAssessmentReports/TableauCompetencyDashboard.cshtml
[TD-5408](https://hee-tis.atlassian.net/browse/TD-5408)
Sets the admin id and email parameters using the visualisation API after the Tableau workbook has loaded.
-----
I have:
Either:
- [Tableau Embedding](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/4688805890/Tableau+Embedding?force_transition=36816ada-c5e5-4105-aba8-6a8d0cafa701)
Or:
[TD-5408]: https://hee-tis.atlassian.net/browse/TD-5408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5408 use type script to set url params

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentDescription.cshtml
[TD-5438](https://hee-tis.atlassian.net/browse/TD-5438)
Moved the 'View Proficiencies' button to the top.
-----
I have:
Either:
Or:
[TD-5438]: https://hee-tis.atlassian.net/browse/TD-5438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5438-Moved the 'View Proficiencies' button to the top.

DigitalLearningSolutions.Data/DataServices/FrameworkDataService.cs, DigitalLearningSolutions.Web/Controllers/FrameworksController/ImportCompetencies.cs, DigitalLearningSolutions.Web/Models/BulkCompetenciesData.cs, DigitalLearningSolutions.Web/Services/FrameworkService.cs, DigitalLearningSolutions.Web/Services/ImportCompetenciesFromFileService.cs, DigitalLearningSolutions.Web/ViewModels/Frameworks/Import/AddQuestionsToWhichCompetenciesViewModel.cs, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/AddQuestionsToWhichCompetencies.cshtml
[TD-5155](https://hee-tis.atlassian.net/browse/TD-5155)
Fixes issues with the add assessment question flow identified during testing.
-----
I have:
Either:
Or:
[TD-5155]: https://hee-tis.atlassian.net/browse/TD-5155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5155 fix testing fails

DigitalLearningSolutions.Web/Helpers/StringHelper.cs, DigitalLearningSolutions.Web/Services/FrameworkService.cs
When a description is edited and left blank, a spurious <br/> tag is stored to the description field. This was causing an empty box to be displayed for framework description. This change uses a string helper to strip HTML tags and set the description to empty if the string is empty after tags have been stripped.
-----
I have:
Either:
Or:
=> TD- 5263 fix empty description

DigitalLearningSolutions.Web/Views/Supervisor/VerifyMultipleResults.cshtml
[TD-5439](https://hee-tis.atlassian.net/browse/TD-5439)
When a competency description exists, it is shown to the competency in the view.
-----
I have:
Either:
Or:
[TD-5439]: https://hee-tis.atlassian.net/browse/TD-5439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5439 - A competency description is added to competency when it exists.

DigitalLearningSolutions.Web/Views/Frameworks/Developer/FrameworkPrintLayout.cshtml
Fixes ungrouped competencies heading to use framework vocabulary in the print preview view.
-----
I have:
Either:
Or:
=> TD-5263 Fixes ungrouped competencies heading to use framework vocabulary

DigitalLearningSolutions.Web/Views/ApplicationSelector/Index.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentOverview.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Users/Index.cshtml
[TD-5327](https://hee-tis.atlassian.net/browse/TD-5327)
- Uses a string helper to check whether HTML stripped description string is empty before deciding whether to display a description expander.
- Fixes the styling of app selector cards and drop-down filters to ensure mouse interactivity.
-----
I have:
Either:
Or:
[TD-5327]: https://hee-tis.atlassian.net/browse/TD-5327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5327 Fix testing fails

DigitalLearningSolutions.Web/Views/Supervisor/Shared/_DelegateProfileAssessmentGrid.cshtml
[TD-5482](https://hee-tis.atlassian.net/browse/TD-5482)
Related supervisor role added to view.
-----
I have:
Either:
Or:
[TD-5482]: https://hee-tis.atlassian.net/browse/TD-5482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5482-Related supervisor role added to view.

DigitalLearningSolutions.Web/Views/Frameworks/Developer/_Structure.cshtml
Makes the "View for print" button visible for reviewers and view only users.
-----
I have:
Either:
Or:
=> TD-5263 fix visibility of print button

DigitalLearningSolutions.Web/Styles/trackingSystem/delegates/courseDelegates.scss, DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/Shared/_DelegateSelfAssessmentDetails.cshtml
[TD-5481](https://hee-tis.atlassian.net/browse/TD-5481)
Added a Details view component in the view to show the supervisor list.
Note: As per discussion with @rshrirohit, decided to show a comma-separated Details heading.
-----
I have:
Either:
Or:
[TD-5481]: https://hee-tis.atlassian.net/browse/TD-5481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5481-Added a Details view component to show supervisor list.

DigitalLearningSolutions.Data/DataServices/FrameworkDataService.cs, DigitalLearningSolutions.Web/Services/FrameworkService.cs, DigitalLearningSolutions.Web/Services/ImportCompetenciesFromFileService.cs
[TD-5158](https://hee-tis.atlassian.net/browse/TD-5158)
Fixes committing of changes to competency groups during bulk upload by introducing a new service method to update the framework competency group for the framework competency. Also, checks competency groups for reordering during preprocess (as well as competencies).
-----
I have:
Either:
Or:
[TD-5158]: https://hee-tis.atlassian.net/browse/TD-5158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5158 Fixes committing updates to competency groups during bulk upload

DigitalLearningSolutions.Data/DataServices/FrameworkDataService.cs
[TD5511](https://hee-tis.atlassian.net/browse/TD-5511)
Framework query modified- The admin userid is used to check the framework owner.
Note: Sql query constant is being used in multiple methods due to which testing needed in the following framework functionalities:
- Frameworks Dashboard
- All Frameworks
- Mine Frameworks
- Create new framework 
- - Add competency group
- Edit framework (Branding)
-----
I have:
Either:
Or:
=> TD-5511- The admin userid is used to check the framework owner

DigitalLearningSolutions.Web/Views/Frameworks/Developer/_Structure.cshtml
[TD-5153](https://hee-tis.atlassian.net/browse/TD-5153)
Reinstates logic to show only the download template option if the framework only contained empty groups. This was overwritten when resolving merge conflicts in the past.
-----
I have:
Either:
Or:
[TD-5153]: https://hee-tis.atlassian.net/browse/TD-5153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5153 Reapplies new logic to cope with only empty competency groups

DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/ApplyCompetencyOrdering.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/UploadResults.cshtml
[TD-5220](https://hee-tis.atlassian.net/browse/TD-5220)
Fixes typo on apply changes to order screen and removes counts from competencies reordered line on upload results screen.
-----
I have:
Either:
Or:
[TD-5220]: https://hee-tis.atlassian.net/browse/TD-5220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5220 fix typo and remove reorder count

DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/Index.cshtml
[TD-5158](https://hee-tis.atlassian.net/browse/TD-5158)
Adds a new line to the start page inset text explaining that groups cannot be deleted or modified but that competencies can be moved to new groups.
-----
I have:
Either:
Or:
[TD-5158]: https://hee-tis.atlassian.net/browse/TD-5158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5158 add notice re not being able to modify groups notice

DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/UploadResults.cshtml
[TD-5220](https://hee-tis.atlassian.net/browse/TD-5220)
Removes spurious bracket from new message.
-----
I have:
Either:
Or:
[TD-5220]: https://hee-tis.atlassian.net/browse/TD-5220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5220 fix typo

DigitalLearningSolutions.Web/Services/ImportCompetenciesFromFileService.cs
[TD-5220](https://hee-tis.atlassian.net/browse/TD-5220)
Excludes empty or null group names from order comparison to avoid warning the user that order has changed when framework includes ungrouped competencies.
-----
I have:
Either:
Or:
[TD-5220]: https://hee-tis.atlassian.net/browse/TD-5220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5220 excludes empty or null group names from order comparison

DigitalLearningSolutions.Web/Controllers/Support/RequestSupportTicketController.cs, DigitalLearningSolutions.Web/Helpers/StringHelper.cs, DigitalLearningSolutions.Web/Scripts/frameworks/htmleditor.ts, DigitalLearningSolutions.Web/Styles/jodit.scss, DigitalLearningSolutions.Web/ViewModels/Support/RequestSupportTicket/RequestSummaryViewModel.cs, DigitalLearningSolutions.Web/Views/Support/RequestSupportTicket/RequestSummary.cshtml
[TD-5390](https://hee-tis.atlassian.net/browse/TD-5390)
1. validation code added to htmleditor.ts.
2. Removed [Required] attribute from view model as there is code in controller to validate and add model error.
Note: Wave errors exist for the Jodit editor that have been noticed in the application.
-----
I have:
Either:
Or:
[TD-5390]: https://hee-tis.atlassian.net/browse/TD-5390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5390-Jodit editor validation added

DigitalLearningSolutions.Data/DataServices/FrameworkDataService.cs, DigitalLearningSolutions.Web/Controllers/Support/RequestSupportTicketController.cs, DigitalLearningSolutions.Web/Helpers/StringHelper.cs, DigitalLearningSolutions.Web/Scripts/frameworks/htmleditor.ts, DigitalLearningSolutions.Web/Services/ImportCompetenciesFromFileService.cs, DigitalLearningSolutions.Web/Styles/jodit.scss, DigitalLearningSolutions.Web/ViewModels/Support/RequestSupportTicket/RequestSummaryViewModel.cs, DigitalLearningSolutions.Web/Views/Support/RequestSupportTicket/RequestSummary.cshtml
Dls release [v1.2.0](https://hee-tis.atlassian.net/projects/TD/versions/12718/tab/release-report-all-issues) to UAT
=> Dls release v1.2.0 to UAT

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/_OverviewTable.cshtml
[TD-5451](https://hee-tis.atlassian.net/browse/TD-5451)
Empty competency description check added
-----
I have:
Either:
Or:
[TD-5451]: https://hee-tis.atlassian.net/browse/TD-5451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5451- Empty competency description check added

DigitalLearningSolutions.Data.Migrations/202504241517_AddFieldIsPrimaryToSelfAssessmentFrameworksTable.cs, DigitalLearningSolutions.Data/DataServices/CompetencyAssessmentDataService.cs, DigitalLearningSolutions.Web/Controllers/CompetencyAssessmentsController/CompetencyAssessments.cs, DigitalLearningSolutions.Web/Helpers/DisplayStringHelper.cs, DigitalLearningSolutions.Web/Services/CompetencyAssessmentService.cs, DigitalLearningSolutions.Web/ViewModels/CompetencyAssessments/ConfirmRemoveFrameworkSourceViewModel.cs, DigitalLearningSolutions.Web/ViewModels/CompetencyAssessments/SelectFrameworkSourcesFormData.cs, DigitalLearningSolutions.Web/ViewModels/CompetencyAssessments/SelectFrameworkSourcesViewModel.cs, DigitalLearningSolutions.Web/Views/CompetencyAssessments/ConfirmRemoveFrameworkSource.cshtml, DigitalLearningSolutions.Web/Views/CompetencyAssessments/EditRoleProfileLinks.cshtml, DigitalLearningSolutions.Web/Views/CompetencyAssessments/ManageCompetencyAssessment.cshtml, DigitalLearningSolutions.Web/Views/CompetencyAssessments/SelectFrameworkSources.cshtml
[TD-5307](https://hee-tis.atlassian.net/browse/TD-5307)
Implements the interface for managing linked competency frameworks. Includes a remove source framework feature that checks for linked competencies and prompts the user to confirm removal if they exist, resetting related task statuses. We need to implement "set as primary" feature but this will be handled through a follow up ticket.
-----
I have:
Either:
Or:
[TD-5307]: https://hee-tis.atlassian.net/browse/TD-5307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5307 Implement select framework sources for competency framework

DigitalLearningSolutions.Web/Controllers/FrameworksController/Review.cs
https://hee-tis.atlassian.net/browse/TD-5487
There was no validation to prevent multiple submissions of a review comment. If users clicked the back button after submitting a review, they could unintentionally resubmit it.
I added a check using the FrameworkReviewID property. Since this property is not null until the review is submitted, we now verify its value before allowing any further submissions. This prevents duplicate posting of review comments.
-----
I have:
Either:
Or:
=> TD-5487 Issue showing multiple comments when clicked the back link after submitted the review on Frameworks section

DigitalLearningSolutions.Web/Controllers/FrameworksController/ImportCompetencies.cs
https://hee-tis.atlassian.net/browse/TD-5528
A 500 error occurs when the user clicks the browser's back button because GetMultiPageFormData returns null and triggers an exception.
To handle this, I added a validation step to check whether the required value exists in TempData before calling GetMultiPageFormData.
If the value is missing, the application now returns a 410 (Gone) status page to indicate that the session data is no longer available.page
-----
I have:
Either:
Or:
=> TD-5528 Issue showing console '500' error on the screen when clicked browser back link on 'Import competencies complete' screen

DigitalLearningSolutions.Web/Controllers/FrameworksController/Competencies.cs, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Competency.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/CompetencyGroup.cshtml
https://hee-tis.atlassian.net/browse/TD-5542
I resolved a validation UI issue where the clickable error summary wasn't scrolling to the correct form field due to mismatched id attributes. Changing the field name from competency-group-name to Name ensures the error summary link now correctly targets the form field, since the generated id now matches.
I also removed SearchableName from ModelState because it's not required, and it is not necessary to show on validation errors or interfere with model binding.
_Paste screenshots for all views created or changed: mobile, tablet, and desktop, wave analyser showing no errors._
-----
I have:
Either:
Or:
=> TD-5542 Issue not focussing to the respective fields when clicked the error links on the frameworks section

DigitalLearningSolutions.Data/DataServices/FrameworkDataService.cs
[TD-5557](https://hee-tis.atlassian.net/browse/TD-5557)
Added a null check for description property within the inline sql code snippet in the updateCompetencyGroup method of the frameworkDataService.
No Screenshots, it's a sql change.
-----
I have:
Either:
Or:
[TD-5557]: https://hee-tis.atlassian.net/browse/TD-5557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD_5557 Framework Competency Group Description not showing up after update

DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/SelfAssessmentDescription.cshtml
https://hee-tis.atlassian.net/browse/TD-5561
To resolve the issue, the primary button for "View Proficiencies" should appear in green, while the "Continue where I left off" button should be displayed in grey.
To achieve this, I need to remove the current if condition and swap the button colors accordingly.
-----
I have:
Either:
Or:
=> TD-5561 Issue showing mismatch of colouring of buttons on Learning Portal - Self assessments screen

DigitalLearningSolutions.Web/Views/Frameworks/Developer/CompetencyPreview.cshtml
https://hee-tis.atlassian.net/browse/TD-5544
I resolved the issue by adding top padding to the Done button, creating space between the 'Previous question' and 'Skip' link , and the buttons
-----
I have:
Either:
Or:
=> TD-5544 Formatting issue for the links showing on the 'preview' screen on Frameworks section

DigitalLearningSolutions.Web/Views/Supervisor/ReviewSelfAssessment.cshtml
[TD-5451](https://hee-tis.atlassian.net/browse/TD-5451)
Empty competency description check added for competencies in the Supervise section.
-----
I have:
Either:
Or:
[TD-5451]: https://hee-tis.atlassian.net/browse/TD-5451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5451-Empty competency description check added in the Supervise section.

DigitalLearningSolutions.Web/Views/TrackingSystem/Delegates/AllDelegates/_SearchableDelegateCard.cshtml
https://hee-tis.atlassian.net/browse/TD-3714
I updated the Last accessed date label in the delegate cards to use a lowercase "a" in "accessed" for consistency
-----
I have:
Either:
Or:
=> TD- 3714 Display the DelegateAccounts.LastAccessed date on the Tracking System -> Delegates cards

DigitalLearningSolutions.Web/Controllers/FrameworksController/Frameworks.cs, DigitalLearningSolutions.Web/Views/Frameworks/Developer/EditCustomFlag.cshtml
[TD-5443](https://hee-tis.atlassian.net/browse/TD-5443)
The name of the validation summary field has been corrected. This places focus on the input field when clicking on the summary error message.
The names of the flags have been compared by converting them to lowercase letters.
-----
I have:
Either:
Or:
[TD-5443]: https://hee-tis.atlassian.net/browse/TD-5443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5443-Validation summary field name corrected

DigitalLearningSolutions.Web/Views/Supervisor/VerifyMultipleResults.cshtml
[TD-5439](https://hee-tis.atlassian.net/browse/TD-5439)
Added empty competency description check. 
Increased competency text font to 19.
-----
I have:
Either:
Or:
[TD-5439]: https://hee-tis.atlassian.net/browse/TD-5439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5439-Added empty competency description check

DigitalLearningSolutions.Web/ViewComponents/DlsFooterBannerTextViewComponent.cs, DigitalLearningSolutions.Web/ViewModels/Common/ViewComponents/DlsFooterBannerTextViewModel.cs, DigitalLearningSolutions.Web/Views/LearningMenu/CoursePassword.cshtml, DigitalLearningSolutions.Web/Views/LearningMenu/Index.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/Available/Available.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/Completed/Completed.cshtml, DigitalLearningSolutions.Web/Views/LearningPortal/Current/Current.cshtml, DigitalLearningSolutions.Web/Views/Shared/Components/DlsFooterBannerText/Default.cshtml, DigitalLearningSolutions.Web/Views/Shared/_DlsFooter.cshtml, DigitalLearningSolutions.Web/Views/Supervisor/Index.cshtml
[TD-5434](https://hee-tis.atlassian.net/browse/TD-5434)
I added the centre name to the footer and accessed it as a ViewData across the footer partial after making changes to three Learning Hub pages i.e. Current, Available and Completed.
Wave tool screenshot
-----
I have:
Either:
Or:
[TD-5434]: https://hee-tis.atlassian.net/browse/TD-5434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD_5434 Move the Centre Name to the top of footer across all Learning Portal Pages.

DigitalLearningSolutions.Web/Scripts/frameworks/htmleditor.ts, DigitalLearningSolutions.Web/Styles/jodit.scss, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Competency.cshtml, DigitalLearningSolutions.Web/Views/Frameworks/Developer/Import/ImportCompleted.cshtml
[TD-5453](https://hee-tis.atlassian.net/browse/TD-5453)
Code added/updated to remove Wave, axe DevTools and Lighthouse issues of jodit editor and of web pages.
Placeholder 'Start writing' of jodit editor has been hidden.
-----
I have:
Either:
Or:
[TD-5453]: https://hee-tis.atlassian.net/browse/TD-5453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5453-Code added/updated to remove Wave, axe DevTools and Lighthouse issues

DigitalLearningSolutions.Data/DataServices/UserDataService/DelegateUserCardDataService.cs, DigitalLearningSolutions.Data/Helpers/GenericSortingHelper.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Delegates/AllDelegates/AllDelegatesViewModel.cs
https://hee-tis.atlassian.net/browse/TD-5568
I added the Last Accessed Date and its corresponding property to the static class DelegateSortByOptions.
I also included LastAccessed in the overridden SortOptions within the AllDelegatesViewModel.
Additionally, I refactored the OrderBy condition to incorporate LastAccessed as a sorting option
-----
I have:
Either:
Or:
=> TD-5568 Add 'Last accessed date' to 'sort' filter on 'Tracking system - Delegates' screen 

DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAsssessmentReportDataService.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/Export/SelfAssessmentReportData.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentReportService.cs
[TD-5547](https://hee-tis.atlassian.net/browse/TD-5547)
Added the centre custom fields logic, removed the hardcoded centre fields from the sql query, used the XLWorkbook functions to map the query records onto the workbook sheet. Formatted the row contents to centre align.
No Screenshots, backend change only
-----
I have:
Either:
Or:
[TD-5547]: https://hee-tis.atlassian.net/browse/TD-5547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5547_Added logic to generate the Centre Custom Fields dynamically for Self Assessment Reports for a given centre.

DigitalLearningSolutions.Data/DataServices/FrameworkDataService.cs
[TD-5511](https://hee-tis.atlassian.net/browse/TD-5511)
Issue on Add/Edit (Competency/Competency group) button click: - SQL query modified to get correct admin user role of framework when admin logged in to different centre.
N/A
-----
I have:
Either:
Or:
[TD-5511]: https://hee-tis.atlassian.net/browse/TD-5511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5511-SQL query modified to get correct admin user role of framework

DigitalLearningSolutions.Web/Views/SuperAdmin/AdminAccounts/_SearchableAdminAccountsCard.cshtml
[TD-3718](https://hee-tis.atlassian.net/browse/TD-3718)
Changed the label display from 'Last Accessed' to 'Last accessed date' on the administrators card.
-----
I have:
Either:
Or:
[TD-3718]: https://hee-tis.atlassian.net/browse/TD-3718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD_3718 Adding the text 'Last accessed date' to the administrators card in the superadmin section

DigitalLearningSolutions.Web/Services/DelegateDownloadFileService.cs
[TD-3715](https://hee-tis.atlassian.net/browse/TD-3715)
Changed the excel report column name to 'Last accessed date' from 'Last Accessed'.
-----
I have:
Either:
Or:
[TD-3715]: https://hee-tis.atlassian.net/browse/TD-3715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-3715 Fix for initial test fail scenario changed Last Accessed column name to Last accessed date in delegate excel reports

DigitalLearningSolutions.Web/Controllers/FrameworksController/AssessmentQuestions.cs, DigitalLearningSolutions.Web/Controllers/FrameworksController/Competencies.cs
[TD-5620](https://hee-tis.atlassian.net/browse/TD-5620)
Added code to check if the html editor is empty.
Implemented for Competency groups, Competency and Assessment question.
N/A
-----
I have:
Either:
Or:
[TD-5620]: https://hee-tis.atlassian.net/browse/TD-5620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5620-Added code to check if the html editor is empty.

DigitalLearningSolutions.Web/Views/Frameworks/Shared/_CommentCard.cshtml
https://hee-tis.atlassian.net/browse/TD-5581
I added autocomplete="off" to the <textarea> to prevent the browser from remembering and repopulating the <textarea>  when a user clicks the Back button and the page reloads
-----
I have:
Either:
Or:
=> TD-5581 Issue showing multiple comments on 'Frameworks' - 'Comments' section when clicked browser back link

DigitalLearningSolutions.Data.Migrations/202507030918_CreateOrAlterGetSelfAssessmentReport.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.Designer.cs, DigitalLearningSolutions.Data.Migrations/Properties/Resources.resx, DigitalLearningSolutions.Data.Migrations/Scripts/TD-5759_CreateOrAlterSelfAssessmentReportSPandTVF_UP.sql, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAsssessmentReportDataService.cs
[TD-5759](https://hee-tis.atlassian.net/browse/TD-5759)
Refactors the self assessment report query to use the following:
- Added stored procedure: usp_GetSelfAssessmentReport
- Added inline TVF: GetOtherCentresForSelfAssessmentTVF
- Updated report query structure for better performance:
- Replaced CTE with #LatestAssessmentResults temp table
- Replaced scalar function with OUTER APPLY to inline TVF
- Added FluentMigrator Down() migration to drop created objects cleanly
Tested to confirm:
- Identical data outputs
- 3 x performance increase
-----
I have:
Either:
Or:
[TD-5759]: https://hee-tis.atlassian.net/browse/TD-5759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2 …
=> TD-5759 Refactors self assessment report sql to use SP, CTE and TVF

DigitalLearningSolutions.Data/DataServices/CompetencyLearningResourcesDataService.cs, DigitalLearningSolutions.Web/Controllers/FrameworksController/Signposting.cs, DigitalLearningSolutions.Web/Services/CompetencyLearningResourcesService.cs, DigitalLearningSolutions.Web/Views/Frameworks/Developer/AddCompetencyLearningResourceSummary.cshtml
https://hee-tis.atlassian.net/browse/TD-5636
I’ve implemented a GetActiveCompetencyLearningResourcesByCompetencyIdAndReferenceId method to retrieve a learning resource based on both CompetencyId and ReferenceId. This is used to check whether the resource has already been added to a competency.
Additionally, I’ve integrated an error summary into the view to notify the admin when a duplicate learning resource is detected, ensuring they’re clearly informed that the resource has already been signposted to the selected competency
-----
I have:
Either:
Or:
=> TD-5636 Issue allowing to add duplicate resources on 'Competence Resource signposting' screen

DigitalLearningSolutions.Web/Controllers/FrameworksController/Review.cs, DigitalLearningSolutions.Web/Views/Frameworks/Developer/SubmitReview.cshtml
[TD-5657](https://hee-tis.atlassian.net/browse/TD-5657)
Review comment empty check validation added.
-----
I have:
Either:
Or:
[TD-5657]: https://hee-tis.atlassian.net/browse/TD-5657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5657-Issue when submitting the review on frameworks section

DigitalLearningSolutions.Web/Views/Frameworks/Developer/Framework.cshtml
[TD-5658](https://hee-tis.atlassian.net/browse/TD-5658)
Empty framework/group validation added to show/hide buttons
-----
I have:
Either:
Or:
[TD-5658]: https://hee-tis.atlassian.net/browse/TD-5658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5658-Issue allowing the empty framework to 'Send for review'/'Publish'

DigitalLearningSolutions.Data/DataServices/FrameworkDataService.cs
[TD-5709](https://hee-tis.atlassian.net/browse/TD-5709)
Adds TOP(1) to subquery to ensure it only returns one record from the framework collaborators table when loading user frameworks
-----
I have:
Either:
Or:
[TD-5709]: https://hee-tis.atlassian.net/browse/TD-5709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5709 fix frameworks error affecting some users

DigitalLearningSolutions.Data/DataServices/FrameworkDataService.cs
https://hee-tis.atlassian.net/browse/TD-5548
Updated the query to change the join between FrameworkCompetencyGroups (fcg) and FrameworkCompetencies (fc) from LEFT OUTER JOIN to INNER JOIN.
This ensures that only competency groups with at least one matching framework competency are returned.
The change resolves the reordering sequence issue when downloading the template by excluding competency groups that have no competencies assigned
Fixed a “Unboxing a possibly null value” warning in FrameworkDataService.cs
-----
I have:
Either:
Or:
=> TD-5548 Issue showing 'some existing competency records changed order' on 'competency file uploaded' screen when even modified the competency names

DigitalLearningSolutions.Data/DataServices/FrameworkDataService.cs, DigitalLearningSolutions.Web/Views/Frameworks/Shared/_CompetencyGroupCard.cshtml
[TD-5666](https://hee-tis.atlassian.net/browse/TD-5666)
Made a query change to not update competency groups that is retrieved while fetching the selfassessment on supervisor/learning portal modules.
-----
I have:
Either:
Or:
[TD-5666]: https://hee-tis.atlassian.net/browse/TD-5666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD_5666_Framework Competency Group Description showing on Learning Portal Supervisor Interface

DigitalLearningSolutions.Data/DataServices/CentresDataService.cs, DigitalLearningSolutions.Web.Tests/Controllers/SuperAdmin/CentresControllerTests.cs, DigitalLearningSolutions.Web/Controllers/SuperAdmin/Centres/CentresController.cs, DigitalLearningSolutions.Web/Services/CentresService.cs, DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Centres/EditCentreDetailsSuperAdminViewModel.cs, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/EditCentreDetails.cshtml, DigitalLearningSolutions.Web/Views/SuperAdmin/Centres/ManageCentre.cshtml
[TD-5797](https://hee-tis.atlassian.net/browse/TD-5797)
As @kevwhitt-hee suggested, the 'pwEmail' field would be the centre email.
The CentreEmail and RegistrationEmail fields in the SQL query have been changed.
The affected areas have been updated accordingly.
-----
I have:
Either:
Or:
[TD-5759]: https://hee-tis.atlassian.net/browse/TD-5759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TD-5797]: https://hee-tis.atlassian.net/browse/TD-5797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5797-The CentreEmail and RegistrationEmail fields in the SQL query have been corrected.

DigitalLearningSolutions.Web/Controllers/TrackingSystem/Centre/SelfAssessmentReports/SelfAssessmentReportsController.cs, DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Reports/SelfAssessmentReportsViewModel.cs, DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/SelfAssessmentReports/Index.cshtml, DigitalLearningSolutions.Web/appSettings.UAT.json, DigitalLearningSolutions.Web/appsettings.Development.json
[TD-5859](https://hee-tis.atlassian.net/browse/TD-5859)
Implements a URL parameter override for the Tableau dashboard feature flag to allow testing from production.
-----
I have:
Either:
Or:
[TD-5859]: https://hee-tis.atlassian.net/browse/TD-5859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5859 url parameter flag override for tableau dashboard feature flag

DigitalLearningSolutions.Web/Controllers/LearningPortalController/Current.cs
[TD-5535](https://hee-tis.atlassian.net/browse/TD-5535)
Undid the retirement logic code to bring in all the self assessments from the db.
No screenshots.
-----
I have:
Either:
Or:
[TD-5535]: https://hee-tis.atlassian.net/browse/TD-5535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD_5535_Undid the retirement date logic to display all the self assessments on the current activities page.

DigitalLearningSolutions.Data/DataServices/SupervisorDataService.cs
[TD-5611](https://hee-tis.atlassian.net/browse/TD-5611)
Modified SQL query to hide retired self-assessment role profiles
N/A
-----
I have:
Either:
Or:
[TD-5611]: https://hee-tis.atlassian.net/browse/TD-5611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5611-Supervise - modified SQL query to hide retired self-assessment role profiles

DigitalLearningSolutions.Web/Middleware/DLSIPRateLimitMiddleware.cs, DigitalLearningSolutions.Web/appSettings.UAT.json
[TD-5410](https://hee-tis.atlassian.net/browse/TD-5410)
Using Iconfiguration interface fetching the environment value and adding the rate limiter for request logic only on the Production level.
No Screenshots
-----
I have:
Either:
Or:
[TD-5410]: https://hee-tis.atlassian.net/browse/TD-5410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD_5410_Adding config to the rate limiter so that we can environment, and add production logic to it.

DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs
[TD-5816](https://hee-tis.atlassian.net/browse/TD-5816)
Swapped piece of code execution: Moved ‘competencies update’ code before ‘competencies remove’ code.
N/A
-----
I have:
Either:
Or:
[TD-5816]: https://hee-tis.atlassian.net/browse/TD-5816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-5816-Moved competencies update code before competencies remove code

DigitalLearningSolutions.Data.Migrations/202508190845_AddSelfAssessmentProcessAgreed .cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/CandidateAssessmentsDataService.cs, DigitalLearningSolutions.Data/DataServices/SelfAssessmentDataService/SelfAssessmentDataService.cs, DigitalLearningSolutions.Data/Models/SelfAssessments/CurrentSelfAssessment.cs, DigitalLearningSolutions.Web.Tests/Controllers/LearningPortal/SelfAssessmentTests.cs, DigitalLearningSolutions.Web/Controllers/LearningPortalController/SelfAssessment.cs, DigitalLearningSolutions.Web/Services/SelfAssessmentService.cs, DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/SelfAssessmentDescriptionViewModel.cs, DigitalLearningSolutions.Web/ViewModels/LearningPortal/SelfAssessments/SelfAssessmentProcessViewModel.cs, DigitalLearningSolutions.Web/Views/LearningPortal/SelfAssessments/AgreeSelfAssessmentProcess.cshtml
[TD-5339](https://hee-tis.atlassian.net/browse/TD-5339)
This PR introduces the "Self Assessment Process Agreement" functionality.
Key Changes
- **Added DB Column**:  
SelfAssessmentProcessAgreed - nullable
- **Self Assessment Agreement Step**:  
Added a new step in the self-assessment process where users must review and agree to the process agreement before continuing.
- **UI Updates**:  
Introduced a new UI component/page/model for displaying the process agreement and capturing user consent.
- **Backend Support**:  
Updated backend logic to track user agreement status and enforce the process agreement step as mandatory.
- **Validation**:  
Users cannot proceed with their self assessment until they explicitly accept the agreement.
- **Unit/Integration Tests**:  
Added/updated tests to …
=> TD-5339 Self Assessment Process Agreement

DigitalLearningSolutions.Web/ServiceFilter/RequireProcessAgreementFilter .cs
[TD-6108](https://hee-tis.atlassian.net/browse/TD-6108)
Updating servicefilter logic so that it works only on the self assessments and excludes other areas such as re-enrolment.
-----
I have:
Either:
Or:
[TD-6108]: https://hee-tis.atlassian.net/browse/TD-6108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TD-6108 Updating ServiceFilter Logic To Exclude Other Areas

DigitalLearningSolutions.Web.Tests/Controllers/Register/RegisterDelegateByCentreControllerTests.cs, DigitalLearningSolutions.Web.Tests/Controllers/TrackingSystem/Delegates/EditDelegateControllerTests.cs, DigitalLearningSolutions.Web.Tests/Helpers/ProfessionalRegistrationNumberHelperTests.cs, DigitalLearningSolutions.Web.Tests/TestHelpers/ErrorMessagesTestHelper.cs, DigitalLearningSolutions.Web/Helpers/ProfessionalRegistrationNumberHelper.cs
https://hee-tis.atlassian.net/browse/TD-4624
I swapped out the pattern string for the .NET regex that validates professional registration numbers.
I updated the test data to match the new pattern so the tests pass, and I revised the error message to reflect the updated allowed format.
-----
I have:
Either:
Or:
=> TD-4624 Add regex validation of professional registration number field throughout the application
